# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('device_uuid', models.CharField(max_length=64, unique=True)),
                ('device_kind', models.CharField(choices=[('tablet', 'Tablet'), ('laptop', 'Laptop'), ('phone', 'Phone'), ('kiosk', 'Kiosk'), ('mobile_clinic_van', 'Mobile Clinic Van')], max_length=32)),
                ('operator_profile_id', models.UUIDField(blank=True, null=True)),
                ('facility_id', models.UUIDField(blank=True, null=True)),
                ('accho_flag', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('storage_used_mb', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('platform', models.CharField(blank=True, max_length=32)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_mrff_offline_kit_offline_device',
            },
        ),
        migrations.CreateModel(
            name='OfflineIntake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('local_id', models.CharField(max_length=64)),
                ('patient_profile_id', models.UUIDField(blank=True, null=True)),
                ('patient_snapshot', models.JSONField(default=dict)),
                ('chief_complaint', models.TextField(blank=True)),
                ('vitals', models.JSONField(default=dict)),
                ('history', models.JSONField(default=list)),
                ('cdss_alerts', models.JSONField(default=list)),
                ('encounter_kind', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency'), ('outreach_visit', 'Outreach Visit'), ('follow_up', 'Follow Up')], default='routine', max_length=32)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accho_specific', models.JSONField(default=dict)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('conflicted', 'Conflicted'), ('rejected', 'Rejected')], default='pending', max_length=32)),
                ('sync_error', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='cymed_mrff_offline_kit.offlinedevice')),
            ],
            options={
                'db_table': 'cymed_mrff_offline_kit_offline_intake',
                'unique_together': {('device', 'local_id')},
            },
        ),
        migrations.CreateModel(
            name='OfflineCdssRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('kind', models.CharField(choices=[('qsofa', 'qSOFA'), ('news2', 'NEWS2'), ('lace', 'LACE'), ('morse', 'Morse'), ('peds_asthma', 'Pediatric Asthma'), ('red_flag_screen', 'Red Flag Screen'), ('ottawa_ankle', 'Ottawa Ankle'), ('cage', 'CAGE'), ('ausdrisk', 'AUSDRISK')], max_length=32)),
                ('score', models.DecimalField(decimal_places=4, max_digits=9)),
                ('band', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical'), ('n_a', 'N/A')], default='n_a', max_length=32)),
                ('recommendations', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdss_runs', to='cymed_mrff_offline_kit.offlineintake')),
            ],
            options={
                'db_table': 'cymed_mrff_offline_kit_offline_cdss_run',
            },
        ),
        migrations.CreateModel(
            name='SyncQueueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('payload_kind', models.CharField(choices=[('intake', 'Intake'), ('vitals', 'Vitals'), ('lab_result', 'Lab Result'), ('prescription', 'Prescription'), ('consent', 'Consent'), ('note', 'Note'), ('attachment', 'Attachment')], max_length=32)),
                ('local_ref', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('sent', 'Sent'), ('failed', 'Failed'), ('conflict', 'Conflict'), ('superseded', 'Superseded')], default='queued', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('attempts', models.IntegerField(default=0)),
                ('server_id', models.UUIDField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='cymed_mrff_offline_kit.offlinedevice')),
            ],
            options={
                'db_table': 'cymed_mrff_offline_kit_sync_queue_item',
            },
        ),
        migrations.CreateModel(
            name='ConflictResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('server_snapshot', models.JSONField(default=dict)),
                ('client_snapshot', models.JSONField(default=dict)),
                ('strategy', models.CharField(choices=[('server_wins', 'Server Wins'), ('client_wins', 'Client Wins'), ('merge', 'Merge'), ('manual', 'Manual')], default='manual', max_length=32)),
                ('resolved_by_profile_id', models.UUIDField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_payload', models.JSONField(default=dict)),
                ('queue_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_resolutions', to='cymed_mrff_offline_kit.syncqueueitem')),
            ],
            options={
                'db_table': 'cymed_mrff_offline_kit_conflict_resolution',
            },
        ),
    ]
