# Generated by Django 6.0.6 on 2026-06-23 04:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_pathology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('slide_number', models.CharField(max_length=20)),
                ('stain_type', models.CharField(choices=[('he', 'H&E â€” Hematoxylin & Eosin'), ('pas', 'PAS â€” Periodic Acid-Schiff'), ('giemsa', 'Giemsa'), ('gram', 'Gram Stain'), ('zn', 'Ziehl-Neelsen (ZN)'), ('masson', 'Masson Trichrome'), ('reticulin', 'Reticulin'), ('oil_red_o', 'Oil Red O'), ('congo_red', 'Congo Red'), ('ihc', 'IHC â€” Immunohistochemistry'), ('fish', 'FISH'), ('pcr', 'Molecular PCR'), ('other', 'Other')], default='he', max_length=20)),
                ('stain_status', models.CharField(default='pending', max_length=20)),
                ('quality_grade', models.CharField(blank=True, choices=[('optimal', 'Optimal'), ('acceptable', 'Acceptable'), ('suboptimal', 'Suboptimal'), ('unacceptable', 'Unacceptable â€” Recut')], max_length=20)),
                ('cut_thickness_microns', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stained_by', models.UUIDField(blank=True, null=True)),
                ('stained_at', models.DateTimeField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, unique=True)),
                ('digital_scan_url', models.URLField(blank=True, max_length=2000)),
                ('is_request', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cymed_lab_slides',
            },
        ),
        migrations.CreateModel(
            name='HistologyCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('case_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('received', 'Case Received'), ('embedding', 'Embedding'), ('sectioning', 'Sectioning'), ('staining', 'Staining'), ('ready_for_review', 'Ready for Pathologist Review'), ('under_review', 'Under Review'), ('additional_stains', 'Additional Stains Requested'), ('signed_out', 'Signed Out')], default='received', max_length=30)),
                ('assigned_histotechnician', models.UUIDField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('signed_out_at', models.DateTimeField(blank=True, null=True)),
                ('turnaround_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('pathology_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='histology_case', to='lab_pathology.pathologycase')),
            ],
            options={
                'db_table': 'cymed_lab_histology_cases',
            },
        ),
        migrations.CreateModel(
            name='HistologyDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('snomed_code', models.CharField(blank=True, max_length=50)),
                ('icd11_code', models.CharField(blank=True, max_length=20)),
                ('diagnosis_text', models.TextField()),
                ('diagnosis_category', models.CharField(blank=True, choices=[('benign', 'Benign'), ('malignant', 'Malignant'), ('borderline', 'Borderline'), ('inflammatory', 'Inflammatory'), ('reactive', 'Reactive'), ('normal', 'Normal Tissue'), ('inconclusive', 'Inconclusive')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('signed_by', models.UUIDField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('digital_signature', models.CharField(blank=True, max_length=512)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='lab_histopathology.histologycase')),
            ],
            options={
                'db_table': 'cymed_lab_histology_diagnoses',
            },
        ),
        migrations.CreateModel(
            name='SlideReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('reviewed_by', models.UUIDField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('deferred', 'Deferred â€” Awaiting Additional Stain')], default='pending', max_length=20)),
                ('findings', models.TextField(blank=True)),
                ('additional_stains_requested', models.JSONField(default=list)),
                ('ai_assistance_used', models.BooleanField(default=False)),
                ('ai_suggestions', models.JSONField(default=dict)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lab_histopathology.slide')),
            ],
            options={
                'db_table': 'cymed_lab_slide_reviews',
            },
        ),
        migrations.CreateModel(
            name='TissueBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('block_number', models.CharField(max_length=20)),
                ('cassette_number', models.CharField(max_length=20)),
                ('tissue_type', models.CharField(blank=True, max_length=100)),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending Embedding'), ('embedded', 'Embedded'), ('sectioned', 'Sectioned'), ('archived', 'Archived'), ('depleted', 'Depleted')], default='pending', max_length=20)),
                ('embedded_by', models.UUIDField(blank=True, null=True)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=100)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='lab_histopathology.histologycase')),
                ('pathology_specimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tissue_blocks', to='lab_pathology.pathologyspecimen')),
            ],
            options={
                'db_table': 'cymed_lab_tissue_blocks',
                'unique_together': {('case', 'block_number')},
            },
        ),
        migrations.AddField(
            model_name='slide',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='lab_histopathology.tissueblock'),
        ),
        migrations.AlterUniqueTogether(
            name='slide',
            unique_together={('block', 'slide_number')},
        ),
    ]
