# Generated by Django 6.0.7 on 2026-08-06 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_hr', '0001_initial'),
        ('cyed_org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='cyed_org.campus'),
        ),
    ]
