# Generated by Django 6.1 on 2026-08-12 07:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_hr', '0003_onboardingtask_performancereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffleave',
            name='balance_override_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='staffleave',
            name='balance_override_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='LeaveEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('leave_type', models.CharField(choices=[('annual', 'Annual'), ('sick', 'Personal/Sick'), ('long_service', 'Long Service'), ('unpaid', 'Unpaid'), ('parental', 'Parental')], default='annual', max_length=20)),
                ('year', models.PositiveSmallIntegerField(help_text='Leave year, e.g. 2026.')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('entitled_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='cyed_hr.staff')),
            ],
            options={
                'db_table': 'cyed_hr_leave_entitlements',
                'ordering': ['-year', 'leave_type'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'staff', 'leave_type', 'year'), name='uniq_entitlement_per_staff_type_year'), models.CheckConstraint(condition=models.Q(('entitled_days__gte', 0)), name='entitlement_days_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='StaffClearance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('kind', models.CharField(choices=[('wwcc', 'Working With Children Check'), ('teacher_registration', 'Teacher Registration'), ('police_check', 'National Police Check'), ('first_aid', 'First Aid'), ('anaphylaxis', 'Anaphylaxis Management'), ('cpr', 'CPR'), ('other', 'Other')], default='wwcc', max_length=30)),
                ('number', models.CharField(blank=True, max_length=100)),
                ('issuing_state', models.CharField(blank=True, max_length=10)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, help_text='Null means this credential does not expire — a deliberate choice, not unknown.', null=True)),
                ('verified_by', models.CharField(blank=True, max_length=255)),
                ('verified_on', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='cyed_hr.staff')),
            ],
            options={
                'db_table': 'cyed_hr_clearances',
                'ordering': ['staff', 'kind', '-expires_on'],
                'indexes': [models.Index(fields=['tenant_id', 'expires_on'], name='idx_clearance_expiry')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'staff', 'kind'), name='uniq_clearance_per_staff_kind')],
            },
        ),
    ]
