# Generated by Django 6.1 on 2026-09-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_hr', '0004_staffleave_balance_override_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='leaveentitlement',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='leaveentitlement',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='leaveentitlement',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='leaveentitlement',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='staff',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='staffclearance',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='staffclearance',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='staffclearance',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='staffclearance',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='staffleave',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='staffleave',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='staffleave',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='staffleave',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
