# Generated by Django 6.0.6 on 2026-06-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="demorequest",
            new_name="website_dem_status_96e4f2_idx",
            old_name="website_dr_status_idx",
        ),
        migrations.RenameIndex(
            model_name="demorequest",
            new_name="website_dem_email_011552_idx",
            old_name="website_dr_email_idx",
        ),
        migrations.RenameIndex(
            model_name="productlisting",
            new_name="website_pro_categor_47a184_idx",
            old_name="website_pl_cat_pub_idx",
        ),
        migrations.RenameIndex(
            model_name="productlisting",
            new_name="website_pro_is_feat_0673df_idx",
            old_name="website_pl_feat_pub_idx",
        ),
        migrations.RenameIndex(
            model_name="websiteapilog",
            new_name="website_api_endpoin_bd06c7_idx",
            old_name="website_log_ep_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="websiteapilog",
            new_name="website_api_status__42899a_idx",
            old_name="website_log_sc_ts_idx",
        ),
        migrations.AlterField(
            model_name="demorequest",
            name="company_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1-10", "1–10"),
                    ("11-50", "11–50"),
                    ("51-200", "51–200"),
                    ("201-1000", "201–1000"),
                    ("1001+", "1001+"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="newslettersubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Confirmation"),
                    ("active", "Active"),
                    ("unsubscribed", "Unsubscribed"),
                    ("bounced", "Bounced"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="partnerapplication",
            name="partner_type",
            field=models.CharField(
                choices=[
                    ("reseller", "Reseller"),
                    ("implementation", "Implementation Partner"),
                    ("technology", "Technology Partner"),
                    ("isv", "ISV / Software Partner"),
                    ("referral", "Referral Partner"),
                    ("strategic", "Strategic Alliance"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="partnerapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("on_hold", "On Hold"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productlisting",
            name="seo_keywords",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
