# Generated by Django 6.0.7 on 2026-09-28 07:23

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('bank_statement', 'Bank Statement')], max_length=30)),
                ('file', models.FileField(upload_to='cycom_docai/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed'), ('reviewed', 'Reviewed')], default='pending', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('confidence_notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('reviewed_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cycom_docai_parsed_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='cycom_docai_tenant__c76104_idx')],
            },
        ),
    ]
