# Generated by Django 6.0.7 on 2026-09-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_docai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddocument',
            name='applied_record_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parseddocument',
            name='applied_record_type',
            field=models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('purchase_order', 'Purchase Order')], max_length=30),
        ),
        migrations.AlterField(
            model_name='parseddocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed'), ('reviewed', 'Reviewed'), ('applied', 'Applied')], default='pending', max_length=20),
        ),
    ]
