# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDSAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('encounter_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('drug_interaction', 'Drug interaction'), ('drug_allergy', 'Drug allergy'), ('dose_warning', 'Dose warning'), ('renal_adjustment', 'Renal dose adjustment'), ('pregnancy_contraindication', 'Pregnancy contraindication'), ('pediatric_dose', 'Pediatric dose check'), ('duplicate_therapy', 'Duplicate therapy'), ('sepsis_early_warning', 'Sepsis early warning'), ('readmission_risk', 'Readmission risk'), ('fall_risk', 'Fall risk'), ('deterioration', 'Deterioration risk')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('score', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('acknowledged_by', models.UUIDField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('overridden', models.BooleanField(default=False)),
                ('override_reason', models.CharField(blank=True, max_length=400)),
            ],
            options={
                'db_table': 'cymed_cds_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ICDCodeSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('encounter_id', models.UUIDField(db_index=True)),
                ('source_text', models.TextField()),
                ('suggestions', models.JSONField(default=list)),
                ('accepted_code', models.CharField(blank=True, max_length=20)),
                ('accepted_by', models.UUIDField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('model_version', models.CharField(default='cymed-icd11-nlp-v1', max_length=50)),
            ],
            options={
                'db_table': 'cymed_cds_icd_suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('encounter_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('score_type', models.CharField(choices=[('sepsis', 'Sepsis (qSOFA / SIRS)'), ('news2', 'NEWS2 (National Early Warning Score)'), ('mews', 'MEWS'), ('readmission_30d', '30-day readmission'), ('mortality_hospital', 'In-hospital mortality'), ('fall_morse', 'Fall risk (Morse)'), ('braden', 'Braden pressure injury')], db_index=True, max_length=40)),
                ('value', models.DecimalField(decimal_places=3, max_digits=8)),
                ('band', models.CharField(blank=True, max_length=20)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('model_version', models.CharField(default='v1', max_length=50)),
            ],
            options={
                'db_table': 'cymed_cds_risk_scores',
                'ordering': ['-created_at'],
            },
        ),
    ]
