# Generated by Django 6.0.7 on 2026-09-21 19:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycom_hr', '0005_contract_attributes_contract_created_by_and_more'),
        ('cycom_recruitment', '0002_applicant_attributes_applicant_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_email', models.EmailField(blank=True, max_length=254)),
                ('candidate_phone', models.CharField(blank=True, max_length=50)),
                ('job_title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Screening'), ('interviewing', 'Interviewing'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus_paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='cycom_recruitment.applicant')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='cycom_hr.employee')),
            ],
            options={
                'db_table': 'cycom_referrals',
                'ordering': ['-created_at'],
            },
        ),
    ]
