# Generated by Django 6.1.1 on 2026-09-04 03:04

import platform.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_hospital_nursing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursingassessment',
            name='nursing_summary',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='nursingcareplan',
            name='activities',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='nursingcareplan',
            name='goals',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='nursinghandover',
            name='assessment_recommendation',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='nursinghandover',
            name='situation_background',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
    ]
