# Generated by Django 6.0.7 on 2026-10-02 19:26

import django.db.models.deletion
import django.utils.timezone
import platform.common.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_hospital_nursing', '0004_nursingassessment_attributes_and_more'),
        ('cymed_pharmacy_prescriptions', '0002_medicationhistory_attributes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('admission_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('given', 'Given'), ('held', 'Held'), ('refused', 'Refused by patient'), ('missed', 'Missed')], db_index=True, default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('administered_at', models.DateTimeField(blank=True, null=True)),
                ('administered_by', models.CharField(blank=True, max_length=255)),
                ('witnessed_by', models.CharField(blank=True, max_length=255)),
                ('dose_given', models.CharField(blank=True, max_length=100)),
                ('dose_unit', models.CharField(blank=True, max_length=50)),
                ('route', models.CharField(blank=True, max_length=100)),
                ('site', models.CharField(blank=True, max_length=100)),
                ('patient_barcode_verified', models.BooleanField(default=False)),
                ('medication_barcode_verified', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('notes', platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True)),
                ('medication_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrations', to='cymed_pharmacy_prescriptions.medicationorder')),
            ],
            options={
                'db_table': 'cymed_nursing_medication_administrations',
                'ordering': ['scheduled_at', 'administered_at'],
                'indexes': [models.Index(fields=['tenant_id', 'admission_id', 'status'], name='cymed_nursi_tenant__1feadd_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('scheduled_at__isnull', False)), fields=('medication_order', 'scheduled_at'), name='uniq_mar_dose_per_order_slot')],
            },
        ),
    ]
