# Generated by Django 6.0.7 on 2026-08-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_org', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='campus',
            name='uniq_campus_code_per_group',
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('tenant_id', 'code'), name='uniq_campus_code_per_group'),
        ),
    ]
