# Generated by Django 6.1 on 2026-08-12 12:53

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SifRefId',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('object_type', models.CharField(help_text='SIF object name, e.g. StudentPersonal.', max_length=60)),
                ('local_id', models.CharField(max_length=64)),
                ('refid', models.UUIDField()),
                ('source_local_id', models.CharField(blank=True, max_length=64)),
                ('source_description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'cyed_sif_refids',
                'ordering': ['object_type', 'local_id'],
                'indexes': [models.Index(fields=['tenant_id', 'refid'], name='idx_sif_refid_lookup')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'object_type', 'local_id'), name='uniq_sif_refid_per_object'), models.UniqueConstraint(fields=('tenant_id', 'refid'), name='uniq_sif_refid_value')],
            },
        ),
    ]
