# Generated by Django 6.0.7 on 2026-07-20 12:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSubscriptionInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('card_placeholder', 'Card (not yet available)')], default='bank_transfer', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('paid', 'Paid'), ('void', 'Void')], default='pending', max_length=20)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='platform_tenant.tenantsubscription')),
            ],
            options={
                'db_table': 'platform_tenant_subscription_invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
