# Generated by Django 6.0.7 on 2026-08-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_tenant', '0002_tenantsubscriptioninvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsubscriptioninvoice',
            name='provider',
            field=models.CharField(default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='tenantsubscriptioninvoice',
            name='provider_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
