# Generated by Django 6.1.1 on 2026-09-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_tenant', '0003_tenantsubscriptioninvoice_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='compliance_flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tenant',
            name='encryption_key_ref',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tenant',
            name='flavor_set',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tenant',
            name='residency_region',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
