# Generated by Django 6.1.1 on 2026-09-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_tenant', '0005_backfill_residency_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
