# Generated by Django 6.0.7 on 2026-08-06 16:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyed_sis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('identifier', models.CharField(max_length=50)),
                ('rego', models.CharField(blank=True, max_length=20)),
                ('make_model', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveSmallIntegerField(default=30)),
                ('driver_name', models.CharField(blank=True, max_length=255)),
                ('driver_license', models.CharField(blank=True, max_length=50)),
                ('supervisor_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cyed_transport_buses',
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='TransportZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('min_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='AUD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cyed_transport_zones',
                'ordering': ['min_km'],
            },
        ),
        migrations.CreateModel(
            name='RfidBoardingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('event_type', models.CharField(choices=[('board', 'Boarded'), ('alight', 'Alighted')], default='board', max_length=10)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boarding_events', to='cyed_transport.bus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_events', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_transport_boarding_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('trip_type', models.CharField(choices=[('full_trip', 'Full Trip (Two-Way)'), ('half_morning', 'Half Trip — Morning'), ('half_afternoon', 'Half Trip — Afternoon'), ('custom', 'Custom / Multi-Address')], default='full_trip', max_length=20)),
                ('pickup_address', models.CharField(blank=True, max_length=500)),
                ('dropoff_address', models.CharField(blank=True, max_length=500)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('assigned_bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='cyed_transport.bus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_subscriptions', to='cyed_sis.student')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='cyed_transport.transportzone')),
            ],
            options={
                'db_table': 'cyed_transport_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('weekday', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday')], max_length=3)),
                ('pickup_address', models.CharField(blank=True, max_length=500)),
                ('dropoff_address', models.CharField(blank=True, max_length=500)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_stops', to='cyed_transport.transportsubscription')),
            ],
            options={
                'db_table': 'cyed_transport_custom_stops',
                'ordering': ['weekday'],
                'constraints': [models.UniqueConstraint(fields=('subscription', 'weekday'), name='uniq_custom_stop_per_weekday')],
            },
        ),
        migrations.AddConstraint(
            model_name='transportsubscription',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'student'), name='uniq_transport_sub_per_student'),
        ),
    ]
