# Generated by Django 6.1 on 2026-09-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_transport', '0002_busroute_routestop_buslocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bus',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='buslocation',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='buslocation',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='buslocation',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='buslocation',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='busroute',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='busroute',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='busroute',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='busroute',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='customstop',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customstop',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='customstop',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='customstop',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='rfidboardingevent',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='rfidboardingevent',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='rfidboardingevent',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='rfidboardingevent',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='routestop',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='routestop',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transportsubscription',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transportsubscription',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transportsubscription',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='transportsubscription',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transportzone',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transportzone',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transportzone',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='transportzone',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
