# Generated by Django 6.0.7 on 2026-09-25 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymart_orders', '0002_marketplaceorder_delivery_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('center_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('center_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cymart_delivery_zone',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=32)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('motorcycle', 'Motorcycle'), ('car', 'Car')], default='motorcycle', max_length=12)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cymart_driver',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('picked_up', 'Picked up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='assigned', max_length=12)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignment', to='cymart_orders.marketplaceorder')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='cymart_delivery.driver')),
            ],
            options={
                'db_table': 'cymart_delivery_assignment',
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('picked_up', 'Picked up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cymart_delivery.deliveryassignment')),
            ],
            options={
                'db_table': 'cymart_tracking_event',
                'ordering': ['occurred_at'],
            },
        ),
    ]
