# Generated by Django 6.0.7 on 2026-09-26 10:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymart_delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='stop_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DeliveryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='cymart_delivery.driver')),
            ],
            options={
                'db_table': 'cymart_delivery_run',
            },
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cymart_delivery.deliveryrun'),
        ),
    ]
