# Generated by Django 6.0.7 on 2026-07-21 10:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'db_table': 'cycom_localization_currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('country_code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('compliance_region', models.CharField(max_length=10)),
                ('default_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurisdictions', to='cycom_localization.currency')),
            ],
            options={
                'db_table': 'cycom_localization_jurisdictions',
                'ordering': ['country_code'],
            },
        ),
    ]
