# Generated by Django 6.0.7 on 2026-07-19 18:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycom_accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='JOD', max_length=10)),
                ('expense_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='cycom_expense_receipts/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted')], default='draft', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('rejection_reason', models.TextField(blank=True)),
                ('expense_account', models.ForeignKey(help_text='GL expense account debited when this expense is posted.', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='cycom_accounting.account')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cycom_accounting.journalentry')),
                ('payable_account', models.ForeignKey(help_text='GL liability/cash account credited when this expense is posted.', on_delete=django.db.models.deletion.PROTECT, related_name='expense_payables', to='cycom_accounting.account')),
            ],
            options={
                'db_table': 'cycom_expenses',
                'ordering': ['-expense_date'],
            },
        ),
    ]
