# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('origin_facility_id', models.UUIDField(blank=True, null=True)),
                ('destination_facility_id', models.UUIDField(blank=True, null=True)),
                ('schedule_kind', models.CharField(choices=[('fixed', 'Fixed'), ('on_demand', 'On Demand'), ('hub_and_spoke', 'Hub and Spoke')], default='fixed', max_length=32)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_lab_courier_tracking_route',
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('run_date', models.DateField()),
                ('driver_id', models.UUIDField(blank=True, null=True)),
                ('vehicle_plate', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cold_chain', models.BooleanField(default=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='cymed_lab_courier_tracking.route')),
            ],
            options={
                'db_table': 'cymed_lab_courier_tracking_run',
            },
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('specimen_barcodes', models.JSONField(blank=True, default=list)),
                ('total_specimens', models.IntegerField(default=0)),
                ('driver_signature_url', models.URLField(blank=True)),
                ('receiver_signature_url', models.URLField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifests', to='cymed_lab_courier_tracking.run')),
            ],
            options={
                'db_table': 'cymed_lab_courier_tracking_manifest',
            },
        ),
        migrations.CreateModel(
            name='ChainOfCustodyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('specimen_barcode', models.CharField(db_index=True, max_length=64)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kind', models.CharField(choices=[('collected', 'Collected'), ('handed_to_courier', 'Handed to Courier'), ('in_transit', 'In Transit'), ('arrived_at_hub', 'Arrived at Hub'), ('departed_hub', 'Departed Hub'), ('delivered_to_lab', 'Delivered to Lab'), ('accessioned', 'Accessioned'), ('rejected', 'Rejected'), ('lost', 'Lost')], max_length=32)),
                ('actor_profile_id', models.UUIDField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('signature_url', models.URLField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_events', to='cymed_lab_courier_tracking.run')),
            ],
            options={
                'db_table': 'cymed_lab_courier_tracking_chain_of_custody_event',
            },
        ),
        migrations.CreateModel(
            name='TransportTemperature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('specimen_barcode', models.CharField(db_index=True, max_length=64)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature_c', models.DecimalField(decimal_places=2, max_digits=6)),
                ('breach', models.BooleanField(default=False)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to='cymed_lab_courier_tracking.run')),
            ],
            options={
                'db_table': 'cymed_lab_courier_tracking_transport_temperature',
            },
        ),
    ]
