# Generated by Django 6.0.7 on 2026-07-16 18:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycom_accounting', '0001_initial'),
        ('cycom_hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('currency', models.CharField(default='JOD', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=20)),
                ('deduction_recovery_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs_deduction', to='cycom_accounting.account')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cycom_accounting.journalentry')),
                ('salary_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs_expense', to='cycom_accounting.account')),
                ('salary_payable_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs_payable', to='cycom_accounting.account')),
            ],
            options={
                'db_table': 'cycom_payroll_runs',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('date', models.DateField()),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('biometric_import', 'Biometric Import')], default='manual', max_length=20)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='cycom_hr.employee')),
            ],
            options={
                'db_table': 'cycom_payroll_attendance',
                'ordering': ['-date'],
                'unique_together': {('tenant_id', 'employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowances_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('late_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=20)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='cycom_hr.contract')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='cycom_hr.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='cycom_payroll.payrollrun')),
            ],
            options={
                'db_table': 'cycom_payroll_payslips',
                'ordering': ['employee__employee_number'],
                'unique_together': {('payroll_run', 'employee')},
            },
        ),
    ]
