# Generated by Django 6.0.7 on 2026-07-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='income_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='social_security_employee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='social_security_employer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
