# Generated by Django 6.0.7 on 2026-09-10 07:51
# A-4: give PayrollRun a gapless per-tenant number. Existing rows predate the
# sequence, so backfill them (PR-<year>-<NNN>, ordered by period_start) between
# adding the column and adding the unique constraint.

from django.db import migrations, models


def backfill_numbers(apps, schema_editor):
    PayrollRun = apps.get_model("cycom_payroll", "PayrollRun")
    by_tenant = {}
    for run in PayrollRun.objects.order_by("tenant_id", "period_start", "created_at"):
        seq = by_tenant.get(run.tenant_id)
        year = run.period_start.year
        if seq is None or seq[0] != year:
            seq = [year, 0]
            by_tenant[run.tenant_id] = seq
        seq[1] += 1
        run.number = f"PR-{year}-{seq[1]:03d}"
        run.save(update_fields=["number"])


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_payroll', '0003_attendancerecord_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RunPython(backfill_numbers, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='payrollrun',
            unique_together={('tenant_id', 'number')},
        ),
    ]
