# Generated by Django 6.0.7 on 2026-08-05 12:08

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(max_length=50)),
                ('learning_area', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('year_level', models.PositiveSmallIntegerField(default=0)),
                ('strand', models.CharField(blank=True, max_length=150)),
                ('sub_strand', models.CharField(blank=True, max_length=150)),
                ('content_description', models.TextField(blank=True)),
                ('achievement_standard', models.TextField(blank=True)),
                ('elaboration', models.TextField(blank=True)),
                ('framework', models.CharField(default='ACARA v9', max_length=50)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cyed_curriculum_outcomes',
                'ordering': ['learning_area', 'year_level', 'code'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'code', 'framework'), name='uniq_outcome_code_framework')],
            },
        ),
    ]
