# Generated by Django 6.0.7 on 2026-08-09 18:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MracImportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('set_code', models.CharField(blank=True, max_length=20)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('framework', models.CharField(default='ACARA v9', max_length=50)),
                ('statements_seen', models.PositiveIntegerField(default=0)),
                ('outcomes_created', models.PositiveIntegerField(default=0)),
                ('outcomes_updated', models.PositiveIntegerField(default=0)),
                ('elaborations_linked', models.PositiveIntegerField(default=0)),
                ('capability_links', models.PositiveIntegerField(default=0)),
                ('priority_links', models.PositiveIntegerField(default=0)),
                ('standards_upserted', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('attribution', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cyed_curriculum_mrac_import_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='curriculumoutcome',
            name='is_elaboration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curriculumoutcome',
            name='parent_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elaborations', to='cyed_curriculum.curriculumoutcome'),
        ),
        migrations.AddField(
            model_name='curriculumoutcome',
            name='source_uri',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='AchievementStandard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('learning_area', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('year_level', models.PositiveSmallIntegerField(default=0)),
                ('standard_text', models.TextField(blank=True)),
                ('framework', models.CharField(default='ACARA v9', max_length=50)),
                ('source_uri', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cyed_curriculum_achievement_standards',
                'ordering': ['learning_area', 'year_level'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'learning_area', 'subject', 'year_level', 'framework'), name='uniq_achievement_standard_area_year')],
            },
        ),
        migrations.AddField(
            model_name='curriculumoutcome',
            name='achievement_standard_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcomes', to='cyed_curriculum.achievementstandard'),
        ),
        migrations.CreateModel(
            name='CrossCurriculumPriority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('framework', models.CharField(default='ACARA v9', max_length=50)),
                ('source_uri', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cyed_curriculum_cross_curriculum_priorities',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'code', 'framework'), name='uniq_ccp_code_framework')],
            },
        ),
        migrations.AddField(
            model_name='curriculumoutcome',
            name='cross_curriculum_priorities',
            field=models.ManyToManyField(blank=True, db_table='cyed_curriculum_outcome_priorities', related_name='outcomes', to='cyed_curriculum.crosscurriculumpriority'),
        ),
        migrations.CreateModel(
            name='GeneralCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('framework', models.CharField(default='ACARA v9', max_length=50)),
                ('source_uri', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cyed_curriculum_general_capabilities',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'code', 'framework'), name='uniq_gencap_code_framework')],
            },
        ),
        migrations.AddField(
            model_name='curriculumoutcome',
            name='general_capabilities',
            field=models.ManyToManyField(blank=True, db_table='cyed_curriculum_outcome_general_capabilities', related_name='outcomes', to='cyed_curriculum.generalcapability'),
        ),
    ]
