# Generated by Django 6.0.7 on 2026-10-02 19:27

import django.db.models.deletion
import django.utils.timezone
import platform.common.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_patients', '0008_encrypt_patient_name_mrn'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('general', 'General question'), ('prescription', 'Prescription / refill'), ('results', 'Test results'), ('appointment', 'Appointment'), ('billing', 'Billing')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=10)),
                ('assigned_to', models.CharField(blank=True, db_index=True, max_length=255)),
                ('last_message_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='cymed_patients.patient')),
            ],
            options={
                'db_table': 'cymed_message_threads',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('sender_type', models.CharField(choices=[('patient', 'Patient'), ('staff', 'Care team')], max_length=10)),
                ('sender', models.CharField(max_length=255)),
                ('body', platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cymed_messaging.messagethread')),
            ],
            options={
                'db_table': 'cymed_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
