# Generated by Django 6.0.7 on 2026-07-15 12:49

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TerminologyAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('provider', models.CharField(db_index=True, max_length=100)),
                ('operation', models.CharField(db_index=True, max_length=100)),
                ('query', models.CharField(blank=True, max_length=1000)),
                ('code', models.CharField(blank=True, max_length=500)),
                ('records_returned', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('requested_by', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'platform_terminology_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
