# Generated by Django 5.1.15 on 2026-06-22 20:33

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cymed_patients", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsurancePlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("plan_name", models.CharField(max_length=255)),
                ("plan_code", models.CharField(max_length=100)),
                (
                    "copay_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
            ],
            options={
                "db_table": "cymed_clinic_insurance_plans",
            },
        ),
        migrations.CreateModel(
            name="Payer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("name", models.CharField(max_length=255)),
                ("payer_code", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "cymed_clinic_insurance_payers",
            },
        ),
        migrations.CreateModel(
            name="AuthorizationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("requested_service", models.CharField(max_length=255)),
                ("clinical_justification", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cymed_patients.patient"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cymed_clinic_insurance_bridge.insuranceplan",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_clinic_insurance_auth_requests",
            },
        ),
        migrations.CreateModel(
            name="AuthorizationResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("decision_date", models.DateTimeField(auto_now_add=True)),
                ("authorization_number", models.CharField(blank=True, max_length=100)),
                ("denial_reason", models.TextField(blank=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="cymed_clinic_insurance_bridge.authorizationrequest",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_clinic_insurance_auth_responses",
            },
        ),
        migrations.CreateModel(
            name="EligibilityCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("is_eligible", models.BooleanField(default=False)),
                ("response_details", models.JSONField(default=dict)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_checks",
                        to="cymed_patients.patient",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cymed_clinic_insurance_bridge.insuranceplan",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_clinic_insurance_eligibility",
            },
        ),
        migrations.AddField(
            model_name="insuranceplan",
            name="payer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to="cymed_clinic_insurance_bridge.payer",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="insuranceplan",
            unique_together={("payer", "plan_code")},
        ),
    ]
