# Generated by Django 6.1.1 on 2026-09-04 07:14

import platform.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_clinic_insurance_bridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationrequest',
            name='clinical_justification',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='authorizationresponse',
            name='denial_reason',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
    ]
