# Generated by Django 6.0.7 on 2026-07-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='probability',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
