# Generated by Django 6.1.1 on 2026-09-04 03:15

import platform.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborder',
            name='clinical_notes',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
    ]
