# Generated by Django 6.0.7 on 2026-07-19 19:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DividendDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='JOD', max_length=10)),
                ('distribution_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('computed', 'Computed'), ('paid', 'Paid')], default='draft', max_length=10)),
            ],
            options={
                'db_table': 'cycom_equity_dividend_distributions',
                'ordering': ['-distribution_date'],
            },
        ),
        migrations.CreateModel(
            name='ShareClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('class_type', models.CharField(choices=[('common', 'Common'), ('preferred', 'Preferred')], default='common', max_length=10)),
                ('liquidation_preference_multiple', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='e.g. 1.00 for 1x, 2.00 for 2x. Always 0 for common.', max_digits=6)),
                ('seniority_rank', models.PositiveIntegerField(default=100, help_text='Lower is paid first. Only meaningful for preferred classes.')),
                ('is_participating', models.BooleanField(default=False, help_text="If true, this class takes its preference AND shares pro-rata in what's left.")),
                ('convert_to_common', models.BooleanField(default=False, help_text='Manual election: skip liquidation preference entirely, join the common pro-rata pool instead.')),
                ('conversion_ratio', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='How many common-equivalent shares each share of this class counts as when participating pro-rata.', max_digits=8)),
            ],
            options={
                'db_table': 'cycom_equity_share_classes',
                'ordering': ['seniority_rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('holder_type', models.CharField(choices=[('founder', 'Founder'), ('employee', 'Employee'), ('investor', 'Investor'), ('other', 'Other')], default='other', max_length=20)),
            ],
            options={
                'db_table': 'cycom_equity_shareholders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShareGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('price_per_share', models.DecimalField(decimal_places=6, max_digits=14)),
                ('grant_date', models.DateField()),
                ('vesting_start_date', models.DateField(blank=True, null=True)),
                ('cliff_months', models.PositiveIntegerField(default=0)),
                ('vest_duration_months', models.PositiveIntegerField(default=0, help_text='0 means fully vested immediately (no cliff/vesting schedule).')),
                ('notes', models.TextField(blank=True)),
                ('share_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='cycom_equity.shareclass')),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='cycom_equity.shareholder')),
            ],
            options={
                'db_table': 'cycom_equity_share_grants',
                'ordering': ['grant_date'],
            },
        ),
        migrations.CreateModel(
            name='DividendAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('basis', models.CharField(choices=[('liquidation_preference', 'Liquidation Preference'), ('pro_rata', 'Pro-Rata Participation')], max_length=25)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='cycom_equity.dividenddistribution')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividend_allocations', to='cycom_equity.sharegrant')),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividend_allocations', to='cycom_equity.shareholder')),
            ],
            options={
                'db_table': 'cycom_equity_dividend_allocations',
                'ordering': ['shareholder__name'],
            },
        ),
    ]
