# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcosystemAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('patient_profile_id', models.UUIDField(db_index=True)),
                ('primary_country', models.CharField(blank=True, max_length=2)),
                ('balance_points', models.IntegerField(default=0)),
                ('lifetime_points', models.IntegerField(default=0)),
                ('current_tier', models.CharField(blank=True, max_length=64)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'cymed_eco_rewards_ecosystem_account',
            },
        ),
        migrations.CreateModel(
            name='EcosystemProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('currency_conversion', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=9)),
                ('redeem_ratio', models.DecimalField(decimal_places=4, default=Decimal('100'), max_digits=9)),
                ('partner_tenant_ids', models.JSONField(default=list)),
                ('cross_country_convertible', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_eco_rewards_ecosystem_program',
            },
        ),
        migrations.CreateModel(
            name='EcosystemPointsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kind', models.CharField(choices=[('earn', 'Earn'), ('redeem', 'Redeem'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('expire', 'Expire'), ('adjust', 'Adjust')], max_length=32)),
                ('points', models.IntegerField()),
                ('source_tenant_id', models.UUIDField(blank=True, null=True)),
                ('reference_kind', models.CharField(blank=True, max_length=32)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cymed_eco_rewards.ecosystemaccount')),
            ],
            options={
                'db_table': 'cymed_eco_rewards_ecosystem_points_event',
            },
        ),
        migrations.AddField(
            model_name='ecosystemaccount',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='cymed_eco_rewards.ecosystemprogram'),
        ),
        migrations.CreateModel(
            name='EcosystemReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('cost_points', models.IntegerField()),
                ('monetary_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('redeemable_at_tenant_ids', models.JSONField(default=list)),
                ('redeemable_at_kinds', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('stock_left', models.IntegerField(default=-1)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='cymed_eco_rewards.ecosystemprogram')),
            ],
            options={
                'db_table': 'cymed_eco_rewards_ecosystem_reward',
            },
        ),
        migrations.CreateModel(
            name='EcosystemRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('points_spent', models.IntegerField()),
                ('code', models.CharField(max_length=64)),
                ('redeemed_at_tenant_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('used', 'Used'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='issued', max_length=32)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='cymed_eco_rewards.ecosystemaccount')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='cymed_eco_rewards.ecosystemreward')),
            ],
            options={
                'db_table': 'cymed_eco_rewards_ecosystem_redemption',
            },
        ),
        migrations.CreateModel(
            name='EcosystemTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('name_ar', models.CharField(blank=True, max_length=128)),
                ('threshold_points', models.IntegerField()),
                ('benefits', models.JSONField(default=dict)),
                ('priority', models.IntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='cymed_eco_rewards.ecosystemprogram')),
            ],
            options={
                'db_table': 'cymed_eco_rewards_ecosystem_tier',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ecosystemaccount',
            unique_together={('program', 'patient_profile_id')},
        ),
    ]
