# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import products.cymed.rcm.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim837',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('claim_number', models.CharField(default=products.cymed.rcm.models._default_claim_number, max_length=50, unique=True)),
                ('bill_id', models.UUIDField(db_index=True)),
                ('encounter_id', models.UUIDField(db_index=True)),
                ('patient_profile_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(choices=[('professional', '837P Professional'), ('institutional', '837I Institutional')], default='professional', max_length=20)),
                ('payer_code', models.CharField(db_index=True, max_length=50)),
                ('payer_country', models.CharField(default='SA', max_length=2)),
                ('diagnosis_codes', models.JSONField(default=list)),
                ('procedure_codes', models.JSONField(default=list)),
                ('charge_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scrubbed', 'Scrubbed'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('denied', 'Denied'), ('appealed', 'Appealed')], db_index=True, default='draft', max_length=20)),
                ('scrub_errors', models.JSONField(blank=True, default=list)),
                ('denial_risk', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('denial_risk_drivers', models.JSONField(blank=True, default=list)),
                ('x12_payload', models.TextField(blank=True)),
                ('fhir_payload', models.JSONField(blank=True, default=dict)),
                ('external_reference', models.CharField(blank=True, max_length=200)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('denied_at', models.DateTimeField(blank=True, null=True)),
                ('dso_days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cymed_rcm_claims',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppealCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('level', models.IntegerField(choices=[(1, 'First-level'), (2, 'Second-level'), (3, 'External review')], default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('won', 'Won'), ('lost', 'Lost'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('denial_codes_addressed', models.JSONField(default=list)),
                ('appeal_letter_html', models.TextField(blank=True)),
                ('supporting_docs', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('recovered_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='cymed_rcm.claim837')),
            ],
            options={
                'db_table': 'cymed_rcm_appeals',
            },
        ),
        migrations.CreateModel(
            name='ClaimResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('outcome', models.CharField(choices=[('accepted', 'Accepted'), ('partial', 'Partial'), ('rejected', 'Rejected'), ('denied', 'Denied'), ('paid', 'Paid')], max_length=20)),
                ('payer_reference', models.CharField(blank=True, max_length=200)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('adjustments', models.JSONField(blank=True, default=list)),
                ('denial_codes', models.JSONField(blank=True, default=list)),
                ('remittance_advice_raw', models.JSONField(blank=True, default=dict)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='cymed_rcm.claim837')),
            ],
            options={
                'db_table': 'cymed_rcm_claim_responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DenialCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code_type', models.CharField(choices=[('carc', 'CARC'), ('rarc', 'RARC'), ('local', 'Payer-specific')], max_length=10)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('description', models.TextField()),
                ('is_appealable', models.BooleanField(default=True)),
                ('default_appeal_strategy', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'cymed_rcm_denial_codes',
                'unique_together': {('code_type', 'code')},
            },
        ),
        migrations.CreateModel(
            name='EligibilityCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('policy_id', models.UUIDField(db_index=True)),
                ('service_code', models.CharField(db_index=True, max_length=50)),
                ('covered', models.BooleanField()),
                ('co_pay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('requires_preauth', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('raw', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'cymed_rcm_eligibility_cache',
                'indexes': [models.Index(fields=['policy_id', 'service_code', 'expires_at'], name='cymed_rcm_e_policy__dcd27f_idx')],
            },
        ),
    ]
