# Generated by Django 6.0.7 on 2026-07-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='marital',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('cohabitant', 'Legal Cohabitant'), ('divorced', 'Divorced'), ('widower', 'Widower')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='spouse_employed',
            field=models.BooleanField(default=False),
        ),
    ]
