# Generated by Django 6.1.1 on 2026-09-04 02:25

import platform.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_hr', '0002_employee_marital_employee_spouse_employed'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email_bidx',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=platform.common.fields.EncryptedText(blank=True, blind_index=True, classification='pii', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=platform.common.fields.EncryptedText(blank=True, classification='pii', default=b'', editable=True),
        ),
    ]
