# Generated by Django 6.0.7 on 2026-09-25 20:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_hr', '0005_contract_attributes_contract_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('iqama', 'Iqama / Work Permit'), ('visa', 'Visa'), ('license', 'Driving License'), ('health_certificate', 'Health Certificate'), ('other', 'Other')], max_length=30)),
                ('number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cycom_hr.employee')),
            ],
            options={
                'db_table': 'cycom_hr_employee_documents',
                'ordering': ['expiry_date'],
            },
        ),
    ]
