# Generated by Django 6.0.6 on 2026-07-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantsettings_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='commission_policy_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='delivery_policy_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='marketplace_category_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='branch',
            name='marketplace_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='settlement_policy_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='marketplace_agreement_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='marketplace_agreement_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='marketplace_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='marketplace_status',
            field=models.CharField(choices=[('not_applied', 'Not Applied'), ('application_pending', 'Application Pending'), ('documents_required', 'Documents Required'), ('compliance_review', 'Compliance Review'), ('approved', 'Approved'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected'), ('terminated', 'Terminated')], default='not_applied', max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='merchant_verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=16),
        ),
        migrations.AddField(
            model_name='company',
            name='operates_customer_facing_store',
            field=models.BooleanField(default=True),
        ),
    ]
