# Generated by Django 6.0.6 on 2026-06-23 07:48

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedicationReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("patient_id", models.UUIDField(db_index=True)),
                ("encounter_id", models.UUIDField(blank=True, null=True)),
                ("admission_id", models.UUIDField(blank=True, null=True)),
                ("pharmacist_id", models.UUIDField(db_index=True)),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("dur", "Drug Utilization Review"),
                            ("cmr", "Comprehensive Medication Review"),
                            ("tmr", "Targeted Medication Review"),
                            ("admission", "Admission Medication Review"),
                            ("discharge", "Discharge Medication Review"),
                            ("transfer", "Transfer Medication Review"),
                        ],
                        default="dur",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=30,
                    ),
                ),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("medications_reviewed", models.JSONField(default=list)),
                ("diagnoses_considered", models.JSONField(default=list)),
                ("lab_values_considered", models.JSONField(default=dict)),
                (
                    "polypharmacy_risk",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("ai_polypharmacy_score", models.FloatField(default=0.0)),
                ("adherence_score", models.FloatField(blank=True, null=True)),
                ("clinical_summary", models.TextField(blank=True)),
                ("therapy_gaps", models.TextField(blank=True)),
                ("optimization_notes", models.TextField(blank=True)),
                ("interventions_count", models.PositiveSmallIntegerField(default=0)),
                ("recommendations_count", models.PositiveSmallIntegerField(default=0)),
                ("accepted_recommendations", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "cymed_clinical_medication_reviews",
                "indexes": [
                    models.Index(
                        fields=["patient_id", "status"], name="cymed_clini_patient_d74a6b_idx"
                    ),
                    models.Index(
                        fields=["pharmacist_id", "scheduled_date"],
                        name="cymed_clini_pharmac_90a4d9_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "review_type"], name="cymed_clini_tenant__44d4af_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MedicationTherapyManagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("patient_id", models.UUIDField(db_index=True)),
                ("pharmacist_id", models.UUIDField()),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Assessment"),
                            ("follow_up", "Follow-Up Session"),
                            ("annual", "Annual Comprehensive Review"),
                            ("targeted", "Targeted Intervention"),
                        ],
                        default="initial",
                        max_length=30,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveSmallIntegerField(default=0)),
                ("program_name", models.CharField(blank=True, max_length=200)),
                ("conditions_addressed", models.JSONField(default=list)),
                ("medications_addressed", models.JSONField(default=list)),
                ("goals_set", models.TextField(blank=True)),
                ("barriers_identified", models.TextField(blank=True)),
                ("action_plan", models.TextField(blank=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("patient_satisfaction", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("billing_code", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "cymed_medication_therapy_mgmt",
                "ordering": ["-scheduled_date"],
                "indexes": [
                    models.Index(
                        fields=["patient_id", "session_type"], name="cymed_medic_patient_8442ca_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ClinicalIntervention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("patient_id", models.UUIDField(db_index=True)),
                ("pharmacist_id", models.UUIDField()),
                ("prescriber_id", models.UUIDField(blank=True, null=True)),
                (
                    "intervention_type",
                    models.CharField(
                        choices=[
                            ("dose_optimization", "Dose Optimization"),
                            ("drug_substitution", "Drug Substitution"),
                            ("therapy_addition", "Therapy Addition"),
                            ("therapy_discontinuation", "Therapy Discontinuation"),
                            ("drug_interaction_resolution", "Drug Interaction Resolution"),
                            ("allergy_resolution", "Allergy Conflict Resolution"),
                            ("compliance_counseling", "Compliance Counseling"),
                            ("cost_optimization", "Cost Optimization"),
                            ("route_change", "Route of Administration Change"),
                            ("monitoring_recommendation", "Monitoring Recommendation"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("problem_identified", models.TextField()),
                ("intervention_action", models.TextField()),
                ("drug_code", models.CharField(blank=True, max_length=100)),
                ("drug_name", models.CharField(blank=True, max_length=500)),
                ("icd11_code", models.CharField(blank=True, max_length=20)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted by Prescriber"),
                            ("partially_accepted", "Partially Accepted"),
                            ("declined", "Declined by Prescriber"),
                            ("no_action_needed", "No Action Needed"),
                            ("pending", "Pending Prescriber Response"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "clinical_significance",
                    models.CharField(
                        choices=[("minor", "Minor"), ("moderate", "Moderate"), ("major", "Major")],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                ("outcome_notes", models.TextField(blank=True)),
                (
                    "cost_saving_estimate",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("intervened_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="cymed_pharmacy_clinical.medicationreview",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_clinical_interventions",
                "ordering": ["-intervened_at"],
                "indexes": [
                    models.Index(
                        fields=["patient_id", "outcome"], name="cymed_clini_patient_fce2ce_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PharmacistRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("patient_id", models.UUIDField(db_index=True)),
                ("pharmacist_id", models.UUIDField()),
                ("prescriber_id", models.UUIDField(blank=True, null=True)),
                ("recommendation_text", models.TextField()),
                ("rationale", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                ("drug_code", models.CharField(blank=True, max_length=100)),
                ("drug_name", models.CharField(blank=True, max_length=500)),
                ("evidence_references", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted to Prescriber"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("prescriber_response", models.TextField(blank=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="cymed_pharmacy_clinical.medicationreview",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_pharmacist_recommendations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient_id", "status"], name="cymed_pharm_patient_f95bc8_idx"
                    )
                ],
            },
        ),
    ]
