# Generated by Django 5.1.15 on 2026-06-23 03:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('customer_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('customer_type', models.CharField(choices=[('clinic', 'Clinic / Medical Center'), ('hospital', 'Hospital'), ('hospital_group', 'Hospital Group'), ('ministry', 'Ministry of Health'), ('government', 'Government Agency'), ('network', 'Healthcare Network'), ('laboratory', 'Laboratory'), ('imaging_center', 'Imaging Center'), ('pharmacy_chain', 'Pharmacy Chain')], max_length=50)),
                ('country_code', models.CharField(max_length=10)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('active', 'Active Customer'), ('churned', 'Churned'), ('suspended', 'Suspended')], default='prospect', max_length=50)),
                ('csm_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cymed_commercial_customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('contract_number', models.CharField(max_length=100, unique=True)),
                ('contract_type', models.CharField(choices=[('saas', 'SaaS Agreement'), ('enterprise', 'Enterprise License Agreement'), ('government', 'Government Procurement Contract'), ('pilot', 'Pilot Agreement'), ('reseller', 'Reseller Agreement')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('negotiation', 'Under Negotiation'), ('signed', 'Signed'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=50)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_schedule', models.JSONField(default=list)),
                ('governing_law', models.CharField(blank=True, max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='commercial_customer_management.customer')),
            ],
            options={
                'db_table': 'cymed_commercial_customer_contracts',
            },
        ),
        migrations.CreateModel(
            name='CustomerDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('deployment_profile_code', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=100)),
                ('edition_code', models.CharField(max_length=100)),
                ('environment', models.CharField(default='production', max_length=50)),
                ('go_live_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='commercial_customer_management.customer')),
            ],
            options={
                'db_table': 'cymed_commercial_customer_deployments',
            },
        ),
        migrations.CreateModel(
            name='CustomerOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_code', models.CharField(max_length=100)),
                ('primary_contact_name', models.CharField(blank=True, max_length=255)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254)),
                ('primary_contact_phone', models.CharField(blank=True, max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='commercial_customer_management.customer')),
            ],
            options={
                'db_table': 'cymed_commercial_customer_organizations',
            },
        ),
        migrations.CreateModel(
            name='CustomerSuccessPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('plan_name', models.CharField(max_length=255)),
                ('health_score', models.PositiveSmallIntegerField(default=80)),
                ('nps_score', models.SmallIntegerField(blank=True, null=True)),
                ('adoption_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('next_qbr_date', models.DateField(blank=True, null=True)),
                ('renewal_risk', models.CharField(default='low', max_length=50)),
                ('milestones', models.JSONField(default=list)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_plans', to='commercial_customer_management.customer')),
            ],
            options={
                'db_table': 'cymed_commercial_customer_success_plans',
            },
        ),
    ]
