# Generated by Django 6.0.7 on 2026-08-06 17:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyed_timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstitutionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('absent_teacher', models.CharField(max_length=255)),
                ('day_of_week', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('generated_by', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'cyed_substitution_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubstitutionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('class_section_name', models.CharField(blank=True, max_length=150)),
                ('period_label', models.CharField(blank=True, max_length=50)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('original_teacher', models.CharField(blank=True, max_length=255)),
                ('substitute_teacher', models.CharField(blank=True, max_length=255)),
                ('covered', models.BooleanField(default=False)),
                ('timetable_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitutions', to='cyed_timetable.timetableslot')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cyed_substitution.substitutionplan')),
            ],
            options={
                'db_table': 'cyed_substitution_assignments',
                'ordering': ['start_time'],
            },
        ),
    ]
