# Generated by Django 6.1 on 2026-08-12 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_hr', '0004_staffleave_balance_override_by_and_more'),
        ('cyed_substitution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitutionassignment',
            name='gap_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='substitutionassignment',
            name='original_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_away', to='cyed_hr.staff'),
        ),
        migrations.AddField(
            model_name='substitutionassignment',
            name='substitute_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_assignments', to='cyed_hr.staff'),
        ),
        migrations.AddField(
            model_name='substitutionplan',
            name='absent_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absence_plans', to='cyed_hr.staff'),
        ),
    ]
