# Generated by Django 6.1 on 2026-08-14 08:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_hr', '0004_staffleave_balance_override_by_and_more'),
        ('cyed_org', '0002_remove_campus_uniq_campus_code_per_group_and_more'),
        ('cyed_substitution', '0002_substitutionassignment_gap_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliefTeacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('agency', models.CharField(blank=True, help_text='Blank if they are booked directly.', max_length=150)),
                ('subjects', models.CharField(blank=True, max_length=500)),
                ('year_levels', models.CharField(blank=True, max_length=100)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('half_day_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('wwcc_number', models.CharField(blank=True, max_length=100)),
                ('wwcc_expires_on', models.DateField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('registration_expires_on', models.DateField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=255)),
                ('verified_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('do_not_book', 'Do not book')], default='active', max_length=20)),
                ('do_not_book_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relief_teachers', to='cyed_org.campus')),
            ],
            options={
                'db_table': 'cyed_relief_teachers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ReliefBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('date', models.DateField()),
                ('periods', models.CharField(blank=True, help_text="e.g. 'P1, P2, P4'", max_length=255)),
                ('is_full_day', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled by school'), ('completed', 'Completed')], default='offered', max_length=20)),
                ('offered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('offered_by', models.CharField(blank=True, max_length=255)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_note', models.CharField(blank=True, max_length=255)),
                ('agreed_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cost_centre', models.CharField(blank=True, max_length=100)),
                ('covering_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relief_cover', to='cyed_hr.staff')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relief_bookings', to='cyed_substitution.substitutionplan')),
                ('relief_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='cyed_substitution.reliefteacher')),
            ],
            options={
                'db_table': 'cyed_relief_bookings',
                'ordering': ['-date', '-offered_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['offered', 'accepted'])), fields=('tenant_id', 'relief_teacher', 'date'), name='uniq_live_relief_booking_per_day')],
            },
        ),
        migrations.CreateModel(
            name='ReliefAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('date', models.DateField()),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('relief_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='cyed_substitution.reliefteacher')),
            ],
            options={
                'db_table': 'cyed_relief_availability',
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('relief_teacher', 'date'), name='uniq_relief_availability_per_day')],
            },
        ),
    ]
