# Generated by Django 6.0.7 on 2026-07-19 18:46

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('attendees', models.JSONField(blank=True, default=list, help_text='List of attendee emails.')),
                ('linked_model', models.CharField(blank=True, max_length=100)),
                ('linked_id', models.UUIDField(blank=True, null=True)),
                ('recurrence', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10)),
                ('organizer', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'cycom_calendar_events',
                'ordering': ['start_at'],
            },
        ),
    ]
