# Generated by Django 6.0.7 on 2026-10-02 19:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_pharmacy_prescriptions', '0002_medicationhistory_attributes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErxTransmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('network', models.CharField(choices=[('nphies', 'NPHIES (Saudi Arabia)'), ('wasfaty', 'Wasfaty (Saudi Arabia)'), ('hakeem', 'Hakeem (Jordan)'), ('fhir', 'Generic FHIR R4 endpoint')], max_length=20)),
                ('status', models.CharField(choices=[('blocked', 'Blocked by a pre-transmission rule'), ('not_configured', 'Network not configured'), ('sent', 'Sent, awaiting answer'), ('accepted', 'Accepted by network'), ('rejected', 'Rejected by network'), ('failed', 'Transport failure'), ('cancelled', 'Cancelled')], db_index=True, max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('sent_by', models.CharField(blank=True, max_length=255)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erx_transmissions', to='cymed_pharmacy_prescriptions.prescription')),
            ],
            options={
                'db_table': 'cymed_erx_transmissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PdmpCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('result', models.CharField(choices=[('clear', 'No concerning history'), ('review', 'History needs prescriber review'), ('not_configured', 'PDMP not configured'), ('failed', 'Lookup failed')], max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('checked_by', models.CharField(blank=True, max_length=255)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdmp_checks', to='cymed_pharmacy_prescriptions.prescription')),
            ],
            options={
                'db_table': 'cymed_erx_pdmp_checks',
                'ordering': ['-created_at'],
            },
        ),
    ]
