# Generated by Django 6.0.7 on 2026-07-15 09:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_facilities', '0001_initial'),
        ('cymed_organizations', '0001_initial'),
        ('cymed_patients', '0001_initial'),
        ('cymed_providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('encounter_type', models.CharField(choices=[('outpatient', 'Outpatient'), ('emergency', 'Emergency'), ('inpatient', 'Inpatient'), ('telemedicine', 'Telemedicine'), ('home_care', 'Home Care')], max_length=30)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='planned', max_length=30)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='cymed_facilities.facility')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='cymed_organizations.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='cymed_patients.patient')),
            ],
            options={
                'db_table': 'cymed_encounters',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EncounterDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('condition_code', models.CharField(max_length=100)),
                ('display', models.CharField(max_length=255)),
                ('use', models.CharField(choices=[('admission', 'Admission Diagnosis'), ('discharge', 'Discharge Diagnosis'), ('chief_complaint', 'Chief Complaint')], default='chief_complaint', max_length=50)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='cymed_encounters.encounter')),
            ],
            options={
                'db_table': 'cymed_encounter_diagnoses',
            },
        ),
        migrations.CreateModel(
            name='EncounterLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], max_length=30)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cymed_facilities.bed')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='cymed_encounters.encounter')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cymed_facilities.room')),
            ],
            options={
                'db_table': 'cymed_encounter_locations',
            },
        ),
        migrations.CreateModel(
            name='EncounterNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('note_text', models.TextField()),
                ('recorded_by', models.CharField(max_length=255)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cymed_encounters.encounter')),
            ],
            options={
                'db_table': 'cymed_encounter_notes',
            },
        ),
        migrations.CreateModel(
            name='EncounterParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('role', models.CharField(choices=[('lead', 'Lead Attending Physician'), ('attending', 'Attending Physician'), ('consulting', 'Consulting Physician'), ('referring', 'Referring Professional')], default='attending', max_length=50)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='cymed_encounters.encounter')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='cymed_providers.provider')),
            ],
            options={
                'db_table': 'cymed_encounter_participants',
            },
        ),
        migrations.CreateModel(
            name='EncounterReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('reason_code', models.CharField(max_length=100)),
                ('reason_text', models.TextField()),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='cymed_encounters.encounter')),
            ],
            options={
                'db_table': 'cymed_encounter_reasons',
            },
        ),
        migrations.CreateModel(
            name='EncounterStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], max_length=30)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='cymed_encounters.encounter')),
            ],
            options={
                'db_table': 'cymed_encounter_status_history',
            },
        ),
        migrations.CreateModel(
            name='EpisodeOfCare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=30)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('managing_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cymed_organizations.organization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes_of_care', to='cymed_patients.patient')),
            ],
            options={
                'db_table': 'cymed_episodes_of_care',
            },
        ),
        migrations.AddField(
            model_name='encounter',
            name='episode_of_care',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='cymed_encounters.episodeofcare'),
        ),
    ]
