# Generated by Django 6.1.1 on 2026-09-04 02:49

import platform.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_encounters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounterdiagnosis',
            name='display',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='encounternote',
            name='note_text',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='encounterreason',
            name='reason_text',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
    ]
