# Generated by Django 5.1.15 on 2026-06-23 03:25

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeatureMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('product_code', models.CharField(max_length=100)),
                ('edition_code', models.CharField(max_length=100)),
                ('feature_code', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('requires_addon', models.BooleanField(default=False)),
                ('addon_code', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'cymed_commercial_product_feature_matrix',
                'unique_together': {('product_code', 'edition_code', 'feature_code')},
            },
        ),
        migrations.CreateModel(
            name='ProductLicenseMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('product_code', models.CharField(max_length=100)),
                ('edition_code', models.CharField(max_length=100)),
                ('license_types_allowed', models.JSONField(default=list)),
                ('delivery_modes_allowed', models.JSONField(default=list)),
                ('supports_white_label', models.BooleanField(default=True)),
                ('supports_multi_tenant', models.BooleanField(default=False)),
                ('requires_government_license', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cymed_commercial_product_license_mappings',
                'unique_together': {('product_code', 'edition_code')},
            },
        ),
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('product_code', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('release_notes', models.TextField(blank=True)),
                ('is_lts', models.BooleanField(default=False)),
                ('minimum_upgrade_from', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'cymed_commercial_product_versions',
                'unique_together': {('product_code', 'version')},
            },
        ),
    ]
