# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologistPoolShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('provider_id', models.UUIDField(blank=True, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('modalities', models.JSONField(blank=True, default=list)),
                ('max_studies', models.IntegerField(default=0)),
                ('accepted_studies', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_full', 'Partially Full'), ('full', 'Full'), ('closed', 'Closed')], default='open', max_length=32)),
            ],
            options={
                'db_table': 'cymed_eco_shared_capacity_radiologist_pool_shift',
            },
        ),
        migrations.CreateModel(
            name='ResourceOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('kind', models.CharField(choices=[('drug_stock', 'Drug Stock'), ('lab_capacity', 'Lab Capacity'), ('radiologist_shift', 'Radiologist Shift'), ('imaging_slot', 'Imaging Slot'), ('or_block', 'OR Block'), ('hospital_bed', 'Hospital Bed'), ('phlebotomist', 'Phlebotomist')], max_length=32)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('uom', models.CharField(blank=True, max_length=16)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('visible_to_tenant_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reserved', 'Reserved'), ('partially_taken', 'Partially Taken'), ('closed', 'Closed'), ('expired', 'Expired')], default='open', max_length=32)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'cymed_eco_shared_capacity_resource_offer',
            },
        ),
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('kind', models.CharField(choices=[('drug_stock', 'Drug Stock'), ('lab_capacity', 'Lab Capacity'), ('radiologist_shift', 'Radiologist Shift'), ('imaging_slot', 'Imaging Slot'), ('or_block', 'OR Block'), ('hospital_bed', 'Hospital Bed'), ('phlebotomist', 'Phlebotomist')], max_length=32)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity_needed', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('uom', models.CharField(blank=True, max_length=16)),
                ('needed_by', models.DateTimeField(blank=True, null=True)),
                ('max_price_per_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='routine', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='open', max_length=32)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('matched_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='cymed_eco_shared_capacity.resourceoffer')),
            ],
            options={
                'db_table': 'cymed_eco_shared_capacity_resource_request',
            },
        ),
        migrations.CreateModel(
            name='ResourceMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('agreed_price_per_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='proposed', max_length=32)),
                ('created_at_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=255)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='cymed_eco_shared_capacity.resourceoffer')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='cymed_eco_shared_capacity.resourcerequest')),
            ],
            options={
                'db_table': 'cymed_eco_shared_capacity_resource_match',
            },
        ),
    ]
