# Generated by Django 6.0.7 on 2026-08-05 12:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyed_sis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviourIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('positive', 'Positive Recognition'), ('minor', 'Minor'), ('major', 'Major')], default='minor', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('reported_by', models.CharField(blank=True, max_length=255)),
                ('resolved', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_incidents', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_behaviour_incidents',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('eald_level', models.CharField(blank=True, choices=[('', 'Not EAL/D'), ('BL', 'Beginning'), ('EM', 'Emerging'), ('DV', 'Developing'), ('CO', 'Consolidating')], default='', max_length=2)),
                ('first_language', models.CharField(blank=True, max_length=100)),
                ('is_neurodivergent', models.BooleanField(default=False)),
                ('accommodations', models.TextField(blank=True)),
                ('reading_level', models.CharField(blank=True, max_length=50)),
                ('preferred_modalities', models.CharField(blank=True, max_length=255)),
                ('has_individual_plan', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_learner_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WellbeingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('date', models.DateField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('is_confidential', models.BooleanField(default=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellbeing_notes', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_wellbeing_notes',
                'ordering': ['-date'],
            },
        ),
    ]
