# Generated by Django 6.0.7 on 2026-08-06 17:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_sis', '0001_initial'),
        ('cyed_wellbeing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellbeingCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('mood', models.CharField(blank=True, choices=[('great', 'Great'), ('ok', 'OK'), ('low', 'Low'), ('struggling', 'Struggling')], max_length=20)),
                ('response_text', models.TextField(blank=True)),
                ('sentiment_score', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('sentiment_label', models.CharField(blank=True, max_length=20)),
                ('flagged', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_wellbeing_checkins',
                'ordering': ['-created_at'],
            },
        ),
    ]
