# Generated by Django 6.0.7 on 2026-08-06 22:04

import core.crypto
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_wellbeing', '0002_wellbeingcheckin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprofile',
            name='notes',
            field=core.crypto.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wellbeingcheckin',
            name='response_text',
            field=core.crypto.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wellbeingnote',
            name='note',
            field=core.crypto.EncryptedTextField(blank=True),
        ),
    ]
