# Generated by Django 6.1 on 2026-08-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_sis', '0006_student_exit_date_student_exit_destination_and_more'),
        ('cyed_wellbeing', '0003_alter_learnerprofile_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviourincident',
            name='house',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='behaviourincident',
            name='points',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='behaviourincident',
            index=models.Index(fields=['tenant_id', 'student', 'date'], name='idx_behaviour_student_date'),
        ),
    ]
