# Generated by Django 6.1 on 2026-08-14 12:40

import core.crypto
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_hr', '0004_staffleave_balance_override_by_and_more'),
        ('cyed_sis', '0006_student_exit_date_student_exit_destination_and_more'),
        ('cyed_wellbeing', '0004_behaviourincident_house_behaviourincident_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('plan_type', models.CharField(choices=[('iep', 'Individual Education Plan'), ('ilp', 'Individual Learning Plan'), ('behaviour', 'Behaviour Support Plan'), ('risk', 'Risk Management Plan'), ('eald', 'EAL/D Support Plan')], default='iep', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('superseded', 'Superseded'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('review_due', models.DateField(blank=True, null=True)),
                ('strengths', core.crypto.EncryptedTextField(blank=True)),
                ('needs', core.crypto.EncryptedTextField(blank=True)),
                ('family_consulted_on', models.DateField(blank=True, null=True)),
                ('student_voice', core.crypto.EncryptedTextField(blank=True)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('closed_reason', models.CharField(blank=True, max_length=255)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_support_plans', to='cyed_hr.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_plans', to='cyed_sis.student')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='cyed_wellbeing.supportplan')),
            ],
            options={
                'db_table': 'cyed_support_plans',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('description', models.TextField()),
                ('success_criteria', models.TextField(blank=True, help_text='How the school will know it has been met.')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('progress', models.CharField(choices=[('not_started', 'Not started'), ('working_towards', 'Working towards'), ('achieved', 'Achieved'), ('discontinued', 'Discontinued')], default='not_started', max_length=20)),
                ('progress_note', models.TextField(blank=True)),
                ('progress_updated_on', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='cyed_wellbeing.supportplan')),
            ],
            options={
                'db_table': 'cyed_support_goals',
                'ordering': ['target_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('category', models.CharField(choices=[('curriculum', 'Curriculum'), ('instruction', 'Instruction'), ('environment', 'Environment'), ('assessment', 'Assessment'), ('personal_care', 'Personal care'), ('safety', 'Safety'), ('communication', 'Communication')], max_length=30)),
                ('description', models.TextField(help_text='What is done differently — concrete enough for a relief teacher to follow.')),
                ('nccd_level', models.CharField(blank=True, choices=[('qdtp', 'Quality differentiated teaching practice'), ('supplementary', 'Supplementary'), ('substantial', 'Substantial'), ('extensive', 'Extensive')], max_length=20)),
                ('responsible', models.CharField(blank=True, max_length=255)),
                ('frequency', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='cyed_wellbeing.supportplan')),
            ],
            options={
                'db_table': 'cyed_support_adjustments',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='SupportPlanReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('held_on', models.DateField()),
                ('participants', models.CharField(help_text='Everyone present, including the family.', max_length=500)),
                ('family_present', models.BooleanField(default=False)),
                ('student_present', models.BooleanField(default=False)),
                ('discussion', core.crypto.EncryptedTextField(blank=True)),
                ('outcome', models.CharField(blank=True, max_length=500)),
                ('next_review_due', models.DateField(blank=True, null=True)),
                ('recorded_by', models.CharField(blank=True, max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cyed_wellbeing.supportplan')),
            ],
            options={
                'db_table': 'cyed_support_plan_reviews',
                'ordering': ['-held_on'],
            },
        ),
        migrations.AddIndex(
            model_name='supportplan',
            index=models.Index(fields=['tenant_id', 'status', 'review_due'], name='idx_support_plan_review'),
        ),
    ]
