# Generated by Django 6.1 on 2026-09-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_wellbeing', '0005_supportplan_supportgoal_supportadjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviourincident',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='behaviourincident',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='behaviourincident',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='behaviourincident',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='supportadjustment',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='supportadjustment',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='supportadjustment',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='supportadjustment',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='supportgoal',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='supportgoal',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='supportgoal',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='supportgoal',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='supportplan',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='supportplan',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='supportplan',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='supportplan',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='supportplanreview',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='supportplanreview',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='supportplanreview',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='supportplanreview',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='wellbeingcheckin',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='wellbeingcheckin',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='wellbeingcheckin',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='wellbeingcheckin',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='wellbeingnote',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='wellbeingnote',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='wellbeingnote',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='wellbeingnote',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
