# Generated by Django 5.1.15 on 2026-06-23 00:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_patients', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgicalCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('surgeon_id', models.UUIDField()),
                ('procedure_code', models.CharField(max_length=100)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('pre_op', 'Pre-Op'), ('intra_op', 'Intra-Op'), ('post_op', 'Post-Op'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cymed_patients.patient')),
            ],
            options={
                'db_table': 'cymed_hospital_surgical_cases',
            },
        ),
        migrations.CreateModel(
            name='ProcedureConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('patient_signature_blob', models.TextField()),
                ('witness_name', models.CharField(max_length=255)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('surgical_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='cymed_hospital_operating_room.surgicalcase')),
            ],
            options={
                'db_table': 'cymed_hospital_procedure_consents',
            },
        ),
        migrations.CreateModel(
            name='ProcedureChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('sign_in_ok', models.BooleanField(default=False)),
                ('time_out_ok', models.BooleanField(default=False)),
                ('sign_out_ok', models.BooleanField(default=False)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('surgical_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='cymed_hospital_operating_room.surgicalcase')),
            ],
            options={
                'db_table': 'cymed_hospital_procedure_checklists',
            },
        ),
        migrations.CreateModel(
            name='ProcedureBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('priority', models.CharField(choices=[('elective', 'Elective'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='elective', max_length=50)),
                ('surgical_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cymed_hospital_operating_room.surgicalcase')),
            ],
            options={
                'db_table': 'cymed_hospital_procedure_bookings',
            },
        ),
        migrations.CreateModel(
            name='SurgicalEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('asset_serial', models.CharField(max_length=100)),
                ('sterilized_status', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('surgical_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='cymed_hospital_operating_room.surgicalcase')),
            ],
            options={
                'db_table': 'cymed_hospital_surgical_equipments',
            },
        ),
        migrations.CreateModel(
            name='SurgicalSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('operating_room_id', models.UUIDField()),
                ('allocated_date', models.DateField()),
                ('surgical_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='cymed_hospital_operating_room.surgicalcase')),
            ],
            options={
                'db_table': 'cymed_hospital_surgical_schedules',
            },
        ),
        migrations.CreateModel(
            name='SurgicalTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('member_id', models.UUIDField()),
                ('role', models.CharField(max_length=100)),
                ('surgical_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='cymed_hospital_operating_room.surgicalcase')),
            ],
            options={
                'db_table': 'cymed_hospital_surgical_teams',
            },
        ),
    ]
