# Generated by Django 6.0.6 on 2026-06-23 04:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('img_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('modality', models.CharField(max_length=20)),
                ('body_part', models.CharField(blank=True, max_length=100)),
                ('subspecialty', models.CharField(blank=True, max_length=100)),
                ('template_text', models.TextField()),
                ('findings_template', models.TextField(blank=True)),
                ('impression_template', models.TextField(blank=True)),
                ('is_structured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'cymed_img_report_templates',
            },
        ),
        migrations.CreateModel(
            name='RadiologyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('radiologist_id', models.UUIDField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('preliminary', 'Preliminary'), ('final', 'Final'), ('amended', 'Amended'), ('addended', 'Addended')], db_index=True, default='draft', max_length=30)),
                ('technique', models.TextField(blank=True)),
                ('clinical_indication', models.TextField(blank=True)),
                ('comparison_studies', models.TextField(blank=True)),
                ('findings', models.TextField(blank=True)),
                ('impression', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_assistance_used', models.BooleanField(default=False)),
                ('dictated_at', models.DateTimeField(blank=True, null=True)),
                ('transcribed_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_by', models.UUIDField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('report_tat_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('fhir_diagnostic_report_id', models.CharField(blank=True, max_length=255)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='img_orders.imagingorderitem')),
                ('report_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='img_reporting.reporttemplate')),
            ],
            options={
                'db_table': 'cymed_img_reports',
            },
        ),
        migrations.CreateModel(
            name='RadiologyImpression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('impression_number', models.PositiveSmallIntegerField(default=1)),
                ('impression_text', models.TextField()),
                ('icd11_code', models.CharField(blank=True, max_length=20)),
                ('snomed_code', models.CharField(blank=True, max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_impressions', to='img_reporting.radiologyreport')),
            ],
            options={
                'db_table': 'cymed_img_impressions',
                'ordering': ['impression_number'],
            },
        ),
        migrations.CreateModel(
            name='RadiologyFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('finding_code', models.CharField(blank=True, max_length=100)),
                ('body_region', models.CharField(blank=True, max_length=100)),
                ('laterality', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('severity', models.CharField(blank=True, choices=[('normal', 'Normal'), ('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], max_length=20)),
                ('is_incidental', models.BooleanField(default=False)),
                ('follow_up_recommended', models.BooleanField(default=False)),
                ('follow_up_timeframe', models.CharField(blank=True, max_length=100)),
                ('size_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('location_detail', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_findings', to='img_reporting.radiologyreport')),
            ],
            options={
                'db_table': 'cymed_img_findings',
            },
        ),
        migrations.CreateModel(
            name='CriticalFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('finding_description', models.TextField()),
                ('snomed_code', models.CharField(blank=True, max_length=20)),
                ('severity', models.CharField(choices=[('urgent', 'Urgent'), ('emergent', 'Emergent')], default='urgent', max_length=20)),
                ('notification_status', models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('acknowledged', 'Acknowledged'), ('completed', 'Completed')], db_index=True, default='pending', max_length=30)),
                ('notified_clinician_id', models.UUIDField(blank=True, null=True)),
                ('notification_method', models.CharField(blank=True, max_length=30)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('read_back_verified', models.BooleanField(default=False)),
                ('escalated', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_findings', to='img_reporting.radiologyreport')),
            ],
            options={
                'db_table': 'cymed_img_critical_findings',
            },
        ),
        migrations.CreateModel(
            name='ReportAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('amended_by', models.UUIDField()),
                ('amendment_reason', models.TextField()),
                ('previous_findings', models.TextField()),
                ('previous_impression', models.TextField()),
                ('new_findings', models.TextField()),
                ('new_impression', models.TextField()),
                ('amendment_date', models.DateTimeField(auto_now_add=True)),
                ('is_significant', models.BooleanField(default=False)),
                ('original_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='img_reporting.radiologyreport')),
            ],
            options={
                'db_table': 'cymed_img_report_amendments',
            },
        ),
        migrations.CreateModel(
            name='StructuredReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('report_schema', models.CharField(blank=True, max_length=100)),
                ('schema_version', models.CharField(blank=True, max_length=20)),
                ('score', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('structured_data', models.JSONField(default=dict)),
                ('dicom_sr_uid', models.CharField(blank=True, max_length=255)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='img_reporting.radiologyreport')),
            ],
            options={
                'db_table': 'cymed_img_structured_reports',
            },
        ),
    ]
