# Generated by Django 6.0.6 on 2026-06-23 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('prescription_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('medication_order_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('encounter_id', models.UUIDField(blank=True, null=True)),
                ('admission_id', models.UUIDField(blank=True, null=True)),
                ('interaction_type', models.CharField(choices=[('drug_drug', 'Drug-Drug'), ('drug_allergy', 'Drug-Allergy'), ('drug_diagnosis', 'Drug-Diagnosis (Contraindication)'), ('drug_age', 'Drug-Age'), ('drug_pregnancy', 'Drug-Pregnancy'), ('drug_renal', 'Drug-Renal Function'), ('drug_hepatic', 'Drug-Hepatic Function'), ('drug_food', 'Drug-Food'), ('duplicate_therapy', 'Duplicate Therapy')], max_length=30)),
                ('severity', models.CharField(choices=[('contraindicated', 'Contraindicated'), ('severe', 'Severe'), ('moderate', 'Moderate'), ('minor', 'Minor'), ('informational', 'Informational')], max_length=30)),
                ('drug_a_code', models.CharField(max_length=100)),
                ('drug_a_name', models.CharField(max_length=500)),
                ('drug_b_code', models.CharField(blank=True, max_length=100)),
                ('drug_b_name', models.CharField(blank=True, max_length=500)),
                ('alert_status', models.CharField(choices=[('active', 'Active Alert'), ('pharmacist_reviewed', 'Pharmacist Reviewed'), ('overridden', 'Overridden with Justification'), ('dismissed', 'Dismissed'), ('resolved', 'Resolved')], default='active', max_length=30)),
                ('ai_priority_score', models.FloatField(default=0.0)),
                ('ai_clinical_context', models.TextField(blank=True)),
                ('overridden_by', models.UUIDField(blank=True, null=True)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('override_approved_by', models.UUIDField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cymed_rx_drug_interactions',
            },
        ),
        migrations.CreateModel(
            name='InteractionSeverity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('severity', models.CharField(choices=[('contraindicated', 'Contraindicated'), ('severe', 'Severe'), ('moderate', 'Moderate'), ('minor', 'Minor'), ('informational', 'Informational')], max_length=30, unique=True)),
                ('auto_block_dispensing', models.BooleanField(default=False)),
                ('requires_pharmacist_review', models.BooleanField(default=True)),
                ('notify_prescriber', models.BooleanField(default=False)),
                ('notify_clinical_pharmacist', models.BooleanField(default=True)),
                ('alert_color', models.CharField(default='#FF0000', max_length=10)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'cymed_rx_interaction_severity_config',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='InteractionAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('recipient_id', models.UUIDField(db_index=True)),
                ('recipient_role', models.CharField(max_length=50)),
                ('channel', models.CharField(choices=[('ui_popup', 'UI Pop-up'), ('notification', 'Notification Center'), ('email', 'Email'), ('sms', 'SMS'), ('worklist', 'Pharmacist Worklist')], default='ui_popup', max_length=30)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.UUIDField(blank=True, null=True)),
                ('action_taken', models.CharField(blank=True, max_length=100)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cymed_pharmacy_interactions.druginteraction')),
            ],
            options={
                'db_table': 'cymed_rx_interaction_alerts',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='InteractionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('rule_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('interaction_type', models.CharField(choices=[('drug_drug', 'Drug-Drug'), ('drug_allergy', 'Drug-Allergy'), ('drug_diagnosis', 'Drug-Diagnosis (Contraindication)'), ('drug_age', 'Drug-Age'), ('drug_pregnancy', 'Drug-Pregnancy'), ('drug_renal', 'Drug-Renal Function'), ('drug_hepatic', 'Drug-Hepatic Function'), ('drug_food', 'Drug-Food'), ('duplicate_therapy', 'Duplicate Therapy')], default='drug_drug', max_length=30)),
                ('severity', models.CharField(choices=[('contraindicated', 'Contraindicated'), ('severe', 'Severe'), ('moderate', 'Moderate'), ('minor', 'Minor'), ('informational', 'Informational')], default='moderate', max_length=30)),
                ('drug_a_code', models.CharField(db_index=True, max_length=100)),
                ('drug_a_name', models.CharField(max_length=500)),
                ('drug_a_class', models.CharField(blank=True, max_length=200)),
                ('drug_b_code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('drug_b_name', models.CharField(blank=True, max_length=500)),
                ('drug_b_class', models.CharField(blank=True, max_length=200)),
                ('allergen_code', models.CharField(blank=True, max_length=100)),
                ('diagnosis_code', models.CharField(blank=True, max_length=50)),
                ('min_age_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pregnancy_category', models.CharField(blank=True, max_length=10)),
                ('pregnancy_trimester', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('clinical_significance', models.TextField(blank=True)),
                ('management_recommendation', models.TextField()),
                ('references', models.JSONField(default=list)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('override_allowed', models.BooleanField(default=True)),
                ('requires_pharmacist_approval', models.BooleanField(default=True)),
                ('ai_priority_score', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'cymed_rx_interaction_rules',
                'indexes': [models.Index(fields=['drug_a_code', 'drug_b_code'], name='cymed_rx_in_drug_a__77d626_idx'), models.Index(fields=['interaction_type', 'severity'], name='cymed_rx_in_interac_ac4c9e_idx'), models.Index(fields=['is_active', 'override_allowed'], name='cymed_rx_in_is_acti_f75027_idx')],
            },
        ),
        migrations.AddField(
            model_name='druginteraction',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detected_interactions', to='cymed_pharmacy_interactions.interactionrule'),
        ),
        migrations.AddIndex(
            model_name='druginteraction',
            index=models.Index(fields=['patient_id', 'alert_status'], name='cymed_rx_dr_patient_b79034_idx'),
        ),
        migrations.AddIndex(
            model_name='druginteraction',
            index=models.Index(fields=['prescription_id', 'severity'], name='cymed_rx_dr_prescri_5bb18b_idx'),
        ),
        migrations.AddIndex(
            model_name='druginteraction',
            index=models.Index(fields=['tenant_id', 'detected_at'], name='cymed_rx_dr_tenant__15d550_idx'),
        ),
    ]
