# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_profile_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('checked_out', 'Checked Out'), ('abandoned', 'Abandoned')], default='open', max_length=32)),
            ],
            options={
                'db_table': 'cymed_pharmacy_ecommerce_cart',
            },
        ),
        migrations.CreateModel(
            name='PharmacyOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_profile_id', models.UUIDField(db_index=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('phone', 'Phone'), ('kiosk', 'Kiosk'), ('walkin', 'Walk-in')], default='web', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('placed', 'Placed'), ('paid', 'Paid'), ('dispensing', 'Dispensing'), ('ready', 'Ready'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('fulfillment', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('mail', 'Mail')], default='pickup', max_length=32)),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('vat', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('discount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('total', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('payment_ref', models.CharField(blank=True, max_length=128)),
                ('delivery_address', models.JSONField(blank=True, default=dict)),
                ('delivery_slot_start', models.DateTimeField(blank=True, null=True)),
                ('delivery_slot_end', models.DateTimeField(blank=True, null=True)),
                ('delivery_id', models.UUIDField(blank=True, null=True)),
                ('bill_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cymed_pharmacy_ecommerce_pharmacy_order',
            },
        ),
        migrations.CreateModel(
            name='RefillRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_profile_id', models.UUIDField(db_index=True)),
                ('original_prescription_id', models.UUIDField(blank=True, null=True)),
                ('drug_id', models.UUIDField(blank=True, null=True)),
                ('drug_name', models.CharField(max_length=255)),
                ('qty', models.IntegerField(default=1)),
                ('delivery_address', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='submitted', max_length=32)),
                ('pharmacist_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cymed_pharmacy_ecommerce_refill_request',
            },
        ),
        migrations.CreateModel(
            name='PharmacyOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('product_id', models.UUIDField()),
                ('product_name', models.CharField(max_length=255)),
                ('qty', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('is_prescription', models.BooleanField(default=False)),
                ('refill_request_id', models.UUIDField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cymed_pharmacy_ecommerce.pharmacyorder')),
            ],
            options={
                'db_table': 'cymed_pharmacy_ecommerce_pharmacy_order_item',
            },
        ),
        migrations.CreateModel(
            name='PharmacyProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('sku', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('rx', 'Prescription'), ('otc', 'OTC'), ('cosmetic', 'Cosmetic'), ('supplement', 'Supplement'), ('device', 'Device'), ('baby', 'Baby'), ('other', 'Other')], default='otc', max_length=32)),
                ('drug_id', models.UUIDField(blank=True, null=True)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=5)),
                ('stock_qty', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_pharmacy_ecommerce_pharmacy_product',
                'unique_together': {('tenant_id', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('qty', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('snapshot_name', models.CharField(max_length=255)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cymed_pharmacy_ecommerce.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='cymed_pharmacy_ecommerce.pharmacyproduct')),
            ],
            options={
                'db_table': 'cymed_pharmacy_ecommerce_cart_item',
            },
        ),
    ]
