# Generated by Django 5.1.15 on 2026-06-22 20:33

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TriageAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.CharField(max_length=255)),
                ('chief_complaint', models.TextField()),
                ('triage_category', models.CharField(choices=[('immediate', 'Immediate (Level 1)'), ('emergent', 'Emergent (Level 2)'), ('urgent', 'Urgent (Level 3)'), ('less_urgent', 'Less Urgent (Level 4)'), ('non_urgent', 'Non Urgent (Level 5)')], default='non_urgent', max_length=50)),
            ],
            options={
                'db_table': 'cymed_clinic_triage_assessments',
            },
        ),
        migrations.CreateModel(
            name='TriageRiskScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('mews_score', models.PositiveIntegerField(default=0)),
                ('abnormal_flag', models.BooleanField(default=False)),
                ('risk_level', models.CharField(default='low', max_length=50)),
                ('ai_risk_assessment', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cymed_clinic_triage_risk_scores',
            },
        ),
        migrations.CreateModel(
            name='TriageVitalSigns',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('pulse_bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('respiratory_rate_pm', models.PositiveIntegerField(blank=True, null=True)),
                ('oxygen_saturation_pct', models.PositiveIntegerField(blank=True, null=True)),
                ('pain_score', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'cymed_clinic_triage_vitals',
            },
        ),
    ]
