"""
CyMed Pharmacy — Drug Interaction Engine
Models: DrugInteraction, InteractionSeverity, InteractionRule, InteractionAlert

Capabilities: Drug-Drug, Drug-Allergy, Drug-Diagnosis, Drug-Age, Drug-Pregnancy
AI-assisted alert prioritization allowed.
Human pharmacist approval required for all overrides.

Terminology: Drug codes via TerminologyService (RxNorm, SNOMED).
             Diagnoses via ICD-11 (TerminologyService).
"""
from django.db import models
from platform.common.models import BaseModel


class InteractionSeverityLevel(models.TextChoices):
    CONTRAINDICATED = "contraindicated", "Contraindicated"
    SEVERE = "severe", "Severe"
    MODERATE = "moderate", "Moderate"
    MINOR = "minor", "Minor"
    INFORMATIONAL = "informational", "Informational"


class InteractionType(models.TextChoices):
    DRUG_DRUG = "drug_drug", "Drug-Drug"
    DRUG_ALLERGY = "drug_allergy", "Drug-Allergy"
    DRUG_DIAGNOSIS = "drug_diagnosis", "Drug-Diagnosis (Contraindication)"
    DRUG_AGE = "drug_age", "Drug-Age"
    DRUG_PREGNANCY = "drug_pregnancy", "Drug-Pregnancy"
    DRUG_RENAL = "drug_renal", "Drug-Renal Function"
    DRUG_HEPATIC = "drug_hepatic", "Drug-Hepatic Function"
    DRUG_FOOD = "drug_food", "Drug-Food"
    DUPLICATE_THERAPY = "duplicate_therapy", "Duplicate Therapy"


class InteractionRule(BaseModel):
    """
    Master interaction rule database entry.
    Rules are seeded from external clinical databases (Micromedex, First DataBank, etc.)
    via CyIntegrationHub — no local clinical database duplication.
    Drug codes: RxNorm via TerminologyService.
    Diagnosis codes: ICD-11 via TerminologyService.
    """
    rule_code = models.CharField(max_length=100, unique=True, db_index=True)
    interaction_type = models.CharField(
        max_length=30, choices=InteractionType.choices, default=InteractionType.DRUG_DRUG
    )
    severity = models.CharField(
        max_length=30, choices=InteractionSeverityLevel.choices,
        default=InteractionSeverityLevel.MODERATE
    )

    # Primary drug (RxNorm code via TerminologyService)
    drug_a_code = models.CharField(max_length=100, db_index=True)
    drug_a_name = models.CharField(max_length=500)
    drug_a_class = models.CharField(max_length=200, blank=True)       # Drug class level matching

    # Secondary drug / allergen / diagnosis
    drug_b_code = models.CharField(max_length=100, blank=True, db_index=True)
    drug_b_name = models.CharField(max_length=500, blank=True)
    drug_b_class = models.CharField(max_length=200, blank=True)
    allergen_code = models.CharField(max_length=100, blank=True)
    diagnosis_code = models.CharField(max_length=50, blank=True)      # ICD-11

    # Age constraints (for drug-age rules)
    min_age_years = models.PositiveSmallIntegerField(null=True, blank=True)
    max_age_years = models.PositiveSmallIntegerField(null=True, blank=True)

    # Pregnancy category
    pregnancy_category = models.CharField(max_length=10, blank=True)  # A, B, C, D, X
    pregnancy_trimester = models.CharField(max_length=20, blank=True)

    # Content
    description = models.TextField()
    clinical_significance = models.TextField(blank=True)
    management_recommendation = models.TextField()
    references = models.JSONField(default=list)

    # Rule management
    source = models.CharField(max_length=100, blank=True)             # "micromedex", "fdb", "custom"
    is_active = models.BooleanField(default=True)
    override_allowed = models.BooleanField(default=True)
    requires_pharmacist_approval = models.BooleanField(default=True)
    ai_priority_score = models.FloatField(default=0.0)               # CyAI scoring

    class Meta:
        db_table = "cymed_rx_interaction_rules"
        indexes = [
            models.Index(fields=["drug_a_code", "drug_b_code"]),
            models.Index(fields=["interaction_type", "severity"]),
            models.Index(fields=["is_active", "override_allowed"]),
        ]

    def __str__(self):
        return f"{self.rule_code}: {self.drug_a_name} × {self.drug_b_name or self.allergen_code or self.diagnosis_code}"


class DrugInteraction(BaseModel):
    """
    Detected interaction instance for a specific patient/prescription/order context.
    Generated by the interaction engine when processing new medications.
    """
    ALERT_STATUS = [
        ("active", "Active Alert"),
        ("pharmacist_reviewed", "Pharmacist Reviewed"),
        ("overridden", "Overridden with Justification"),
        ("dismissed", "Dismissed"),
        ("resolved", "Resolved"),
    ]

    # Context
    patient_id = models.UUIDField(db_index=True)
    prescription_id = models.UUIDField(null=True, blank=True, db_index=True)
    medication_order_id = models.UUIDField(null=True, blank=True, db_index=True)
    encounter_id = models.UUIDField(null=True, blank=True)
    admission_id = models.UUIDField(null=True, blank=True)

    # Rule reference
    rule = models.ForeignKey(
        InteractionRule, on_delete=models.PROTECT, related_name="detected_interactions"
    )

    interaction_type = models.CharField(max_length=30, choices=InteractionType.choices)
    severity = models.CharField(max_length=30, choices=InteractionSeverityLevel.choices)

    # Specific drugs detected
    drug_a_code = models.CharField(max_length=100)
    drug_a_name = models.CharField(max_length=500)
    drug_b_code = models.CharField(max_length=100, blank=True)
    drug_b_name = models.CharField(max_length=500, blank=True)

    alert_status = models.CharField(max_length=30, choices=ALERT_STATUS, default="active")

    # AI prioritization (CyAI)
    ai_priority_score = models.FloatField(default=0.0)
    ai_clinical_context = models.TextField(blank=True)               # CyAI explanation

    # Override (requires pharmacist)
    overridden_by = models.UUIDField(null=True, blank=True)          # Pharmacist UUID
    overridden_at = models.DateTimeField(null=True, blank=True)
    override_reason = models.TextField(blank=True)
    override_approved_by = models.UUIDField(null=True, blank=True)

    detected_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "cymed_rx_drug_interactions"
        indexes = [
            models.Index(fields=["patient_id", "alert_status"]),
            models.Index(fields=["prescription_id", "severity"]),
            models.Index(fields=["tenant_id", "detected_at"]),
        ]

    def __str__(self):
        return f"Interaction: {self.drug_a_name} × {self.drug_b_name} [{self.severity}]"


class InteractionSeverity(BaseModel):
    """
    Configuration for how different severity levels are handled in the system.
    Controls whether auto-block, alert, or informational flow is triggered.
    """
    severity = models.CharField(
        max_length=30, choices=InteractionSeverityLevel.choices, unique=True
    )
    auto_block_dispensing = models.BooleanField(default=False)
    requires_pharmacist_review = models.BooleanField(default=True)
    notify_prescriber = models.BooleanField(default=False)
    notify_clinical_pharmacist = models.BooleanField(default=True)
    alert_color = models.CharField(max_length=10, default="#FF0000")  # UI hint
    display_order = models.PositiveSmallIntegerField(default=0)

    class Meta:
        db_table = "cymed_rx_interaction_severity_config"
        ordering = ["display_order"]


class InteractionAlert(BaseModel):
    """
    Real-time alert sent to pharmacist/prescriber when interaction is detected.
    Tracks acknowledgement and resolution.
    """
    ALERT_CHANNELS = [
        ("ui_popup", "UI Pop-up"),
        ("notification", "Notification Center"),
        ("email", "Email"),
        ("sms", "SMS"),
        ("worklist", "Pharmacist Worklist"),
    ]

    interaction = models.ForeignKey(
        DrugInteraction, on_delete=models.CASCADE, related_name="alerts"
    )
    recipient_id = models.UUIDField(db_index=True)                   # Pharmacist or prescriber
    recipient_role = models.CharField(max_length=50)                  # pharmacist, prescriber, etc.
    channel = models.CharField(max_length=30, choices=ALERT_CHANNELS, default="ui_popup")
    sent_at = models.DateTimeField(auto_now_add=True)
    acknowledged_at = models.DateTimeField(null=True, blank=True)
    acknowledged_by = models.UUIDField(null=True, blank=True)
    action_taken = models.CharField(max_length=100, blank=True)

    class Meta:
        db_table = "cymed_rx_interaction_alerts"
        ordering = ["-sent_at"]
