# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RobotDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=64)),
                ('vendor', models.CharField(choices=[('pyxis', 'Pyxis'), ('omnicell', 'Omnicell'), ('parata', 'Parata'), ('meditech', 'Meditech'), ('kirby_lester', 'Kirby-Lester'), ('generic', 'Generic')], max_length=32)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('location_label', models.CharField(blank=True, max_length=128)),
                ('facility_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('api_endpoint', models.URLField(blank=True)),
                ('protocol', models.CharField(choices=[('http_json', 'HTTP JSON'), ('hl7', 'HL7'), ('vendor_sdk', 'Vendor SDK'), ('manual', 'Manual')], default='http_json', max_length=32)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error'), ('maintenance', 'Maintenance')], default='offline', max_length=32)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'cymed_pharmacy_robotics_robot_device',
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='RobotBinInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('bin_code', models.CharField(max_length=32)),
                ('drug_id', models.UUIDField(blank=True, null=True)),
                ('drug_name', models.CharField(max_length=255)),
                ('ndc', models.CharField(blank=True, max_length=32)),
                ('lot_number', models.CharField(blank=True, max_length=64)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('qty_on_hand', models.IntegerField(default=0)),
                ('par_level', models.IntegerField(default=0)),
                ('last_counted_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='cymed_pharmacy_robotics.robotdevice')),
            ],
            options={
                'db_table': 'cymed_pharmacy_robotics_robot_bin_inventory',
            },
        ),
        migrations.CreateModel(
            name='DispenseJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('order_id', models.UUIDField(db_index=True)),
                ('patient_profile_id', models.UUIDField(blank=True, null=True)),
                ('drug_id', models.UUIDField(blank=True, null=True)),
                ('drug_name', models.CharField(max_length=255)),
                ('qty_requested', models.IntegerField()),
                ('qty_dispensed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('dispatched', 'Dispatched'), ('dispensing', 'Dispensing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=32)),
                ('lot_number', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('vendor_reference', models.CharField(blank=True, max_length=128)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='cymed_pharmacy_robotics.robotdevice')),
            ],
            options={
                'db_table': 'cymed_pharmacy_robotics_dispense_job',
            },
        ),
        migrations.CreateModel(
            name='RobotEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kind', models.CharField(choices=[('heartbeat', 'Heartbeat'), ('dispense_ok', 'Dispense OK'), ('dispense_fail', 'Dispense Fail'), ('low_stock', 'Low Stock'), ('expiry_warn', 'Expiry Warn'), ('restock', 'Restock'), ('maintenance', 'Maintenance')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cymed_pharmacy_robotics.robotdevice')),
            ],
            options={
                'db_table': 'cymed_pharmacy_robotics_robot_event',
            },
        ),
    ]
