# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('internal', 'Internal'), ('aramex', 'Aramex'), ('dhl', 'DHL'), ('naqel', 'Naqel'), ('smsa', 'SMSA'), ('mrsool', 'Mrsool'), ('careem', 'Careem'), ('other', 'Other')], default='internal', max_length=32)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_endpoint', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('coverage_areas', models.JSONField(blank=True, default=list)),
                ('cold_chain_capable', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cymed_pharmacy_delivery_courier',
            },
        ),
        migrations.CreateModel(
            name='DeliveryJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('order_id', models.UUIDField(db_index=True)),
                ('patient_profile_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='created', max_length=32)),
                ('pickup_address', models.JSONField(blank=True, default=dict)),
                ('drop_address', models.JSONField(blank=True, default=dict)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('drop_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('drop_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('requested_slot_start', models.DateTimeField(blank=True, null=True)),
                ('requested_slot_end', models.DateTimeField(blank=True, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('cold_chain_required', models.BooleanField(default=False)),
                ('proof_of_delivery', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('courier_tracking_id', models.CharField(blank=True, max_length=128)),
                ('cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='cymed_pharmacy_delivery.courier')),
            ],
            options={
                'db_table': 'cymed_pharmacy_delivery_delivery_job',
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=32)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('note', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cymed_pharmacy_delivery.deliveryjob')),
            ],
            options={
                'db_table': 'cymed_pharmacy_delivery_delivery_status_event',
            },
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('external_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('vehicle_type', models.CharField(choices=[('motorbike', 'Motorbike'), ('car', 'Car'), ('van', 'Van'), ('bicycle', 'Bicycle')], default='motorbike', max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riders', to='cymed_pharmacy_delivery.courier')),
            ],
            options={
                'db_table': 'cymed_pharmacy_delivery_rider',
            },
        ),
        migrations.AddField(
            model_name='deliveryjob',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='cymed_pharmacy_delivery.rider'),
        ),
    ]
