# Generated by Django 6.0.7 on 2026-09-07 21:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_providers', '0002_provider_attributes_provider_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCredentialingStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('verified_by', models.CharField(blank=True, max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('license_verified', models.BooleanField(default=False)),
                ('board_certification_verified', models.BooleanField(default=False)),
                ('background_check_passed', models.BooleanField(default=False)),
                ('malpractice_insurance_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentialing_status', to='cymed_providers.provider')),
            ],
            options={
                'db_table': 'cymed_provider_credentialing_status',
            },
        ),
        migrations.CreateModel(
            name='ProviderPortalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('theme_preference', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=20)),
                ('dashboard_layout', models.JSONField(blank=True, default=dict)),
                ('quick_actions', models.JSONField(blank=True, default=list)),
                ('is_on_call', models.BooleanField(default=False)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_profile', to='cymed_providers.provider')),
            ],
            options={
                'db_table': 'cymed_provider_portal_profiles',
            },
        ),
        migrations.CreateModel(
            name='ProviderPortalActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('patient_viewed', 'Patient Viewed'), ('prescription_issued', 'Prescription Issued'), ('lab_ordered', 'Lab Ordered'), ('imaging_ordered', 'Imaging Ordered'), ('referral_sent', 'Referral Sent'), ('note_added', 'Clinical Note Added'), ('schedule_updated', 'Schedule Updated')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('patient_mrn', models.CharField(blank=True, db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cymed_provider_portal.providerportalprofile')),
            ],
            options={
                'db_table': 'cymed_provider_portal_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
