# Generated by Django 6.0.6 on 2026-06-23 04:10

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lab_orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specimen",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("specimen_number", models.CharField(db_index=True, max_length=100, unique=True)),
                ("barcode", models.CharField(blank=True, max_length=100, unique=True)),
                ("qr_code", models.CharField(blank=True, max_length=255)),
                ("patient_id", models.UUIDField(db_index=True)),
                ("specimen_type", models.CharField(max_length=100)),
                ("snomed_specimen_code", models.CharField(blank=True, max_length=50)),
                ("collection_site", models.CharField(blank=True, max_length=200)),
                (
                    "volume_ml",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
                ),
                ("container_type", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Collection"),
                            ("collected", "Collected"),
                            ("in_transit", "In Transit"),
                            ("received", "Received"),
                            ("accessioned", "Accessioned"),
                            ("in_processing", "In Processing"),
                            ("stored", "In Storage"),
                            ("rejected", "Rejected"),
                            ("disposed", "Disposed"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("fhir_specimen_id", models.CharField(blank=True, max_length=255)),
                (
                    "order_item",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specimen",
                        to="lab_orders.laborderitem",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_lab_specimens",
            },
        ),
        migrations.CreateModel(
            name="SpecimenChainOfCustody",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("collected", "Collected"),
                            ("labeled", "Labeled"),
                            ("packaged", "Packaged"),
                            ("transferred", "Transferred"),
                            ("received", "Received"),
                            ("accessioned", "Accessioned"),
                            ("aliquoted", "Aliquoted"),
                            ("processed", "Processed"),
                            ("stored", "Stored"),
                            ("retrieved", "Retrieved from Storage"),
                            ("disposed", "Disposed"),
                            ("sent_external", "Sent to External Lab"),
                        ],
                        max_length=30,
                    ),
                ),
                ("performed_by", models.UUIDField()),
                ("location", models.CharField(blank=True, max_length=255)),
                ("action_timestamp", models.DateTimeField()),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("digital_signature", models.CharField(blank=True, max_length=512)),
                (
                    "specimen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chain_of_custody",
                        to="lab_specimens.specimen",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_lab_specimen_chain_of_custody",
                "ordering": ["action_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SpecimenCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("collected_by", models.UUIDField()),
                ("collected_at", models.DateTimeField()),
                ("collection_site", models.CharField(max_length=200)),
                ("collection_method", models.CharField(blank=True, max_length=100)),
                ("patient_fasting", models.BooleanField(default=False)),
                ("fasting_hours", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("collection_notes", models.TextField(blank=True)),
                ("collection_device", models.CharField(blank=True, max_length=100)),
                (
                    "specimen",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection",
                        to="lab_specimens.specimen",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_lab_specimen_collections",
            },
        ),
        migrations.CreateModel(
            name="SpecimenContainer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "container_type",
                    models.CharField(
                        choices=[
                            ("edta", "EDTA Purple Top"),
                            ("sst", "SST Gold Top"),
                            ("plain", "Plain Red Top"),
                            ("citrate", "Sodium Citrate Blue Top"),
                            ("heparin", "Lithium Heparin Green Top"),
                            ("fluoride", "Sodium Fluoride Grey Top"),
                            ("urine_cup", "Urine Cup"),
                            ("sterile_jar", "Sterile Jar"),
                            ("swab", "Swab"),
                            ("slide", "Glass Slide"),
                            ("cassette", "Tissue Cassette"),
                            ("blood_culture", "Blood Culture Bottle"),
                            ("csf_tube", "CSF Collection Tube"),
                        ],
                        max_length=50,
                    ),
                ),
                ("barcode", models.CharField(max_length=100, unique=True)),
                (
                    "volume_ml",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
                ),
                ("is_primary", models.BooleanField(default=True)),
                ("is_aliquot", models.BooleanField(default=False)),
                ("label_printed", models.BooleanField(default=False)),
                (
                    "aliquot_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aliquots",
                        to="lab_specimens.specimencontainer",
                    ),
                ),
                (
                    "specimen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="containers",
                        to="lab_specimens.specimen",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_lab_specimen_containers",
            },
        ),
        migrations.CreateModel(
            name="SpecimenRejection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "rejection_reason",
                    models.CharField(
                        choices=[
                            ("quantity_insufficient", "Quantity Not Sufficient (QNS)"),
                            ("hemolyzed", "Hemolyzed"),
                            ("lipemic", "Lipemic"),
                            ("icteric", "Icteric"),
                            ("clotted", "Clotted"),
                            ("wrong_container", "Wrong Container Type"),
                            ("mislabeled", "Mislabeled"),
                            ("expired_container", "Expired Container"),
                            ("improper_storage", "Improper Storage/Transport Temperature"),
                            ("contaminated", "Contaminated"),
                            ("broken", "Broken Container"),
                            ("wrong_test", "Wrong Test Requested"),
                            ("no_request", "No Request/Requisition"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("rejection_details", models.TextField(blank=True)),
                ("rejected_by", models.UUIDField()),
                ("rejected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action_taken",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("recollect", "Recollect"),
                            ("partial_result", "Partial Result Reported"),
                            ("add_comment", "Add Comment and Process"),
                            ("cancel_order", "Cancel Order Item"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notified_provider", models.UUIDField(blank=True, null=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "specimen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rejections",
                        to="lab_specimens.specimen",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_lab_specimen_rejections",
            },
        ),
        migrations.CreateModel(
            name="SpecimenStorage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("location_code", models.CharField(max_length=100)),
                ("location_description", models.CharField(blank=True, max_length=255)),
                ("temperature_celsius", models.DecimalField(decimal_places=1, max_digits=5)),
                ("stored_at", models.DateTimeField()),
                ("stored_by", models.UUIDField(blank=True, null=True)),
                ("scheduled_disposal_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "specimen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_records",
                        to="lab_specimens.specimen",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_lab_specimen_storage",
            },
        ),
        migrations.CreateModel(
            name="SpecimenTransport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("from_location", models.CharField(max_length=255)),
                ("to_location", models.CharField(max_length=255)),
                ("transported_by", models.UUIDField(blank=True, null=True)),
                ("dispatched_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("dispatched", "Dispatched"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed â€” Specimen Issue"),
                        ],
                        default="dispatched",
                        max_length=20,
                    ),
                ),
                (
                    "temperature_celsius",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
                ),
                ("tracking_code", models.CharField(blank=True, max_length=100)),
                ("transport_notes", models.TextField(blank=True)),
                (
                    "specimen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transports",
                        to="lab_specimens.specimen",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_lab_specimen_transports",
            },
        ),
        migrations.AddIndex(
            model_name="specimen",
            index=models.Index(
                fields=["patient_id", "status"], name="cymed_lab_s_patient_b05893_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="specimen",
            index=models.Index(
                fields=["tenant_id", "specimen_type"], name="cymed_lab_s_tenant__01794b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="specimenstorage",
            index=models.Index(
                fields=["specimen", "is_current"], name="cymed_lab_s_specime_05dc66_idx"
            ),
        ),
    ]
