# Generated by Django 5.1.15 on 2026-06-22 20:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_patients', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('session_token', models.CharField(max_length=255)),
                ('connection_url', models.URLField(max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cymed_clinic_virtual_sessions',
            },
        ),
        migrations.CreateModel(
            name='VirtualConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('signature_blob', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemedicine_consents', to='cymed_patients.patient')),
            ],
            options={
                'db_table': 'cymed_clinic_virtual_consents',
            },
        ),
        migrations.CreateModel(
            name='VirtualRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('recording_url', models.URLField(max_length=500)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='cymed_clinic_telemedicine.virtualsession')),
            ],
            options={
                'db_table': 'cymed_clinic_virtual_recordings',
            },
        ),
        migrations.CreateModel(
            name='VirtualVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('provider_id', models.UUIDField()),
                ('scheduled_start', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_visits', to='cymed_patients.patient')),
            ],
            options={
                'db_table': 'cymed_clinic_virtual_visits',
            },
        ),
        migrations.AddField(
            model_name='virtualsession',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='cymed_clinic_telemedicine.virtualvisit'),
        ),
    ]
