# Generated by Django 6.1.1 on 2026-09-04 03:04

import platform.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_hospital_emergency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencydisposition',
            name='notes',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='emergencyobservation',
            name='notes',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='emergencytriage',
            name='chief_complaint',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='emergencyvisit',
            name='presenting_complaint',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
    ]
