# Generated by Django 6.0.6 on 2026-06-23 07:48

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PharmacyAnalyticsConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "dashboard_type",
                    models.CharField(
                        choices=[
                            ("operations", "Pharmacy Operations"),
                            ("clinical", "Clinical Pharmacy"),
                            ("safety", "Medication Safety"),
                            ("executive", "Executive"),
                        ],
                        max_length=30,
                    ),
                ),
                ("metrics_enabled", models.JSONField(default=list)),
                ("alert_thresholds", models.JSONField(default=dict)),
                ("refresh_interval_minutes", models.PositiveSmallIntegerField(default=15)),
                ("email_recipients", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "cymed_pharmacy_analytics_config",
            },
        ),
        migrations.CreateModel(
            name="MedicationSafetyEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("near_miss", "Near Miss"),
                            ("prescribing_error", "Prescribing Error"),
                            ("transcription_error", "Transcription Error"),
                            ("dispensing_error", "Dispensing Error"),
                            ("administration_error", "Administration Error"),
                            ("adverse_drug_event", "Adverse Drug Event"),
                            ("adverse_drug_reaction", "Adverse Drug Reaction"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("a", "Category A — No Error"),
                            ("b", "Category B — Error / No Harm"),
                            ("c", "Category C — Error / Monitoring"),
                            ("d", "Category D — Error / Intervention"),
                            ("e", "Category E — Error / Temporary Harm"),
                            ("f", "Category F — Error / Prolonged Harm"),
                            ("g", "Category G — Error / Permanent Harm"),
                            ("h", "Category H — Error / Near Death"),
                            ("i", "Category I — Error / Patient Death"),
                        ],
                        default="b",
                        max_length=5,
                    ),
                ),
                ("patient_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("prescription_id", models.UUIDField(blank=True, null=True)),
                ("dispense_order_id", models.UUIDField(blank=True, null=True)),
                ("drug_code", models.CharField(blank=True, max_length=100)),
                ("drug_name", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField()),
                ("root_cause", models.TextField(blank=True)),
                ("contributing_factors", models.JSONField(default=list)),
                ("corrective_action", models.TextField(blank=True)),
                ("reported_by", models.UUIDField()),
                ("occurred_at", models.DateTimeField()),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("is_reported_to_authority", models.BooleanField(default=False)),
                ("authority_report_reference", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "db_table": "cymed_medication_safety_events",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "event_type", "severity"],
                        name="cymed_medic_tenant__e61a7a_idx",
                    ),
                    models.Index(
                        fields=["patient_id", "occurred_at"], name="cymed_medic_patient_8c7023_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PharmacyDashboardSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "snapshot_type",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("snapshot_date", models.DateField(db_index=True)),
                ("snapshot_hour", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("prescriptions_total", models.PositiveIntegerField(default=0)),
                ("prescriptions_pending", models.PositiveIntegerField(default=0)),
                ("prescriptions_dispensed", models.PositiveIntegerField(default=0)),
                ("prescriptions_cancelled", models.PositiveIntegerField(default=0)),
                ("controlled_substance_count", models.PositiveIntegerField(default=0)),
                ("dispense_orders_total", models.PositiveIntegerField(default=0)),
                ("dispense_avg_minutes", models.FloatField(default=0.0)),
                ("dispense_verified_count", models.PositiveIntegerField(default=0)),
                ("dispense_errors", models.PositiveIntegerField(default=0)),
                ("automation_dispense_count", models.PositiveIntegerField(default=0)),
                ("drug_interactions_detected", models.PositiveIntegerField(default=0)),
                ("interactions_overridden", models.PositiveIntegerField(default=0)),
                ("clinical_interventions", models.PositiveIntegerField(default=0)),
                ("recommendations_accepted", models.PositiveIntegerField(default=0)),
                ("polypharmacy_cases", models.PositiveIntegerField(default=0)),
                ("reconciliations_completed", models.PositiveIntegerField(default=0)),
                ("conflicts_identified", models.PositiveIntegerField(default=0)),
                ("total_medication_charges_ref", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "cymed_pharmacy_dashboard_snapshots",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "snapshot_type", "snapshot_date"],
                        name="cymed_pharm_tenant__a36c46_idx",
                    )
                ],
                "unique_together": {
                    ("tenant_id", "snapshot_type", "snapshot_date", "snapshot_hour")
                },
            },
        ),
    ]
