# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('vendor', models.CharField(max_length=128)),
                ('product_code', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=32)),
                ('modality', models.CharField(max_length=32)),
                ('body_part', models.CharField(blank=True, max_length=64)),
                ('finding_kinds', models.JSONField(blank=True, default=list)),
                ('regulatory_kind', models.CharField(choices=[('fda_cleared', 'FDA Cleared'), ('ce_marked', 'CE Marked'), ('tga_included', 'TGA Included'), ('sfda_cleared', 'SFDA Cleared'), ('research_only', 'Research Only'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('regulatory_reference', models.CharField(blank=True, max_length=255)),
                ('endpoint_url', models.URLField(blank=True)),
                ('auth_kind', models.CharField(choices=[('none', 'None'), ('bearer', 'Bearer'), ('mtls', 'mTLS'), ('api_key', 'API Key')], default='none', max_length=32)),
                ('auth_secret_ref', models.CharField(blank=True, max_length=128)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_img_ai_triage_ai_model',
                'unique_together': {('vendor', 'product_code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='InferenceRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('study_instance_uid', models.CharField(db_index=True, max_length=128)),
                ('ordered_by_profile_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('dispatched', 'Dispatched'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=32)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inference_runs', to='cymed_img_ai_triage.aimodel')),
            ],
            options={
                'db_table': 'cymed_img_ai_triage_inference_run',
            },
        ),
        migrations.CreateModel(
            name='TriageFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('finding_kind', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=32)),
                ('confidence', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('bbox', models.JSONField(blank=True, default=dict)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='cymed_img_ai_triage.inferencerun')),
            ],
            options={
                'db_table': 'cymed_img_ai_triage_triage_finding',
            },
        ),
        migrations.CreateModel(
            name='TriageQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('modality', models.CharField(max_length=32)),
                ('priority_rules', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_img_ai_triage_triage_queue',
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TriageAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('study_instance_uid', models.CharField(db_index=True, max_length=128)),
                ('patient_profile_id', models.UUIDField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('urgent', 'Urgent'), ('routine', 'Routine')], default='routine', max_length=32)),
                ('finding_kind', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated'), ('read_by_radiologist', 'Read by Radiologist')], default='open', max_length=32)),
                ('assigned_radiologist_id', models.UUIDField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_reason', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cymed_img_ai_triage.inferencerun')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='cymed_img_ai_triage.triagequeue')),
            ],
            options={
                'db_table': 'cymed_img_ai_triage_triage_alert',
            },
        ),
    ]
