# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('appointment_reminder', 'Appointment reminder'), ('recall_annual_checkup', 'Annual checkup recall'), ('recall_lab_repeat', 'Lab repeat reminder'), ('promo_service', 'Service promotion'), ('birthday', 'Birthday greeting'), ('no_show_win_back', 'No-show win-back'), ('post_visit_survey', 'Post-visit survey')], max_length=40)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body_template', models.TextField(help_text='Supports {{patient_name}}, {{clinic_name}}, {{appt_time}}')),
                ('audience_filter', models.JSONField(blank=True, default=dict)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed'), ('paused', 'Paused')], db_index=True, default='draft', max_length=20)),
            ],
            options={
                'db_table': 'cymed_clinic_campaigns',
            },
        ),
        migrations.CreateModel(
            name='CampaignSend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('patient_profile_id', models.UUIDField(db_index=True)),
                ('channel_address', models.CharField(max_length=200)),
                ('payload', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('opened', 'Opened'), ('clicked', 'Clicked')], db_index=True, default='queued', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=200)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='cymed_clinic_marketing.campaign')),
            ],
            options={
                'db_table': 'cymed_clinic_campaign_sends',
                'indexes': [models.Index(fields=['campaign', 'status'], name='cymed_clini_campaig_0ecea3_idx')],
            },
        ),
    ]
