# Generated by Django 6.0.6 on 2026-06-23 04:51

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImagingRevenueEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("order_item_id", models.UUIDField(db_index=True)),
                ("patient_id", models.UUIDField()),
                ("procedure_code", models.CharField(max_length=100)),
                ("modality", models.CharField(max_length=20)),
                (
                    "rvu_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("charge_created", "Charge Created"),
                            ("charge_voided", "Charge Voided"),
                        ],
                        default="charge_created",
                        max_length=30,
                    ),
                ),
                ("outbox_event_id", models.UUIDField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "cymed_img_revenue_events",
            },
        ),
        migrations.CreateModel(
            name="RadiologistProductivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("radiologist_id", models.UUIDField(db_index=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "period_type",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("total_rvu", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("studies_read", models.PositiveIntegerField(default=0)),
                ("reports_finalized", models.PositiveIntegerField(default=0)),
                (
                    "avg_report_tat_hours",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "critical_findings_rate",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "peer_review_score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                ("amendments_issued", models.PositiveIntegerField(default=0)),
                ("by_modality", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "cymed_img_radiologist_productivity",
            },
        ),
        migrations.CreateModel(
            name="ImagingOperationsDashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("snapshot_date", models.DateField(db_index=True)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("studies_completed", models.PositiveIntegerField(default=0)),
                ("reports_finalized", models.PositiveIntegerField(default=0)),
                ("critical_findings", models.PositiveIntegerField(default=0)),
                (
                    "average_tat_hours",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "stat_tat_hours",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "urgent_tat_hours",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "capacity_utilization_pct",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("no_shows", models.PositiveIntegerField(default=0)),
                ("cancellations", models.PositiveIntegerField(default=0)),
                ("by_modality", models.JSONField(default=dict)),
                ("by_priority", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "cymed_img_ops_dashboard",
                "unique_together": {("tenant_id", "snapshot_date", "department")},
            },
        ),
        migrations.CreateModel(
            name="TeleradiologyDashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("snapshot_date", models.DateField(db_index=True)),
                ("total_cases", models.PositiveIntegerField(default=0)),
                ("cases_completed", models.PositiveIntegerField(default=0)),
                ("cases_pending", models.PositiveIntegerField(default=0)),
                (
                    "avg_tat_hours",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "on_time_rate",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("second_opinion_requests", models.PositiveIntegerField(default=0)),
                (
                    "discrepancy_rate",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("by_subspecialty", models.JSONField(default=dict)),
                ("by_facility", models.JSONField(default=dict)),
                ("by_priority", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "cymed_img_teleradiology_dashboard",
                "unique_together": {("tenant_id", "snapshot_date")},
            },
        ),
    ]
