# Generated by Django 6.0.7 on 2026-08-06 15:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCardDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('content_hash', models.CharField(max_length=64)),
                ('snapshot', models.JSONField(default=dict)),
                ('pdf_bytes', models.BinaryField()),
                ('published_by', models.CharField(blank=True, max_length=255)),
                ('acknowledged_by', models.CharField(blank=True, max_length=255)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cyed_reporting.reportcard')),
            ],
            options={
                'db_table': 'cyed_report_card_documents',
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('report_card', 'version'), name='uniq_reportcard_document_version')],
            },
        ),
    ]
