# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NphiesInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('kind', models.CharField(choices=[('eligibility', 'Coverage Eligibility Request'), ('preauth_submit', 'Pre-Auth Submit'), ('preauth_status', 'Pre-Auth Status'), ('claim_submit', 'Claim Submit'), ('remittance', 'Remittance Advice')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, max_length=20)),
                ('licensee_id', models.CharField(blank=True, max_length=100)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('request_bundle', models.JSONField(default=dict)),
                ('response_bundle', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cymed_nphies_interactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
