# Generated by Django 6.0.6 on 2026-06-28 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cymed_portal_accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="patientdevice",
            new_name="cymed_porta_account_60f556_idx",
            old_name="cymed_porta_dev_active_idx",
        ),
        migrations.RenameIndex(
            model_name="patientportalaccount",
            new_name="cymed_porta_patient_305b88_idx",
            old_name="cymed_porta_patient_idx",
        ),
        migrations.RenameIndex(
            model_name="patientportalaccount",
            new_name="cymed_porta_email_5c1b7a_idx",
            old_name="cymed_porta_email_idx",
        ),
        migrations.RenameIndex(
            model_name="patientportalaccount",
            new_name="cymed_porta_account_f5b1ae_idx",
            old_name="cymed_porta_status_idx",
        ),
        migrations.AlterField(
            model_name="patientdevice",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="patientdevice",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="patientdevice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="patientportalaccount",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="patientportalaccount",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="patientportalaccount",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="patientpreferences",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="patientpreferences",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="patientpreferences",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="patientsecuritysettings",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="patientsecuritysettings",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="patientsecuritysettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
