# Generated by Django 6.0.7 on 2026-09-21 19:01

import django.db.models.deletion
import django.utils.timezone
import products.cycom.esign.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='cycom_esign/templates/%Y/%m/')),
                ('fields_config', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'cycom_esign_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('token', models.CharField(default=products.cycom.esign.models._generate_token, editable=False, max_length=64, unique=True)),
                ('signers', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Viewed', 'Viewed'), ('Signed', 'Signed')], default='Sent', max_length=20)),
                ('signature', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='cycom_esign.signtemplate')),
            ],
            options={
                'db_table': 'cycom_esign_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
