# Generated by Django 5.1.15 on 2026-06-23 03:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('product_code', models.CharField(max_length=100)),
                ('edition_code', models.CharField(max_length=100)),
                ('license_type', models.CharField(choices=[('trial', 'Trial'), ('subscription', 'Subscription'), ('annual', 'Annual'), ('multi_year', 'Multi-Year'), ('enterprise', 'Enterprise'), ('government', 'Government'), ('perpetual', 'Perpetual')], default='subscription', max_length=50)),
                ('delivery_mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('air_gapped', 'Air-Gapped'), ('government', 'Government')], default='online', max_length=50)),
                ('customer_id', models.UUIDField(blank=True, null=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('grace_period_days', models.PositiveIntegerField(default=14)),
                ('max_users', models.PositiveIntegerField(default=0)),
                ('max_providers', models.PositiveIntegerField(default=0)),
                ('max_beds', models.PositiveIntegerField(default=0)),
                ('max_facilities', models.PositiveIntegerField(default=0)),
                ('max_api_calls_per_day', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('grace', 'Grace Period'), ('suspended', 'Suspended')], default='active', max_length=50)),
                ('is_multi_tenant', models.BooleanField(default=False)),
                ('signature_hash', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'db_table': 'cymed_commercial_licenses',
            },
        ),
        migrations.CreateModel(
            name='LicenseServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('server_url', models.URLField(blank=True, max_length=500)),
                ('public_key_pem', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_commercial_license_servers',
            },
        ),
        migrations.CreateModel(
            name='LicenseAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('event_type', models.CharField(max_length=100)),
                ('performed_by', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='commercial_licensing.license')),
            ],
            options={
                'db_table': 'cymed_commercial_license_audit',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('key_string', models.CharField(max_length=255, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('is_revoked', models.BooleanField(default=False)),
                ('max_activations', models.PositiveIntegerField(default=1)),
                ('activation_count', models.PositiveIntegerField(default=0)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='commercial_licensing.license')),
            ],
            options={
                'db_table': 'cymed_commercial_license_keys',
            },
        ),
        migrations.CreateModel(
            name='LicenseActivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('machine_fingerprint', models.CharField(blank=True, max_length=512)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('deployment_profile_code', models.CharField(blank=True, max_length=100)),
                ('is_online', models.BooleanField(default=True)),
                ('license_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='commercial_licensing.licensekey')),
            ],
            options={
                'db_table': 'cymed_commercial_license_activations',
            },
        ),
        migrations.CreateModel(
            name='OfflineActivationPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('package_token', models.CharField(max_length=512, unique=True)),
                ('machine_fingerprint', models.CharField(max_length=512)),
                ('signed_payload', models.TextField()),
                ('is_consumed', models.BooleanField(default=False)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_packages', to='commercial_licensing.license')),
            ],
            options={
                'db_table': 'cymed_commercial_offline_packages',
            },
        ),
        migrations.CreateModel(
            name='LicenseFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('feature_code', models.CharField(max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('limit_value', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='commercial_licensing.license')),
            ],
            options={
                'db_table': 'cymed_commercial_license_features',
                'unique_together': {('license', 'feature_code')},
            },
        ),
        migrations.CreateModel(
            name='LicenseUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('snapshot_date', models.DateField()),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('active_providers', models.PositiveIntegerField(default=0)),
                ('active_beds', models.PositiveIntegerField(default=0)),
                ('api_calls', models.PositiveIntegerField(default=0)),
                ('storage_gb', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('is_over_limit', models.BooleanField(default=False)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='commercial_licensing.license')),
            ],
            options={
                'db_table': 'cymed_commercial_license_usage',
                'unique_together': {('license', 'snapshot_date')},
            },
        ),
    ]
