# Generated by Django 6.0.7 on 2026-08-06 21:38

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('asset_tag', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('useful_life_years', models.PositiveSmallIntegerField(default=5)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('in_use', 'In Use'), ('maintenance', 'Maintenance'), ('disposed', 'Disposed')], default='in_use', max_length=20)),
            ],
            options={
                'db_table': 'cyed_assets',
                'ordering': ['name'],
            },
        ),
    ]
