# Generated by Django 6.0.7 on 2026-09-21 19:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_quality', '0002_qualitycheckpoint_attributes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('linked_model', models.CharField(blank=True, help_text="What kind of record this plan applies to, e.g. 'catalog.Product'.", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cycom_quality_inspection_plans',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='qualitycheckpoint',
            name='inspection_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkpoints', to='cycom_quality.inspectionplan'),
        ),
        migrations.CreateModel(
            name='InspectionPlanCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('description', models.CharField(max_length=500)),
                ('expected_value', models.CharField(blank=True, max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='cycom_quality.inspectionplan')),
            ],
            options={
                'db_table': 'cycom_quality_inspection_plan_criteria',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NonConformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('corrective_action', 'Corrective Action'), ('closed', 'Closed')], default='open', max_length=20)),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('disposition', models.CharField(blank=True, choices=[('reject', 'Reject'), ('rework', 'Rework'), ('use_as_is', 'Use As Is'), ('return_to_vendor', 'Return to Vendor')], max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_conformances', to='cycom_quality.qualitycheckpoint')),
            ],
            options={
                'db_table': 'cycom_quality_non_conformances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckpointCriterionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_results', to='cycom_quality.qualitycheckpoint')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cycom_quality.inspectionplancriterion')),
            ],
            options={
                'db_table': 'cycom_quality_checkpoint_criterion_results',
                'ordering': ['criterion__sequence'],
                'unique_together': {('checkpoint', 'criterion')},
            },
        ),
    ]
