# Generated by Django 6.0.7 on 2026-07-22 00:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('number', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=255)),
                ('order_date', models.DateField()),
                ('currency', models.CharField(default='JOD', max_length=10)),
                ('amount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Quotation'), ('confirmed', 'Sales Order'), ('delivered', 'Delivered'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('salesperson', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cycom_sales_orders',
                'ordering': ['-order_date', '-created_at'],
                'unique_together': {('tenant_id', 'number')},
            },
        ),
    ]
