# Generated by Django 6.0.7 on 2026-08-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_sales', '0002_salesorder_amount_subtotal_salesorder_amount_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='customer_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], default='retail', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
