# Generated by Django 6.0.6 on 2026-07-13 19:18

import apps.tenants.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='kitchen_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('READY', 'Ready'), ('SERVED', 'Served')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=apps.tenants.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('device_type', models.CharField(choices=[('POS', 'POS Terminal'), ('KDS', 'Kitchen Display'), ('WAITER', 'Waiter Handheld'), ('CUSTOMER_DISPLAY', 'Customer-Facing Display'), ('WAREHOUSE_SCANNER', 'Warehouse Scanner'), ('SELF_ORDER', 'Self-Order Kiosk')], max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='tenants.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['branch', 'device_type', 'name'],
                'unique_together': {('tenant_id', 'company', 'code')},
            },
        ),
    ]
