# Generated by Django 6.0.6 on 2026-09-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_posorder_kitchen_status_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='daypart',
            field=models.CharField(blank=True, choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('AFTERNOON', 'Afternoon'), ('DINNER', 'Dinner'), ('LATE_NIGHT', 'Late Night')], max_length=20),
        ),
        migrations.AddField(
            model_name='posorder',
            name='placed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posorder',
            name='prep_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posorder',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posorder',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posorder',
            name='source',
            field=models.CharField(choices=[('POS', 'POS Terminal'), ('KIOSK', 'Self-Service Kiosk'), ('ONLINE', 'Online Order'), ('DRIVE_THRU', 'Drive-Thru')], default='POS', max_length=20),
        ),
    ]
