# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCollectionBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_profile_id', models.UUIDField(db_index=True)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('tests_requested', models.JSONField(blank=True, default=list)),
                ('fasting_required', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('dispatched', 'Dispatched'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('collected', 'Collected'), ('delivered_to_lab', 'Delivered To Lab'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='requested', max_length=32)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=32)),
                ('payment_ref', models.CharField(blank=True, max_length=128)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('collection_started_at', models.DateTimeField(blank=True, null=True)),
                ('collection_completed_at', models.DateTimeField(blank=True, null=True)),
                ('specimen_barcodes', models.JSONField(blank=True, default=list)),
                ('proof_of_collection', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'cymed_lab_home_collection_homecollectionbooking',
            },
        ),
        migrations.CreateModel(
            name='HomeCollectionSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.IntegerField(default=1)),
                ('booked_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='open', max_length=32)),
            ],
            options={
                'db_table': 'cymed_lab_home_collection_homecollectionslot',
            },
        ),
        migrations.CreateModel(
            name='Phlebotomist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_profile_id', models.UUIDField(db_index=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=32)),
                ('license_number', models.CharField(blank=True, max_length=64)),
                ('vehicle_plate', models.CharField(blank=True, max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('coverage_cities', models.JSONField(blank=True, default=list)),
                ('cold_chain_capable', models.BooleanField(default=False)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cymed_lab_home_collection_phlebotomist',
            },
        ),
        migrations.CreateModel(
            name='HomeCollectionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kind', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('dispatched', 'Dispatched'), ('arrived', 'Arrived'), ('collected', 'Collected'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('customer_absent', 'Customer Absent')], max_length=32)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('note', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cymed_lab_home_collection.homecollectionbooking')),
            ],
            options={
                'db_table': 'cymed_lab_home_collection_homecollectionevent',
            },
        ),
        migrations.AddField(
            model_name='homecollectionbooking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='cymed_lab_home_collection.homecollectionslot'),
        ),
        migrations.AddField(
            model_name='homecollectionslot',
            name='phlebotomist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='cymed_lab_home_collection.phlebotomist'),
        ),
        migrations.AddField(
            model_name='homecollectionbooking',
            name='phlebotomist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='cymed_lab_home_collection.phlebotomist'),
        ),
    ]
