# Generated by Django 6.0.7 on 2026-07-15 09:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_patients', '0001_initial'),
        ('cymed_providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePathway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cymed_careplan_pathways',
            },
        ),
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Completed')], default='active', max_length=30)),
                ('intent', models.CharField(choices=[('proposal', 'Proposal'), ('plan', 'Plan'), ('order', 'Order')], default='plan', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careplans', to='cymed_patients.patient')),
            ],
            options={
                'db_table': 'cymed_careplans',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='CareIntervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('intervention_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('careplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='cymed_careplans.careplan')),
            ],
            options={
                'db_table': 'cymed_careplan_interventions',
            },
        ),
        migrations.CreateModel(
            name='CareGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('active', 'Active'), ('achieved', 'Achieved'), ('failed', 'Failed')], default='active', max_length=30)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('careplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='cymed_careplans.careplan')),
            ],
            options={
                'db_table': 'cymed_careplan_goals',
            },
        ),
        migrations.CreateModel(
            name='CareTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ready', max_length=30)),
                ('assigned_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cymed_providers.provider')),
                ('careplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cymed_careplans.careplan')),
            ],
            options={
                'db_table': 'cymed_careplan_tasks',
            },
        ),
        migrations.CreateModel(
            name='CareTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('careplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_teams', to='cymed_careplans.careplan')),
                ('members', models.ManyToManyField(db_table='cymed_careteam_members', to='cymed_providers.provider')),
            ],
            options={
                'db_table': 'cymed_careteams',
            },
        ),
    ]
