# Generated by Django 6.1.1 on 2026-09-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_careplans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregoal',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='caregoal',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='caregoal',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='caregoal',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='careintervention',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='careintervention',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='careintervention',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='careintervention',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='carepathway',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='carepathway',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='carepathway',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='carepathway',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='careplan',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='careplan',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='careplan',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='careplan',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='caretask',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='caretask',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='caretask',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='caretask',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='careteam',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='careteam',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='careteam',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='careteam',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
