# Generated by Django 6.0.7 on 2026-08-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='report_accent_color',
            field=models.CharField(default='#0EA5A4', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='report_footer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='report_show_effort',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='report_show_general_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='report_show_logo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='report_title',
            field=models.CharField(default='Student Report Card', max_length=120),
        ),
    ]
