# Generated by Django 6.1 on 2026-08-14 08:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_org', '0002_remove_campus_uniq_campus_code_per_group_and_more'),
        ('cyed_school', '0002_schoolprofile_report_accent_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'Everyone'), ('staff', 'Staff'), ('students', 'Students'), ('parents', 'Parents')], default='all', max_length=20)),
                ('year_levels', models.CharField(blank=True, help_text="e.g. '9,10'. Blank means all year levels.", max_length=100)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('posted_by', models.CharField(blank=True, max_length=255)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='cyed_org.campus')),
            ],
            options={
                'db_table': 'cyed_notices',
                'ordering': ['-priority', '-starts_on'],
                'indexes': [models.Index(fields=['tenant_id', 'starts_on', 'ends_on'], name='idx_notice_window')],
            },
        ),
    ]
