# Generated by Django 6.0.6 on 2026-06-28 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cymed_rcm_pricing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountrule",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="discountrule",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="discountrule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="packageprice",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="packageprice",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="packageprice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="serviceprice",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="serviceprice",
            name="service_category",
            field=models.CharField(
                choices=[
                    ("hospital", "Hospital"),
                    ("clinic", "Clinic"),
                    ("laboratory", "Laboratory"),
                    ("imaging", "Imaging"),
                    ("pharmacy", "Pharmacy"),
                    ("emergency", "Emergency"),
                    ("package", "Package"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="serviceprice",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="serviceprice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name="serviceprice",
            unique_together={("tenant_id", "price_list", "service_code")},
        ),
        migrations.AddIndex(
            model_name="discountrule",
            index=models.Index(
                fields=["tenant_id", "discount_type", "is_active"],
                name="cymed_rcm_p_tenant__bcb3cf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="packageprice",
            index=models.Index(
                fields=["tenant_id", "price_list_id", "package_type"],
                name="cymed_rcm_p_tenant__28be94_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricelist",
            index=models.Index(
                fields=["tenant_id", "service_category", "is_active"],
                name="cymed_rcm_p_tenant__421c66_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricelist",
            index=models.Index(
                fields=["tenant_id", "facility_id"], name="cymed_rcm_p_tenant__d6388f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="serviceprice",
            index=models.Index(
                fields=["tenant_id", "price_list_id", "service_code"],
                name="cymed_rcm_p_tenant__822386_idx",
            ),
        ),
    ]
