# Generated by Django 6.0.7 on 2026-07-15 09:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('organization_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('laboratory', 'Laboratory'), ('imaging_center', 'Imaging Center'), ('pharmacy', 'Pharmacy'), ('health_network', 'Health Network')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationAccreditation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('accreditation_body', models.CharField(max_length=100)),
                ('accreditation_number', models.CharField(max_length=100)),
                ('valid_until', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreditations', to='cymed_organizations.organization')),
            ],
            options={
                'db_table': 'cymed_organization_accreditations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='cymed_organizations.organization')),
            ],
            options={
                'db_table': 'cymed_organization_addresses',
            },
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('telecom_system', models.CharField(choices=[('phone', 'Phone'), ('fax', 'Fax'), ('email', 'Email'), ('url', 'URL')], max_length=20)),
                ('telecom_value', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='cymed_organizations.organization')),
            ],
            options={
                'db_table': 'cymed_organization_contacts',
            },
        ),
        migrations.CreateModel(
            name='OrganizationRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('relationship_type', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('partner', 'Partner')], max_length=50)),
                ('source_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='cymed_organizations.organization')),
                ('target_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relationships', to='cymed_organizations.organization')),
            ],
            options={
                'db_table': 'cymed_organization_relationships',
                'unique_together': {('source_organization', 'target_organization', 'relationship_type')},
            },
        ),
    ]
