# Generated by Django 6.0.6 on 2026-06-28 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cymed_rcm_claims", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="claim",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="claimattachment",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="claimattachment",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="claimattachment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="claimline",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="claimline",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="claimline",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="claimresponse",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="claimresponse",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("eft", "EFT"),
                    ("cheque", "Cheque"),
                    ("credit", "Credit"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="claimresponse",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="claimresponse",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="claimstatus",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="claimstatus",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="claimstatus",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="claimsubmission",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="claimsubmission",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="claimsubmission",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["tenant_id", "patient_id"], name="cymed_rcm_c_tenant__a0377e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["tenant_id", "status"], name="cymed_rcm_c_tenant__8305e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["tenant_id", "claim_date"], name="cymed_rcm_c_tenant__255730_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["tenant_id", "insurance_plan_id"], name="cymed_rcm_c_tenant__1b77fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimattachment",
            index=models.Index(
                fields=["tenant_id", "claim_id"], name="cymed_rcm_c_tenant__6fbd0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimline",
            index=models.Index(
                fields=["tenant_id", "claim_id"], name="cymed_rcm_c_tenant__0a4da4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimresponse",
            index=models.Index(
                fields=["tenant_id", "claim_id"], name="cymed_rcm_c_tenant__38d71f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimstatus",
            index=models.Index(
                fields=["tenant_id", "claim_id"], name="cymed_rcm_c_tenant__1a3bac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimsubmission",
            index=models.Index(
                fields=["tenant_id", "claim_id"], name="cymed_rcm_c_tenant__d4fcc6_idx"
            ),
        ),
    ]
