# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiasAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('ai_model_id', models.UUIDField(db_index=True)),
                ('version', models.CharField(blank=True, max_length=32)),
                ('cohort_kind', models.CharField(choices=[('sex', 'Sex'), ('age_group', 'Age Group'), ('ethnicity', 'Ethnicity'), ('socioeconomic', 'Socioeconomic'), ('geographic', 'Geographic'), ('language', 'Language'), ('equipment_vendor', 'Equipment Vendor')], max_length=32)),
                ('cohort_value', models.CharField(blank=True, max_length=64)),
                ('sample_size', models.IntegerField(default=0)),
                ('auc', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('sensitivity', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('specificity', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('false_positive_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('false_negative_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('equity_flag', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cymed_mrff_ai_diagnostics_biasaudit',
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('ai_model_id', models.UUIDField(db_index=True)),
                ('version', models.CharField(max_length=32)),
                ('environment', models.CharField(choices=[('shadow', 'Shadow'), ('canary', 'Canary'), ('production', 'Production'), ('retired', 'Retired')], default='canary', max_length=32)),
                ('traffic_percent', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('rollback_reason', models.TextField(blank=True)),
                ('deployed_by_profile_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cymed_mrff_ai_diagnostics_deployment',
            },
        ),
        migrations.CreateModel(
            name='DriftMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('metric_kind', models.CharField(choices=[('input_drift', 'Input Drift'), ('prediction_drift', 'Prediction Drift'), ('performance_drift', 'Performance Drift'), ('calibration_drift', 'Calibration Drift'), ('data_quality', 'Data Quality')], max_length=32)),
                ('score', models.DecimalField(decimal_places=6, max_digits=9)),
                ('threshold', models.DecimalField(decimal_places=6, default=Decimal('0.05'), max_digits=9)),
                ('breach', models.BooleanField(default=False)),
                ('details', models.JSONField(default=dict)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_metrics', to='cymed_mrff_ai_diagnostics.deployment')),
            ],
            options={
                'db_table': 'cymed_mrff_ai_diagnostics_driftmetric',
            },
        ),
        migrations.CreateModel(
            name='HitlReviewQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('trigger_rules', models.JSONField(default=dict)),
                ('priority', models.IntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_mrff_ai_diagnostics_hitlreviewqueue',
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='HitlReviewItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('inference_run_id', models.UUIDField(db_index=True)),
                ('study_instance_uid', models.CharField(db_index=True, max_length=128)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='routine', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('overridden', 'Overridden'), ('no_change', 'No Change'), ('escalated', 'Escalated'), ('expired', 'Expired')], default='pending', max_length=32)),
                ('assigned_reviewer_id', models.UUIDField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('override_kind', models.CharField(blank=True, max_length=64)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cymed_mrff_ai_diagnostics.hitlreviewqueue')),
            ],
            options={
                'db_table': 'cymed_mrff_ai_diagnostics_hitlreviewitem',
            },
        ),
        migrations.CreateModel(
            name='InferenceOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('study_instance_uid', models.CharField(db_index=True, max_length=128)),
                ('inference_run_id', models.UUIDField(blank=True, null=True)),
                ('predicted_kind', models.CharField(blank=True, max_length=64)),
                ('predicted_confidence', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('ground_truth_kind', models.CharField(blank=True, max_length=64)),
                ('ground_truth_source', models.CharField(choices=[('radiologist_reviewed', 'Radiologist Reviewed'), ('gold_standard', 'Gold Standard'), ('follow_up', 'Follow-up'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('outcome', models.CharField(choices=[('true_positive', 'True Positive'), ('false_positive', 'False Positive'), ('true_negative', 'True Negative'), ('false_negative', 'False Negative'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_profile_id', models.UUIDField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='cymed_mrff_ai_diagnostics.deployment')),
            ],
            options={
                'db_table': 'cymed_mrff_ai_diagnostics_inferenceoutcome',
            },
        ),
        migrations.CreateModel(
            name='ModelCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('ai_model_id', models.UUIDField(db_index=True)),
                ('intended_use', models.TextField()),
                ('target_population', models.TextField(blank=True)),
                ('clinical_workflow', models.TextField(blank=True)),
                ('inputs_description', models.TextField(blank=True)),
                ('outputs_description', models.TextField(blank=True)),
                ('performance', models.JSONField(default=dict)),
                ('validation_datasets', models.JSONField(default=list)),
                ('known_limitations', models.TextField(blank=True)),
                ('ethical_considerations', models.TextField(blank=True)),
                ('maintainer_email', models.CharField(blank=True, max_length=255)),
                ('regulatory_kind', models.CharField(choices=[('fda_cleared', 'FDA Cleared'), ('ce_marked', 'CE Marked'), ('tga_included', 'TGA Included'), ('sfda_cleared', 'SFDA Cleared'), ('research_only', 'Research Only'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('regulatory_reference', models.CharField(blank=True, max_length=255)),
                ('tga_artg_number', models.CharField(blank=True, max_length=64)),
                ('version', models.CharField(max_length=32)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cymed_mrff_ai_diagnostics_modelcard',
                'unique_together': {('ai_model_id', 'version')},
            },
        ),
    ]
