# Generated by Django 6.0.7 on 2026-09-23 13:21

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('sales_orders', 'Sales Orders'), ('invoices', 'Invoices')], max_length=40)),
                ('dimension', models.CharField(max_length=60)),
                ('measure', models.CharField(max_length=60)),
                ('aggregation', models.CharField(choices=[('sum', 'Sum'), ('avg', 'Average'), ('count', 'Count')], default='sum', max_length=10)),
                ('chart_type', models.CharField(choices=[('table', 'Table'), ('bar', 'Bar Chart'), ('pie', 'Pie Chart')], default='table', max_length=10)),
            ],
            options={
                'db_table': 'cycom_reporting_saved_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
