# Generated by Django 6.0.6 on 2026-06-28 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cymed_provider_workforce", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="credentialexpiry",
            new_name="cymed_prov__tenant__777b47_idx",
            old_name="cymed_prov_cred_tid_pid_exp_idx",
        ),
        migrations.RenameIndex(
            model_name="credentialexpiry",
            new_name="cymed_prov__tenant__b7fff6_idx",
            old_name="cymed_prov_cred_tid_alert_idx",
        ),
        migrations.RenameIndex(
            model_name="providerschedule",
            new_name="cymed_prov__tenant__9fec62_idx",
            old_name="cymed_prov_sched_tid_pid_date_idx",
        ),
        migrations.RenameIndex(
            model_name="providerschedule",
            new_name="cymed_prov__tenant__6ad437_idx",
            old_name="cymed_prov_sched_tid_uid_date_idx",
        ),
    ]
