# Generated by Django 6.0.7 on 2026-09-27 18:30

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('model_key', models.CharField(db_index=True, max_length=50)),
                ('field_key', models.SlugField()),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Yes / No'), ('select', 'Dropdown')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cycom_customfield_definitions',
                'ordering': ['sort_order', 'label'],
                'indexes': [models.Index(fields=['tenant_id', 'model_key', 'is_active'], name='cycom_custo_tenant__be525b_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'model_key', 'field_key'), name='unique_customfield_key_per_model_per_tenant')],
            },
        ),
    ]
