# Generated by Django 6.0.6 on 2026-06-28 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_rcm_contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrate',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='contractrate',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='contractrate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='contractrule',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='contractrule',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='contractrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payercontract',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='payercontract',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='payercontract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='reimbursementrule',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='reimbursementrule',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='reimbursementrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='contractrate',
            unique_together={('tenant_id', 'contract', 'service_code', 'effective_date')},
        ),
        migrations.AddIndex(
            model_name='contractrate',
            index=models.Index(fields=['tenant_id', 'contract_id', 'service_code'], name='cymed_rcm_c_tenant__89f58c_idx'),
        ),
        migrations.AddIndex(
            model_name='contractrule',
            index=models.Index(fields=['tenant_id', 'contract_id', 'rule_type'], name='cymed_rcm_c_tenant__ccf630_idx'),
        ),
        migrations.AddIndex(
            model_name='payercontract',
            index=models.Index(fields=['tenant_id', 'insurance_company_id'], name='cymed_rcm_c_tenant__b10ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='payercontract',
            index=models.Index(fields=['tenant_id', 'status'], name='cymed_rcm_c_tenant__2e23ae_idx'),
        ),
        migrations.AddIndex(
            model_name='reimbursementrule',
            index=models.Index(fields=['tenant_id', 'contract_id'], name='cymed_rcm_c_tenant__252098_idx'),
        ),
    ]
