# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('requested_by_profile_id', models.UUIDField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX'), ('pdf', 'PDF'), ('json', 'JSON')], max_length=32)),
                ('filter_payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('file_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cymed_eco_analytics_export',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('snapshot_date', models.DateField()),
                ('kind', models.CharField(choices=[('patient_flow', 'Patient Flow'), ('revenue', 'Revenue'), ('referral_network', 'Referral Network'), ('provider_utilisation', 'Provider Utilisation'), ('wait_times', 'Wait Times'), ('adherence', 'Adherence'), ('retention', 'Retention'), ('claim_kpis', 'Claim KPIs')], max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'cymed_eco_analytics_snapshot',
                'unique_together': {('tenant_id', 'snapshot_date', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('audience', models.CharField(choices=[('executive', 'Executive'), ('clinical', 'Clinical'), ('operations', 'Operations'), ('commercial', 'Commercial'), ('regulator', 'Regulator')], max_length=32)),
                ('layout', models.JSONField(default=dict)),
                ('shared_with_tenant_ids', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_eco_analytics_dashboard',
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('position', models.IntegerField(default=0)),
                ('kind', models.CharField(choices=[('kpi', 'KPI'), ('line', 'Line'), ('bar', 'Bar'), ('pie', 'Pie'), ('heatmap', 'Heatmap'), ('geomap', 'Geomap'), ('funnel', 'Funnel'), ('cohort', 'Cohort'), ('table', 'Table')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('data_source', models.CharField(max_length=64)),
                ('params', models.JSONField(default=dict)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='cymed_eco_analytics.dashboard')),
            ],
            options={
                'db_table': 'cymed_eco_analytics_dashboard_widget',
            },
        ),
    ]
