# Generated by Django 6.0.7 on 2026-09-13 11:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_access', '0003_accessgrant_product_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('pin_hash', models.CharField(blank=True, max_length=255)),
                ('barcode_hash', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('role_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='cycom_access.roleassignment')),
            ],
            options={
                'db_table': 'cycom_access_manager_credentials',
                'ordering': ['-created_at'],
            },
        ),
    ]
