# Generated by Django 6.0.6 on 2026-06-28 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_portal_appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='portalappointmentrequest',
            new_name='cymed_porta_account_610c5f_idx',
            old_name='cymed_appt_req_acct_status_idx',
        ),
        migrations.RenameIndex(
            model_name='portalappointmentrequest',
            new_name='cymed_porta_patient_af3c78_idx',
            old_name='cymed_appt_req_patient_status_idx',
        ),
        migrations.RenameIndex(
            model_name='portalappointmentrequest',
            new_name='cymed_porta_provide_997ef6_idx',
            old_name='cymed_appt_req_provider_date_idx',
        ),
        migrations.RenameIndex(
            model_name='waitlistentry',
            new_name='cymed_porta_account_c2a9a4_idx',
            old_name='cymed_waitlist_acct_status_idx',
        ),
        migrations.RenameIndex(
            model_name='waitlistentry',
            new_name='cymed_porta_provide_2772a3_idx',
            old_name='cymed_waitlist_provider_status_idx',
        ),
        migrations.AlterField(
            model_name='appointmentrating',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='appointmentrating',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='appointmentrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='appointmentreminder',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='appointmentreminder',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='appointmentreminder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='portalappointmentrequest',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='portalappointmentrequest',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='portalappointmentrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
