# Generated by Django 6.0.7 on 2026-07-15 12:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('protocol', models.CharField(default='fhir', max_length=50)),
                ('direction', models.CharField(default='bidirectional', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'platform_integration_partners',
            },
        ),
        migrations.CreateModel(
            name='TransformationMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('source_format', models.CharField(max_length=50)),
                ('target_format', models.CharField(max_length=50)),
                ('mapping_rules', models.JSONField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'platform_transformation_mappings',
            },
        ),
        migrations.CreateModel(
            name='ConnectorConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('connector_type', models.CharField(max_length=50)),
                ('endpoint_url', models.CharField(max_length=1000)),
                ('auth_config', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('sync_interval_seconds', models.PositiveIntegerField(default=300)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='cyintegrationhub.integrationpartner')),
            ],
            options={
                'db_table': 'platform_connector_configs',
            },
        ),
        migrations.CreateModel(
            name='MessageAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('connector_type', models.CharField(db_index=True, max_length=50)),
                ('direction', models.CharField(db_index=True, max_length=20)),
                ('payload_size_bytes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('processed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyintegrationhub.integrationpartner')),
            ],
            options={
                'db_table': 'platform_integration_message_audits',
                'ordering': ['-processed_at'],
            },
        ),
    ]
