# Generated by Django 6.0.6 on 2026-06-23 07:48

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryQueryResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("drug_code", models.CharField(db_index=True, max_length=100)),
                ("drug_name", models.CharField(blank=True, max_length=500)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "quantity_on_hand",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("quantity_unit", models.CharField(blank=True, max_length=50)),
                ("reorder_level", models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ("is_below_reorder", models.BooleanField(default=False)),
                ("is_out_of_stock", models.BooleanField(default=False)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("erp_item_id", models.CharField(blank=True, max_length=255)),
                ("cached_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cymed_inventory_query_cache",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "drug_code"], name="cymed_inven_tenant__c8fbe4_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MedicationConsumptionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("dispense_order_id", models.UUIDField(db_index=True)),
                ("prescription_id", models.UUIDField(blank=True, null=True)),
                ("patient_id", models.UUIDField(db_index=True)),
                ("drug_code", models.CharField(db_index=True, max_length=100)),
                ("drug_name", models.CharField(max_length=500)),
                ("ndc_code", models.CharField(blank=True, max_length=50)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("quantity_unit", models.CharField(max_length=50)),
                ("lot_number", models.CharField(blank=True, max_length=100)),
                ("dispensed_from_location", models.CharField(blank=True, max_length=255)),
                ("dispensed_at", models.DateTimeField()),
                (
                    "erp_sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("synced", "Synced"),
                            ("failed", "Failed"),
                            ("manual", "Manual"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("erp_transaction_id", models.CharField(blank=True, max_length=255)),
                ("erp_synced_at", models.DateTimeField(blank=True, null=True)),
                ("erp_error", models.TextField(blank=True)),
            ],
            options={
                "db_table": "cymed_inventory_consumption_events",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "erp_sync_status"],
                        name="cymed_inven_tenant__ae3e5b_idx",
                    ),
                    models.Index(
                        fields=["drug_code", "dispensed_at"], name="cymed_inven_drug_co_70d0e7_idx"
                    ),
                ],
            },
        ),
    ]
