# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HakeemMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('direction', models.CharField(choices=[('pull', 'Pull from Hakeem'), ('push', 'Push to Hakeem')], max_length=10)),
                ('transport', models.CharField(choices=[('rpc', 'VistaRPC'), ('sftp_hl7', 'SFTP HL7 v2'), ('fhir', 'FHIR (2026)')], max_length=20)),
                ('op', models.CharField(db_index=True, max_length=100)),
                ('subject_national_id', models.CharField(blank=True, db_index=True, max_length=30)),
                ('request_payload', models.TextField(blank=True)),
                ('response_payload', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cymed_hakeem_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
