# Generated by Django 6.1.1 on 2026-09-04 02:39

import platform.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_int_hakeem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakeemmessage',
            name='subject_national_id_bidx',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='hakeemmessage',
            name='subject_national_id',
            field=platform.common.fields.EncryptedText(blank=True, blind_index=True, classification='national_id', default=b'', editable=True),
        ),
    ]
