# Generated by Django 6.1.1 on 2026-09-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_int_hakeem', '0003_encrypt_hakeem_subject_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakeemmessage',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hakeemmessage',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='hakeemmessage',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='hakeemmessage',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
