# Generated by Django 6.0.6 on 2026-06-28 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cymed_provider_orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="providerorderrequest",
            new_name="cymed_prov__tenant__f55947_idx",
            old_name="cymed_prov_ord_tid_pid_cat_idx",
        ),
        migrations.RenameIndex(
            model_name="providerorderrequest",
            new_name="cymed_prov__tenant__b61ced_idx",
            old_name="cymed_prov_ord_tid_opid_sts_idx",
        ),
    ]
