# Generated by Django 6.0.7 on 2026-07-19 18:40

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='cycom_documents/%Y/%m/')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('linked_model', models.CharField(blank=True, max_length=100)),
                ('linked_id', models.UUIDField(blank=True, null=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cycom_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['linked_model', 'linked_id'], name='cycom_docum_linked__6e4529_idx')],
            },
        ),
    ]
