# Generated by Django 6.0.7 on 2026-07-19 19:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('activity_name', models.CharField(help_text="e.g. 'Diesel combustion', 'Grid electricity'.", max_length=255)),
                ('unit', models.CharField(help_text="e.g. 'liter', 'kWh', 'km'.", max_length=50)),
                ('kg_co2e_per_unit', models.DecimalField(decimal_places=6, max_digits=12)),
                ('source', models.CharField(blank=True, help_text='Reference for this factor.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cycom_esg_emission_factors',
                'ordering': ['activity_name'],
            },
        ),
        migrations.CreateModel(
            name='EmissionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1 — Direct'), ('scope_2', 'Scope 2 — Purchased Energy'), ('scope_3', 'Scope 3 — Value Chain')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('activity_date', models.DateField()),
                ('department', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('co2e_kg', models.DecimalField(decimal_places=4, default=Decimal('0'), editable=False, max_digits=16)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='cycom_esg.emissionfactor')),
            ],
            options={
                'db_table': 'cycom_esg_emission_entries',
                'ordering': ['-activity_date'],
            },
        ),
    ]
