# Generated by Django 6.0.7 on 2026-10-02 08:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('api_key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('key_prefix', models.CharField(help_text='First chars of the key, for display/audit.', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cymart_partner',
            },
        ),
        migrations.CreateModel(
            name='PartnerCallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='cymart_partners.partner')),
            ],
            options={
                'db_table': 'cymart_partner_call_log',
                'indexes': [models.Index(fields=['partner', 'created_at'], name='cymart_part_partner_fbe6c1_idx')],
            },
        ),
    ]
