# Generated by Django 6.0.7 on 2026-09-21 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_company', '0001_initial'),
        ('cycom_procurement', '0004_requestforquotation_vendorbid_vendorbidline'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='cycom_company.company'),
        ),
    ]
