# Generated by Django 6.0.7 on 2026-09-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_procurement', '0005_purchaseorder_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('received', 'Received'), ('partially_received', 'Partially Received')], default='draft', max_length=20),
        ),
    ]
