# Generated by Django 6.0.7 on 2026-07-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_cyidentity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationclient',
            name='client_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='applicationclient',
            unique_together={('realm', 'client_id')},
        ),
    ]
