# Generated by Django 6.0.7 on 2026-07-20 11:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_cyidentity', '0002_alter_applicationclient_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('cyid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=300)),
                ('primary_email', models.EmailField(max_length=254)),
                ('primary_phone', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('home_realm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_persons', to='platform_cyidentity.identityrealm')),
            ],
            options={
                'db_table': 'platform_person_identities',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='person',
            field=models.ForeignKey(blank=True, help_text='CyID this profile belongs to. Null for realm-local users never enrolled in CyID.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='platform_cyidentity.personidentity'),
        ),
        migrations.AddIndex(
            model_name='personidentity',
            index=models.Index(fields=['primary_email'], name='platform_pe_primary_d32696_idx'),
        ),
        migrations.AddIndex(
            model_name='personidentity',
            index=models.Index(fields=['status'], name='platform_pe_status_ca13e1_idx'),
        ),
    ]
