# Generated by Django 6.1.1 on 2026-09-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_cyidentity', '0003_personidentity_userprofile_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakglassaccess',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='breakglassaccess',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='breakglassaccess',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='breakglassaccess',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='clientsecret',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='clientsecret',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='clientsecret',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='deviceregistration',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='loginaudit',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='loginaudit',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='loginaudit',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='loginaudit',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usersession',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='webauthncredential',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='webauthncredential',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='webauthncredential',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='webauthncredential',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
