# Generated by Django 6.0.6 on 2026-06-23 04:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('loinc_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('snomed_code', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('chemistry', 'Chemistry'), ('hematology', 'Hematology'), ('immunology', 'Immunology'), ('serology', 'Serology'), ('microbiology', 'Microbiology'), ('pathology', 'Pathology'), ('molecular', 'Molecular Diagnostics'), ('blood_bank', 'Blood Bank'), ('urinalysis', 'Urinalysis'), ('toxicology', 'Toxicology')], default='chemistry', max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('specimen_types_accepted', models.JSONField(default=list)),
                ('container_types', models.JSONField(default=list)),
                ('turn_around_hours', models.PositiveIntegerField(default=24)),
                ('stat_tat_hours', models.PositiveIntegerField(default=2)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('method', models.CharField(blank=True, max_length=100)),
                ('analyzer_code', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_fasting', models.BooleanField(default=False)),
                ('requires_clinical_info', models.BooleanField(default=False)),
                ('patient_preparation', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'cymed_lab_tests',
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('encounter_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('admission_id', models.UUIDField(blank=True, null=True)),
                ('order_type', models.CharField(choices=[('hospital', 'Hospital Inpatient'), ('clinic', 'Outpatient Clinic'), ('external', 'External Referral'), ('standing', 'Standing Order'), ('stat_manual', 'STAT Manual')], default='clinic', max_length=30)),
                ('priority', models.CharField(choices=[('stat', 'STAT'), ('urgent', 'Urgent'), ('routine', 'Routine'), ('timed', 'Timed'), ('fasting', 'Fasting')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_progress', 'In Progress'), ('partial', 'Partially Resulted'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='submitted', max_length=30)),
                ('ordered_by', models.UUIDField()),
                ('ordering_location', models.CharField(blank=True, max_length=255)),
                ('clinical_notes', models.TextField(blank=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('fhir_service_request_id', models.CharField(blank=True, max_length=255)),
                ('hl7_placer_order_number', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'cymed_lab_orders',
                'indexes': [models.Index(fields=['patient_id', 'status'], name='cymed_lab_o_patient_b97209_idx'), models.Index(fields=['tenant_id', 'order_type', 'priority'], name='cymed_lab_o_tenant__ddbdff_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabOrderAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_url', models.URLField(max_length=1000)),
                ('uploaded_by', models.UUIDField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='lab_orders.laborder')),
            ],
            options={
                'db_table': 'cymed_lab_order_attachments',
            },
        ),
        migrations.CreateModel(
            name='LabOrderDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('icd11_code', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='lab_orders.laborder')),
            ],
            options={
                'db_table': 'cymed_lab_order_diagnoses',
            },
        ),
        migrations.CreateModel(
            name='LabOrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('changed_by', models.UUIDField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='lab_orders.laborder')),
            ],
            options={
                'db_table': 'cymed_lab_order_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='LabPanel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('loinc_code', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('chemistry', 'Chemistry'), ('hematology', 'Hematology'), ('immunology', 'Immunology'), ('serology', 'Serology'), ('microbiology', 'Microbiology'), ('pathology', 'Pathology'), ('molecular', 'Molecular Diagnostics'), ('blood_bank', 'Blood Bank'), ('urinalysis', 'Urinalysis'), ('toxicology', 'Toxicology')], default='chemistry', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_orderable', models.BooleanField(default=True)),
                ('cpt_code', models.CharField(blank=True, max_length=20)),
                ('tests', models.ManyToManyField(blank=True, related_name='panels', to='lab_orders.labtest')),
            ],
            options={
                'db_table': 'cymed_lab_panels',
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('collected', 'Specimen Collected'), ('received', 'Specimen Received'), ('in_progress', 'In Progress'), ('resulted', 'Resulted'), ('verified', 'Verified'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold'), ('referred', 'Referred to Reference Lab')], default='ordered', max_length=30)),
                ('priority', models.CharField(choices=[('stat', 'STAT'), ('urgent', 'Urgent'), ('routine', 'Routine'), ('timed', 'Timed'), ('fasting', 'Fasting')], default='routine', max_length=20)),
                ('specimen_type', models.CharField(blank=True, max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resulted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('worklist_assigned', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lab_orders.laborder')),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='lab_orders.labpanel')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='lab_orders.labtest')),
            ],
            options={
                'db_table': 'cymed_lab_order_items',
                'indexes': [models.Index(fields=['order', 'status'], name='cymed_lab_o_order_i_b51ac1_idx')],
            },
        ),
    ]
