# Generated by Django 6.0.7 on 2026-07-19 18:46

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('assignee', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('linked_model', models.CharField(blank=True, max_length=100)),
                ('linked_id', models.UUIDField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cycom_todo_tasks',
                'ordering': ['is_done', 'due_date'],
            },
        ),
    ]
