# Generated by Django 6.0.7 on 2026-10-02 19:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_orders', '0003_order_attributes_order_created_by_order_row_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_order_sets',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'code'), name='uniq_order_set_code_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='OrderSetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('order_type', models.CharField(choices=[('laboratory', 'Laboratory Order'), ('imaging', 'Imaging Order'), ('medication', 'Medication Request'), ('procedure', 'Procedure Request'), ('referral', 'Referral Request')], max_length=30)),
                ('code', models.CharField(max_length=100)),
                ('display', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT (Immediate)')], default='routine', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('default_selected', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('order_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cymed_orders.orderset')),
            ],
            options={
                'db_table': 'cymed_order_set_items',
                'ordering': ['sort_order', 'display'],
            },
        ),
    ]
