# Generated by Django 6.0.6 on 2026-06-23 04:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceLab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(default='SA', max_length=5)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('integration_type', models.CharField(choices=[('fhir', 'FHIR R4 API'), ('hl7', 'HL7 v2.x (via CyIntegrationHub)'), ('flat_file', 'Flat File (CSV/Excel)'), ('api_rest', 'REST API'), ('manual', 'Manual Entry')], max_length=20)),
                ('api_endpoint', models.URLField(blank=True, max_length=500)),
                ('api_key_reference', models.CharField(blank=True, max_length=255)),
                ('fhir_base_url', models.URLField(blank=True, max_length=500)),
                ('integration_hub_channel', models.CharField(blank=True, max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('sla_tat_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Onboarding')], default='active', max_length=20)),
                ('is_national', models.BooleanField(default=False)),
                ('is_government', models.BooleanField(default=False)),
                ('certifications', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'cymed_lab_reference_labs',
            },
        ),
        migrations.CreateModel(
            name='ReferenceLabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('external_order_id', models.CharField(blank=True, max_length=255)),
                ('external_accession_number', models.CharField(blank=True, max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('expected_result_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Dispatch'), ('sent', 'Sent to Reference Lab'), ('received', 'Received by Reference Lab'), ('in_progress', 'In Progress'), ('resulted', 'Result Received'), ('imported', 'Result Imported'), ('failed', 'Failed â€” Intervention Required'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('dispatch_method', models.CharField(blank=True, max_length=30)),
                ('specimen_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('local_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_lab_orders', to='lab_orders.laborderitem')),
                ('reference_lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='lab_reference.referencelab')),
            ],
            options={
                'db_table': 'cymed_lab_reference_orders',
            },
        ),
        migrations.CreateModel(
            name='ReferenceLabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('raw_result', models.JSONField(default=dict)),
                ('raw_format', models.CharField(blank=True, max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('imported_by', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Raw Result Received'), ('parsed', 'Parsed Successfully'), ('imported', 'Imported to LIS Result'), ('parse_error', 'Parse Error'), ('import_error', 'Import Error')], default='received', max_length=20)),
                ('error_detail', models.TextField(blank=True)),
                ('linked_result_id', models.UUIDField(blank=True, null=True)),
                ('reference_lab_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='lab_reference.referencelaborder')),
            ],
            options={
                'db_table': 'cymed_lab_reference_results',
            },
        ),
        migrations.CreateModel(
            name='ReferenceLabRouting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('is_default', models.BooleanField(default=False)),
                ('conditions', models.JSONField(default=dict)),
                ('estimated_tat_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('priority_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('reference_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='lab_reference.referencelab')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='lab_orders.labtest')),
            ],
            options={
                'db_table': 'cymed_lab_reference_routing',
                'ordering': ['test', 'priority_order'],
            },
        ),
        migrations.AddIndex(
            model_name='referencelaborder',
            index=models.Index(fields=['reference_lab', 'status', 'sent_at'], name='cymed_lab_r_referen_60ea5f_idx'),
        ),
    ]
