# Generated by Django 6.0.7 on 2026-07-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_alter_role_code_alter_role_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cyid_person_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
