# Generated by Django 6.0.6 on 2026-06-28 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cymed_portal_payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="installmentplan",
            new_name="cymed_porta_account_e1d19c_idx",
            old_name="cymed_portal_inst_acct_status_idx",
        ),
        migrations.RenameIndex(
            model_name="patientinvoice",
            new_name="cymed_porta_account_1692a6_idx",
            old_name="cymed_portal_invoices_acct_status_due_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentmethod",
            new_name="cymed_porta_account_f6b2c3_idx",
            old_name="cymed_portal_pm_acct_active_idx",
        ),
        migrations.RenameIndex(
            model_name="paymenttransaction",
            new_name="cymed_porta_account_b0ccd7_idx",
            old_name="cymed_portal_txn_acct_status_paid_idx",
        ),
        migrations.AlterField(
            model_name="installmentplan",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="installmentplan",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="installmentplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="patientinvoice",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="patientinvoice",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="patientinvoice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
