# Generated by Django 6.0.7 on 2026-08-06 17:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyed_sis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('blood_type', models.CharField(blank=True, max_length=5)),
                ('allergies', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('dietary_requirements', models.CharField(blank=True, max_length=255)),
                ('emergency_contact', models.CharField(blank=True, max_length=255)),
                ('medicare_number', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_record', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_health_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('administered_by', models.CharField(blank=True, max_length=255)),
                ('medication_given', models.CharField(blank=True, max_length=255)),
                ('parent_notified', models.BooleanField(default=False)),
                ('sent_home', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_incidents', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_medical_incidents',
                'ordering': ['-date'],
            },
        ),
    ]
