# Generated by Django 6.0.7 on 2026-08-06 22:04

import core.crypto
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='allergies',
            field=core.crypto.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='conditions',
            field=core.crypto.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='medicare_number',
            field=core.crypto.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='medications',
            field=core.crypto.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='notes',
            field=core.crypto.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalincident',
            name='description',
            field=core.crypto.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalincident',
            name='treatment',
            field=core.crypto.EncryptedTextField(blank=True),
        ),
    ]
