# Generated by Django 6.1 on 2026-08-14 07:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_health', '0003_immunisationrecord_medicationauthority_and_more'),
        ('cyed_sis', '0006_student_exit_date_student_exit_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('plan_type', models.CharField(choices=[('anaphylaxis', 'Anaphylaxis'), ('asthma', 'Asthma'), ('diabetes', 'Diabetes'), ('seizure', 'Seizure / epilepsy'), ('allergy', 'Allergy (non-anaphylactic)'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Critical — life-threatening'), ('high', 'High'), ('moderate', 'Moderate')], default='high', max_length=20)),
                ('triggers', models.CharField(blank=True, max_length=500)),
                ('emergency_steps', models.TextField(help_text='What to do, in order. Read aloud in an emergency — keep it plain.')),
                ('medication', models.CharField(blank=True, help_text="e.g. 'EpiPen Jr 150mcg — in the front office fridge, red box'", max_length=255)),
                ('medication_location', models.CharField(blank=True, max_length=255)),
                ('prescriber_name', models.CharField(blank=True, max_length=255)),
                ('signed_on', models.DateField(blank=True, null=True)),
                ('review_due', models.DateField(blank=True, null=True)),
                ('document_ref', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_health_action_plans',
                'ordering': ['student', 'plan_type'],
                'indexes': [models.Index(fields=['tenant_id', 'review_due'], name='idx_action_plan_review')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'student', 'plan_type'), name='uniq_action_plan_per_student_type')],
            },
        ),
    ]
