# Generated by Django 6.1 on 2026-08-14 10:03

import core.crypto
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_health', '0004_actionplan'),
        ('cyed_hr', '0004_staffleave_balance_override_by_and_more'),
        ('cyed_sis', '0006_student_exit_date_student_exit_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SickBayVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('arrived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('referred_by', models.CharField(blank=True, max_length=255)),
                ('complaint', core.crypto.EncryptedTextField(blank=True)),
                ('observations', core.crypto.EncryptedTextField(blank=True)),
                ('treatment', core.crypto.EncryptedTextField(blank=True)),
                ('outcome', models.CharField(choices=[('in_progress', 'Still in the sick bay'), ('returned_to_class', 'Returned to class'), ('sent_home', 'Collected by a guardian'), ('emergency', 'Emergency services called')], default='in_progress', max_length=30)),
                ('collected_by', models.CharField(blank=True, max_length=255)),
                ('guardians_notified', models.PositiveSmallIntegerField(default=0)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('medication_given', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sick_bay_visits', to='cyed_health.medicationadministration')),
                ('seen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sick_bay_visits', to='cyed_hr.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sick_bay_visits', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_sick_bay_visits',
                'ordering': ['-arrived_at'],
                'indexes': [models.Index(fields=['tenant_id', 'departed_at'], name='idx_sickbay_open')],
            },
        ),
    ]
