# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabAppointmentSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('facility_id', models.UUIDField(blank=True, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.IntegerField(default=1)),
                ('booked_count', models.IntegerField(default=0)),
                ('collection_mode', models.CharField(choices=[('in_lab', 'In Lab'), ('home', 'Home'), ('drive_through', 'Drive Through')], default='in_lab', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='open', max_length=32)),
            ],
            options={
                'db_table': 'cymed_lab_online_booking_lab_appointment_slot',
            },
        ),
        migrations.CreateModel(
            name='BookableTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('specimen_type', models.CharField(blank=True, max_length=32)),
                ('turnaround_hours', models.IntegerField(default=24)),
                ('fasting_required', models.BooleanField(default=False)),
                ('preparation_instructions', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=5)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'cymed_lab_online_booking_bookable_test',
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LabBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_profile_id', models.UUIDField(db_index=True)),
                ('tests', models.JSONField(blank=True, default=list)),
                ('packages', models.JSONField(blank=True, default=list)),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('discount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('vat', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('total', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('partial_refund', 'Partial Refund')], default='unpaid', max_length=32)),
                ('payment_ref', models.CharField(blank=True, max_length=128)),
                ('bill_id', models.UUIDField(blank=True, null=True)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('home_collection_booking_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('placed', 'Placed'), ('paid', 'Paid'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('booking_ref', models.CharField(blank=True, max_length=64)),
                ('requisition_url', models.URLField(blank=True)),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='cymed_lab_online_booking.labappointmentslot')),
            ],
            options={
                'db_table': 'cymed_lab_online_booking_lab_booking',
            },
        ),
        migrations.CreateModel(
            name='LabPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=5)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True)),
                ('tests', models.ManyToManyField(blank=True, related_name='packages', to='cymed_lab_online_booking.bookabletest')),
            ],
            options={
                'db_table': 'cymed_lab_online_booking_lab_package',
                'unique_together': {('tenant_id', 'code')},
            },
        ),
    ]
