# Generated by Django 5.1.15 on 2026-06-23 00:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_patients', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivingFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('facility_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cymed_hospital_transfer_facilities',
            },
        ),
        migrations.CreateModel(
            name='TransferCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('source_hospital_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='initiated', max_length=50)),
                ('reason', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cymed_patients.patient')),
                ('target_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cymed_hospital_transfer_center.receivingfacility')),
            ],
            options={
                'db_table': 'cymed_hospital_transfer_cases',
            },
        ),
        migrations.CreateModel(
            name='ExternalReferral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('referring_physician_name', models.CharField(max_length=255)),
                ('referral_document_url', models.URLField(blank=True, max_length=500)),
                ('transfer_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cymed_hospital_transfer_center.transfercase')),
            ],
            options={
                'db_table': 'cymed_hospital_transfer_referrals',
            },
        ),
        migrations.CreateModel(
            name='AcceptanceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('reviewed_by', models.UUIDField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(choices=[('accept', 'Accept'), ('deny', 'Deny')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('transfer_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='cymed_hospital_transfer_center.transfercase')),
            ],
            options={
                'db_table': 'cymed_hospital_transfer_reviews',
            },
        ),
    ]
