# Generated by Django 6.0.6 on 2026-06-28 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cymed_rcm_collections", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionaction",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="collectionaction",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="collectionaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="collectioncase",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="collectioncase",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="collectioncase",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="collectionoutcome",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="collectionoutcome",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="collectionoutcome",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="tenant_id",
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
