# Generated by Django 6.0.7 on 2026-08-06 15:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyed_sis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('recipient_kind', models.CharField(choices=[('guardian', 'Guardian'), ('student', 'Student'), ('staff', 'Staff'), ('other', 'Other')], default='guardian', max_length=20)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_email', models.CharField(blank=True, max_length=255)),
                ('recipient_phone', models.CharField(blank=True, max_length=50)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('whatsapp', 'WhatsApp')], default='in_app', max_length=20)),
                ('category', models.CharField(choices=[('attendance', 'Attendance'), ('announcement', 'Announcement'), ('billing', 'Billing'), ('wellbeing', 'Wellbeing'), ('general', 'General')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('related_model', models.CharField(blank=True, max_length=100)),
                ('related_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], default='queued', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'recipient_email'], name='cyed_notifi_tenant__defd7a_idx')],
            },
        ),
    ]
