# Generated by Django 6.1 on 2026-08-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='provider',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='notification',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
