# Generated by Django 6.1 on 2026-08-14 13:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_notifications', '0002_notification_provider_and_more'),
        ('cyed_org', '0002_remove_campus_uniq_campus_code_per_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('parents', 'Parents and guardians'), ('staff', 'Staff'), ('students', 'Students'), ('all', 'Everyone')], default='parents', max_length=20)),
                ('year_levels', models.CharField(blank=True, max_length=100)),
                ('channel', models.CharField(default='in_app', help_text='in_app, email or push. SMS is deliberately not offered for bulk.', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_by', models.CharField(blank=True, max_length=255)),
                ('recipients', models.PositiveIntegerField(default=0)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='cyed_org.campus')),
            ],
            options={
                'db_table': 'cyed_newsletters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('owner_email', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('web', 'Web push'), ('ios', 'iOS'), ('android', 'Android')], default='web', max_length=20)),
                ('token', models.TextField()),
                ('endpoint', models.TextField(blank=True)),
                ('p256dh', models.CharField(blank=True, max_length=255)),
                ('auth', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'cyed_push_devices',
                'ordering': ['-last_used_at', '-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'owner_email'], name='idx_push_owner')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'token'), name='uniq_push_token_per_tenant')],
            },
        ),
    ]
