# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('clinic', 'Clinic'), ('hospital', 'Hospital'), ('pharmacy', 'Pharmacy'), ('lab', 'Lab'), ('imaging_center', 'Imaging Center'), ('telehealth_desk', 'Telehealth Desk'), ('dental', 'Dental')], default='clinic', max_length=32)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('address', models.JSONField(default=dict)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('specialties', models.JSONField(default=list)),
                ('services', models.JSONField(default=list)),
                ('languages', models.JSONField(default=list)),
                ('accepts_insurers', models.JSONField(default=list)),
                ('accreditations', models.JSONField(default=list)),
                ('hours', models.JSONField(default=dict)),
                ('telehealth_capable', models.BooleanField(default=False)),
                ('home_visit_capable', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_eco_provider_directory_network_facility',
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='NetworkPractitioner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_profile_id', models.UUIDField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, max_length=16)),
                ('specialty', models.CharField(blank=True, max_length=64)),
                ('subspecialties', models.JSONField(default=list)),
                ('languages', models.JSONField(default=list)),
                ('years_experience', models.IntegerField(default=0)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('teleconsultation_capable', models.BooleanField(default=False)),
                ('accepts_new_patients', models.BooleanField(default=True)),
                ('photo_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('primary_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_practitioners', to='cymed_eco_provider_directory.networkfacility')),
            ],
            options={
                'db_table': 'cymed_eco_provider_directory_network_practitioner',
            },
        ),
        migrations.CreateModel(
            name='DirectoryReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(choices=[('facility', 'Facility'), ('practitioner', 'Practitioner')], default='facility', max_length=32)),
                ('patient_profile_id', models.UUIDField(db_index=True)),
                ('rating', models.IntegerField(default=5)),
                ('text', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=32)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cymed_eco_provider_directory.networkfacility')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cymed_eco_provider_directory.networkpractitioner')),
            ],
            options={
                'db_table': 'cymed_eco_provider_directory_directory_review',
            },
        ),
        migrations.CreateModel(
            name='PractitionerFacilityAffiliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('role', models.CharField(choices=[('attending', 'Attending'), ('consultant', 'Consultant'), ('visiting', 'Visiting'), ('on_call', 'On Call'), ('owner', 'Owner')], default='attending', max_length=32)),
                ('days', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='cymed_eco_provider_directory.networkfacility')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='cymed_eco_provider_directory.networkpractitioner')),
            ],
            options={
                'db_table': 'cymed_eco_provider_directory_practitioner_facility_affiliation',
            },
        ),
    ]
