# Generated by Django 6.1.1 on 2026-09-04 07:20

import platform.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_clinic_consultations', '0003_encrypt_consultation_narrative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationplan',
            name='prescriptions',
            field=platform.common.fields.EncryptedJSON(blank=True, classification='phi', default=list, editable=True),
        ),
    ]
