# Generated by Django 5.1.15 on 2026-06-22 20:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_clinic_specialties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_clinic_clinical_forms',
            },
        ),
        migrations.CreateModel(
            name='ClinicalFormSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cymed_clinic_clinical_forms.clinicalform')),
            ],
            options={
                'db_table': 'cymed_clinic_clinical_form_sections',
            },
        ),
        migrations.CreateModel(
            name='ClinicalFormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('label', models.CharField(max_length=255)),
                ('label_ar', models.CharField(blank=True, max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=50)),
                ('options_json', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='cymed_clinic_clinical_forms.clinicalformsection')),
            ],
            options={
                'db_table': 'cymed_clinic_clinical_form_fields',
            },
        ),
        migrations.CreateModel(
            name='ClinicalFormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('encounter_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('submitted_by', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('values_json', models.JSONField(default=dict)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='cymed_clinic_clinical_forms.clinicalform')),
            ],
            options={
                'db_table': 'cymed_clinic_clinical_form_submissions',
            },
        ),
        migrations.CreateModel(
            name='ClinicalFormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='cymed_clinic_clinical_forms.clinicalform')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_templates', to='cymed_clinic_specialties.specialtyprofile')),
            ],
            options={
                'db_table': 'cymed_clinic_clinical_form_templates',
                'unique_together': {('specialty', 'form')},
            },
        ),
    ]
