# Generated by Django 6.0.6 on 2026-06-23 04:10

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lab_orders", "0001_initial"),
        ("lab_worklists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProficiencyTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("program_name", models.CharField(max_length=255)),
                ("program_provider", models.CharField(blank=True, max_length=255)),
                ("testing_period", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("submission_date", models.DateField(blank=True, null=True)),
                ("deadline_date", models.DateField(blank=True, null=True)),
                ("test_list", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("sample_received", "Sample Received"),
                            ("testing", "Testing in Progress"),
                            ("submitted", "Results Submitted"),
                            ("graded", "Graded"),
                        ],
                        default="enrolled",
                        max_length=30,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "score_percentage",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("grade", models.CharField(blank=True, max_length=20)),
                ("report_url", models.URLField(blank=True, max_length=1000)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "cymed_lab_proficiency_tests",
            },
        ),
        migrations.CreateModel(
            name="QualityControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("lot_number", models.CharField(max_length=100)),
                ("product_name", models.CharField(blank=True, max_length=255)),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("L1", "Level 1 (Low Normal)"),
                            ("L2", "Level 2 (Normal)"),
                            ("L3", "Level 3 (High)"),
                            ("L4", "Level 4 (Pathological)"),
                        ],
                        default="L2",
                        max_length=5,
                    ),
                ),
                ("target_mean", models.DecimalField(decimal_places=6, max_digits=18)),
                ("target_sd", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "allowable_sd_multiplier",
                    models.DecimalField(decimal_places=1, default=2, max_digits=4),
                ),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("expiry_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "analyzer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_materials",
                        to="lab_worklists.analyzer",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_materials",
                        to="lab_orders.labtest",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_lab_quality_controls",
                "unique_together": {("tenant_id", "test", "lot_number", "level")},
            },
        ),
        migrations.CreateModel(
            name="QualityRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("12s", "1â‚‚s â€” Warning: >2 SD"),
                            ("13s", "1â‚ƒs â€” Rejection: >3 SD"),
                            ("22s", "2â‚‚s â€” Rejection: 2 consecutive >2 SD same direction"),
                            ("r4s", "Râ‚„s â€” Rejection: Range >4 SD between controls"),
                            ("41s", "4â‚\x81s â€” Rejection: 4 consecutive >1 SD same direction"),
                            ("10x", "10x â€” Rejection: 10 consecutive on same side of mean"),
                            ("custom", "Custom Rule"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("is_warning", models.BooleanField(default=False)),
                ("is_rejection", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                (
                    "analyzer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qc_rules",
                        to="lab_worklists.analyzer",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_rules",
                        to="lab_orders.labtest",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_lab_quality_rules",
            },
        ),
        migrations.CreateModel(
            name="QualityRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("run_date", models.DateField()),
                ("run_time", models.TimeField()),
                ("technologist_id", models.UUIDField()),
                ("analyzer_id", models.UUIDField(blank=True, null=True)),
                ("measured_value", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "z_score",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
                ),
                ("passed", models.BooleanField()),
                ("is_warning", models.BooleanField(default=False)),
                ("is_rejection", models.BooleanField(default=False)),
                ("rules_triggered", models.JSONField(default=list)),
                ("comments", models.CharField(blank=True, max_length=500)),
                (
                    "qc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="lab_quality.qualitycontrol",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_lab_quality_runs",
            },
        ),
        migrations.CreateModel(
            name="QualityFailure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("failure_type", models.CharField(blank=True, max_length=100)),
                ("root_cause", models.TextField(blank=True)),
                ("corrective_action", models.TextField(blank=True)),
                ("action_taken_by", models.UUIDField(blank=True, null=True)),
                ("action_taken_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by", models.UUIDField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Under Investigation"),
                            ("corrective_action", "Corrective Action Taken"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated"),
                        ],
                        default="open",
                        max_length=30,
                    ),
                ),
                ("patient_results_affected", models.BooleanField(default=False)),
                ("results_held_count", models.PositiveIntegerField(default=0)),
                (
                    "qc_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failures",
                        to="lab_quality.qualityrun",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_lab_quality_failures",
            },
        ),
        migrations.AddIndex(
            model_name="qualityrun",
            index=models.Index(
                fields=["qc", "run_date", "passed"], name="cymed_lab_q_qc_id_568f37_idx"
            ),
        ),
    ]
