# Generated by Django 6.0.6 on 2026-06-23 04:51

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("img_orders", "0001_initial"),
        ("img_reporting", "0001_initial"),
        ("img_worklist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccreditationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("accreditation_body", models.CharField(max_length=100)),
                ("accreditation_type", models.CharField(max_length=100)),
                ("certificate_number", models.CharField(blank=True, max_length=100)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("modality_types", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "cymed_img_accreditation",
            },
        ),
        migrations.CreateModel(
            name="QualityAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("auditor_id", models.UUIDField()),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("peer_review", "Peer Review"),
                            ("clinical_audit", "Clinical Audit"),
                            ("random_audit", "Random Audit"),
                            ("targeted_audit", "Targeted Audit"),
                        ],
                        default="peer_review",
                        max_length=30,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                (
                    "discrepancy_level",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("minor", "Minor"),
                            ("major", "Major"),
                            ("critical", "Critical"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("action_required", models.BooleanField(default=False)),
                ("action_description", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_audits",
                        to="img_reporting.radiologyreport",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_img_quality_audits",
            },
        ),
        migrations.CreateModel(
            name="RadiationDoseRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("patient_id", models.UUIDField(db_index=True)),
                ("modality", models.CharField(max_length=20)),
                (
                    "effective_dose_msv",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "ctdivol",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "dlp",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "dap",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                ("kvp", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("mas", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                (
                    "ssde",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                ("dose_report_uid", models.CharField(blank=True, max_length=255)),
                ("exceeds_drp", models.BooleanField(default=False)),
                (
                    "order_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dose_record",
                        to="img_orders.imagingorderitem",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_img_dose_records",
            },
        ),
        migrations.CreateModel(
            name="ImagingQualityMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("metric_date", models.DateField(db_index=True)),
                ("repeat_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("rejection_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                (
                    "patient_dose_avg",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
                ),
                ("patient_dose_unit", models.CharField(blank=True, max_length=20)),
                ("total_studies", models.PositiveIntegerField(default=0)),
                ("repeated_studies", models.PositiveIntegerField(default=0)),
                ("reason_breakdown", models.JSONField(default=dict)),
                ("within_dose_reference", models.BooleanField(default=True)),
                (
                    "modality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="img_worklist.modality"
                    ),
                ),
            ],
            options={
                "db_table": "cymed_img_quality_metrics",
                "unique_together": {("modality", "metric_date")},
            },
        ),
    ]
