# Generated by Django 5.1.15 on 2026-06-23 00:21

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnesthesiaAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("assessed_by", models.UUIDField()),
                ("asa_class", models.CharField(max_length=50)),
                ("airway_mallampati", models.PositiveSmallIntegerField()),
                ("notes", models.TextField()),
            ],
            options={
                "db_table": "cymed_hospital_anesthesia_assessments",
            },
        ),
        migrations.CreateModel(
            name="AnesthesiaPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("anesthetic_type", models.CharField(max_length=100)),
                ("plan_description", models.TextField()),
            ],
            options={
                "db_table": "cymed_hospital_anesthesia_plans",
            },
        ),
        migrations.CreateModel(
            name="AnesthesiaRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("anesthesiologist_id", models.UUIDField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("agents_used", models.JSONField()),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "cymed_hospital_anesthesia_records",
            },
        ),
        migrations.CreateModel(
            name="RecoveryAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                ("aldrete_score", models.PositiveIntegerField()),
                ("comments", models.TextField(blank=True)),
            ],
            options={
                "db_table": "cymed_hospital_anesthesia_recovery_assessments",
            },
        ),
    ]
