# Generated by Django 6.0.7 on 2026-07-16 18:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycom_accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('uom', models.CharField(default='each', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('inventory_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_as_inventory', to='cycom_accounting.account')),
            ],
            options={
                'db_table': 'cycom_inventory_products',
                'ordering': ['sku'],
                'unique_together': {('tenant_id', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cycom_inventory_warehouses',
                'ordering': ['code'],
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('move_type', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('done', 'Done'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cycom_accounting.journalentry')),
                ('offset_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='cycom_accounting.account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='cycom_inventory.product')),
                ('destination_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves_in', to='cycom_inventory.warehouse')),
                ('warehouse', models.ForeignKey(help_text='Source warehouse (issue/transfer/adjustment) or destination (receipt).', on_delete=django.db.models.deletion.PROTECT, related_name='moves_out', to='cycom_inventory.warehouse')),
            ],
            options={
                'db_table': 'cycom_inventory_stock_moves',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('quantity_on_hand', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('average_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='cycom_inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='cycom_inventory.warehouse')),
            ],
            options={
                'db_table': 'cycom_inventory_stock_items',
                'unique_together': {('tenant_id', 'product', 'warehouse')},
            },
        ),
    ]
