# Generated by Django 6.0.7 on 2026-07-16 22:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('number', models.CharField(max_length=100)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('allocated', 'Allocated'), ('dispatched', 'Dispatched'), ('received', 'Received'), ('partially_received', 'Partially Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_orders_in', to='cycom_inventory.warehouse')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_orders_out', to='cycom_inventory.warehouse')),
            ],
            options={
                'db_table': 'cycom_inventory_internal_orders',
                'ordering': ['-created_at'],
                'unique_together': {('tenant_id', 'number')},
            },
        ),
        migrations.CreateModel(
            name='InternalOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('requested_qty', models.DecimalField(decimal_places=4, max_digits=12)),
                ('allocated_qty', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('shipped_qty', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('received_qty', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('discrepancy_reason', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cycom_inventory.internalorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_order_lines', to='cycom_inventory.product')),
            ],
            options={
                'db_table': 'cycom_inventory_internal_order_lines',
                'ordering': ['id'],
            },
        ),
    ]
