# Generated by Django 6.0.7 on 2026-09-13 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_accounting', '0004_documentsequence'),
        ('cycom_inventory', '0003_internalorder_attributes_internalorder_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='pos_advance_liability_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses_pos_advance_liability', to='cycom_accounting.account'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='pos_cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses_pos_cash', to='cycom_accounting.account'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='pos_cogs_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses_pos_cogs', to='cycom_accounting.account'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='pos_revenue_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses_pos_revenue', to='cycom_accounting.account'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='pos_tax_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses_pos_tax', to='cycom_accounting.account'),
        ),
    ]
