# Generated by Django 6.0.7 on 2026-09-13 10:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_catalog', '0004_product_pricing_mode_product_tracking_mode'),
        ('cycom_inventory', '0005_product_master_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmove',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='lot_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='serial_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('lot_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_on_hand', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('average_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='cycom_catalog.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='cycom_inventory.warehouse')),
            ],
            options={
                'db_table': 'cycom_inventory_stock_lots',
                'ordering': ['expiry_date', 'lot_number'],
                'unique_together': {('tenant_id', 'product', 'warehouse', 'lot_number')},
            },
        ),
        migrations.AddField(
            model_name='stockmove',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='cycom_inventory.stocklot'),
        ),
        migrations.CreateModel(
            name='SerialUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('serial_number', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('issued', 'Issued'), ('returned', 'Returned')], default='in_stock', max_length=20)),
                ('sold_reference', models.CharField(blank=True, max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serial_units', to='cycom_catalog.product')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Null once issued — the unit has left the warehouse.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serial_units', to='cycom_inventory.warehouse')),
            ],
            options={
                'db_table': 'cycom_inventory_serial_units',
                'ordering': ['serial_number'],
                'unique_together': {('tenant_id', 'product', 'serial_number')},
            },
        ),
    ]
