# Generated by Django 6.0.7 on 2026-09-26 19:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_inventory', '0006_stockmove_expiry_date_stockmove_lot_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('location_type', models.CharField(choices=[('zone', 'Zone'), ('aisle', 'Aisle'), ('rack', 'Rack'), ('shelf', 'Shelf'), ('bin', 'Bin')], max_length=20)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cycom_inventory.storagelocation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='cycom_inventory.warehouse')),
            ],
            options={
                'db_table': 'cycom_inventory_storage_locations',
                'ordering': ['warehouse', 'sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='stockitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='cycom_inventory.storagelocation'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['tenant_id', 'warehouse', 'location_type'], name='cycom_inven_tenant__928d7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storagelocation',
            unique_together={('tenant_id', 'warehouse', 'code')},
        ),
    ]
