# Generated by Django 6.0.7 on 2026-09-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_inventory', '0007_storagelocation_stockitem_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='pos_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='pos_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='size_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='size_w',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
