# Generated by Django 5.1.15 on 2026-06-23 03:25

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("customer_id", models.UUIDField()),
                ("license_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=50,
                    ),
                ),
                ("started_at", models.DateField()),
                ("current_period_start", models.DateField()),
                ("current_period_end", models.DateField()),
                ("auto_renew", models.BooleanField(default=True)),
                ("contracted_users", models.PositiveIntegerField(default=0)),
                ("contracted_beds", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "cymed_commercial_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("product_code", models.CharField(max_length=100)),
                ("edition_code", models.CharField(max_length=100)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                            ("multi_year", "Multi-Year"),
                            ("enterprise", "Enterprise Agreement"),
                        ],
                        default="annual",
                        max_length=50,
                    ),
                ),
                ("base_price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("per_user_price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("per_bed_price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "cymed_commercial_subscription_plans",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("contract_number", models.CharField(max_length=100, unique=True)),
                ("signed_at", models.DateField(blank=True, null=True)),
                ("contract_years", models.PositiveIntegerField(default=1)),
                ("total_contract_value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("payment_terms", models.CharField(blank=True, max_length=255)),
                ("sla_tier", models.CharField(default="standard", max_length=50)),
                ("dedicated_csm", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract",
                        to="commercial_subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_commercial_subscription_contracts",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("invoice_number", models.CharField(max_length=100, unique=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("base_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("overage_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("void", "Void"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("due_date", models.DateField()),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="commercial_subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_commercial_subscription_invoices",
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="commercial_subscriptions.subscriptionplan",
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("peak_users", models.PositiveIntegerField(default=0)),
                ("peak_providers", models.PositiveIntegerField(default=0)),
                ("peak_beds", models.PositiveIntegerField(default=0)),
                ("total_api_calls", models.PositiveBigIntegerField(default=0)),
                (
                    "total_storage_gb",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("total_transactions", models.PositiveBigIntegerField(default=0)),
                (
                    "billable_overage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage",
                        to="commercial_subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_commercial_subscription_usage",
                "unique_together": {("subscription", "period_start")},
            },
        ),
    ]
