# Generated by Django 6.0.7 on 2026-08-05 11:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyed_sis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('assessment_type', models.CharField(choices=[('formative', 'Formative'), ('summative', 'Summative'), ('assignment', 'Assignment'), ('exam', 'Exam')], default='assignment', max_length=20)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=7)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('curriculum_code', models.CharField(blank=True, max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='cyed_sis.classsection')),
            ],
            options={
                'db_table': 'cyed_assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('comment', models.TextField(blank=True)),
                ('achievement_level', models.CharField(blank=True, max_length=5)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='cyed_gradebook.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_grades',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'student'), name='uniq_grade_per_student_assessment')],
            },
        ),
    ]
