# Generated by Django 6.1 on 2026-08-14 12:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_gradebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('year_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('curriculum_code', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cyed_rubrics',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='cyed_gradebook.rubric'),
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='cyed_gradebook.rubric')),
            ],
            options={
                'db_table': 'cyed_rubric_criteria',
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RubricLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('label', models.CharField(max_length=100)),
                ('descriptor', models.TextField(help_text='What work at this level actually looks like.')),
                ('marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('achievement_level', models.CharField(blank=True, max_length=5)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='cyed_gradebook.rubriccriterion')),
            ],
            options={
                'db_table': 'cyed_rubric_levels',
                'ordering': ['criterion', '-marks'],
            },
        ),
        migrations.CreateModel(
            name='RubricMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('comment', models.TextField(blank=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgements', to='cyed_gradebook.rubriccriterion')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_marks', to='cyed_gradebook.grade')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awarded_to', to='cyed_gradebook.rubriclevel')),
            ],
            options={
                'db_table': 'cyed_rubric_marks',
                'ordering': ['criterion__sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='rubriclevel',
            constraint=models.UniqueConstraint(fields=('criterion', 'label'), name='uniq_level_label_per_criterion'),
        ),
        migrations.AddConstraint(
            model_name='rubricmark',
            constraint=models.UniqueConstraint(fields=('grade', 'criterion'), name='uniq_mark_per_criterion_per_grade'),
        ),
    ]
