# Generated by Django 5.1.15 on 2026-06-23 00:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('rule_name', models.CharField(max_length=255)),
                ('metric_source', models.CharField(max_length=100)),
                ('threshold_value', models.PositiveIntegerField()),
                ('action_plan_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cymed_hospital_capacity_rules',
            },
        ),
        migrations.CreateModel(
            name='OverflowUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('temporary_capacity', models.PositiveIntegerField()),
                ('current_occupancy', models.PositiveIntegerField(default=0)),
                ('is_open', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cymed_hospital_overflow_units',
            },
        ),
        migrations.CreateModel(
            name='SurgePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('trigger_condition', models.CharField(max_length=255)),
                ('allocated_beds_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cymed_hospital_surge_plans',
            },
        ),
        migrations.CreateModel(
            name='CapacityThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('current_value', models.PositiveIntegerField()),
                ('status_level', models.CharField(default='normal', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cymed_hospital_capacity_management.capacityrule')),
            ],
            options={
                'db_table': 'cymed_hospital_capacity_thresholds',
            },
        ),
    ]
