# Generated by Django 6.0.6 on 2026-06-23 07:48

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcurementRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("request_number", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("reorder", "Routine Reorder"),
                            ("emergency", "Emergency Procurement"),
                            ("non_formulary", "Non-Formulary Request"),
                            ("shortage", "Drug Shortage"),
                        ],
                        default="reorder",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted to ERP"),
                            ("approved", "ERP Approved"),
                            ("ordered", "Purchase Order Created"),
                            ("received", "Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("drug_code", models.CharField(db_index=True, max_length=100)),
                ("drug_name", models.CharField(max_length=500)),
                ("quantity_requested", models.DecimalField(decimal_places=3, max_digits=12)),
                ("quantity_unit", models.CharField(max_length=50)),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("routine", "Routine"),
                            ("urgent", "Urgent"),
                            ("emergency", "Emergency"),
                        ],
                        default="routine",
                        max_length=20,
                    ),
                ),
                ("clinical_justification", models.TextField(blank=True)),
                ("requested_by", models.UUIDField()),
                ("preferred_supplier_id", models.CharField(blank=True, max_length=255)),
                ("target_delivery_date", models.DateField(blank=True, null=True)),
                ("erp_purchase_order_id", models.CharField(blank=True, max_length=255)),
                ("erp_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("erp_response", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "cymed_procurement_requests",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status", "urgency"],
                        name="cymed_procu_tenant__afa253_idx",
                    ),
                    models.Index(
                        fields=["drug_code", "request_type"], name="cymed_procu_drug_co_660847_idx"
                    ),
                ],
            },
        ),
    ]
