# Generated by Django 6.0.6 on 2026-06-28 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_portal_insurance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='claimstatus',
            new_name='cymed_porta_account_8c1219_idx',
            old_name='cymed_portal_claim_acct_idx',
        ),
        migrations.RenameIndex(
            model_name='coverageverification',
            new_name='cymed_porta_account_1faa7f_idx',
            old_name='cymed_portal_cov_ver_acct_idx',
        ),
        migrations.RenameIndex(
            model_name='insurancecard',
            new_name='cymed_porta_account_36502b_idx',
            old_name='cymed_portal_ins_card_acct_idx',
        ),
        migrations.RenameIndex(
            model_name='preauthorizationrequest',
            new_name='cymed_porta_account_35c325_idx',
            old_name='cymed_portal_preauth_acct_idx',
        ),
        migrations.AlterField(
            model_name='claimstatus',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='claimstatus',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='claimstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='coverageverification',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='coverageverification',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='coverageverification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='insurancecard',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='insurancecard',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='insurancecard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='preauthorizationrequest',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='preauthorizationrequest',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='preauthorizationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
