# Generated by Django 6.0.6 on 2026-06-28 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_provider_care_team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='careteammember',
            name='unique_care_team_member_per_team',
        ),
        migrations.AlterField(
            model_name='careteam',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='careteam',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='careteam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='careteamassignment',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='careteamassignment',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='careteamassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='careteammember',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='careteammember',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='careteammember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='careteamrole',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='careteamrole',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='careteamrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='coverageschedule',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='coverageschedule',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='coverageschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='careteammember',
            unique_together={('tenant_id', 'care_team', 'provider_id')},
        ),
    ]
