# Generated by Django 6.1.1 on 2026-09-04 07:20

import platform.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_img_tele_marketplace', '0003_encrypt_telereport_narrative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telereport',
            name='findings',
            field=platform.common.fields.EncryptedJSON(blank=True, classification='phi', default=dict, editable=True, json_default=dict),
        ),
    ]
