# Generated by Django 6.0.6 on 2026-06-28 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_portal_directory', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cliniclisting',
            new_name='cymed_dir_c_tenant__fec974_idx',
            old_name='cymed_dir_clinic_tenant_city_spec_idx',
        ),
        migrations.RenameIndex(
            model_name='cliniclisting',
            new_name='cymed_dir_c_is_feat_042ad1_idx',
            old_name='cymed_dir_clinic_featured_idx',
        ),
        migrations.RenameIndex(
            model_name='hospitallisting',
            new_name='cymed_dir_h_tenant__356acb_idx',
            old_name='cymed_dir_hosp_tenant_city_pub_idx',
        ),
        migrations.RenameIndex(
            model_name='hospitallisting',
            new_name='cymed_dir_h_is_feat_2e5944_idx',
            old_name='cymed_dir_hosp_featured_pub_idx',
        ),
        migrations.RenameIndex(
            model_name='providerreview',
            new_name='cymed_dir_r_provide_61043d_idx',
            old_name='cymed_dir_rev_type_listing_pub_idx',
        ),
        migrations.AlterField(
            model_name='cliniclisting',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='cliniclisting',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='cliniclisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='clinicspecialty',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='clinicspecialty',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='clinicspecialty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='hospitallisting',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='hospitallisting',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='hospitallisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='imagingcenterlisting',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='imagingcenterlisting',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='imagingcenterlisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='laboratorylisting',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='laboratorylisting',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='laboratorylisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pharmacylisting',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='pharmacylisting',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='pharmacylisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='providerreview',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='providerreview',
            name='tenant_id',
            field=models.UUIDField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='providerreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
