# Generated by Django 6.0.6 on 2026-06-23 04:10

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lab_orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodCompatibility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("patient_id", models.UUIDField(db_index=True)),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("AB", "AB"),
                            ("O", "O"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "rh_type",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "antibody_screen",
                    models.CharField(
                        choices=[
                            ("negative", "Negative"),
                            ("positive", "Positive â€” Antibody Identified"),
                            ("positive_pending", "Positive â€” Antibody Identification Pending"),
                            ("not_done", "Not Done"),
                        ],
                        default="not_done",
                        max_length=20,
                    ),
                ),
                ("antibodies_identified", models.JSONField(default=list)),
                ("special_requirements", models.JSONField(default=list)),
                ("verified_by", models.UUIDField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("sample_expiry_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "cymed_lab_blood_compatibility",
                "indexes": [
                    models.Index(
                        fields=["patient_id", "verified_at"], name="cymed_lab_b_patient_a985b4_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BloodInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("prbc", "Packed Red Blood Cells (PRBC)"),
                            ("ffp", "Fresh Frozen Plasma (FFP)"),
                            ("platelets", "Platelet Concentrate"),
                            ("cryo", "Cryoprecipitate"),
                            ("whole_blood", "Whole Blood"),
                            ("albumin", "Albumin"),
                            ("ivig", "IVIG"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("AB", "AB"),
                            ("O", "O"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "rh_type",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=10,
                    ),
                ),
                ("storage_location", models.CharField(blank=True, max_length=100)),
                ("available_units", models.PositiveIntegerField(default=0)),
                ("reserved_units", models.PositiveIntegerField(default=0)),
                ("minimum_threshold", models.PositiveIntegerField(default=2)),
                ("reorder_level", models.PositiveIntegerField(default=5)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cymed_lab_blood_inventory",
                "unique_together": {
                    ("tenant_id", "product_type", "blood_group", "rh_type", "storage_location")
                },
            },
        ),
        migrations.CreateModel(
            name="BloodProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("unit_number", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("prbc", "Packed Red Blood Cells (PRBC)"),
                            ("ffp", "Fresh Frozen Plasma (FFP)"),
                            ("platelets", "Platelet Concentrate"),
                            ("cryo", "Cryoprecipitate"),
                            ("whole_blood", "Whole Blood"),
                            ("albumin", "Albumin"),
                            ("ivig", "IVIG"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("AB", "AB"),
                            ("O", "O"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "rh_type",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("volume_ml", models.PositiveIntegerField(blank=True, null=True)),
                ("collection_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("issued", "Issued"),
                            ("transfused", "Transfused"),
                            ("discarded", "Discarded"),
                            ("quarantined", "Quarantined"),
                            ("expired", "Expired"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("storage_location", models.CharField(blank=True, max_length=100)),
                ("supplier", models.CharField(blank=True, max_length=255)),
                ("special_attributes", models.JSONField(default=list)),
            ],
            options={
                "db_table": "cymed_lab_blood_products",
                "indexes": [
                    models.Index(
                        fields=["product_type", "blood_group", "rh_type", "status"],
                        name="cymed_lab_b_product_7ed203_idx",
                    ),
                    models.Index(
                        fields=["expiry_date", "status"], name="cymed_lab_b_expiry__61d5a7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TransfusionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("patient_id", models.UUIDField(db_index=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("prbc", "Packed Red Blood Cells (PRBC)"),
                            ("ffp", "Fresh Frozen Plasma (FFP)"),
                            ("platelets", "Platelet Concentrate"),
                            ("cryo", "Cryoprecipitate"),
                            ("whole_blood", "Whole Blood"),
                            ("albumin", "Albumin"),
                            ("ivig", "IVIG"),
                        ],
                        max_length=20,
                    ),
                ),
                ("units_requested", models.PositiveSmallIntegerField(default=1)),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("elective", "Elective"),
                            ("urgent", "Urgent (2h)"),
                            ("emergency", "Emergency (30min)"),
                            ("massive_hemorrhage", "Massive Haemorrhage Protocol"),
                        ],
                        default="elective",
                        max_length=30,
                    ),
                ),
                ("clinical_indication", models.CharField(blank=True, max_length=500)),
                ("requested_by", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("crossmatch_ordered", "Crossmatch Ordered"),
                            ("crossmatch_done", "Crossmatch Complete"),
                            ("units_allocated", "Units Allocated"),
                            ("issued", "Issued to Ward"),
                            ("transfused", "Transfused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("special_requirements", models.JSONField(default=list)),
                ("requested_for_date", models.DateTimeField(blank=True, null=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfusion_requests",
                        to="lab_orders.laborderitem",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_lab_transfusion_requests",
                "indexes": [
                    models.Index(
                        fields=["patient_id", "status"], name="cymed_lab_t_patient_940169_idx"
                    )
                ],
            },
        ),
    ]
