# Generated by Django 6.0.6 on 2026-06-28 10:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_hospital_clinical_command_center', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commandcenteralert',
            new_name='cymed_hospi_tenant__9c6816_idx',
            old_name='ccc_alert_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='commandcenteralert',
            new_name='cymed_hospi_tenant__ffac80_idx',
            old_name='ccc_alert_tenant_time_idx',
        ),
        migrations.RenameIndex(
            model_name='commandcentersnapshot',
            new_name='cymed_hospi_tenant__4fc543_idx',
            old_name='ccc_snapshot_tenant_time_idx',
        ),
        migrations.AlterField(
            model_name='bedturnoverlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='capacitythreshold',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commandcenteralert',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commandcenterkpi',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commandcentersnapshot',
            name='ed_lwbs',
            field=models.PositiveIntegerField(default=0, help_text='Left without being seen'),
        ),
        migrations.AlterField(
            model_name='commandcentersnapshot',
            name='hap_infections_mtd',
            field=models.PositiveIntegerField(default=0, help_text='Hospital-acquired infections month-to-date'),
        ),
        migrations.AlterField(
            model_name='commandcentersnapshot',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospitaldiversionstatus',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
