# Generated by Django 6.0.6 on 2026-06-23 04:51

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("img_orders", "0001_initial"),
        ("img_pacs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DICOMSeries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "series_instance_uid",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("series_number", models.PositiveIntegerField(blank=True, null=True)),
                ("series_description", models.CharField(blank=True, max_length=255)),
                ("modality", models.CharField(blank=True, max_length=20)),
                ("body_part", models.CharField(blank=True, max_length=100)),
                ("laterality", models.CharField(blank=True, max_length=20)),
                ("instance_count", models.PositiveIntegerField(default=0)),
                (
                    "slice_thickness",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
                ),
                ("pixel_spacing", models.CharField(blank=True, max_length=50)),
                ("acquisition_time", models.TimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "cymed_img_dicom_series",
            },
        ),
        migrations.CreateModel(
            name="DICOMInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("sop_instance_uid", models.CharField(db_index=True, max_length=255, unique=True)),
                ("sop_class_uid", models.CharField(blank=True, max_length=255)),
                ("instance_number", models.PositiveIntegerField(blank=True, null=True)),
                ("image_type", models.CharField(blank=True, max_length=100)),
                ("rows", models.PositiveIntegerField(blank=True, null=True)),
                ("columns", models.PositiveIntegerField(blank=True, null=True)),
                ("bits_allocated", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "window_center",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "window_width",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("wado_url", models.TextField(blank=True)),
                ("transfer_syntax_uid", models.CharField(blank=True, max_length=255)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="img_dicom.dicomseries",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_img_dicom_instances",
            },
        ),
        migrations.CreateModel(
            name="DICOMStudy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "study_instance_uid",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("accession_number", models.CharField(blank=True, db_index=True, max_length=100)),
                ("patient_id", models.UUIDField(db_index=True)),
                ("modality", models.CharField(max_length=20)),
                ("study_date", models.DateField(blank=True, null=True)),
                ("study_time", models.TimeField(blank=True, null=True)),
                ("study_description", models.CharField(blank=True, max_length=255)),
                ("referring_physician", models.CharField(blank=True, max_length=255)),
                ("series_count", models.PositiveIntegerField(default=0)),
                ("instance_count", models.PositiveIntegerField(default=0)),
                ("storage_size_mb", models.PositiveIntegerField(default=0)),
                (
                    "archive_status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("nearline", "Nearline"),
                            ("offline", "Offline"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order_item",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dicom_study",
                        to="img_orders.imagingorderitem",
                    ),
                ),
                (
                    "pacs_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="img_pacs.pacsnode",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_img_dicom_studies",
            },
        ),
        migrations.AddField(
            model_name="dicomseries",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="series",
                to="img_dicom.dicomstudy",
            ),
        ),
        migrations.CreateModel(
            name="StudyArchive",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "archive_tier",
                    models.CharField(
                        choices=[("hot", "Hot"), ("warm", "Warm"), ("cold", "Cold")],
                        default="hot",
                        max_length=20,
                    ),
                ),
                ("retention_years", models.PositiveSmallIntegerField(default=10)),
                ("compressed", models.BooleanField(default=False)),
                ("compression_type", models.CharField(blank=True, max_length=50)),
                (
                    "compression_ratio",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("archive_location", models.TextField(blank=True)),
                ("archive_bucket", models.CharField(blank=True, max_length=255)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("retrieval_sla_hours", models.PositiveIntegerField(default=1)),
                ("checksum", models.CharField(blank=True, max_length=128)),
                (
                    "study",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive",
                        to="img_dicom.dicomstudy",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_img_study_archives",
            },
        ),
    ]
