# Generated by Django 6.0.6 on 2026-07-14 22:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymart_commission', '0002_seed_global_default_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='The merchant fulfilling this order.')),
                ('store_id', models.UUIDField(db_index=True)),
                ('customer_id', models.UUIDField(db_index=True)),
                ('category_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('payment_authorized', 'Payment Authorized'), ('submitted', 'Submitted'), ('merchant_pending', 'Merchant Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('preparing', 'Preparing'), ('ready_for_pickup', 'Ready For Pickup'), ('delivery_requested', 'Delivery Requested'), ('driver_assigned', 'Driver Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancellation_requested', 'Cancellation Requested'), ('cancelled', 'Cancelled'), ('refund_pending', 'Refund Pending'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('failed', 'Failed')], db_index=True, default='draft', max_length=32)),
                ('fulfillment_type', models.CharField(choices=[('pickup', 'Pickup'), ('merchant_delivery', 'Merchant Delivery'), ('cydrive_delivery', 'CyDrive Delivery'), ('third_party_delivery', 'Third-Party Delivery')], default='pickup', max_length=32)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('merchant_funded_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cybercom_funded_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer_notes', models.TextField(blank=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_calculation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cymart_commission.commissioncalculation')),
            ],
            options={
                'db_table': 'cymart_marketplace_order',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField()),
                ('product_name_snapshot', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cymart_orders.marketplaceorder')),
            ],
            options={
                'db_table': 'cymart_marketplace_order_line',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='cymart_orders.marketplaceorder')),
            ],
            options={
                'db_table': 'cymart_order_status_history',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='marketplaceorder',
            index=models.Index(fields=['tenant_id', 'status'], name='cymart_mark_tenant__49753b_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceorder',
            index=models.Index(fields=['customer_id', 'status'], name='cymart_mark_custome_627092_idx'),
        ),
    ]
