# Generated by Django 6.0.6 on 2026-07-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymart_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorder',
            name='delivery_company_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='delivery_job_id',
            field=models.UUIDField(blank=True, help_text='Set once a CyDrive DeliveryJob is created for this order.', null=True),
        ),
    ]
