# Generated by Django 6.1 on 2026-08-12 10:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyed_hr', '0004_staffleave_balance_override_by_and_more'),
        ('cyed_sis', '0005_campustransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('subject', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('teacher_parent', 'Teacher ↔ parent'), ('teacher_student', 'Teacher ↔ student'), ('office_parent', 'Office ↔ parent'), ('staff_staff', 'Staff ↔ staff')], default='teacher_parent', max_length=30)),
                ('opened_by_email', models.CharField(blank=True, max_length=255)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_on', models.DateTimeField(blank=True, null=True)),
                ('closed_by_email', models.CharField(blank=True, max_length=255)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_message_threads',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('sender_kind', models.CharField(choices=[('staff', 'Staff'), ('guardian', 'Guardian'), ('student', 'Student')], max_length=20)),
                ('sender_email', models.CharField(max_length=255)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cyed_messaging.messagethread')),
            ],
            options={
                'db_table': 'cyed_messages',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('party_kind', models.CharField(choices=[('staff', 'Staff'), ('guardian', 'Guardian'), ('student', 'Student')], max_length=20)),
                ('email', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_threads', to='cyed_sis.guardian')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_threads', to='cyed_hr.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_memberships', to='cyed_sis.student')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='cyed_messaging.messagethread')),
            ],
            options={
                'db_table': 'cyed_thread_participants',
                'ordering': ['party_kind', 'display_name'],
            },
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['tenant_id', '-last_message_at'], name='idx_thread_recent'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['tenant_id', 'thread', 'sent_at'], name='idx_message_thread_time'),
        ),
        migrations.AddConstraint(
            model_name='threadparticipant',
            constraint=models.UniqueConstraint(fields=('thread', 'email'), name='uniq_participant_email_per_thread'),
        ),
    ]
