# Generated by Django 6.0.7 on 2026-10-04 17:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_tenant', '0006_tenant_row_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='EphemeralEnvironment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.SlugField(help_text="Branch or tenant slug, e.g. 'pr-482'.", max_length=41, unique=True)),
                ('app', models.CharField(choices=[('cymed', 'CyMed'), ('cycom', 'CyCom')], max_length=10)),
                ('git_ref', models.CharField(default='develop', max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('provisioning', 'Provisioning'), ('ready', 'Ready'), ('failed', 'Failed'), ('destroying', 'Destroying'), ('destroyed', 'Destroyed'), ('destroy_failed', 'Destroy Failed')], db_index=True, default='queued', max_length=20)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('terraform_instance_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('requested_by', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(blank=True, help_text='Set only when this environment is a dedicated copy for one real customer, not a CI preview.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ephemeral_environments', to='platform_tenant.tenant')),
            ],
            options={
                'db_table': 'platform_ephemeral_environments',
                'ordering': ['-created_at'],
            },
        ),
    ]
