# Generated by Django 6.0.7 on 2026-09-08 09:27
# A-3: mark group/header accounts (any account that is a `parent` of another)
# non-postable so journal lines can't be booked against roll-up nodes.

from django.db import migrations, models


def mark_headers_non_postable(apps, schema_editor):
    Account = apps.get_model("cycom_accounting", "Account")
    parent_ids = (
        Account.objects.filter(parent__isnull=False)
        .values_list("parent_id", flat=True)
        .distinct()
    )
    Account.objects.filter(id__in=list(parent_ids)).update(is_postable=False)


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_accounting', '0002_account_attributes_account_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_postable',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(mark_headers_non_postable, migrations.RunPython.noop),
    ]
