# Generated by Django 6.0.7 on 2026-09-10 07:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_accounting', '0003_account_is_postable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('doc_type', models.CharField(max_length=40)),
                ('prefix', models.CharField(blank=True, max_length=16)),
                ('pattern', models.CharField(default='{prefix}{yyyy}-{seq}', max_length=64)),
                ('padding', models.PositiveSmallIntegerField(default=5)),
                ('period_scope', models.CharField(choices=[('none', 'Continuous'), ('yearly', 'Reset yearly'), ('monthly', 'Reset monthly')], default='yearly', max_length=8)),
                ('period_key', models.CharField(blank=True, max_length=7)),
                ('next_value', models.PositiveBigIntegerField(default=1)),
            ],
            options={
                'db_table': 'cycom_accounting_document_sequences',
                'ordering': ['doc_type'],
                'unique_together': {('tenant_id', 'doc_type')},
            },
        ),
    ]
