# Generated by Django 6.0.7 on 2026-09-21 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_accounting', '0006_budget_account_cash_flow_type_fixedasset_budgetline_and_more'),
        ('cycom_company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='cycom_company.company'),
        ),
    ]
