# Generated by Django 5.1.15 on 2026-06-23 03:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsageMeter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('snapshot_date', models.DateField()),
                ('product_code', models.CharField(max_length=100)),
                ('edition_code', models.CharField(blank=True, max_length=100)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('active_providers', models.PositiveIntegerField(default=0)),
                ('active_facilities', models.PositiveIntegerField(default=0)),
                ('active_clinics', models.PositiveIntegerField(default=0)),
                ('active_hospitals', models.PositiveIntegerField(default=0)),
                ('licensed_beds', models.PositiveIntegerField(default=0)),
                ('occupied_beds', models.PositiveIntegerField(default=0)),
                ('api_calls', models.PositiveBigIntegerField(default=0)),
                ('storage_gb', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_transactions', models.PositiveBigIntegerField(default=0)),
                ('is_over_user_limit', models.BooleanField(default=False)),
                ('is_over_bed_limit', models.BooleanField(default=False)),
                ('is_over_api_limit', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cymed_commercial_usage_meters',
                'unique_together': {('tenant_id', 'snapshot_date', 'product_code')},
            },
        ),
        migrations.CreateModel(
            name='UsageAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('alert_type', models.CharField(choices=[('approaching_limit', 'Approaching Limit'), ('over_limit', 'Over Limit'), ('license_expiry', 'License Expiry'), ('api_quota', 'API Quota')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('resource', models.CharField(max_length=100)),
                ('current_value', models.PositiveIntegerField()),
                ('limit_value', models.PositiveIntegerField()),
                ('percentage_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_resolved', models.BooleanField(default=False)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='commercial_usage_metering.usagemeter')),
            ],
            options={
                'db_table': 'cymed_commercial_usage_alerts',
            },
        ),
    ]
