# Generated by Django 6.0.7 on 2026-08-06 16:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyed_sis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=150)),
                ('schedule_type', models.CharField(choices=[('upfront', 'Full Upfront'), ('monthly', 'Monthly'), ('termly', 'Termly (3)'), ('quarterly', 'Quarterly (4)'), ('custom', 'Custom')], default='termly', max_length=20)),
                ('installments_count', models.PositiveSmallIntegerField(default=3)),
                ('upfront_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('late_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cyed_fee_plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('installment_no', models.PositiveSmallIntegerField(default=1)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=20)),
                ('late_fee_applied', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cyed_installments',
                'ordering': ['installment_no'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('method', models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('bpay', 'BPAY'), ('direct_debit', 'Direct Debit'), ('cash', 'Cash')], default='card', max_length=20)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cyed_billing.installment')),
            ],
            options={
                'db_table': 'cyed_installment_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('currency', models.CharField(default='AUD', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('settled', 'Settled'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='cyed_sis.academicyear')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='cyed_billing.feeplan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_student_bills',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='installment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='cyed_billing.studentbill'),
        ),
        migrations.CreateModel(
            name='BillLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('category', models.CharField(choices=[('tuition', 'Tuition'), ('transport', 'Transport'), ('material', 'Materials'), ('other', 'Other')], default='tuition', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('source_ref', models.CharField(blank=True, max_length=64)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='cyed_billing.studentbill')),
            ],
            options={
                'db_table': 'cyed_bill_line_items',
                'ordering': ['category'],
            },
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.UniqueConstraint(fields=('bill', 'installment_no'), name='uniq_installment_no_per_bill'),
        ),
    ]
