# Generated by Django 6.1 on 2026-08-11 11:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_billing', '0002_studentbill_campus'),
        ('cyed_org', '0002_remove_campus_uniq_campus_code_per_group_and_more'),
        ('cyed_sis', '0004_classsection_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiblingDiscountRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=150)),
                ('ordinal', models.PositiveSmallIntegerField(help_text='Applies to this child and every later one, until a higher rule takes over.')),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('categories', models.JSONField(blank=True, default=list, help_text='Bill line-item categories the discount applies to. Empty = ["tuition"].')),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(blank=True, help_text='Restrict to one year. Null applies to every year.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sibling_discount_rules', to='cyed_sis.academicyear')),
                ('campus', models.ForeignKey(blank=True, help_text='Restrict to one campus. Null applies group-wide.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sibling_discount_rules', to='cyed_org.campus')),
            ],
            options={
                'db_table': 'cyed_sibling_discount_rules',
                'ordering': ['-ordinal'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'ordinal', 'academic_year', 'campus'), name='uniq_sibling_rule_scope'), models.CheckConstraint(condition=models.Q(('percent__gte', 0), ('percent__lte', 100)), name='sibling_discount_percent_range'), models.CheckConstraint(condition=models.Q(('ordinal__gte', 1)), name='sibling_discount_ordinal_positive')],
            },
        ),
    ]
