# Generated by Django 6.1 on 2026-08-12 10:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_billing', '0003_siblingdiscountrule'),
        ('cyed_sis', '0005_campustransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DunningCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('stage', models.PositiveSmallIntegerField(choices=[(0, 'Opened'), (1, 'Reminder sent'), (2, 'Formal notice'), (3, 'Meeting / payment plan offered'), (4, 'Referred')], default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paused', 'Paused'), ('resolved', 'Resolved'), ('written_off', 'Written off')], default='open', max_length=20)),
                ('opened_on', models.DateField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_action_on', models.DateField(blank=True, null=True)),
                ('paused_until', models.DateField(blank=True, null=True)),
                ('pause_reason', models.CharField(blank=True, max_length=255)),
                ('resolved_on', models.DateField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=255)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dunning_cases', to='cyed_sis.family')),
            ],
            options={
                'db_table': 'cyed_dunning_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DunningAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('stage', models.PositiveSmallIntegerField(choices=[(0, 'Opened'), (1, 'Reminder sent'), (2, 'Formal notice'), (3, 'Meeting / payment plan offered'), (4, 'Referred')])),
                ('action_on', models.DateField()),
                ('performed_by', models.CharField(blank=True, max_length=255)),
                ('balance_at_action', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('notification_id', models.CharField(blank=True, max_length=64)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='cyed_billing.dunningcase')),
            ],
            options={
                'db_table': 'cyed_dunning_actions',
                'ordering': ['action_on', 'stage'],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('number', models.CharField(blank=True, max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('withdrawal', 'Student withdrew'), ('remission', 'Fee remission / scholarship'), ('hardship', 'Financial hardship concession'), ('billing_error', 'Billing error'), ('goodwill', 'Goodwill'), ('other', 'Other')], default='other', max_length=30)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=255)),
                ('cancelled_on', models.DateField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=255)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('journal_reference', models.CharField(blank=True, max_length=64)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='cyed_billing.studentbill')),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='cyed_billing.installment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_credit_notes',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='credit_note_amount_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='dunningcase',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'paused'])), fields=('tenant_id', 'family'), name='uniq_open_dunning_case_per_family'),
        ),
    ]
