# Generated by Django 6.1 on 2026-08-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_billing', '0004_dunningcase_dunningaction_creditnote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentpayment',
            name='method',
            field=models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('bpay', 'BPAY'), ('direct_debit', 'Direct Debit'), ('cash', 'Cash'), ('credit_note', 'Credit note')], default='card', max_length=20),
        ),
    ]
