# Generated by Django 5.1.15 on 2026-06-22 20:33

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpecialtyProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "cymed_clinic_specialty_profiles",
            },
        ),
        migrations.CreateModel(
            name="SpecialtyClinicalRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("rule_name", models.CharField(max_length=255)),
                ("trigger_expression", models.CharField(max_length=500)),
                ("action_type", models.CharField(max_length=100)),
                ("action_message", models.TextField()),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_rules",
                        to="cymed_clinic_specialties.specialtyprofile",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_clinic_specialty_rules",
            },
        ),
        migrations.CreateModel(
            name="SpecialtyQuestionnaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("title", models.CharField(max_length=255)),
                ("questions_json", models.JSONField(default=list)),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaires",
                        to="cymed_clinic_specialties.specialtyprofile",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_clinic_specialty_questionnaires",
            },
        ),
        migrations.CreateModel(
            name="SpecialtyTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=100)),
                ("schema_definition", models.JSONField(default=dict)),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="cymed_clinic_specialties.specialtyprofile",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_clinic_specialty_templates",
                "unique_together": {("specialty", "code")},
            },
        ),
    ]
