# Generated by Django 6.0.7 on 2026-09-25 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name_en', models.CharField(max_length=150)),
                ('name_ar', models.CharField(blank=True, max_length=150)),
                ('servings', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymart_recipe',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField(db_index=True)),
                ('product_id', models.UUIDField()),
                ('product_name_snapshot', models.CharField(blank=True, max_length=300)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('last_purchased_at', models.DateField(blank=True, null=True)),
                ('last_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('typical_interval_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('predicted_runout_date', models.DateField(blank=True, null=True)),
                ('is_tracked', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cymart_pantry_item',
                'ordering': ['predicted_runout_date'],
                'constraints': [models.UniqueConstraint(fields=('customer_id', 'product_id'), name='unique_pantry_item_per_customer')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField(db_index=True)),
                ('product_id', models.UUIDField(db_index=True)),
                ('product_name_snapshot', models.CharField(blank=True, max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('purchased_at', models.DateField()),
                ('source', models.CharField(choices=[('order', 'Order checkout'), ('manual', 'Manually logged')], default='order', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cymart_purchase_history',
                'ordering': ['-purchased_at'],
                'indexes': [models.Index(fields=['customer_id', 'product_id', 'purchased_at'], name='cymart_purc_custome_63aa84_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cymart_pantry.recipe')),
            ],
            options={
                'db_table': 'cymart_recipe_ingredient',
            },
        ),
    ]
