# Generated by Django 6.0.7 on 2026-07-17 00:30

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryQueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('question', models.TextField()),
                ('matched_plan_code', models.CharField(blank=True, max_length=100)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('answer_text', models.TextField(blank=True)),
                ('used_llm_fallback', models.BooleanField(default=False)),
                ('asked_by', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'cycom_cyai_memory_query_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('example_questions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cycom_cyai_query_plans',
                'ordering': ['name'],
            },
        ),
    ]
