# Generated by Django 6.1.1 on 2026-09-04 00:14

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoiceInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('mode', models.CharField(max_length=16)),
                ('invoice_ref', models.CharField(db_index=True, max_length=200)),
                ('invoice_uuid', models.UUIDField()),
                ('icv', models.PositiveBigIntegerField()),
                ('pih', models.TextField()),
                ('invoice_hash', models.TextField()),
                ('status', models.CharField(default='pending', max_length=16)),
                ('provider_reference', models.CharField(blank=True, max_length=200)),
                ('qr', models.TextField(blank=True)),
                ('request_xml_sha', models.CharField(blank=True, max_length=64)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'platform_einvoice_interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EInvoiceSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('scope', models.CharField(db_index=True, max_length=200)),
                ('mode', models.CharField(max_length=16)),
                ('next_icv', models.PositiveBigIntegerField(default=1)),
                ('last_hash', models.TextField(default='0000000000000000000000000000000000000000000000000000000000000000')),
            ],
            options={
                'db_table': 'platform_einvoice_sequences',
                'unique_together': {('tenant_id', 'scope', 'mode')},
            },
        ),
    ]
