# Generated by Django 6.0.7 on 2026-09-28 19:16

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_einvoicing', '0002_einvoiceinteraction_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='einvoiceinteraction',
            name='document',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='einvoiceinteraction',
            name='document_filename',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='EInvoiceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('legal_name', models.CharField(blank=True, max_length=300)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('building_number', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'platform_einvoice_profiles',
                'constraints': [models.UniqueConstraint(fields=('tenant_id',), name='uniq_einvoice_profile_tenant')],
            },
        ),
    ]
