# Generated by Django 6.0.7 on 2026-09-29 08:46

import django.utils.timezone
import platform.common.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_einvoicing', '0003_national_documents_and_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HmrcMtdConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('vrn', models.CharField(max_length=9)),
                ('access_token', platform.common.fields.EncryptedText(blank=True, classification='financial_id', default=b'', editable=True)),
                ('refresh_token', platform.common.fields.EncryptedText(blank=True, classification='financial_id', default=b'', editable=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'platform_hmrc_mtd_connections',
                'constraints': [models.UniqueConstraint(fields=('tenant_id',), name='uniq_hmrc_mtd_connection_tenant')],
            },
        ),
        migrations.CreateModel(
            name='MtdVatSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('vrn', models.CharField(max_length=9)),
                ('period_key', models.CharField(max_length=4)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('payload', models.JSONField()),
                ('receipt', models.JSONField(blank=True, default=dict)),
                ('submitted_by', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'platform_mtd_vat_submissions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'vrn', 'period_key'), name='uniq_mtd_submission_period')],
            },
        ),
    ]
