# Generated by Django 6.0.6 on 2026-06-23 04:51

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("img_orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modality",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(max_length=100)),
                (
                    "modality_type",
                    models.CharField(
                        choices=[
                            ("xray", "X-Ray"),
                            ("ct", "CT"),
                            ("mri", "MRI"),
                            ("us", "Ultrasound"),
                            ("mg", "Mammography"),
                            ("pet", "PET"),
                            ("nm", "Nuclear Medicine"),
                            ("fl", "Fluoroscopy"),
                            ("xa", "Angiography"),
                            ("dxa", "DEXA"),
                        ],
                        max_length=20,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("model_number", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("ae_title", models.CharField(blank=True, max_length=16)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("dicom_port", models.PositiveIntegerField(default=104)),
                ("worklist_port", models.PositiveIntegerField(default=1050)),
                ("is_active", models.BooleanField(default=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("last_maintenance", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "cymed_img_modalities",
                "unique_together": {("tenant_id", "code")},
            },
        ),
        migrations.CreateModel(
            name="ModalityWorklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("worklist_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_by", models.UUIDField()),
                ("total_entries", models.PositiveIntegerField(default=0)),
                (
                    "modality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worklists",
                        to="img_worklist.modality",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_img_modality_worklists",
            },
        ),
        migrations.CreateModel(
            name="StudyQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "queue_type",
                    models.CharField(
                        choices=[
                            ("reading", "Reading"),
                            ("qa", "QA"),
                            ("critical", "Critical"),
                            ("teleradiology", "Teleradiology"),
                        ],
                        default="reading",
                        max_length=30,
                    ),
                ),
                ("assigned_to", models.UUIDField(blank=True, null=True)),
                ("position", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "ai_priority_score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("ai_findings_summary", models.TextField(blank=True)),
                ("status", models.CharField(db_index=True, default="queued", max_length=20)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="img_orders.imagingorderitem",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_img_study_queue",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="WorklistEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("priority_rank", models.PositiveIntegerField(default=999)),
                ("scheduled_time", models.TimeField(blank=True, null=True)),
                ("patient_id", models.UUIDField()),
                ("accession_number", models.CharField(blank=True, max_length=100)),
                ("dicom_study_uid", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("technologist_id", models.UUIDField(blank=True, null=True)),
                ("images_acquired", models.PositiveIntegerField(default=0)),
                ("dose_report", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="img_orders.imagingorderitem",
                    ),
                ),
                (
                    "worklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="img_worklist.modalityworklist",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_img_worklist_entries",
                "ordering": ["priority_rank", "scheduled_time"],
            },
        ),
    ]
