# Generated by Django 6.0.7 on 2026-08-05 12:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyed_sis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('date', models.DateField()),
                ('period_label', models.CharField(blank=True, max_length=50)),
                ('taken_by', models.CharField(blank=True, max_length=255)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_calls', to='cyed_sis.classsection')),
            ],
            options={
                'db_table': 'cyed_roll_calls',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('left_early', 'Left Early')], default='present', max_length=20)),
                ('minutes_late', models.PositiveSmallIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_marks', to='cyed_sis.student')),
                ('roll_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='cyed_attendance.rollcall')),
            ],
            options={
                'db_table': 'cyed_attendance_marks',
                'ordering': ['student__last_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='rollcall',
            constraint=models.UniqueConstraint(fields=('class_section', 'date', 'period_label'), name='uniq_rollcall_section_date_period'),
        ),
        migrations.AddConstraint(
            model_name='attendancemark',
            constraint=models.UniqueConstraint(fields=('roll_call', 'student'), name='uniq_mark_per_student_rollcall'),
        ),
    ]
