# Generated by Django 6.1 on 2026-08-14 07:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_attendance', '0001_initial'),
        ('cyed_sis', '0006_student_exit_date_student_exit_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceExplanation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('kind', models.CharField(choices=[('absence', 'Absent'), ('late', 'Late arrival'), ('early_departure', 'Early departure')], default='absence', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(choices=[('illness', 'Illness'), ('medical', 'Medical or dental appointment'), ('family', 'Family reason'), ('bereavement', 'Bereavement'), ('religious', 'Religious observance'), ('travel', 'Travel'), ('other', 'Other')], default='illness', max_length=20)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('submitted_by_email', models.CharField(blank=True, max_length=255)),
                ('submitted_by_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='submitted', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_on', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('marks_updated', models.PositiveSmallIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_explanations', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_absence_explanations',
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status', 'start_date'], name='idx_absence_expl_queue')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='absence_explanation_dates_ordered')],
            },
        ),
    ]
