# Generated by Django 6.1 on 2026-09-20 11:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_attendance', '0004_absenceexplanation_attributes_and_more'),
        ('cyed_sis', '0007_academicyear_attributes_academicyear_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatePass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('arrival_date', models.DateField(default=django.utils.timezone.localdate)),
                ('arrival_time', models.TimeField(default=django.utils.timezone.localtime)),
                ('reason', models.CharField(choices=[('transport', 'Transport / traffic'), ('medical', 'Medical appointment'), ('family', 'Family reason'), ('overslept', 'Overslept'), ('other', 'Other')], default='other', max_length=20)),
                ('reason_detail', models.CharField(blank=True, max_length=255)),
                ('issued_by', models.CharField(blank=True, max_length=255)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_passes', to='cyed_sis.classsection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_passes', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_late_passes',
                'ordering': ['-arrival_date', '-arrival_time'],
                'indexes': [models.Index(fields=['tenant_id', 'arrival_date'], name='idx_late_pass_by_date')],
            },
        ),
    ]
