# Generated by Django 6.0.7 on 2026-08-06 17:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyed_sis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('meeting_type', models.CharField(choices=[('parent_teacher', 'Parent–Teacher'), ('counselling', 'Counselling'), ('staff', 'Staff Meeting'), ('other', 'Other')], default='parent_teacher', max_length=20)),
                ('participants', models.CharField(blank=True, max_length=500)),
                ('transcript', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('action_items', models.JSONField(default=list)),
                ('key_points', models.JSONField(default=list)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('is_confidential', models.BooleanField(default=False)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_meeting_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
