# Generated by Django 6.1 on 2026-08-14 08:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_hr', '0004_staffleave_balance_override_by_and_more'),
        ('cyed_meetings', '0001_initial'),
        ('cyed_org', '0002_remove_campus_uniq_campus_code_per_group_and_more'),
        ('cyed_sis', '0006_student_exit_date_student_exit_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('bookings_open_at', models.DateTimeField()),
                ('bookings_close_at', models.DateTimeField()),
                ('max_bookings_per_student', models.PositiveSmallIntegerField(default=8)),
                ('instructions', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_rounds', to='cyed_sis.academicyear')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_rounds', to='cyed_org.campus')),
            ],
            options={
                'db_table': 'cyed_interview_rounds',
                'ordering': ['-bookings_open_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('starts_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=10)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('is_available', models.BooleanField(default=True)),
                ('blocked_reason', models.CharField(blank=True, max_length=255)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='cyed_meetings.interviewround')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_slots', to='cyed_hr.staff')),
            ],
            options={
                'db_table': 'cyed_interview_slots',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('booked_by_email', models.CharField(blank=True, max_length=255)),
                ('booked_by_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'Did not attend')], default='booked', max_length=20)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_bookings', to='cyed_sis.student')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cyed_meetings.interviewslot')),
            ],
            options={
                'db_table': 'cyed_interview_bookings',
                'ordering': ['slot__starts_at'],
            },
        ),
        migrations.AddIndex(
            model_name='interviewslot',
            index=models.Index(fields=['tenant_id', 'round', 'starts_at'], name='idx_slot_round_time'),
        ),
        migrations.AddConstraint(
            model_name='interviewslot',
            constraint=models.UniqueConstraint(fields=('teacher', 'starts_at'), name='uniq_slot_per_teacher_time'),
        ),
        migrations.AddConstraint(
            model_name='interviewbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'booked')), fields=('slot',), name='uniq_live_booking_per_slot'),
        ),
    ]
