# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPortalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('theme_preference', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=20)),
                ('nfc_card_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('nfc_card_activated', models.BooleanField(default=False)),
                ('emergency_access_enabled', models.BooleanField(default=True)),
                ('data_sharing_consent', models.BooleanField(default=False)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_profile', to='cymed_patients.patient')),
            ],
            options={
                'db_table': 'cymed_patient_portal_profiles',
            },
        ),
        migrations.CreateModel(
            name='PatientPortalActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('appointment_booked', 'Appointment Booked'), ('appointment_cancelled', 'Appointment Cancelled'), ('prescription_viewed', 'Prescription Viewed'), ('lab_result_viewed', 'Lab Result Viewed'), ('imaging_viewed', 'Imaging Viewed'), ('profile_updated', 'Profile Updated'), ('consent_changed', 'Consent Changed'), ('emergency_access', 'Emergency Access Used'), ('nfc_scan', 'NFC Card Scanned'), ('delegated_grant', 'Delegation Granted'), ('delegated_revoke', 'Delegation Revoked')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cymed_patient_portal.patientportalprofile')),
            ],
            options={
                'db_table': 'cymed_patient_portal_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NFCCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('card_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('public_key_pem', models.TextField(help_text="ECDSA P-256 public key from the card's secure element")),
                ('chip_vendor', models.CharField(choices=[('desfire_ev3', 'NXP MIFARE DESFire EV3'), ('ntag424', 'NXP NTAG424 DNA')], default='desfire_ev3', max_length=50)),
                ('activation_code_hash', models.CharField(blank=True, max_length=128)),
                ('issued_by_user_id', models.UUIDField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_cards', to='cymed_patient_portal.patientportalprofile')),
            ],
            options={
                'db_table': 'cymed_nfc_cards',
            },
        ),
        migrations.CreateModel(
            name='EmergencyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('blood_type', models.CharField(blank=True, max_length=5)),
                ('allergies', models.JSONField(blank=True, default=list, help_text='[{substance, severity, reaction}]')),
                ('current_medications', models.JSONField(blank=True, default=list, help_text='[{drug, dose, frequency}]')),
                ('chronic_conditions', models.JSONField(blank=True, default=list, help_text='[{icd11, label}]')),
                ('emergency_contacts', models.JSONField(blank=True, default=list, help_text='[{name, relation, phone}]')),
                ('dnr_status', models.CharField(choices=[('none', 'None'), ('dnr', 'DNR (Do Not Resuscitate)'), ('dnr_cc', 'DNR / Comfort Care'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('organ_donor', models.BooleanField(default=False)),
                ('religious_preferences', models.CharField(blank=True, max_length=200)),
                ('preferred_language', models.CharField(default='ar', max_length=10)),
                ('updated_from_ehr_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_profile', to='cymed_patient_portal.patientportalprofile')),
            ],
            options={
                'db_table': 'cymed_emergency_profiles',
            },
        ),
        migrations.CreateModel(
            name='PatientPortalNotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('appointment_reminders', models.BooleanField(default=True)),
                ('lab_results_ready', models.BooleanField(default=True)),
                ('prescription_ready', models.BooleanField(default=True)),
                ('billing_updates', models.BooleanField(default=True)),
                ('health_tips', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='cymed_patient_portal.patientportalprofile')),
            ],
            options={
                'db_table': 'cymed_patient_portal_notification_preferences',
                'unique_together': {('profile', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='PatientDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10)),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('push_token', models.CharField(blank=True, max_length=500)),
                ('webauthn_credential_id', models.CharField(blank=True, db_index=True, max_length=500)),
                ('webauthn_public_key', models.TextField(blank=True)),
                ('webauthn_sign_count', models.BigIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(db_index=True, default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='cymed_patient_portal.patientportalprofile')),
            ],
            options={
                'db_table': 'cymed_patient_devices',
                'indexes': [models.Index(fields=['profile', 'revoked'], name='cymed_patie_profile_2ea20f_idx')],
                'unique_together': {('profile', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='NFCScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('purpose', models.CharField(choices=[('reception', 'Reception'), ('pharmacy', 'Pharmacy'), ('lab', 'Laboratory'), ('imaging', 'Imaging'), ('emergency', 'Emergency'), ('other', 'Other')], max_length=20)),
                ('provider_tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('provider_name', models.CharField(blank=True, max_length=200)),
                ('terminal_id', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('scope_granted', models.JSONField(blank=True, default=dict)),
                ('patient_notified_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='cymed_patient_portal.nfccard')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='cymed_patient_portal.patientportalprofile')),
            ],
            options={
                'db_table': 'cymed_nfc_scan_logs',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['profile', '-scanned_at'], name='cymed_nfc_s_profile_4ede0c_idx'), models.Index(fields=['card', '-scanned_at'], name='cymed_nfc_s_card_id_bed6d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='DelegatedAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('guardian', 'Guardian'), ('friend', 'Friend'), ('other', 'Other')], max_length=20)),
                ('scope_read_records', models.BooleanField(default=False)),
                ('scope_book_appt', models.BooleanField(default=False)),
                ('scope_pay_bills', models.BooleanField(default=True)),
                ('scope_max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('scope_expiry', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('consent_signed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('delegate_profile', models.ForeignKey(help_text='Patient who gets access', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to='cymed_patient_portal.patientportalprofile')),
                ('subject_profile', models.ForeignKey(help_text='Patient whose data is being shared', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_granted', to='cymed_patient_portal.patientportalprofile')),
            ],
            options={
                'db_table': 'cymed_delegated_access',
                'unique_together': {('subject_profile', 'delegate_profile')},
            },
        ),
        migrations.CreateModel(
            name='ConsentGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('provider_tenant_id', models.UUIDField(db_index=True)),
                ('scope', models.JSONField(default=dict, help_text='e.g. {"resources": ["Observation", "MedicationRequest"], "categories": ["laboratory"]}')),
                ('purpose', models.CharField(choices=[('treatment', 'Treatment'), ('payment', 'Payment'), ('operations', 'Operations'), ('research', 'Research')], default='treatment', max_length=20)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='cymed_patient_portal.patientportalprofile')),
            ],
            options={
                'db_table': 'cymed_consent_grants',
                'indexes': [models.Index(fields=['profile', 'provider_tenant_id'], name='cymed_conse_profile_574fc5_idx'), models.Index(fields=['provider_tenant_id', 'purpose'], name='cymed_conse_provide_87bc95_idx')],
            },
        ),
    ]
