# Generated by Django 6.0.7 on 2026-10-02 19:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_patient_portal', '0002_consentgrant_attributes_consentgrant_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTerminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('terminal_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('key_hash', models.CharField(editable=False, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cymed_patient_portal_scan_terminals',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'terminal_id'), name='uniq_scan_terminal_per_tenant')],
            },
        ),
    ]
