# Generated by Django 6.0.6 on 2026-06-25 11:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_patients', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('resource_id', models.UUIDField()),
                ('resource_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cymed_resource_schedules',
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('resource_id', models.UUIDField(db_index=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('free', 'Free'), ('busy', 'Busy'), ('tentative', 'Tentative')], default='free', max_length=30)),
            ],
            options={
                'db_table': 'cymed_schedule_slots',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('appointment_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('pending', 'Pending'), ('booked', 'Booked'), ('arrived', 'Arrived'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='booked', max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='cymed_patients.patient')),
            ],
            options={
                'db_table': 'cymed_appointments',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('actor_id', models.UUIDField()),
                ('actor_type', models.CharField(choices=[('patient', 'Patient'), ('provider', 'Provider'), ('location', 'Location')], max_length=30)),
                ('required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('tentative', 'Tentative'), ('needs_action', 'Needs Action')], default='needs_action', max_length=30)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='cymed_scheduling.appointment')),
            ],
            options={
                'db_table': 'cymed_appointment_participants',
            },
        ),
    ]
