# Generated by Django 6.0.6 on 2026-06-23 04:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_specimens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('site_code', models.CharField(blank=True, max_length=20)),
                ('created_by', models.UUIDField()),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('accession_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_open', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_lab_accession_batches',
            },
        ),
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('accession_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('site_code', models.CharField(blank=True, max_length=20)),
                ('accessioned_at', models.DateTimeField(auto_now_add=True)),
                ('accessioned_by', models.UUIDField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('referred', 'Referred to Reference Lab'), ('completed', 'Completed')], default='active', max_length=20)),
                ('priority_override', models.CharField(blank=True, max_length=20)),
                ('routing_destination', models.CharField(blank=True, max_length=255)),
                ('is_referred', models.BooleanField(default=False)),
                ('specimen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accession', to='lab_specimens.specimen')),
            ],
            options={
                'db_table': 'cymed_lab_accessions',
            },
        ),
        migrations.CreateModel(
            name='AccessionAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('event_type', models.CharField(max_length=100)),
                ('performed_by', models.UUIDField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('event_at', models.DateTimeField(auto_now_add=True)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='lab_accessioning.accession')),
            ],
            options={
                'db_table': 'cymed_lab_accession_audit',
                'ordering': ['-event_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessionNumberSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('site_code', models.CharField(max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('last_sequence', models.PositiveBigIntegerField(default=0)),
                ('prefix', models.CharField(default='ACC', max_length=10)),
            ],
            options={
                'db_table': 'cymed_lab_accession_sequences',
                'unique_together': {('tenant_id', 'site_code', 'year')},
            },
        ),
        migrations.CreateModel(
            name='AccessionBatchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='lab_accessioning.accession')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lab_accessioning.accessionbatch')),
            ],
            options={
                'db_table': 'cymed_lab_accession_batch_items',
                'unique_together': {('batch', 'accession')},
            },
        ),
    ]
