# Generated by Django 6.0.6 on 2026-06-28 19:04

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompetitiveBenchmark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("product_code", models.CharField(db_index=True, max_length=50)),
                ("competitor_name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("features", "Features"),
                            ("pricing", "Pricing"),
                            ("performance", "Performance"),
                            ("security", "Security"),
                            ("compliance", "Compliance"),
                            ("support", "Support"),
                            ("scalability", "Scalability"),
                        ],
                        max_length=20,
                    ),
                ),
                ("our_score", models.DecimalField(decimal_places=1, max_digits=4)),
                ("competitor_score", models.DecimalField(decimal_places=1, max_digits=4)),
                ("benchmark_notes", models.TextField(blank=True)),
                ("last_updated", models.DateField()),
            ],
            options={
                "db_table": "cybercom_cr_competitive_benchmark",
            },
        ),
        migrations.CreateModel(
            name="ComplianceCertification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("product_code", models.CharField(db_index=True, max_length=50)),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("hipaa", "HIPAA"),
                            ("gdpr", "GDPR"),
                            ("pdpl", "PDPL"),
                            ("iso27001", "ISO 27001"),
                            ("soc2", "SOC 2"),
                            ("jcia", "JCIA"),
                            ("cbahi", "CBAHI"),
                            ("fhir_r4", "FHIR R4"),
                            ("hl7_v2", "HL7 v2"),
                            ("dicom", "DICOM"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("certified", "Certified"),
                            ("in_progress", "In Progress"),
                            ("planned", "Planned"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("certified_at", models.DateField(blank=True, null=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("certificate_url", models.URLField(blank=True)),
                ("auditor_name", models.CharField(blank=True, max_length=200)),
                ("scope_description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "cybercom_cr_compliance_cert",
            },
        ),
        migrations.CreateModel(
            name="CustomerPortalAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("user_id", models.UUIDField(db_index=True)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("viewer", "Viewer"),
                            ("standard", "Standard"),
                            ("admin", "Admin"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("can_manage_licenses", models.BooleanField(default=False)),
                ("can_manage_billing", models.BooleanField(default=False)),
                ("can_open_tickets", models.BooleanField(default=True)),
                ("can_download_software", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "cybercom_cr_portal_access",
            },
        ),
        migrations.CreateModel(
            name="LicenseKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("customer_id", models.UUIDField(db_index=True)),
                ("product_code", models.CharField(db_index=True, max_length=50)),
                ("edition", models.CharField(blank=True, max_length=50)),
                ("key_value", models.CharField(max_length=200, unique=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("max_users", models.PositiveIntegerField(blank=True, null=True)),
                ("max_beds", models.PositiveIntegerField(blank=True, null=True)),
                ("licensed_modules", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "cybercom_cr_license_key",
            },
        ),
        migrations.CreateModel(
            name="MarketplaceListing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("module", "Module"),
                            ("extension", "Extension"),
                            ("theme", "Theme"),
                            ("connector", "Connector"),
                            ("ai_package", "AI Package"),
                            ("clinical_template", "Clinical Template"),
                            ("report", "Report"),
                            ("dashboard", "Dashboard"),
                        ],
                        max_length=30,
                    ),
                ),
                ("product_codes", models.JSONField(default=list)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                (
                    "publisher_type",
                    models.CharField(
                        choices=[
                            ("official", "Official"),
                            ("partner", "Partner"),
                            ("community", "Community"),
                        ],
                        default="official",
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField(blank=True)),
                ("icon_url", models.URLField(blank=True)),
                ("screenshots_urls", models.JSONField(default=list)),
                ("documentation_url", models.URLField(blank=True)),
                (
                    "price_model",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("one_time", "One Time"),
                            ("subscription", "Subscription"),
                            ("usage", "Usage Based"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("price_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("install_count", models.PositiveIntegerField(default=0)),
                ("rating_avg", models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("tags", models.JSONField(default=list)),
                ("is_featured", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "cybercom_cr_marketplace_listing",
                "ordering": ["-is_featured", "-install_count"],
            },
        ),
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("product_code", models.CharField(db_index=True, max_length=50)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("per_user", "Per User"),
                            ("per_bed", "Per Bed"),
                            ("per_transaction", "Per Transaction"),
                            ("flat_fee", "Flat Fee"),
                            ("usage_based", "Usage Based"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                            ("biennial", "Biennial"),
                            ("one_time", "One Time"),
                        ],
                        max_length=20,
                    ),
                ),
                ("min_units", models.PositiveIntegerField(default=1)),
                ("max_units", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("country_codes", models.JSONField(default=list)),
            ],
            options={
                "db_table": "cybercom_cr_pricing_plan",
            },
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("opportunity_id", models.CharField(db_index=True, max_length=100)),
                ("customer_name", models.CharField(max_length=200)),
                ("proposal_title", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Review"),
                            ("submitted", "Submitted"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("rfp_reference", models.CharField(blank=True, max_length=200)),
                ("executive_summary", models.TextField(blank=True)),
                ("solution_scope", models.JSONField(default=list)),
                ("proposed_modules", models.JSONField(default=list)),
                ("total_value", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("submission_date", models.DateField(blank=True, null=True)),
                ("decision_date", models.DateField(blank=True, null=True)),
                ("win_reason", models.TextField(blank=True)),
                ("loss_reason", models.TextField(blank=True)),
            ],
            options={
                "db_table": "cybercom_cr_proposal",
            },
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("quote_number", models.CharField(max_length=100, unique=True)),
                ("customer_name", models.CharField(max_length=200)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_organization", models.CharField(blank=True, max_length=200)),
                ("sales_rep_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("line_items", models.JSONField(default=list)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("discount_pct", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "cybercom_cr_quotation",
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("ticket_number", models.CharField(max_length=100, unique=True)),
                ("submitted_by_id", models.UUIDField(db_index=True)),
                ("subject", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("product_code", models.CharField(db_index=True, max_length=50)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("waiting_customer", "Waiting Customer"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=30,
                    ),
                ),
                ("assigned_to_id", models.UUIDField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("sla_due_at", models.DateTimeField(blank=True, null=True)),
                ("attachments", models.JSONField(default=list)),
            ],
            options={
                "db_table": "cybercom_cr_support_ticket",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WhiteLabelConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("tenant_name", models.CharField(max_length=200)),
                ("display_name", models.CharField(max_length=200)),
                ("primary_color", models.CharField(blank=True, max_length=20)),
                ("secondary_color", models.CharField(blank=True, max_length=20)),
                ("accent_color", models.CharField(blank=True, max_length=20)),
                ("logo_url", models.URLField(blank=True)),
                ("favicon_url", models.URLField(blank=True)),
                ("custom_domain", models.CharField(blank=True, max_length=200)),
                ("login_page_bg_url", models.URLField(blank=True)),
                ("email_from_name", models.CharField(blank=True, max_length=200)),
                ("email_from_address", models.EmailField(blank=True, max_length=254)),
                ("email_header_logo_url", models.URLField(blank=True)),
                ("report_logo_url", models.URLField(blank=True)),
                ("pdf_footer_text", models.CharField(blank=True, max_length=300)),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("support_phone", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "cybercom_cr_white_label_config",
            },
        ),
        migrations.CreateModel(
            name="CommercialMetricsSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("snapshot_date", models.DateField(db_index=True)),
                ("metric_type", models.CharField(max_length=50)),
                ("product_code", models.CharField(blank=True, max_length=50)),
                ("value", models.DecimalField(decimal_places=4, max_digits=16)),
                ("breakdown", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "cybercom_cr_metrics_snapshot",
                "ordering": ["-snapshot_date"],
                "unique_together": {("snapshot_date", "metric_type", "product_code")},
            },
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("product_code", models.CharField(db_index=True, max_length=50)),
                ("edition_code", models.CharField(blank=True, max_length=20)),
                ("flag_key", models.CharField(max_length=100)),
                ("flag_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("enabled_for_editions", models.JSONField(default=list)),
                ("overridable_per_tenant", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "cybercom_cr_feature_flag",
                "unique_together": {("product_code", "flag_key")},
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("perpetual", "Perpetual"),
                            ("subscription", "Subscription"),
                            ("trial", "Trial"),
                            ("evaluation", "Evaluation"),
                            ("oem", "OEM"),
                            ("floating", "Floating"),
                        ],
                        default="subscription",
                        max_length=20,
                    ),
                ),
                (
                    "license_scope",
                    models.CharField(
                        choices=[
                            ("tenant", "Per Tenant"),
                            ("facility", "Per Facility"),
                            ("user", "Per User"),
                            ("product", "Per Product"),
                            ("enterprise", "Enterprise"),
                            ("concurrent", "Concurrent Users"),
                        ],
                        default="tenant",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                            ("trial", "Trial"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("product_code", models.CharField(db_index=True, max_length=50)),
                ("edition", models.CharField(blank=True, max_length=50)),
                ("license_key", models.CharField(max_length=200, unique=True)),
                ("issued_to", models.CharField(max_length=200)),
                ("issued_to_email", models.EmailField(max_length=254)),
                ("max_users", models.PositiveIntegerField(blank=True, null=True)),
                ("max_concurrent", models.PositiveIntegerField(blank=True, null=True)),
                ("max_facilities", models.PositiveIntegerField(blank=True, null=True)),
                ("licensed_features", models.JSONField(default=list)),
                ("licensed_modules", models.JSONField(default=list)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("grace_period_days", models.PositiveIntegerField(default=30)),
                ("offline_token", models.CharField(blank=True, max_length=500)),
                ("offline_valid_days", models.PositiveIntegerField(default=7)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("auto_renew", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "parent_license",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_licenses",
                        to="cybercom_cr.license",
                    ),
                ),
            ],
            options={
                "db_table": "cybercom_cr_license",
            },
        ),
        migrations.CreateModel(
            name="ConcurrentLicenseSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("user_id", models.UUIDField(db_index=True)),
                ("device_fingerprint", models.CharField(blank=True, max_length=200)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_heartbeat_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concurrent_sessions",
                        to="cybercom_cr.license",
                    ),
                ),
            ],
            options={
                "db_table": "cybercom_cr_concurrent_session",
            },
        ),
        migrations.CreateModel(
            name="ProductEdition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("product_code", models.CharField(db_index=True, max_length=50)),
                (
                    "edition_code",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                            ("network", "Network"),
                            ("government", "Government"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("included_modules", models.JSONField(default=list)),
                ("max_users_default", models.PositiveIntegerField(blank=True, null=True)),
                ("min_users", models.PositiveIntegerField(default=1)),
                ("support_level", models.CharField(blank=True, max_length=50)),
                ("deployment_options", models.JSONField(default=list)),
                ("highlighted_features", models.JSONField(default=list)),
            ],
            options={
                "db_table": "cybercom_cr_product_edition",
                "ordering": ["product_code", "sort_order"],
                "unique_together": {("product_code", "edition_code")},
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("paused", "Paused"),
                        ],
                        default="trialing",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                            ("biennial", "Biennial"),
                            ("one_time", "One Time"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("current_period_start", models.DateField()),
                ("current_period_end", models.DateField()),
                ("trial_end", models.DateField(blank=True, null=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("external_subscription_id", models.CharField(blank=True, max_length=200)),
                ("payment_method_last4", models.CharField(blank=True, max_length=10)),
                ("billing_email", models.EmailField(blank=True, max_length=254)),
                ("invoice_count", models.PositiveIntegerField(default=0)),
                ("last_invoice_at", models.DateTimeField(blank=True, null=True)),
                (
                    "license",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="cybercom_cr.license",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cybercom_cr.pricingplan",
                    ),
                ),
            ],
            options={
                "db_table": "cybercom_cr_subscription",
            },
        ),
        migrations.CreateModel(
            name="TenantFeatureFlagOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("is_enabled", models.BooleanField()),
                ("override_reason", models.CharField(blank=True, max_length=200)),
                ("overridden_by_id", models.UUIDField(blank=True, null=True)),
                ("overridden_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_overrides",
                        to="cybercom_cr.featureflag",
                    ),
                ),
            ],
            options={
                "db_table": "cybercom_cr_tenant_flag_override",
            },
        ),
        migrations.CreateModel(
            name="MarketplaceInstallation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("installed_by_id", models.UUIDField()),
                ("installed_version", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                ("config", models.JSONField(default=dict)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="cybercom_cr.marketplacelisting",
                    ),
                ),
            ],
            options={
                "db_table": "cybercom_cr_marketplace_installation",
                "unique_together": {("tenant_id", "listing")},
            },
        ),
    ]
