# Generated by Django 6.0.7 on 2026-07-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='discount_approval_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='posorder',
            name='discount_approved_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='posorder',
            name='discount_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='posorderline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
