# Generated by Django 6.0.7 on 2026-07-17 02:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_accounting', '0001_initial'),
        ('cycom_pos', '0002_posorder_discount_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='advance_liability_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_orders_advance_liability', to='cycom_accounting.account'),
        ),
        migrations.AddField(
            model_name='posorder',
            name='order_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('layaway', 'Layaway / Advance')], default='sale', max_length=20),
        ),
        migrations.CreateModel(
            name='POSOrderPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Bank Transfer')], default='cash', max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cycom_accounting.journalentry')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cycom_pos.posorder')),
            ],
            options={
                'db_table': 'cycom_pos_order_payments',
                'ordering': ['paid_at'],
            },
        ),
    ]
