# Generated by Django 6.0.7 on 2026-08-24 14:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_inventory', '0002_internalorder_internalorderline'),
        ('cycom_pos', '0003_posorder_advance_liability_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('device_type', models.CharField(choices=[('POS', 'POS Terminal'), ('KDS', 'Kitchen Display'), ('WAITER', 'Waiter Handheld'), ('CUSTOMER_DISPLAY', 'Customer-Facing Display'), ('WAREHOUSE_SCANNER', 'Warehouse Scanner'), ('SELF_ORDER', 'Self-Order Kiosk')], max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='cycom_inventory.warehouse')),
            ],
            options={
                'db_table': 'cycom_pos_devices',
                'ordering': ['warehouse', 'device_type', 'name'],
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PosReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('receipt_number', models.CharField(db_index=True, max_length=50)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('qr_data', models.TextField(blank=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='cycom_pos.posorder')),
            ],
            options={
                'db_table': 'cycom_pos_receipts',
                'ordering': ['-created_at'],
                'unique_together': {('tenant_id', 'receipt_number')},
            },
        ),
    ]
