# Generated by Django 6.0.7 on 2026-08-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_pos', '0004_device_posreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='posorder',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='posorder',
            name='kitchen_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('served', 'Served')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='posorder',
            name='source',
            field=models.CharField(choices=[('POS', 'POS Terminal'), ('KIOSK', 'Self-Service Kiosk'), ('ONLINE', 'Online Order')], default='POS', max_length=20),
        ),
        migrations.AddField(
            model_name='posorder',
            name='table_ref',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
