# Generated by Django 6.0.7 on 2026-09-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_pos', '0007_posorderline_product_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderline',
            name='serial_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
