# Generated by Django 6.0.7 on 2026-09-13 11:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_accounting', '0004_documentsequence'),
        ('cycom_pos', '0008_posorderline_serial_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderline',
            name='lot_number_at_sale',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='posorderline',
            name='unit_cost_at_sale',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='PosReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('requested_by', models.CharField(blank=True, max_length=255)),
                ('approved_by_user_id', models.CharField(blank=True, max_length=255)),
                ('approval_method', models.CharField(blank=True, choices=[('self', 'Self (own role)'), ('pin', 'Manager PIN'), ('barcode', 'Manager Barcode')], max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('amount_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cycom_accounting.journalentry')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='cycom_pos.posorder')),
            ],
            options={
                'db_table': 'cycom_pos_returns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PosReturnLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('restock', models.BooleanField(default=True)),
                ('serial_numbers', models.JSONField(blank=True, default=list)),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='cycom_pos.posorderline')),
                ('ret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cycom_pos.posreturn')),
            ],
            options={
                'db_table': 'cycom_pos_return_lines',
                'ordering': ['id'],
            },
        ),
    ]
