# Generated by Django 6.0.7 on 2026-09-14 10:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_pos', '0009_posorderline_lot_number_at_sale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('prescriber_name', models.CharField(blank=True, max_length=255)),
                ('prescriber_license', models.CharField(blank=True, max_length=100)),
                ('rx_number', models.CharField(blank=True, max_length=100)),
                ('date_issued', models.DateField()),
                ('refills_allowed', models.PositiveSmallIntegerField(default=0)),
                ('refills_used', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'cycom_pos_prescriptions',
                'ordering': ['-date_issued'],
            },
        ),
        migrations.AddField(
            model_name='posorder',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='posorder',
            name='vehicle_vin',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='posorderline',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='cycom_pos.prescription'),
        ),
    ]
