# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('from_tenant_id', models.UUIDField(db_index=True)),
                ('from_practitioner_id', models.UUIDField(blank=True, null=True)),
                ('to_tenant_id', models.UUIDField(db_index=True)),
                ('to_practitioner_id', models.UUIDField(blank=True, null=True)),
                ('target_kind', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('lab', 'Lab'), ('imaging', 'Imaging'), ('pharmacy', 'Pharmacy')], max_length=20)),
                ('patient_profile_id', models.UUIDField(db_index=True)),
                ('encounter_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.CharField(max_length=400)),
                ('clinical_summary', models.TextField(blank=True)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('scheduled', 'Appointment scheduled'), ('completed', 'Care completed'), ('result_shared', 'Result shared back'), ('declined', 'Declined'), ('expired', 'Expired')], db_index=True, default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_shared_at', models.DateTimeField(blank=True, null=True)),
                ('result_documents', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cymed_clinic_referral_loop_referrals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient_profile_id', 'status'], name='cymed_clini_patient_c1813d_idx'), models.Index(fields=['from_tenant_id', 'status'], name='cymed_clini_from_te_ffb81d_idx'), models.Index(fields=['to_tenant_id', 'status'], name='cymed_clini_to_tena_259550_idx')],
            },
        ),
    ]
