# Generated by Django 6.0.6 on 2026-06-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_provider_workspace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='providerworkspace',
            name='cymed_prov_wkspc_tenant_prov_idx',
        ),
        migrations.RemoveIndex(
            model_name='providerworkspace',
            name='cymed_prov_wkspc_tenant_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='workspacesession',
            name='cymed_prov_sess_tenant_wkspc_idx',
        ),
        migrations.RemoveIndex(
            model_name='workspacesession',
            name='cymed_prov_sess_tenant_started_idx',
        ),
    ]
