# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialingApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('subject_kind', models.CharField(choices=[('facility', 'Facility'), ('practitioner', 'Practitioner')], max_length=32)),
                ('facility_id', models.UUIDField(blank=True, null=True)),
                ('practitioner_id', models.UUIDField(blank=True, null=True)),
                ('submitted_by_profile_id', models.UUIDField(blank=True, null=True)),
                ('target_networks', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('info_requested', 'Info Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('renewed', 'Renewed')], default='draft', max_length=32)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cymed_eco_credentialing_credentialing_application',
            },
        ),
        migrations.CreateModel(
            name='CredentialDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('kind', models.CharField(choices=[('medical_license', 'Medical License'), ('dea_license', 'DEA License'), ('malpractice_insurance', 'Malpractice Insurance'), ('board_certification', 'Board Certification'), ('medical_school_diploma', 'Medical School Diploma'), ('cme_certificate', 'CME Certificate'), ('passport', 'Passport'), ('national_id', 'National ID'), ('cv', 'CV'), ('accreditation', 'Accreditation'), ('other', 'Other')], max_length=32)),
                ('file_url', models.URLField(blank=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=32)),
                ('verified_by_profile_id', models.UUIDField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_reference', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cymed_eco_credentialing.credentialingapplication')),
            ],
            options={
                'db_table': 'cymed_eco_credentialing_credential_document',
            },
        ),
        migrations.CreateModel(
            name='LicenseVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('issuing_authority', models.CharField(blank=True, max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=128)),
                ('jurisdiction', models.CharField(blank=True, max_length=64)),
                ('verification_kind', models.CharField(choices=[('automated_registry', 'Automated Registry'), ('manual_email', 'Manual Email'), ('primary_source', 'Primary Source'), ('self_attest', 'Self Attest')], default='automated_registry', max_length=32)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.CharField(choices=[('verified', 'Verified'), ('not_found', 'Not Found'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='pending', max_length=32)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='cymed_eco_credentialing.credentialdocument')),
            ],
            options={
                'db_table': 'cymed_eco_credentialing_license_verification',
            },
        ),
        migrations.CreateModel(
            name='PrivilegeGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('subject_kind', models.CharField(choices=[('facility', 'Facility'), ('practitioner', 'Practitioner')], max_length=32)),
                ('facility_id', models.UUIDField(blank=True, null=True)),
                ('practitioner_id', models.UUIDField(blank=True, null=True)),
                ('privilege_scope', models.JSONField(blank=True, default=list)),
                ('granted_by_profile_id', models.UUIDField(blank=True, null=True)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=32)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privilege_grants', to='cymed_eco_credentialing.credentialingapplication')),
            ],
            options={
                'db_table': 'cymed_eco_credentialing_privilege_grant',
            },
        ),
    ]
