# Generated by Django 5.1.15 on 2026-06-23 03:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('partner_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=10)),
                ('regions_covered', models.JSONField(default=list)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='prospect', max_length=50)),
                ('partner_level', models.CharField(default='silver', max_length=50)),
            ],
            options={
                'db_table': 'cymed_commercial_partners',
            },
        ),
        migrations.CreateModel(
            name='PartnerType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('commission_rate_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'cymed_commercial_partner_types',
            },
        ),
        migrations.CreateModel(
            name='DistributorAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('agreement_number', models.CharField(max_length=100, unique=True)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('exclusive_territory', models.JSONField(default=list)),
                ('sub_reseller_rights', models.BooleanField(default=False)),
                ('localization_rights', models.BooleanField(default=False)),
                ('government_bid_rights', models.BooleanField(default=False)),
                ('annual_volume_commitment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_agreement', to='commercial_partner_management.partner')),
            ],
            options={
                'db_table': 'cymed_commercial_distributor_agreements',
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='commercial_partner_management.partnertype'),
        ),
        migrations.CreateModel(
            name='ResellerAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('agreement_number', models.CharField(max_length=100, unique=True)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('territory', models.JSONField(default=list)),
                ('products_authorized', models.JSONField(default=list)),
                ('discount_rate_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payment_terms_days', models.PositiveIntegerField(default=30)),
                ('min_annual_commitment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nda_signed', models.BooleanField(default=False)),
                ('can_white_label', models.BooleanField(default=False)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_agreement', to='commercial_partner_management.partner')),
            ],
            options={
                'db_table': 'cymed_commercial_reseller_agreements',
            },
        ),
    ]
