# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KioskSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('kiosk_id', models.CharField(db_index=True, max_length=100)),
                ('appointment_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('patient_profile_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('started', 'Started'), ('identified', 'Patient identified'), ('insurance_verified', 'Insurance verified'), ('consent_signed', 'Consent signed'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('failed_verify', 'Insurance failed — see staff')], default='started', max_length=30)),
                ('identity_method', models.CharField(blank=True, help_text='nfc | qr | national_id | phone_otp', max_length=30)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('error_note', models.CharField(blank=True, max_length=400)),
            ],
            options={
                'db_table': 'cymed_clinic_kiosk_sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
