# Generated by Django 6.0.7 on 2026-08-05 09:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('channel_type', models.CharField(choices=[('channel', 'Channel'), ('dm', 'Direct Message'), ('group', 'Group')], default='channel', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('last_interest_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cycom_discuss_channels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cycom_discuss.channel')),
            ],
            options={
                'db_table': 'cycom_discuss_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
