# Generated by Django 6.0.6 on 2026-06-23 04:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_orders', '0001_initial'),
        ('lab_specimens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathologyCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('case_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('clinical_history', models.TextField()),
                ('preoperative_diagnosis', models.CharField(blank=True, max_length=500)),
                ('procedure_type', models.CharField(blank=True, max_length=200)),
                ('operating_surgeon', models.UUIDField(blank=True, null=True)),
                ('specimen_received_at', models.DateTimeField(blank=True, null=True)),
                ('received_by', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('grossing', 'Grossing'), ('processing', 'Tissue Processing'), ('sectioning', 'Sectioning and Staining'), ('microscopy', 'Microscopic Examination'), ('draft_report', 'Draft Report'), ('pathologist_review', 'Pathologist Review'), ('signed_out', 'Signed Out'), ('amended', 'Amended')], default='received', max_length=30)),
                ('assigned_pathologist', models.UUIDField(blank=True, null=True)),
                ('priority', models.CharField(default='routine', max_length=20)),
                ('fhir_diagnostic_report_id', models.CharField(blank=True, max_length=255)),
                ('is_intraoperative', models.BooleanField(default=False)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathology_cases', to='lab_orders.laborderitem')),
            ],
            options={
                'db_table': 'cymed_lab_pathology_cases',
            },
        ),
        migrations.CreateModel(
            name='PathologySpecimen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('part_label', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('specimen_site', models.CharField(blank=True, max_length=255)),
                ('snomed_site_code', models.CharField(blank=True, max_length=50)),
                ('fixative', models.CharField(default='formalin', max_length=100)),
                ('cassettes_submitted', models.PositiveSmallIntegerField(default=0)),
                ('weight_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='lab_pathology.pathologycase')),
                ('specimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pathology_specimens', to='lab_specimens.specimen')),
            ],
            options={
                'db_table': 'cymed_lab_pathology_specimens',
            },
        ),
        migrations.CreateModel(
            name='PathologyDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('snomed_code', models.CharField(blank=True, max_length=50)),
                ('icd11_code', models.CharField(blank=True, max_length=20)),
                ('diagnosis_text', models.TextField()),
                ('diagnosis_category', models.CharField(blank=True, choices=[('benign', 'Benign'), ('malignant', 'Malignant'), ('borderline', 'Borderline/Uncertain'), ('inflammatory', 'Inflammatory'), ('reactive', 'Reactive'), ('normal', 'Within Normal Limits'), ('inconclusive', 'Inconclusive')], max_length=20)),
                ('tnm_staging', models.CharField(blank=True, max_length=50)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('is_primary', models.BooleanField(default=True)),
                ('signed_by', models.UUIDField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('digital_signature', models.CharField(blank=True, max_length=512)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='lab_pathology.pathologycase')),
                ('pathology_specimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='lab_pathology.pathologyspecimen')),
            ],
            options={
                'db_table': 'cymed_lab_pathology_diagnoses',
            },
        ),
        migrations.CreateModel(
            name='MicroscopicExamination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('microscopic_description', models.TextField()),
                ('stains_used', models.JSONField(default=list)),
                ('special_stains', models.JSONField(default=list)),
                ('ihc_markers', models.JSONField(default=dict)),
                ('examined_by', models.UUIDField()),
                ('examined_at', models.DateTimeField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microscopic_examinations', to='lab_pathology.pathologycase')),
                ('pathology_specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microscopic_examinations', to='lab_pathology.pathologyspecimen')),
            ],
            options={
                'db_table': 'cymed_lab_microscopic_examinations',
            },
        ),
        migrations.CreateModel(
            name='GrossExamination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('gross_description', models.TextField()),
                ('representative_sections', models.TextField(blank=True)),
                ('examined_by', models.UUIDField()),
                ('examined_at', models.DateTimeField()),
                ('inked', models.BooleanField(default=False)),
                ('ink_colors', models.CharField(blank=True, max_length=100)),
                ('tumor_size_cm', models.CharField(blank=True, max_length=50)),
                ('margin_involvement', models.CharField(blank=True, max_length=100)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gross_examinations', to='lab_pathology.pathologycase')),
                ('pathology_specimen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gross_examination', to='lab_pathology.pathologyspecimen')),
            ],
            options={
                'db_table': 'cymed_lab_gross_examinations',
            },
        ),
        migrations.AddIndex(
            model_name='pathologycase',
            index=models.Index(fields=['tenant_id', 'status', 'assigned_pathologist'], name='cymed_lab_p_tenant__fb30ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pathologyspecimen',
            unique_together={('case', 'part_label')},
        ),
    ]
