# Generated by Django 5.1.15 on 2026-06-23 00:21

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cymed_hospital_inpatient", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DischargeChecklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("task_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cymed_hospital_inpatient.hospitalstay",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_discharge_checklists",
            },
        ),
        migrations.CreateModel(
            name="DischargeInstruction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("dietary_instructions", models.TextField(blank=True)),
                ("activity_restrictions", models.TextField(blank=True)),
                ("warning_symptoms", models.TextField()),
                (
                    "stay",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructions",
                        to="cymed_hospital_inpatient.hospitalstay",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_discharge_instructions",
            },
        ),
        migrations.CreateModel(
            name="DischargeMedication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("medication_code", models.CharField(max_length=100)),
                ("reconciliation_action", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "stay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cymed_hospital_inpatient.hospitalstay",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_discharge_medications",
            },
        ),
        migrations.CreateModel(
            name="FollowUpAppointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("specialty_code", models.CharField(max_length=100)),
                ("target_date", models.DateField()),
                ("scheduled_appointment_id", models.UUIDField(blank=True, null=True)),
                (
                    "stay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cymed_hospital_inpatient.hospitalstay",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_discharge_followups",
            },
        ),
    ]
