# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_profile_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('source_kind', models.CharField(choices=[('cd', 'CD'), ('dvd', 'DVD'), ('usb', 'USB'), ('import_link', 'Import Link'), ('dicom_web', 'DICOMweb'), ('email', 'Email')], default='cd', max_length=32)),
                ('original_facility_name', models.CharField(blank=True, max_length=255)),
                ('size_mb', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('image_count', models.IntegerField(default=0)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('imported_by_profile_id', models.UUIDField(blank=True, null=True)),
                ('study_instance_uid', models.CharField(blank=True, db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('anonymised', 'Anonymised'), ('merged', 'Merged'), ('rejected', 'Rejected')], default='uploaded', max_length=32)),
            ],
            options={
                'db_table': 'cymed_img_image_sharing_external_import',
            },
        ),
        migrations.CreateModel(
            name='ShareableStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_profile_id', models.UUIDField(db_index=True)),
                ('study_instance_uid', models.CharField(db_index=True, max_length=128)),
                ('modality', models.CharField(blank=True, max_length=32)),
                ('study_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('original_facility_id', models.UUIDField(blank=True, null=True)),
                ('size_mb', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('image_count', models.IntegerField(default=0)),
                ('series_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cymed_img_image_sharing_shareable_study',
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_by_profile_id', models.UUIDField(blank=True, null=True)),
                ('recipient_kind', models.CharField(choices=[('patient', 'Patient'), ('provider', 'Provider'), ('external_radiologist', 'External Radiologist'), ('insurer', 'Insurer'), ('lawyer', 'Lawyer')], max_length=32)),
                ('recipient_email', models.CharField(blank=True, max_length=255)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_organization', models.CharField(blank=True, max_length=255)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('passphrase_hash', models.CharField(blank=True, max_length=128)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_views', models.IntegerField(default=-1)),
                ('view_count', models.IntegerField(default=0)),
                ('download_enabled', models.BooleanField(default=True)),
                ('watermark_text', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('used_up', 'Used Up')], default='active', max_length=32)),
                ('shareable_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='cymed_img_image_sharing.shareablestudy')),
            ],
            options={
                'db_table': 'cymed_img_image_sharing_share_link',
            },
        ),
        migrations.CreateModel(
            name='ShareAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('opened', 'Opened'), ('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('passphrase_failed', 'Passphrase Failed'), ('expired', 'Expired')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='cymed_img_image_sharing.sharelink')),
            ],
            options={
                'db_table': 'cymed_img_image_sharing_share_access_log',
            },
        ),
    ]
