# Generated by Django 6.0.7 on 2026-07-15 09:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_encounters', '0001_initial'),
        ('cymed_patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('category', models.CharField(choices=[('food', 'Food Allergy'), ('medication', 'Medication Allergy'), ('environment', 'Environmental Allergy'), ('biologic', 'Biologic Allergy')], max_length=30)),
                ('substance_code', models.CharField(max_length=100)),
                ('substance_display', models.CharField(max_length=255)),
                ('clinical_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=30)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='cymed_patients.patient')),
            ],
            options={
                'db_table': 'cymed_clinical_allergies',
            },
        ),
        migrations.CreateModel(
            name='AllergyReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('manifestation_code', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='cymed_clinical.allergy')),
            ],
            options={
                'db_table': 'cymed_clinical_allergy_reactions',
            },
        ),
        migrations.CreateModel(
            name='ClinicalFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('flag_text', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('security', 'Security Flag'), ('medical', 'Medical Warning Flag'), ('administrative', 'Administrative Flag')], default='medical', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='cymed_patients.patient')),
            ],
            options={
                'db_table': 'cymed_clinical_flags',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('display', models.CharField(max_length=255)),
                ('system', models.CharField(choices=[('icd11', 'ICD-11'), ('snomed', 'SNOMED-CT')], max_length=50)),
                ('clinical_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('remission', 'Remission'), ('resolved', 'Resolved')], default='active', max_length=30)),
                ('verification_status', models.CharField(choices=[('provisional', 'Provisional'), ('confirmed', 'Confirmed'), ('refuted', 'Refuted')], default='confirmed', max_length=30)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_by', models.CharField(max_length=255)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions', to='cymed_encounters.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='cymed_patients.patient')),
            ],
            options={
                'db_table': 'cymed_clinical_conditions',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('vaccine_code', models.CharField(max_length=100)),
                ('vaccine_display', models.CharField(max_length=255)),
                ('administered_date', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('not_done', 'Not Done')], default='completed', max_length=30)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunizations', to='cymed_patients.patient')),
            ],
            options={
                'db_table': 'cymed_clinical_immunizations',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('display', models.CharField(max_length=255)),
                ('value_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('value_string', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('preliminary', 'Preliminary'), ('final', 'Final'), ('amended', 'Amended')], default='final', max_length=30)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='cymed_encounters.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='cymed_patients.patient')),
            ],
            options={
                'db_table': 'cymed_clinical_observations',
            },
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('risk_code', models.CharField(max_length=100)),
                ('risk_display', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='cymed_patients.patient')),
            ],
            options={
                'db_table': 'cymed_clinical_risk_factors',
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('taken_by', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('temperature', 'Temperature (C)'), ('heart_rate', 'Heart Rate (bpm)'), ('respiratory_rate', 'Respiratory Rate (rpm)'), ('systolic_bp', 'Systolic Blood Pressure (mmHg)'), ('diastolic_bp', 'Diastolic Blood Pressure (mmHg)'), ('oxygen_saturation', 'Oxygen Saturation (%)'), ('weight', 'Weight (kg)'), ('height', 'Height (cm)')], max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(max_length=20)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='cymed_encounters.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='cymed_patients.patient')),
            ],
            options={
                'db_table': 'cymed_clinical_vitals',
                'ordering': ['-taken_at'],
            },
        ),
    ]
