# Generated by Django 6.1.1 on 2026-09-04 03:12

import platform.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_clinical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='substance_display',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='clinicalflag',
            name='flag_text',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='display',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='display',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='value_string',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='riskfactor',
            name='risk_display',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
    ]
