# Generated by Django 6.0.7 on 2026-10-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_clinical', '0004_allergy_attributes_allergy_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='abatement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='category',
            field=models.CharField(choices=[('problem_list_item', 'Problem list item'), ('encounter_diagnosis', 'Encounter diagnosis'), ('health_concern', 'Health concern')], db_index=True, default='problem_list_item', max_length=30),
        ),
    ]
