# Generated by Django 6.0.6 on 2026-09-06 20:19

import apps.tenants.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_branch_commission_policy_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=apps.tenants.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('number', models.CharField(max_length=60)),
                ('invoice_type', models.CharField(choices=[('standard', 'Standard tax invoice (B2B)'), ('simplified', 'Simplified tax invoice (B2C)'), ('credit_note', 'Credit note'), ('debit_note', 'Debit note')], default='simplified', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=10)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_tax_number', models.CharField(blank=True, max_length=50)),
                ('customer_address', models.CharField(blank=True, max_length=255)),
                ('issue_date', models.DateField()),
                ('supply_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('source_type', models.CharField(blank=True, max_length=20)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tenants.company')),
                ('corrected_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='einvoicing.invoice')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'einvoicing_invoices',
                'ordering': ['-issue_date', '-created_at'],
                'unique_together': {('tenant_id', 'number')},
            },
        ),
        migrations.CreateModel(
            name='EInvoiceDocument',
            fields=[
                ('id', models.UUIDField(default=apps.tenants.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('scheme', models.CharField(default='none', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'XML generated'), ('signed', 'Signed'), ('submitted', 'Submitted'), ('cleared', 'Cleared'), ('reported', 'Reported'), ('rejected', 'Rejected')], default='draft', max_length=12)),
                ('uuid', models.UUIDField(blank=True, null=True)),
                ('icv', models.PositiveBigIntegerField(default=1)),
                ('pih', models.CharField(blank=True, max_length=100)),
                ('invoice_hash', models.CharField(blank=True, max_length=100)),
                ('qr_code', models.TextField(blank=True)),
                ('ubl_xml', models.TextField(blank=True)),
                ('signed_xml', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('submission_response', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='einvoice', to='einvoicing.invoice')),
            ],
            options={
                'db_table': 'einvoicing_documents',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=apps.tenants.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='einvoicing.invoice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'einvoicing_invoice_lines',
                'ordering': ['line_no'],
            },
        ),
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.UUIDField(default=apps.tenants.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('scheme', models.CharField(choices=[('none', 'None / not required'), ('zatca', 'ZATCA (Saudi Arabia)'), ('jofotara', 'JoFotara (Jordan)')], default='none', max_length=12)),
                ('legal_name', models.CharField(max_length=255)),
                ('legal_name_ar', models.CharField(blank=True, max_length=255)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('tax_scheme_id', models.CharField(default='VAT', max_length=20)),
                ('country_code', models.CharField(default='SA', max_length=2)),
                ('address_street', models.CharField(blank=True, max_length=255)),
                ('address_city', models.CharField(blank=True, max_length=120)),
                ('address_postal', models.CharField(blank=True, max_length=20)),
                ('csid', models.TextField(blank=True, help_text='Compliance/Production CSID (base64)')),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('default_vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=5)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profile', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'einvoicing_tax_profiles',
            },
        ),
    ]
