# Generated by Django 6.0.6 on 2026-09-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einvoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxprofile',
            name='certificate_pem',
            field=models.TextField(blank=True, help_text='PEM X.509 cert issued by the scheme CA (CSID)'),
        ),
        migrations.AddField(
            model_name='taxprofile',
            name='private_key_pem',
            field=models.TextField(blank=True, help_text='PEM private key paired with the CSID cert (sensitive)'),
        ),
    ]
