# Generated by Django 5.1.15 on 2026-06-23 03:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('customer_id', models.UUIDField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_commercial_brands',
            },
        ),
        migrations.CreateModel(
            name='BrandDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('ssl_certificate_status', models.CharField(default='pending', max_length=50)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='commercial_branding.brand')),
            ],
            options={
                'db_table': 'cymed_commercial_brand_domains',
            },
        ),
        migrations.CreateModel(
            name='BrandTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('primary_color', models.CharField(default='#0062CC', max_length=20)),
                ('secondary_color', models.CharField(default='#6C757D', max_length=20)),
                ('accent_color', models.CharField(default='#28A745', max_length=20)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('surface_color', models.CharField(default='#F8F9FA', max_length=20)),
                ('text_primary_color', models.CharField(default='#212529', max_length=20)),
                ('heading_font', models.CharField(default='Inter', max_length=100)),
                ('body_font', models.CharField(default='Inter', max_length=100)),
                ('border_radius', models.CharField(default='8px', max_length=20)),
                ('custom_css', models.TextField(blank=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='commercial_branding.brand')),
            ],
            options={
                'db_table': 'cymed_commercial_brand_themes',
            },
        ),
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('asset_type', models.CharField(choices=[('logo_light', 'Logo (Light Background)'), ('logo_dark', 'Logo (Dark Background)'), ('logo_icon', 'Icon/Favicon'), ('splash_screen', 'Splash Screen'), ('login_background', 'Login Background'), ('email_header', 'Email Header')], max_length=50)),
                ('asset_url', models.URLField(max_length=1000)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='commercial_branding.brand')),
            ],
            options={
                'db_table': 'cymed_commercial_brand_assets',
                'unique_together': {('brand', 'asset_type', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='BrandLocalization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('language_code', models.CharField(max_length=10)),
                ('app_name', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('login_title', models.CharField(blank=True, max_length=255)),
                ('login_message', models.TextField(blank=True)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=50)),
                ('footer_text', models.TextField(blank=True)),
                ('is_rtl', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizations', to='commercial_branding.brand')),
            ],
            options={
                'db_table': 'cymed_commercial_brand_localizations',
                'unique_together': {('brand', 'language_code')},
            },
        ),
    ]
