# Generated by Django 6.0.7 on 2026-08-06 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_org', '0001_initial'),
        ('cyed_sis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_sections', to='cyed_org.campus'),
        ),
        migrations.AddField(
            model_name='student',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='cyed_org.campus'),
        ),
        migrations.AddField(
            model_name='student',
            name='country_of_birth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='indigenous_status',
            field=models.CharField(choices=[('1', 'Aboriginal but not Torres Strait Islander'), ('2', 'Torres Strait Islander but not Aboriginal'), ('3', 'Both Aboriginal and Torres Strait Islander'), ('4', 'Neither'), ('9', 'Not stated / unknown')], default='9', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='language_at_home',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='lbote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='parent1_occupation_group',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='parent1_school_education',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='parent2_occupation_group',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='parent2_school_education',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='state_student_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='usi',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
