# Generated by Django 6.1 on 2026-08-12 10:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_org', '0002_remove_campus_uniq_campus_code_per_group_and_more'),
        ('cyed_sis', '0004_classsection_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('effective_on', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('requested_by', models.CharField(blank=True, max_length=255)),
                ('enrolments_ended', models.PositiveSmallIntegerField(default=0)),
                ('from_campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='cyed_org.campus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_transfers', to='cyed_sis.student')),
                ('to_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='cyed_org.campus')),
            ],
            options={
                'db_table': 'cyed_campus_transfers',
                'ordering': ['-effective_on', '-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'student', 'effective_on'], name='idx_transfer_student_date')],
            },
        ),
    ]
