# Generated by Django 6.1 on 2026-08-12 12:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_sis', '0005_campustransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='exit_destination',
            field=models.CharField(blank=True, help_text='Receiving school or destination, if known.', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='exit_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='TransferCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('number', models.CharField(max_length=60)),
                ('issued_on', models.DateField()),
                ('issued_by', models.CharField(blank=True, max_length=255)),
                ('snapshot', models.JSONField(default=dict)),
                ('fees_settled', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_certificates', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_transfer_certificates',
                'ordering': ['-issued_on', '-version'],
                'constraints': [models.UniqueConstraint(fields=('student', 'version'), name='uniq_tc_version_per_student')],
            },
        ),
    ]
