# Generated by Django 6.0.6 on 2026-06-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_provider_clinical_messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clinicalgroup',
            name='cymed_prov_group_type_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='clinicalmessage',
            name='cymed_prov_msg_thread_sent_idx',
        ),
        migrations.RemoveIndex(
            model_name='clinicalmessage',
            name='cymed_prov_msg_sender_sent_idx',
        ),
        migrations.RemoveIndex(
            model_name='clinicalmessage',
            name='cymed_prov_msg_read_priority_idx',
        ),
        migrations.RemoveIndex(
            model_name='clinicalmessagethread',
            name='cymed_prov_thread_status_msg_idx',
        ),
        migrations.RemoveIndex(
            model_name='clinicalmessagethread',
            name='cymed_prov_thread_patient_idx',
        ),
        migrations.RemoveIndex(
            model_name='clinicalmessagethread',
            name='cymed_prov_thread_urgent_idx',
        ),
        migrations.RemoveIndex(
            model_name='messageattachment',
            name='cymed_prov_msgattach_msg_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagethreadparticipant',
            name='cymed_prov_participant_thread_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagethreadparticipant',
            name='cymed_prov_participant_prov_idx',
        ),
    ]
