# Generated by Django 6.0.6 on 2026-07-05 20:43

import apps.tenants.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollBatch',
            fields=[
                ('id', models.UUIDField(default=apps.tenants.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_batches', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=apps.tenants.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('working_days', models.IntegerField(default=22)),
                ('absent_days', models.IntegerField(default=0)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollbatch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.UUIDField(default=apps.tenants.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('line_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payslip')),
            ],
        ),
    ]
