import logging
from odoo import _, api, fields, models
from odoo.tools import float_compare, float_repr

_logger = logging.getLogger(__name__)


class PosOrder(models.Model):
    _inherit = "pos.order"

    is_advance_generated = fields.Boolean(
        string="Advance Generated",
        default=False,
        help="Technical flag used to exclude this order from POS session closing accounting (advance module flow).",
    )
    advance_order_id = fields.Many2one(
        "pos.advance.order",
        string="Advance Order",
        readonly=True,
        copy=False,
        index=True,
    )

    advance_pledge_line_ids = fields.One2many(
        "pos.advance.order.pledge",
        "pos_order_id",
        string="Pledge Lines",
        readonly=True,
        copy=False,
    )

    def _is_advance_deposit_invoice_line(self, line):
        """Identify advance deposit product line generated by advance flow."""
        self.ensure_one()
        if not self.advance_order_id:
            return False
        deposit_product = self.config_id.advance_deposit_product_id
        if not deposit_product:
            return False
        if line.product_id.id != deposit_product.id:
            return False
        return True

    def _prepare_invoice_lines(self, move_type):
        """Prepare invoice lines and exclude advance deposit helper product line."""
        invoice_lines = []
        for order in self:
            line_values_list = order.with_context(invoicing=True)._prepare_tax_base_line_values()
            for line_values in line_values_list:
                line = line_values["record"]
                if order._is_advance_deposit_invoice_line(line):
                    continue

                invoice_lines_values = order._get_invoice_lines_values(line_values, line, move_type)
                invoice_lines.append((0, None, invoice_lines_values))

                is_percentage = order.pricelist_id and any(
                    order.pricelist_id.item_ids.filtered(
                        lambda rule: rule.compute_price == "percentage"
                    )
                )
                if is_percentage and float_compare(
                    line.price_unit,
                    line.product_id.lst_price,
                    precision_rounding=order.currency_id.rounding,
                ) < 0:
                    invoice_lines.append(
                        (
                            0,
                            None,
                            {
                                "name": _(
                                    "Price discount from %(original_price)s to %(discounted_price)s",
                                    original_price=float_repr(
                                        line.product_id.lst_price,
                                        order.currency_id.decimal_places,
                                    ),
                                    discounted_price=float_repr(
                                        line.price_unit,
                                        order.currency_id.decimal_places,
                                    ),
                                ),
                                "display_type": "line_note",
                            },
                        )
                    )
                if line.customer_note:
                    invoice_lines.append(
                        (
                            0,
                            None,
                            {
                                "name": line.customer_note,
                                "display_type": "line_note",
                            },
                        )
                    )
            if order.general_customer_note:
                invoice_lines.append(
                    (
                        0,
                        None,
                        {
                            "name": order.general_customer_note,
                            "display_type": "line_note",
                        },
                    )
                )
            if order.advance_order_id:
                advance = order.advance_order_id
                currency = order.currency_id
                invoice_lines.append(
                    (
                        0,
                        None,
                        {
                            "name": _(
                                "Advance payment details: Tendered %(tendered)s, Change Returned %(change)s",
                                tendered=float_repr(
                                    advance.amount_tendered or 0.0,
                                    currency.decimal_places,
                                ),
                                change=float_repr(
                                    advance.change_amount or 0.0,
                                    currency.decimal_places,
                                ),
                            ),
                            "display_type": "line_note",
                        },
                    )
                )
                invoice_lines.append(
                    (
                        0,
                        None,
                        {
                            "name": _(
                                "Remaining payment details: Tendered %(tendered)s, Change Returned %(change)s",
                                tendered=float_repr(
                                    advance.remaining_amount_tendered or 0.0,
                                    currency.decimal_places,
                                ),
                                change=float_repr(
                                    advance.remaining_change_amount or 0.0,
                                    currency.decimal_places,
                                ),
                            ),
                            "display_type": "line_note",
                        },
                    )
                )
        return invoice_lines

    def _generate_pos_order_invoice(self):
        invoice = super()._generate_pos_order_invoice()
        for order in self:
            advance = order.advance_order_id
            if not advance:
                continue
            payment = advance.advance_account_payment_id if advance else False
            _logger.info(
                "[ADV_RECON] Invoice reconcile attempt: order=%s advance=%s payment=%s invoice=%s invoice_state=%s",
                order.id,
                advance.id if advance else False,
                payment.id if payment else False,
                invoice.id if invoice else False,
                invoice.state if invoice else False,
            )
            if not invoice or invoice.state != "posted":
                _logger.warning(
                    "[ADV_RECON] Skip invoice reconcile (invoice not posted): order=%s invoice=%s state=%s",
                    order.id,
                    invoice.id if invoice else False,
                    invoice.state if invoice else False,
                )
                continue
            receivable_account = advance._get_advance_receivable_account()

            settlement_moves = self.env["account.move"]
            if advance.advance_completion_settlement_move_id:
                settlement_moves |= advance.advance_completion_settlement_move_id
            if advance.pledge_completion_settlement_move_id:
                settlement_moves |= advance.pledge_completion_settlement_move_id

            if settlement_moves:
                for settle_move in settlement_moves:
                    settlement_lines = settle_move.line_ids.filtered(
                        lambda l: (
                            l.account_id == receivable_account
                            and not l.reconciled
                            and l.balance < 0
                        )
                    )
                    inv_ar_lines = invoice.line_ids.filtered(
                        lambda l: (
                            l.account_id == receivable_account
                            and not l.reconciled
                            and l.balance > 0
                        )
                    )
                    _logger.info(
                        "[ADV_RECON] Completion settlement reconcile: order=%s move=%s settlement_lines=%s invoice_ar=%s",
                        order.id,
                        settle_move.id,
                        settlement_lines.ids,
                        inv_ar_lines.ids,
                    )
                    if settlement_lines and inv_ar_lines:
                        try:
                            (settlement_lines | inv_ar_lines).sudo().reconcile()
                            _logger.info(
                                "[ADV_RECON] Completion settlement reconcile done: order=%s move=%s",
                                order.id,
                                settle_move.id,
                            )
                        except Exception as e:
                            _logger.exception(
                                "[ADV_RECON] Completion settlement reconcile failed: order=%s move=%s error=%s",
                                order.id,
                                settle_move.id,
                                e,
                            )
                            raise
                continue

            if not payment or not payment.move_id or payment.state not in ("in_process", "paid"):
                _logger.warning(
                    "[ADV_RECON] Skip invoice reconcile (payment not ready): order=%s payment=%s payment_move=%s payment_state=%s",
                    order.id,
                    payment.id if payment else False,
                    payment.move_id.id if payment and payment.move_id else False,
                    payment.state if payment else False,
                )
                continue
            _logger.info(
                "[ADV_RECON][INV_DEBUG] Context: order=%s partner=%s receivable_account=%s/%s invoice_partner=%s payment_partner=%s advance=%s",
                order.id,
                order.partner_id.id,
                receivable_account.id if receivable_account else False,
                receivable_account.display_name if receivable_account else False,
                invoice.partner_id.id if invoice and invoice.partner_id else False,
                payment.partner_id.id if payment and payment.partner_id else False,
                advance.id if advance else False,
            )
            _logger.info(
                "[ADV_RECON][INV_DEBUG] payment_move_lines=%s",
                [
                    {
                        "id": l.id,
                        "account_id": l.account_id.id,
                        "account": l.account_id.display_name,
                        "partner_id": l.partner_id.id if l.partner_id else False,
                        "debit": l.debit,
                        "credit": l.credit,
                        "balance": l.balance,
                        "reconciled": l.reconciled,
                    }
                    for l in payment.move_id.line_ids
                ],
            )
            _logger.info(
                "[ADV_RECON][INV_DEBUG] invoice_move_lines=%s",
                [
                    {
                        "id": l.id,
                        "account_id": l.account_id.id,
                        "account": l.account_id.display_name,
                        "account_type": l.account_id.account_type,
                        "partner_id": l.partner_id.id if l.partner_id else False,
                        "debit": l.debit,
                        "credit": l.credit,
                        "balance": l.balance,
                        "reconciled": l.reconciled,
                    }
                    for l in invoice.line_ids
                ],
            )
            payment_lines = payment.move_id.line_ids.filtered(
                lambda l: l.account_id == receivable_account and not l.reconciled
            )
            invoice_lines = invoice.line_ids.filtered(
                lambda l: l.account_id == receivable_account and not l.reconciled
            )
            _logger.info(
                "[ADV_RECON] Invoice reconcile candidates: order=%s receivable=%s payment_lines=%s invoice_lines=%s payment_balances=%s invoice_balances=%s",
                order.id,
                receivable_account.id if receivable_account else False,
                payment_lines.ids,
                invoice_lines.ids,
                payment_lines.mapped("balance"),
                invoice_lines.mapped("balance"),
            )
            if payment_lines and invoice_lines:
                try:
                    (payment_lines | invoice_lines).sudo().reconcile()
                    _logger.info(
                        "[ADV_RECON] Invoice reconcile done: order=%s payment_reconciled=%s invoice_reconciled=%s",
                        order.id,
                        payment_lines.mapped("reconciled"),
                        invoice_lines.mapped("reconciled"),
                    )
                except Exception as e:
                    _logger.exception(
                        "[ADV_RECON] Invoice reconcile failed: order=%s payment_lines=%s invoice_lines=%s error=%s",
                        order.id,
                        payment_lines.ids,
                        invoice_lines.ids,
                        e,
                    )
                    raise
            else:
                _logger.warning(
                    "[ADV_RECON] No direct payment lines for invoice reconcile. Trying liability settlement: order=%s payment_lines=%s invoice_lines=%s",
                    order.id,
                    payment_lines.ids,
                    invoice_lines.ids,
                )
                liability_line = (
                    advance.advance_liability_move_id.line_ids.filtered(
                        lambda l: l.credit > 0 and l.account_id != receivable_account
                    )[:1]
                    if advance and advance.advance_liability_move_id
                    else False
                )
                liability_account = (
                    liability_line.account_id
                    if liability_line
                    else (advance.from_pos_config_id or advance.pos_config_id).pos_advance_account_id if advance else False
                )
                _logger.info(
                    "[ADV_RECON][INV_DEBUG] liability source: advance_liability_move=%s liability_line=%s liability_account=%s/%s liability_move_lines=%s",
                    advance.advance_liability_move_id.id if advance and advance.advance_liability_move_id else False,
                    liability_line.id if liability_line else False,
                    liability_account.id if liability_account else False,
                    liability_account.display_name if liability_account else False,
                    [
                        {
                            "id": l.id,
                            "account_id": l.account_id.id,
                            "account": l.account_id.display_name,
                            "partner_id": l.partner_id.id if l.partner_id else False,
                            "debit": l.debit,
                            "credit": l.credit,
                            "balance": l.balance,
                            "reconciled": l.reconciled,
                        }
                        for l in (advance.advance_liability_move_id.line_ids if advance and advance.advance_liability_move_id else self.env["account.move.line"])
                    ],
                )
                if not liability_account or not invoice_lines:
                    _logger.warning(
                        "[ADV_RECON] Liability settlement skipped: order=%s liability=%s invoice_lines=%s invoice_line_candidates=%s",
                        order.id,
                        liability_account.id if liability_account else False,
                        invoice_lines.ids,
                        [
                            {
                                "id": l.id,
                                "account_id": l.account_id.id,
                                "account": l.account_id.display_name,
                                "account_type": l.account_id.account_type,
                                "partner_id": l.partner_id.id if l.partner_id else False,
                                "balance": l.balance,
                                "reconciled": l.reconciled,
                            }
                            for l in invoice.line_ids
                            if l.account_id.account_type in ("asset_receivable", "liability_payable")
                        ],
                    )
                    continue
                settlement_amount = min(
                    advance.advance_amount or 0.0,
                    abs(sum(invoice_lines.mapped("balance"))),
                )
                if settlement_amount <= 0:
                    _logger.warning(
                        "[ADV_RECON] Liability settlement skipped due to zero amount: order=%s amount=%s",
                        order.id,
                        settlement_amount,
                    )
                    continue
                journal = payment.journal_id or order.config_id.journal_id
                settlement_move = self.env["account.move"].sudo().create({
                    "journal_id": journal.id,
                    "date": fields.Date.context_today(order),
                    "ref": _("Advance settlement to invoice - %s", order.name),
                    "line_ids": [
                        (
                            0,
                            0,
                            {
                                "name": _("Advance settlement %s", order.name),
                                "account_id": liability_account.id,
                                "partner_id": order.partner_id.id,
                                "debit": settlement_amount,
                                "credit": 0.0,
                            },
                        ),
                        (
                            0,
                            0,
                            {
                                "name": _("Advance settlement %s", order.name),
                                "account_id": receivable_account.id,
                                "partner_id": order.partner_id.id,
                                "debit": 0.0,
                                "credit": settlement_amount,
                            },
                        ),
                    ],
                })
                settlement_move.action_post()
                settlement_receivable_lines = settlement_move.line_ids.filtered(
                    lambda l: l.account_id == receivable_account and not l.reconciled
                )
                invoice_lines = invoice.line_ids.filtered(
                    lambda l: l.account_id == receivable_account and not l.reconciled
                )
                _logger.info(
                    "[ADV_RECON] Liability settlement move created: order=%s move=%s amount=%s settlement_receivable_lines=%s invoice_lines=%s",
                    order.id,
                    settlement_move.id,
                    settlement_amount,
                    settlement_receivable_lines.ids,
                    invoice_lines.ids,
                )
                if settlement_receivable_lines and invoice_lines:
                    try:
                        (settlement_receivable_lines | invoice_lines).sudo().reconcile()
                        _logger.info(
                            "[ADV_RECON] Liability settlement reconcile done: order=%s settlement_lines_reconciled=%s invoice_lines_reconciled=%s",
                            order.id,
                            settlement_receivable_lines.mapped("reconciled"),
                            invoice_lines.mapped("reconciled"),
                        )
                    except Exception as e:
                        _logger.exception(
                            "[ADV_RECON] Liability settlement reconcile failed: order=%s move=%s error=%s",
                            order.id,
                            settlement_move.id,
                            e,
                        )
                        raise
        return invoice

class PosOrderLine(models.Model):
    _inherit = "pos.order.line"

    @api.model_create_multi
    def create(self, vals_list):
        lines = super().create(vals_list)

        for line in lines:
            if line.refunded_orderline_id:
                original_order = line.refunded_orderline_id.order_id

                _logger.info(
                    "DEBUG REFUND: refund line detected. original order %s",
                    original_order.name
                )

                advance = original_order.advance_order_id

                if advance:
                    _logger.info(
                        "DEBUG REFUND: advance found %s state=%s",
                        advance.name, advance.state
                    )

                    if advance.state != "cancel":
                        advance.write({"state": "cancel"})
                        _logger.info(
                            "DEBUG REFUND: advance %s cancelled",
                            advance.name
                        )
                else:
                    _logger.info(
                        "DEBUG REFUND: no advance linked to order %s",
                        original_order.name
                    )

        return lines
