# Generated by Django 5.1.15 on 2026-06-23 00:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_patients', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('arrival_method', models.CharField(max_length=100)),
                ('presenting_complaint', models.TextField()),
                ('status', models.CharField(choices=[('triage', 'Triage'), ('fast_track', 'Fast Track'), ('resuscitation', 'Resuscitation'), ('observation', 'Observation'), ('admitted', 'Admitted'), ('discharged', 'Discharged')], default='triage', max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cymed_patients.patient')),
            ],
            options={
                'db_table': 'cymed_hospital_emergency_visits',
            },
        ),
        migrations.CreateModel(
            name='EmergencyTriage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('esi_level', models.PositiveSmallIntegerField()),
                ('chief_complaint', models.TextField()),
                ('triage_nurse_id', models.UUIDField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage', to='cymed_hospital_emergency.emergencyvisit')),
            ],
            options={
                'db_table': 'cymed_hospital_emergency_triages',
            },
        ),
        migrations.CreateModel(
            name='EmergencyTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('location_label', models.CharField(max_length=100)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cymed_hospital_emergency.emergencyvisit')),
            ],
            options={
                'db_table': 'cymed_hospital_emergency_tracking',
            },
        ),
        migrations.CreateModel(
            name='EmergencyObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('systolic_bp', models.PositiveIntegerField()),
                ('diastolic_bp', models.PositiveIntegerField()),
                ('heart_rate', models.PositiveIntegerField()),
                ('resp_rate', models.PositiveIntegerField()),
                ('temp_c', models.DecimalField(decimal_places=2, max_digits=4)),
                ('o2_sat', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cymed_hospital_emergency.emergencyvisit')),
            ],
            options={
                'db_table': 'cymed_hospital_emergency_observations',
            },
        ),
        migrations.CreateModel(
            name='EmergencyDisposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('disposition_type', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposition', to='cymed_hospital_emergency.emergencyvisit')),
            ],
            options={
                'db_table': 'cymed_hospital_emergency_dispositions',
            },
        ),
        migrations.CreateModel(
            name='EmergencyAcuity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('news2_score', models.PositiveIntegerField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cymed_hospital_emergency.emergencyvisit')),
            ],
            options={
                'db_table': 'cymed_hospital_emergency_acuities',
            },
        ),
    ]
