# Generated by Django 6.0.6 on 2026-06-23 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('encounter_id', models.UUIDField(db_index=True)),
                ('admission_id', models.UUIDField(blank=True, null=True)),
                ('reconciliation_type', models.CharField(choices=[('admission', 'Admission Reconciliation'), ('transfer', 'Transfer Reconciliation'), ('discharge', 'Discharge Reconciliation'), ('pre_operative', 'Pre-Operative'), ('post_operative', 'Post-Operative')], default='admission', max_length=30)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('pharmacist_review', 'Under Pharmacist Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='initiated', max_length=30)),
                ('initiated_by', models.UUIDField()),
                ('pharmacist_id', models.UUIDField(blank=True, null=True)),
                ('prescriber_id', models.UUIDField(blank=True, null=True)),
                ('home_medications', models.JSONField(default=list)),
                ('current_medications', models.JSONField(default=list)),
                ('reconciled_medications', models.JSONField(default=list)),
                ('sources_consulted', models.JSONField(default=list)),
                ('medications_count', models.PositiveSmallIntegerField(default=0)),
                ('conflicts_identified', models.PositiveSmallIntegerField(default=0)),
                ('changes_made', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('summary_notes', models.TextField(blank=True)),
                ('fhir_bundle_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'cymed_rx_med_reconciliation',
                'indexes': [models.Index(fields=['patient_id', 'reconciliation_type'], name='cymed_rx_me_patient_fa0a9a_idx'), models.Index(fields=['encounter_id', 'status'], name='cymed_rx_me_encount_a8cc6a_idx'), models.Index(fields=['tenant_id', 'reconciliation_type', 'status'], name='cymed_rx_me_tenant__e97ba8_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicationConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('conflict_type', models.CharField(choices=[('omission', 'Medication Omission'), ('commission', 'Unintended Medication Added'), ('wrong_dose', 'Wrong Dose'), ('wrong_frequency', 'Wrong Frequency'), ('wrong_route', 'Wrong Route'), ('duplicate', 'Duplicate Therapy'), ('allergy_conflict', 'Allergy Conflict'), ('interaction_conflict', 'Interaction Conflict'), ('formulary_conflict', 'Non-Formulary Medication')], max_length=30)),
                ('drug_code', models.CharField(blank=True, max_length=100)),
                ('drug_name', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField()),
                ('clinical_significance', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major')], default='moderate', max_length=20)),
                ('status', models.CharField(choices=[('unresolved', 'Unresolved'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('escalated', 'Escalated to Prescriber')], default='unresolved', max_length=30)),
                ('resolved_by', models.UUIDField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='cymed_pharmacy_reconciliation.medicationreconciliation')),
            ],
            options={
                'db_table': 'cymed_rx_medication_conflicts',
                'indexes': [models.Index(fields=['reconciliation', 'status'], name='cymed_rx_me_reconci_355da7_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicationChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('drug_code', models.CharField(db_index=True, max_length=100)),
                ('drug_name', models.CharField(max_length=500)),
                ('change_type', models.CharField(choices=[('continued', 'Continued Unchanged'), ('dose_changed', 'Dose Changed'), ('frequency_changed', 'Frequency Changed'), ('route_changed', 'Route Changed'), ('discontinued', 'Discontinued'), ('added', 'New Medication Added'), ('held', 'Temporarily Held'), ('substituted', 'Substituted with Alternative')], max_length=30)),
                ('previous_dose', models.CharField(blank=True, max_length=100)),
                ('new_dose', models.CharField(blank=True, max_length=100)),
                ('previous_frequency', models.CharField(blank=True, max_length=100)),
                ('new_frequency', models.CharField(blank=True, max_length=100)),
                ('previous_route', models.CharField(blank=True, max_length=100)),
                ('new_route', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField()),
                ('changed_by', models.UUIDField()),
                ('prescriber_id', models.UUIDField(blank=True, null=True)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('fhir_medication_statement_id', models.CharField(blank=True, max_length=255)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_changes', to='cymed_pharmacy_reconciliation.medicationreconciliation')),
            ],
            options={
                'db_table': 'cymed_rx_medication_changes',
                'indexes': [models.Index(fields=['reconciliation', 'change_type'], name='cymed_rx_me_reconci_51097f_idx')],
            },
        ),
    ]
