# Generated by Django 5.1.15 on 2026-06-23 03:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('profile_type', models.CharField(choices=[('saas', 'SaaS (CyMed Cloud)'), ('private_cloud', 'Private Cloud'), ('government_cloud', 'Government Cloud'), ('hybrid', 'Hybrid'), ('air_gapped', 'Air-Gapped')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('requires_offline_license', models.BooleanField(default=False)),
                ('supports_auto_update', models.BooleanField(default=True)),
                ('supports_telemetry', models.BooleanField(default=True)),
                ('requires_government_clearance', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cymed_commercial_deployment_profiles',
            },
        ),
        migrations.CreateModel(
            name='DeploymentConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('customer_id', models.UUIDField()),
                ('configuration_name', models.CharField(max_length=255)),
                ('cloud_provider', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('cluster_name', models.CharField(blank=True, max_length=255)),
                ('database_host', models.CharField(blank=True, max_length=500)),
                ('is_internet_accessible', models.BooleanField(default=True)),
                ('vpn_required', models.BooleanField(default=False)),
                ('ip_whitelist', models.JSONField(blank=True, default=list)),
                ('update_channel', models.CharField(default='stable', max_length=50)),
                ('maintenance_window', models.CharField(blank=True, max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='commercial_deployment_profiles.deploymentprofile')),
            ],
            options={
                'db_table': 'cymed_commercial_deployment_configurations',
            },
        ),
        migrations.CreateModel(
            name='DeploymentCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('capability_code', models.CharField(max_length=200)),
                ('is_supported', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='commercial_deployment_profiles.deploymentprofile')),
            ],
            options={
                'db_table': 'cymed_commercial_deployment_capabilities',
                'unique_together': {('profile', 'capability_code')},
            },
        ),
    ]
