# Generated by Django 6.0.7 on 2026-07-22 00:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('number', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('assignee', models.CharField(blank=True, max_length=255)),
                ('team', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('stage', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('solved', 'Solved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cycom_helpdesk_tickets',
                'ordering': ['-created_at'],
                'unique_together': {('tenant_id', 'number')},
            },
        ),
    ]
