# Generated by Django 6.0.7 on 2026-09-26 10:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('restaurant', 'Restaurant'), ('hypermarket', 'Hypermarket')], max_length=12)),
                ('cuisine', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(default='Amman', max_length=80)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('source_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cymart_merchant',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('source_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cymart_merchants.merchant')),
            ],
            options={
                'db_table': 'cymart_merchant_product',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['merchant', 'is_active'], name='cymart_merc_merchan_5f5d6b_idx')],
            },
        ),
    ]
