# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DtcKit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('kit_barcode', models.CharField(max_length=64, unique=True)),
                ('lot_number', models.CharField(blank=True, max_length=64)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('dispatched', 'Dispatched'), ('activated', 'Activated'), ('returned_full', 'Returned Full'), ('returned_empty', 'Returned Empty'), ('expired', 'Expired'), ('lost', 'Lost')], default='in_stock', max_length=32)),
            ],
            options={
                'db_table': 'cymed_lab_dtc_catalog_dtc_kit',
            },
        ),
        migrations.CreateModel(
            name='DtcCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('name_ar', models.CharField(blank=True, max_length=128)),
                ('icon_url', models.URLField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_lab_dtc_catalog_dtc_category',
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DtcProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('wellness_panel', 'Wellness Panel'), ('vitamin_panel', 'Vitamin Panel'), ('hormonal_panel', 'Hormonal Panel'), ('genetic', 'Genetic'), ('nutrigenomic', 'Nutrigenomic'), ('microbiome', 'Microbiome'), ('allergy', 'Allergy'), ('fertility', 'Fertility'), ('stress', 'Stress'), ('longevity', 'Longevity')], max_length=32)),
                ('tests_included', models.JSONField(blank=True, default=list)),
                ('specimen_type', models.CharField(choices=[('blood', 'Blood'), ('saliva', 'Saliva'), ('stool', 'Stool'), ('swab', 'Swab'), ('urine', 'Urine'), ('other', 'Other')], max_length=32)),
                ('collection_mode', models.CharField(choices=[('home_kit', 'Home Kit'), ('in_lab', 'In Lab'), ('home_visit', 'Home Visit')], max_length=32)),
                ('turnaround_days', models.IntegerField(default=5)),
                ('includes_consultation', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=5)),
                ('stock_qty', models.IntegerField(default=-1)),
                ('active', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='cymed_lab_dtc_catalog.dtccategory')),
            ],
            options={
                'db_table': 'cymed_lab_dtc_catalog_dtc_product',
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DtcOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_profile_id', models.UUIDField(db_index=True)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('return_pickup_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('paid', 'Paid'), ('kit_dispatched', 'Kit Dispatched'), ('kit_delivered', 'Kit Delivered'), ('kit_activated', 'Kit Activated'), ('sample_received', 'Sample Received'), ('analysing', 'Analysing'), ('results_ready', 'Results Ready'), ('delivered_to_patient', 'Delivered To Patient'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='placed', max_length=32)),
                ('payment_ref', models.CharField(blank=True, max_length=128)),
                ('bill_id', models.UUIDField(blank=True, null=True)),
                ('consultation_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_notes', models.TextField(blank=True)),
                ('kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cymed_lab_dtc_catalog.dtckit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cymed_lab_dtc_catalog.dtcproduct')),
            ],
            options={
                'db_table': 'cymed_lab_dtc_catalog_dtc_order',
            },
        ),
        migrations.AddField(
            model_name='dtckit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kits', to='cymed_lab_dtc_catalog.dtcproduct'),
        ),
    ]
