# Generated by Django 6.0.7 on 2026-07-15 09:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('category', models.CharField(choices=[('treatment', 'Treatment Consent'), ('research', 'Research Consent'), ('data_sharing', 'Data Sharing Consent'), ('telemedicine', 'Telemedicine Consent')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('proposed', 'Proposed')], default='active', max_length=30)),
                ('policy_rule', models.TextField()),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='cymed_patients.patient')),
            ],
            options={
                'db_table': 'cymed_consents',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ConsentAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('action', models.CharField(max_length=100)),
                ('performed_by', models.CharField(max_length=255)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='cymed_consents.consent')),
            ],
            options={
                'db_table': 'cymed_consent_audits',
            },
        ),
        migrations.CreateModel(
            name='ConsentSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('signatory_name', models.CharField(max_length=255)),
                ('signature_image_url', models.URLField(blank=True, max_length=500)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='cymed_consents.consent')),
            ],
            options={
                'db_table': 'cymed_consent_signatures',
            },
        ),
        migrations.CreateModel(
            name='ConsentWitness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('witness_name', models.CharField(max_length=255)),
                ('witnessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='cymed_consents.consent')),
            ],
            options={
                'db_table': 'cymed_consent_witnesses',
            },
        ),
    ]
