# Generated by Django 6.0.7 on 2026-07-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_consents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='granted_to_tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
