# Generated by Django 6.0.6 on 2026-06-23 07:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispenseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('dispense_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('prescription_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('medication_order_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('encounter_id', models.UUIDField(blank=True, null=True)),
                ('admission_id', models.UUIDField(blank=True, null=True)),
                ('dispense_type', models.CharField(choices=[('retail', 'Retail Dispense'), ('inpatient', 'Inpatient / Unit Dose'), ('iv_admixture', 'IV Admixture'), ('batch', 'Batch Dispense'), ('emergency', 'Emergency Dispense')], default='retail', max_length=30)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('verification_pending', 'Pending Pharmacist Verification'), ('verified', 'Pharmacist Verified'), ('ready', 'Ready for Pickup'), ('dispensed', 'Dispensed'), ('partial', 'Partially Dispensed'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='queued', max_length=30)),
                ('pickup_method', models.CharField(choices=[('counter', 'Counter Pickup'), ('bedside', 'Bedside Delivery'), ('ward_cart', 'Ward Medication Cart'), ('adc', 'Automated Dispensing Cabinet'), ('robot', 'Dispensing Robot'), ('mail', 'Mail Order'), ('delivery', 'Home Delivery')], default='counter', max_length=30)),
                ('pharmacist_id', models.UUIDField(blank=True, null=True)),
                ('technician_id', models.UUIDField(blank=True, null=True)),
                ('pharmacy_location', models.CharField(blank=True, max_length=255)),
                ('dispensing_counter', models.CharField(blank=True, max_length=50)),
                ('verified_by', models.UUIDField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('dispensed_by', models.UUIDField(blank=True, null=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_by', models.CharField(blank=True, max_length=255)),
                ('pickup_id_verified', models.BooleanField(default=False)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('fhir_medication_dispense_id', models.CharField(blank=True, max_length=255)),
                ('counseling_provided', models.BooleanField(default=False)),
                ('counseling_notes', models.TextField(blank=True)),
                ('automation_device_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cymed_rx_dispense_orders',
                'indexes': [models.Index(fields=['patient_id', 'status'], name='cymed_rx_di_patient_330c59_idx'), models.Index(fields=['tenant_id', 'dispense_type', 'status'], name='cymed_rx_di_tenant__2e3a66_idx'), models.Index(fields=['prescription_id'], name='cymed_rx_di_prescri_45669e_idx'), models.Index(fields=['medication_order_id'], name='cymed_rx_di_medicat_68f053_idx')],
            },
        ),
        migrations.CreateModel(
            name='DispenseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('drug_code', models.CharField(db_index=True, max_length=100)),
                ('drug_name', models.CharField(max_length=500)),
                ('ndc_code', models.CharField(blank=True, max_length=50)),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_prescribed', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity_dispensed', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity_unit', models.CharField(max_length=50)),
                ('days_supply', models.PositiveSmallIntegerField(default=0)),
                ('is_substituted', models.BooleanField(default=False)),
                ('original_drug_code', models.CharField(blank=True, max_length=100)),
                ('substitution_reason', models.CharField(blank=True, max_length=255)),
                ('barcode_verified', models.BooleanField(default=False)),
                ('barcode_verified_by', models.UUIDField(blank=True, null=True)),
                ('barcode_verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked', 'Picked'), ('barcode_verified', 'Barcode Verified'), ('verified', 'Pharmacist Verified'), ('dispensed', 'Dispensed'), ('returned', 'Returned'), ('substituted', 'Substituted')], default='pending', max_length=30)),
                ('storage_bin', models.CharField(blank=True, max_length=100)),
                ('adc_pocket', models.CharField(blank=True, max_length=100)),
                ('dispense_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cymed_pharmacy_dispensing.dispenseorder')),
            ],
            options={
                'db_table': 'cymed_rx_dispense_items',
            },
        ),
        migrations.CreateModel(
            name='DispenseBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('batch_type', models.CharField(choices=[('unit_dose', 'Unit Dose Batch'), ('ward_distribution', 'Ward Distribution'), ('adc_restock', 'ADC Restock'), ('robot_fill', 'Robot Fill'), ('emergency_kit', 'Emergency Kit')], default='unit_dose', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('verification_pending', 'Pending Verification'), ('verified', 'Verified'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=30)),
                ('ward_id', models.UUIDField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('prepared_by', models.UUIDField(blank=True, null=True)),
                ('verified_by', models.UUIDField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('dispense_orders', models.ManyToManyField(blank=True, related_name='batches', to='cymed_pharmacy_dispensing.dispenseorder')),
            ],
            options={
                'db_table': 'cymed_rx_dispense_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispenseAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('action', models.CharField(choices=[('created', 'Order Created'), ('assigned', 'Assigned to Pharmacist'), ('picked', 'Medication Picked'), ('barcode_scanned', 'Barcode Scanned'), ('verified', 'Pharmacist Verified'), ('dispensed', 'Dispensed to Patient'), ('returned', 'Medication Returned'), ('cancelled', 'Cancelled'), ('override', 'Override Applied')], max_length=30)),
                ('performed_by', models.UUIDField()),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('is_override', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('dispense_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='cymed_pharmacy_dispensing.dispenseorder')),
            ],
            options={
                'db_table': 'cymed_rx_dispense_audit',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='DispenseVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('verification_type', models.CharField(choices=[('first_check', 'First Check'), ('second_check', 'Second Check (Dual Verify)'), ('final_check', 'Final Check'), ('clinical_review', 'Clinical Review')], max_length=30)),
                ('verified_by', models.UUIDField()),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('pass', 'Passed'), ('fail_corrected', 'Failed — Corrected'), ('fail_rejected', 'Failed — Rejected')], default='pass', max_length=30)),
                ('discrepancy_noted', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('dispense_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='cymed_pharmacy_dispensing.dispenseitem')),
                ('dispense_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='cymed_pharmacy_dispensing.dispenseorder')),
            ],
            options={
                'db_table': 'cymed_rx_dispense_verifications',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dispenseitem',
            index=models.Index(fields=['dispense_order', 'status'], name='cymed_rx_di_dispens_002901_idx'),
        ),
        migrations.AddIndex(
            model_name='dispenseaudit',
            index=models.Index(fields=['dispense_order', 'action'], name='cymed_rx_di_dispens_05de26_idx'),
        ),
        migrations.AddIndex(
            model_name='dispenseaudit',
            index=models.Index(fields=['tenant_id', 'performed_at'], name='cymed_rx_di_tenant__4e4f16_idx'),
        ),
    ]
