# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrepAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_profile_id', models.UUIDField(db_index=True)),
                ('booking_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('viewed', 'Viewed'), ('confirmed', 'Confirmed'), ('partial', 'Partial'), ('not_ready', 'Not Ready')], default='assigned', max_length=32)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=8)),
            ],
            options={
                'db_table': 'cymed_img_prep_instructions_prep_assignment',
            },
        ),
        migrations.CreateModel(
            name='ContrastConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_profile_id', models.UUIDField(db_index=True)),
                ('contrast_kind', models.CharField(choices=[('iodinated', 'Iodinated'), ('gadolinium', 'Gadolinium'), ('barium', 'Barium'), ('microbubble', 'Microbubble')], max_length=32)),
                ('allergies_reviewed', models.BooleanField(default=False)),
                ('egfr_verified', models.BooleanField(default=False)),
                ('egfr_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pregnancy_status', models.CharField(choices=[('unknown', 'Unknown'), ('not_pregnant', 'Not Pregnant'), ('pregnant', 'Pregnant'), ('na', 'N/A')], default='unknown', max_length=32)),
                ('consent_signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_url', models.URLField(blank=True)),
                ('witness_profile_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=32)),
                ('decline_reason', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrast_consents', to='cymed_img_prep_instructions.prepassignment')),
            ],
            options={
                'db_table': 'cymed_img_prep_instructions_contrast_consent',
            },
        ),
        migrations.CreateModel(
            name='PrepChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('position', models.IntegerField(default=0)),
                ('label', models.CharField(max_length=255)),
                ('label_ar', models.CharField(blank=True, max_length=255)),
                ('item_kind', models.CharField(choices=[('fasting', 'Fasting'), ('hydration', 'Hydration'), ('hold_medication', 'Hold Medication'), ('bring_item', 'Bring Item'), ('arrival_time', 'Arrival Time'), ('clothing', 'Clothing'), ('consent', 'Consent'), ('other', 'Other')], default='other', max_length=32)),
                ('required', models.BooleanField(default=True)),
                ('checked', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cymed_img_prep_instructions.prepassignment')),
            ],
            options={
                'db_table': 'cymed_img_prep_instructions_prep_checklist_item',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrepTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('modality', models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT'), ('mri', 'MRI'), ('us', 'Ultrasound'), ('mammo', 'Mammography'), ('nm', 'Nuclear Medicine'), ('pet', 'PET'), ('fluoro', 'Fluoroscopy'), ('other', 'Other')], max_length=32)),
                ('body_part', models.CharField(blank=True, max_length=64)),
                ('contrast_involved', models.BooleanField(default=False)),
                ('fasting_required', models.BooleanField(default=False)),
                ('fasting_hours', models.IntegerField(default=0)),
                ('hydration_required', models.BooleanField(default=False)),
                ('medications_to_hold', models.JSONField(blank=True, default=list)),
                ('clothing_instructions', models.TextField(blank=True)),
                ('arrive_minutes_before', models.IntegerField(default=15)),
                ('what_to_bring', models.JSONField(blank=True, default=list)),
                ('body_html', models.TextField(blank=True)),
                ('body_html_ar', models.TextField(blank=True)),
                ('version', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_img_prep_instructions_prep_template',
                'unique_together': {('tenant_id', 'code', 'version')},
            },
        ),
        migrations.AddField(
            model_name='prepassignment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='cymed_img_prep_instructions.preptemplate'),
        ),
    ]
