# Generated by Django 6.0.7 on 2026-08-05 12:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyed_sis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('day_of_week', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', max_length=3)),
                ('period_label', models.CharField(blank=True, max_length=50)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('teacher_name', models.CharField(blank=True, max_length=255)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='cyed_sis.classsection')),
            ],
            options={
                'db_table': 'cyed_timetable_slots',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
