# Generated by Django 6.1 on 2026-09-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_timetable', '0002_timetableslot_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableslot',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='created_by',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='row_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='updated_by',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
