# Generated by Django 6.0.7 on 2026-07-21 19:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('document_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('currency', models.CharField(default='JOD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'provisioning_approval_policies',
                'ordering': ['document_type'],
            },
        ),
        migrations.CreateModel(
            name='CompanyBlueprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('company_name', models.CharField(max_length=200)),
                ('country_code', models.CharField(default='JO', max_length=2)),
                ('industry_key', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('micro', 'Micro'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('enterprise', 'Enterprise Group')], default='small', max_length=20)),
                ('setup_level', models.CharField(choices=[('express', 'Express'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='express', max_length=20)),
                ('business_ops', models.JSONField(default=list)),
                ('selected_department_packs', models.JSONField(default=list)),
                ('companies', models.PositiveIntegerField(default=1)),
                ('branches', models.PositiveIntegerField(default=1)),
                ('warehouses', models.PositiveIntegerField(default=1)),
                ('factories', models.PositiveIntegerField(default=0)),
                ('projects', models.PositiveIntegerField(default=0)),
                ('departments', models.JSONField(default=list)),
                ('cost_centers', models.JSONField(default=list)),
                ('template_version_used', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('provisioning', 'Provisioning'), ('provisioned', 'Provisioned'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('summary', models.JSONField(default=dict)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'provisioning_company_blueprints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CountryPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(default='JOD', max_length=10)),
                ('languages', models.JSONField(default=list)),
                ('default_locale', models.CharField(default='en', max_length=10)),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1)),
                ('tax_config', models.JSONField(default=dict)),
                ('payroll_config', models.JSONField(default=dict)),
                ('coa_template', models.JSONField(default=list)),
                ('einvoicing', models.JSONField(default=dict)),
                ('public_holidays', models.JSONField(default=list)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'provisioning_country_packs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('modules', models.JSONField(default=list)),
                ('roles', models.JSONField(default=list)),
                ('permissions', models.JSONField(default=dict)),
                ('menus', models.JSONField(default=list)),
                ('workflows', models.JSONField(default=list)),
                ('kpis', models.JSONField(default=list)),
                ('dashboards', models.JSONField(default=list)),
                ('reports', models.JSONField(default=list)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'provisioning_department_packs',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('threshold_min', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('threshold_max', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('approver_role', models.CharField(max_length=150)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='provisioning.approvalpolicy')),
            ],
            options={
                'db_table': 'provisioning_approval_tiers',
                'ordering': ['policy', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='approvalpolicy',
            name='generated_by_blueprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_policies', to='provisioning.companyblueprint'),
        ),
        migrations.CreateModel(
            name='IndustryTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('department_pack_keys', models.JSONField(default=list)),
                ('terminology', models.JSONField(default=dict)),
                ('default_config', models.JSONField(default=dict)),
                ('approval_matrix', models.JSONField(default=list)),
                ('categories', models.JSONField(default=list)),
                ('accounting_mappings', models.JSONField(default=dict)),
                ('dashboards', models.JSONField(default=list)),
                ('reports', models.JSONField(default=list)),
                ('doc_templates', models.JSONField(default=list)),
                ('import_templates', models.JSONField(default=list)),
                ('industry_fields', models.JSONField(default=dict)),
                ('ai_knowledge', models.JSONField(default=dict)),
                ('recommended_ops', models.JSONField(default=list)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'provisioning_industry_templates',
                'ordering': ['key', '-version'],
                'unique_together': {('key', 'version')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='approvalpolicy',
            unique_together={('tenant_id', 'document_type')},
        ),
    ]
