# Generated by Django 6.0.7 on 2026-07-21 23:57

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantConfigParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('key', models.CharField(max_length=200)),
                ('value', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'provisioning_config_parameters',
                'ordering': ['key'],
                'unique_together': {('tenant_id', 'key')},
            },
        ),
    ]
