# Generated by Django 6.0.7 on 2026-09-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0003_approvalpolicy_attributes_approvalpolicy_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyblueprint',
            name='approval_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
