# Generated by Django 6.0.7 on 2026-07-15 09:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_cohort_registries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegistryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=30)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registry_entries', to='cymed_patients.patient')),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cymed_registries.cohortregistry')),
            ],
            options={
                'db_table': 'cymed_registry_entries',
                'unique_together': {('registry', 'patient')},
            },
        ),
    ]
