# Generated by Django 6.1.1 on 2026-09-04 03:09

import platform.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_hospital_discharge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargeinstruction',
            name='activity_restrictions',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='dischargeinstruction',
            name='dietary_instructions',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='dischargeinstruction',
            name='warning_symptoms',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='dischargemedication',
            name='notes',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
    ]
