# Generated by Django 6.1 on 2026-08-14 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_docsign', '0001_initial'),
        ('cyed_events', '0001_initial'),
        ('cyed_fees', '0001_initial'),
        ('cyed_hr', '0004_staffleave_balance_override_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='charge_students',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='departs_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='hardship_waivers',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='permission_deadline',
            field=models.DateField(blank=True, help_text='After this, unreturned permissions are chased rather than waited on.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='returns_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='staff_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_in_charge', to='cyed_hr.staff'),
        ),
        migrations.AddField(
            model_name='event',
            name='transport_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='what_to_bring',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='consent_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_participations', to='cyed_docsign.signabledocument'),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='fee_waived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_participations', to='cyed_fees.invoice'),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='medical_notes_ack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='waiver_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
