# Generated by Django 6.0.6 on 2026-07-14 21:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('category', 'Category'), ('merchant', 'Merchant'), ('store', 'Store'), ('product', 'Product'), ('promotional', 'Promotional')], max_length=16)),
                ('scope_ref_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('commission_base', models.CharField(choices=[('gross_merchandise_value', 'Gross Merchandise Value'), ('gross_excluding_tax', 'Gross Value Excluding Tax'), ('gross_after_merchant_discount', 'Gross Value After Merchant-Funded Discount'), ('gross_after_all_discounts', 'Gross Value After All Discounts'), ('net_item_value', 'Net Item Value')], default='gross_after_merchant_discount', max_length=32)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_excluded', models.BooleanField(default=True)),
                ('tips_excluded', models.BooleanField(default=True)),
                ('taxes_included', models.BooleanField(default=False)),
                ('is_exempt', models.BooleanField(default=False, help_text='If true, matching orders pay zero commission.')),
                ('requires_approval', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=True, help_text='Ignored unless requires_approval is true.')),
                ('effective_from', models.DateTimeField()),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cymart_commission_policy',
                'indexes': [models.Index(fields=['scope', 'scope_ref_id'], name='cymart_comm_scope_8983a0_idx'), models.Index(fields=['effective_from', 'effective_until'], name='cymart_comm_effecti_243826_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommissionTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='cymart_commission.commissionpolicy')),
            ],
            options={
                'db_table': 'cymart_commission_tier',
                'ordering': ['min_amount'],
            },
        ),
        migrations.CreateModel(
            name='CommissionCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='The merchant this commission is on.')),
                ('reference_type', models.CharField(default='marketplace_order', max_length=64)),
                ('reference_id', models.UUIDField(db_index=True)),
                ('commission_base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('breakdown', models.JSONField(help_text='Transparent line-level detail: base, rate, fixed fee, min/max clamp applied, exemption, tier used.')),
                ('is_refund_reversal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reverses', models.ForeignKey(blank=True, help_text='Set when is_refund_reversal is true — the original calculation being reversed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entries', to='cymart_commission.commissioncalculation')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='cymart_commission.commissionpolicy')),
            ],
            options={
                'db_table': 'cymart_commission_calculation',
                'indexes': [models.Index(fields=['tenant_id', 'reference_id'], name='cymart_comm_tenant__67a87d_idx')],
            },
        ),
    ]
