# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('earn_ratio', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=9)),
                ('redeem_ratio', models.DecimalField(decimal_places=4, default=Decimal('100'), max_digits=9)),
                ('min_redemption_points', models.IntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_pharmacy_loyalty_loyalty_program',
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('name_ar', models.CharField(blank=True, max_length=128)),
                ('threshold_points', models.IntegerField()),
                ('benefits', models.JSONField(blank=True, default=dict)),
                ('priority', models.IntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='cymed_pharmacy_loyalty.loyaltyprogram')),
            ],
            options={
                'db_table': 'cymed_pharmacy_loyalty_loyalty_tier',
            },
        ),
        migrations.CreateModel(
            name='PatientLoyaltyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_profile_id', models.UUIDField(db_index=True)),
                ('balance_points', models.IntegerField(default=0)),
                ('lifetime_points', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cymed_pharmacy_loyalty.loyaltytier')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='cymed_pharmacy_loyalty.loyaltyprogram')),
            ],
            options={
                'db_table': 'cymed_pharmacy_loyalty_patient_loyalty_account',
                'unique_together': {('program', 'patient_profile_id')},
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kind', models.CharField(choices=[('earn', 'Earn'), ('redeem', 'Redeem'), ('adjust_up', 'Adjust Up'), ('adjust_down', 'Adjust Down'), ('expire', 'Expire')], max_length=32)),
                ('points', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('reference_order_id', models.UUIDField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cymed_pharmacy_loyalty.patientloyaltyaccount')),
            ],
            options={
                'db_table': 'cymed_pharmacy_loyalty_points_transaction',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('cost_points', models.IntegerField()),
                ('monetary_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('kind', models.CharField(choices=[('discount', 'Discount'), ('free_item', 'Free Item'), ('coupon', 'Coupon'), ('donation', 'Donation')], max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('stock_left', models.IntegerField(default=-1)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='cymed_pharmacy_loyalty.loyaltyprogram')),
            ],
            options={
                'db_table': 'cymed_pharmacy_loyalty_reward',
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('points_spent', models.IntegerField()),
                ('code', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('used', 'Used'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='issued', max_length=32)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='cymed_pharmacy_loyalty.patientloyaltyaccount')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='cymed_pharmacy_loyalty.reward')),
            ],
            options={
                'db_table': 'cymed_pharmacy_loyalty_redemption',
            },
        ),
    ]
