# Generated by Django 6.0.7 on 2026-08-05 09:39

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('resource_name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(choices=[('sales', 'Sales'), ('warehouse', 'Warehouse'), ('finance', 'Finance'), ('it', 'IT')], default='sales', max_length=20)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('confirmed', 'Confirmed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cycom_planning_shift_slots',
                'ordering': ['start_datetime'],
            },
        ),
    ]
