# Generated by Django 6.0.7 on 2026-07-15 12:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_event_id', models.UUIDField(blank=True, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('topic', models.CharField(max_length=500)),
                ('payload', models.JSONField()),
                ('error_message', models.TextField()),
                ('failed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'platform_dead_letter_events',
                'ordering': ['-failed_at'],
            },
        ),
        migrations.CreateModel(
            name='EventDeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True)),
                ('consumer_group', models.CharField(db_index=True, max_length=200)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(default='delivered', max_length=50)),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'platform_event_delivery_logs',
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('topic', models.CharField(db_index=True, max_length=500)),
                ('event_type', models.CharField(db_index=True, max_length=200)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'platform_outbox_events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='platform_ou_status_6ff863_idx'), models.Index(fields=['topic', 'status'], name='platform_ou_topic_11b394_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.TextField()),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature_record', to='platform_events.outboxevent')),
            ],
            options={
                'db_table': 'platform_event_signatures',
            },
        ),
    ]
