# Generated by Django 6.0.6 on 2026-09-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='allow_negative',
            field=models.BooleanField(default=False),
        ),
    ]
