# Generated by Django 6.0.7 on 2026-08-05 12:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('applicant_first_name', models.CharField(max_length=100)),
                ('applicant_last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('year_level_applying', models.PositiveSmallIntegerField(default=7)),
                ('guardian_name', models.CharField(blank=True, max_length=255)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('enquiry', 'Enquiry'), ('submitted', 'Submitted'), ('assessment', 'Under Assessment'), ('offer', 'Offer Made'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('enrolled', 'Enrolled')], default='enquiry', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('enrolled_student_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cyed_admissions_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('offered_year_level', models.PositiveSmallIntegerField(default=7)),
                ('offer_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('response', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('conditions', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='cyed_admissions.application')),
            ],
            options={
                'db_table': 'cyed_admissions_offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
