# Generated by Django 6.1 on 2026-08-12 09:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_admissions', '0001_initial'),
        ('cyed_org', '0002_remove_campus_uniq_campus_code_per_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='cyed_org.campus'),
        ),
        migrations.AddField(
            model_name='application',
            name='residential_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='residential_postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='residential_suburb',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='waitlist_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='decline_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='offer',
            name='responded_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='offer',
            name='responded_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('enquiry', 'Enquiry'), ('submitted', 'Submitted'), ('assessment', 'Under Assessment'), ('offer', 'Offer Made'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('waitlisted', 'Waitlisted'), ('withdrawn', 'Withdrawn'), ('enrolled', 'Enrolled')], default='enquiry', max_length=20),
        ),
        migrations.CreateModel(
            name='CatchmentZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=150)),
                ('postcodes', models.JSONField(blank=True, default=list, help_text='e.g. ["3121", "3122"]')),
                ('suburbs', models.JSONField(blank=True, default=list, help_text='e.g. ["Richmond", "Hawthorn"]')),
                ('is_priority', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catchment_zones', to='cyed_org.campus')),
            ],
            options={
                'db_table': 'cyed_catchment_zones',
                'ordering': ['-is_priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('kind', models.CharField(choices=[('birth_certificate', 'Birth certificate'), ('immunisation_statement', 'AIR immunisation history statement'), ('proof_of_address', 'Proof of address'), ('previous_reports', 'Previous school reports'), ('visa_passport', 'Visa / passport'), ('court_orders', 'Court orders / parenting plan'), ('medical_plan', 'Medical or action plan'), ('other', 'Other')], default='other', max_length=40)),
                ('is_received', models.BooleanField(default=False)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, max_length=255)),
                ('document_ref', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cyed_admissions.application')),
            ],
            options={
                'db_table': 'cyed_admissions_documents',
                'ordering': ['kind'],
                'constraints': [models.UniqueConstraint(fields=('application', 'kind'), name='uniq_document_kind_per_application')],
            },
        ),
    ]
