# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScribeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('clinician_profile_id', models.UUIDField(db_index=True)),
                ('patient_profile_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('encounter_id', models.UUIDField(blank=True, null=True)),
                ('consent_kind', models.CharField(choices=[('verbal_recorded', 'Verbal Recorded'), ('written', 'Written'), ('opted_out', 'Opted Out')], default='verbal_recorded', max_length=32)),
                ('consent_captured_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=8)),
                ('device_platform', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('uploaded', 'Uploaded'), ('transcribing', 'Transcribing'), ('transcribed', 'Transcribed'), ('summarising', 'Summarising'), ('drafted', 'Drafted'), ('signed', 'Signed'), ('discarded', 'Discarded'), ('failed', 'Failed')], default='recording', max_length=32)),
                ('audio_url', models.URLField(blank=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('stt_model', models.CharField(blank=True, max_length=64)),
                ('summary_model', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'cymed_mrff_ambient_scribe_scribe_session',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('provider', models.CharField(choices=[('cygpt', 'CyGPT'), ('azure_openai', 'Azure OpenAI'), ('bedrock_claude', 'Bedrock Claude'), ('vertex_gemini', 'Vertex Gemini'), ('on_prem_llama', 'On-Prem Llama')], default='cygpt', max_length=32)),
                ('version', models.IntegerField(default=1)),
                ('soap', models.JSONField(blank=True, default=dict)),
                ('structured', models.JSONField(blank=True, default=dict)),
                ('icd_suggestions', models.JSONField(blank=True, default=list)),
                ('cpt_suggestions', models.JSONField(blank=True, default=list)),
                ('differentials', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prompt_token_count', models.IntegerField(default=0)),
                ('output_token_count', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=9)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='cymed_mrff_ambient_scribe.scribesession')),
            ],
            options={
                'db_table': 'cymed_mrff_ambient_scribe_summary',
            },
        ),
        migrations.CreateModel(
            name='ClinicianEdit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('clinician_profile_id', models.UUIDField(db_index=True)),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('diff', models.JSONField(blank=True, default=dict)),
                ('final_note', models.TextField(blank=True)),
                ('signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='cymed_mrff_ambient_scribe.summary')),
            ],
            options={
                'db_table': 'cymed_mrff_ambient_scribe_clinician_edit',
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('provider', models.CharField(choices=[('whisper', 'Whisper'), ('azure_stt', 'Azure STT'), ('aws_transcribe', 'AWS Transcribe'), ('vosk_offline', 'Vosk Offline'), ('vendor_custom', 'Vendor Custom')], default='whisper', max_length=32)),
                ('text', models.TextField(blank=True)),
                ('segments', models.JSONField(blank=True, default=list)),
                ('confidence', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('language', models.CharField(default='en', max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='cymed_mrff_ambient_scribe.scribesession')),
            ],
            options={
                'db_table': 'cymed_mrff_ambient_scribe_transcript',
            },
        ),
    ]
