# Generated by Django 6.0.7 on 2026-07-22 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_ar_ap', '0002_partner_address_partner_approval_status_and_more'),
        ('cycom_procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bills', to='cycom_procurement.purchaseorder'),
        ),
    ]
