# Generated by Django 6.1.1 on 2026-09-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_ar_ap', '0003_invoice_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='einvoice_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='einvoice_hash',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='einvoice_icv',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='einvoice_mode',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='invoice',
            name='einvoice_pih',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='einvoice_qr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='einvoice_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='einvoice_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='invoice',
            name='einvoice_status',
            field=models.CharField(default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='invoice',
            name='einvoice_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
