# Generated by Django 6.1.1 on 2026-09-04 01:36

import platform.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_ar_ap', '0004_invoice_einvoice_cleared_at_invoice_einvoice_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='iban_bidx',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='iban',
            field=platform.common.fields.EncryptedText(blank=True, blind_index=True, classification='financial_id', editable=True),
        ),
    ]
