# Generated by Django 6.0.7 on 2026-09-08 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_ar_ap', '0009_invoice_attributes_invoice_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='cycom_ar_ap.invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('customer', 'Customer Invoice'), ('vendor', 'Vendor Bill'), ('customer_credit_note', 'Customer Credit Note'), ('vendor_credit_note', 'Vendor Debit Note')], max_length=24),
        ),
    ]
