# Generated by Django 6.1.1 on 2026-09-04 03:09

import platform.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_hospital_adt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargesummary',
            name='instructions',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='summary_text',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='transferapproval',
            name='notes',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='reason',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
    ]
