# Generated by Django 6.0.6 on 2026-06-23 04:51

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("img_dicom", "0001_initial"),
        ("img_orders", "0001_initial"),
        ("img_reporting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "queue_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("subspecialty", "Subspecialty"),
                            ("urgent", "Urgent"),
                            ("night_hawk", "Night Hawk"),
                            ("second_opinion", "Second Opinion"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                ("subspecialty", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("max_turnaround_hours", models.PositiveIntegerField(default=24)),
                ("site_code", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "db_table": "cymed_img_reading_queues",
            },
        ),
        migrations.CreateModel(
            name="SecondOpinion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("requested_by", models.UUIDField()),
                ("second_opinion_radiologist_id", models.UUIDField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("clinical_question", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("opinion_text", models.TextField(blank=True)),
                ("concurs_with_original", models.BooleanField(null=True)),
                (
                    "discrepancy_level",
                    models.CharField(
                        blank=True,
                        choices=[("none", "None"), ("minor", "Minor"), ("major", "Major")],
                        max_length=20,
                    ),
                ),
                (
                    "original_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="img_reporting.radiologyreport",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_img_second_opinions",
            },
        ),
        migrations.CreateModel(
            name="TeleradiologyCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Read"),
                            ("second_opinion", "Second Opinion"),
                            ("consultation", "Consultation"),
                            ("urgent", "Urgent Read"),
                        ],
                        default="primary",
                        max_length=30,
                    ),
                ),
                ("originating_facility", models.CharField(blank=True, max_length=255)),
                ("originating_site_code", models.CharField(blank=True, max_length=50)),
                ("target_turnaround_hours", models.PositiveIntegerField(default=24)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("routine", "Routine"),
                            ("urgent", "Urgent"),
                            ("stat", "STAT"),
                            ("critical", "Critical"),
                        ],
                        default="routine",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("clinical_context", models.TextField(blank=True)),
                ("patient_history", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="img_orders.imagingorderitem",
                    ),
                ),
                (
                    "reading_queue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="img_teleradiology.readingqueue",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="img_dicom.dicomstudy",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_img_teleradiology_cases",
            },
        ),
        migrations.CreateModel(
            name="ReadingAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("radiologist_id", models.UUIDField()),
                ("subspecialty", models.CharField(blank=True, max_length=100)),
                ("assigned_by", models.UUIDField()),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("turnaround_minutes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "teleradiology_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="img_teleradiology.teleradiologycase",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_img_reading_assignments",
            },
        ),
    ]
