# Generated by Django 5.1.15 on 2026-06-22 20:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_encounters', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('consulted_at', models.DateTimeField(auto_now_add=True)),
                ('consulted_by', models.CharField(max_length=255)),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_consultations', to='cymed_encounters.encounter')),
            ],
            options={
                'db_table': 'cymed_clinic_consultations',
            },
        ),
        migrations.CreateModel(
            name='ConsultationAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('file_url', models.URLField(max_length=500)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cymed_clinic_consultations.consultation')),
            ],
            options={
                'db_table': 'cymed_clinic_consultation_attachments',
            },
        ),
        migrations.CreateModel(
            name='ConsultationDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(max_length=100)),
                ('system', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=255)),
                ('status', models.CharField(default='confirmed', max_length=50)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='cymed_clinic_consultations.consultation')),
            ],
            options={
                'db_table': 'cymed_clinic_consultation_diagnoses',
            },
        ),
        migrations.CreateModel(
            name='ConsultationFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('follow_up_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='cymed_clinic_consultations.consultation')),
            ],
            options={
                'db_table': 'cymed_clinic_consultation_follow_ups',
            },
        ),
        migrations.CreateModel(
            name='ConsultationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('instructions', models.TextField(blank=True)),
                ('prescriptions', models.JSONField(default=list)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plan', to='cymed_clinic_consultations.consultation')),
            ],
            options={
                'db_table': 'cymed_clinic_consultation_plans',
            },
        ),
        migrations.CreateModel(
            name='ConsultationProcedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(max_length=100)),
                ('system', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='cymed_clinic_consultations.consultation')),
            ],
            options={
                'db_table': 'cymed_clinic_consultation_procedures',
            },
        ),
    ]
