# Generated by Django 6.0.6 on 2026-07-14 22:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField(db_index=True)),
                ('store_id', models.UUIDField(blank=True, null=True)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('checked_out', 'Checked Out'), ('abandoned', 'Abandoned')], default='active', max_length=16)),
                ('order_id', models.UUIDField(blank=True, help_text='Set once checked out.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cymart_cart',
                'indexes': [models.Index(fields=['customer_id', 'status'], name='cymart_cart_custome_b5f66e_idx')],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField()),
                ('product_name_snapshot', models.CharField(blank=True, max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cymart_cart.cart')),
            ],
            options={
                'db_table': 'cymart_cart_item',
                'constraints': [models.UniqueConstraint(fields=('cart', 'product_id'), name='unique_product_per_cart')],
            },
        ),
    ]
