# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_profile_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('cart', 'Cart'), ('placed', 'Placed'), ('paid', 'Paid'), ('fulfilling', 'Fulfilling'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='cart', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('vat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('delivery_address', models.CharField(blank=True, max_length=400)),
                ('bill_id', models.UUIDField(blank=True, null=True)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cymed_clinic_orders',
            },
        ),
        migrations.CreateModel(
            name='ClinicProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(choices=[('supplement', 'Supplement'), ('skincare', 'Skincare'), ('wellness', 'Wellness package'), ('service', 'Service'), ('membership', 'Membership')], max_length=20)),
                ('sku', models.CharField(db_index=True, max_length=80)),
                ('name_en', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('stock_qty', models.IntegerField(default=0, help_text='Ignored for services/memberships')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'cymed_clinic_products',
                'unique_together': {('tenant_id', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='ClinicOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('qty', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cymed_clinic_ecommerce.clinicorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cymed_clinic_ecommerce.clinicproduct')),
            ],
            options={
                'db_table': 'cymed_clinic_order_items',
            },
        ),
    ]
