# Generated by Django 6.0.7 on 2026-09-24 22:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField(db_index=True, unique=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('age', models.PositiveSmallIntegerField()),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly active'), ('moderate', 'Moderately active'), ('active', 'Very active'), ('athlete', 'Extra active')], default='sedentary', max_length=12)),
                ('goal_type', models.CharField(choices=[('lose', 'Lose weight'), ('maintain', 'Maintain'), ('gain', 'Gain / build')], max_length=8)),
                ('target_weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weekly_pace_kg', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('strictness', models.CharField(choices=[('strict', 'Strict — block off-plan'), ('balanced', 'Balanced — warn, allow override'), ('coach', 'Coach — advise only')], default='balanced', max_length=8)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('medical_conditions', models.JSONField(blank=True, default=list)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('is_breastfeeding', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cymart_diet_profile',
            },
        ),
        migrations.CreateModel(
            name='DietRegime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_ar', models.CharField(blank=True, max_length=120)),
                ('description_en', models.CharField(blank=True, max_length=300)),
                ('block_ingredients', models.JSONField(blank=True, default=list)),
                ('max_item_carbs_g', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('is_hard', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cymart_diet_regime',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='NutritionFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(db_index=True, unique=True)),
                ('name_snapshot', models.CharField(blank=True, max_length=300)),
                ('serving_desc', models.CharField(blank=True, max_length=120)),
                ('calories', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('protein_g', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('carbs_g', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('fat_g', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('sodium_mg', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('sugar_g', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('diet_tags', models.JSONField(blank=True, default=list)),
                ('contains_allergens', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('merchant', 'Merchant-entered'), ('estimated', 'AI-estimated'), ('verified', 'Lab / verified')], default='merchant', max_length=10)),
                ('confidence', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cymart_nutrition_fact',
            },
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bmr', models.PositiveIntegerField()),
                ('tdee', models.PositiveIntegerField()),
                ('daily_calories', models.PositiveIntegerField()),
                ('min_daily_calories', models.PositiveIntegerField()),
                ('protein_g', models.PositiveIntegerField()),
                ('carbs_g', models.PositiveIntegerField()),
                ('fat_g', models.PositiveIntegerField()),
                ('per_meal', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('review_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='cymart_dietshield.dietprofile')),
            ],
            options={
                'db_table': 'cymart_diet_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dietprofile',
            name='regimes',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='cymart_dietshield.dietregime'),
        ),
        migrations.CreateModel(
            name='DietDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('consumed_calories', models.DecimalField(decimal_places=1, default=0, max_digits=9)),
                ('consumed_protein_g', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('consumed_carbs_g', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('consumed_fat_g', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('off_plan_overrides', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='cymart_dietshield.dietprofile')),
            ],
            options={
                'db_table': 'cymart_diet_day',
                'constraints': [models.UniqueConstraint(fields=('profile', 'date'), name='unique_profile_day')],
            },
        ),
    ]
