# Generated by Django 6.1.1 on 2026-09-04 03:04

import platform.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_hospital_anesthesia', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anesthesiaassessment',
            name='notes',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='anesthesiaplan',
            name='plan_description',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='anesthesiarecord',
            name='notes',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='recoveryassessment',
            name='comments',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
    ]
