# Generated by Django 6.1.1 on 2026-09-04 07:20

import platform.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_hospital_anesthesia', '0004_encrypt_anesthesia_narrative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anesthesiarecord',
            name='agents_used',
            field=platform.common.fields.EncryptedJSON(blank=True, classification='phi', default=list, editable=True),
        ),
    ]
