# Generated by Django 5.1.15 on 2026-06-23 00:21

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cymed_hospital_inpatient", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ICUStay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("icu_admitted_at", models.DateTimeField(auto_now_add=True)),
                ("icu_released_at", models.DateTimeField(blank=True, null=True)),
                ("ventilator_status", models.CharField(default="none", max_length=50)),
                ("invasive_lines_count", models.PositiveIntegerField(default=0)),
                (
                    "stay",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="icu_details",
                        to="cymed_hospital_inpatient.hospitalstay",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_icu_stays",
            },
        ),
        migrations.CreateModel(
            name="ICURound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("recorded_by", models.UUIDField()),
                ("heart_rate", models.PositiveIntegerField()),
                ("mean_arterial_pressure", models.PositiveIntegerField()),
                ("temp_c", models.DecimalField(decimal_places=2, max_digits=4)),
                ("resp_rate", models.PositiveIntegerField()),
                ("o2_sat", models.PositiveIntegerField()),
                (
                    "icu_stay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="cymed_hospital_icu.icustay",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_icu_rounds",
            },
        ),
        migrations.CreateModel(
            name="ICUAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("assessed_at", models.DateTimeField(auto_now_add=True)),
                ("sofa_score", models.PositiveIntegerField()),
                ("apache_ii_score", models.PositiveIntegerField()),
                ("glasgow_coma_scale", models.PositiveIntegerField()),
                (
                    "icu_stay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cymed_hospital_icu.icustay"
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_icu_assessments",
            },
        ),
        migrations.CreateModel(
            name="CriticalEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("event_time", models.DateTimeField(auto_now_add=True)),
                ("event_type", models.CharField(max_length=100)),
                ("details", models.TextField()),
                ("actions_taken", models.TextField()),
                (
                    "icu_stay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cymed_hospital_icu.icustay"
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_icu_critical_events",
            },
        ),
        migrations.CreateModel(
            name="VentilatorRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                ("logged_by", models.UUIDField()),
                ("mode", models.CharField(max_length=100)),
                ("fio2_pct", models.PositiveIntegerField()),
                ("peep", models.PositiveIntegerField()),
                ("rate", models.PositiveIntegerField()),
                (
                    "icu_stay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cymed_hospital_icu.icustay"
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_icu_ventilators",
            },
        ),
    ]
