# Generated by Django 6.0.7 on 2026-07-15 12:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuardrailPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('policy_type', models.CharField(max_length=50)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'platform_ai_guardrail_policies',
            },
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=200)),
                ('api_key_ref', models.CharField(blank=True, max_length=255)),
                ('api_base_url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.7, max_digits=3)),
            ],
            options={
                'db_table': 'platform_ai_model_configs',
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('template_text', models.TextField()),
                ('variables', models.JSONField(default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'platform_ai_prompt_templates',
            },
        ),
        migrations.CreateModel(
            name='InferenceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('prompt_used', models.TextField()),
                ('response_text', models.TextField(blank=True)),
                ('tokens_prompt', models.PositiveIntegerField(default=0)),
                ('tokens_completion', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('safety_verdict', models.CharField(db_index=True, default='passed', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cyai.modelconfig')),
            ],
            options={
                'db_table': 'platform_ai_inference_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
