# Generated by Django 6.0.6 on 2026-06-23 04:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('analyzer_type', models.CharField(choices=[('chemistry', 'Chemistry Analyzer'), ('hematology', 'Hematology Analyzer'), ('immunology', 'Immunology/Immunoassay Analyzer'), ('microbiology', 'Microbiology MALDI-TOF'), ('coagulation', 'Coagulation Analyzer'), ('urinalysis', 'Urinalysis Analyzer'), ('molecular', 'Molecular PCR Analyzer'), ('point_of_care', 'Point-of-Care Device'), ('blood_gas', 'Blood Gas Analyzer'), ('flow_cytometry', 'Flow Cytometry')], max_length=30)),
                ('department', models.CharField(choices=[('chemistry', 'Chemistry'), ('hematology', 'Hematology'), ('immunology', 'Immunology'), ('serology', 'Serology'), ('microbiology', 'Microbiology'), ('pathology', 'Pathology'), ('histopathology', 'Histopathology'), ('molecular', 'Molecular Diagnostics'), ('blood_bank', 'Blood Bank'), ('urinalysis', 'Urinalysis')], max_length=30)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('integration_hub_channel', models.CharField(blank=True, max_length=100)),
                ('protocol', models.CharField(blank=True, choices=[('astm', 'ASTM 1394/1381'), ('hl7', 'HL7 v2.x'), ('lis_interface', 'Vendor LIS Interface'), ('serial', 'Serial RS-232'), ('fhir', 'FHIR R4')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('last_calibrated_at', models.DateTimeField(blank=True, null=True)),
                ('last_qc_at', models.DateTimeField(blank=True, null=True)),
                ('asset_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'cymed_lab_analyzers',
            },
        ),
        migrations.CreateModel(
            name='AnalyzerMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('direction', models.CharField(choices=[('inbound', 'From Analyzer'), ('outbound', 'To Analyzer')], max_length=10)),
                ('message_type', models.CharField(blank=True, max_length=20)),
                ('raw_message', models.TextField()),
                ('parsed_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('analyzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='lab_worklists.analyzer')),
            ],
            options={
                'db_table': 'cymed_lab_analyzer_messages',
            },
        ),
        migrations.CreateModel(
            name='AnalyzerResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('instrument_test_code', models.CharField(max_length=100)),
                ('instrument_sample_id', models.CharField(blank=True, max_length=100)),
                ('accession_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('value_raw', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('flags', models.CharField(blank=True, max_length=20)),
                ('instrument_range_low', models.CharField(blank=True, max_length=50)),
                ('instrument_range_high', models.CharField(blank=True, max_length=50)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lab_result_linked', models.BooleanField(default=False)),
                ('analyzer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_results', to='lab_worklists.analyzer')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzer_results', to='lab_worklists.analyzermessage')),
            ],
            options={
                'db_table': 'cymed_lab_analyzer_results',
            },
        ),
        migrations.CreateModel(
            name='LabWorklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('chemistry', 'Chemistry'), ('hematology', 'Hematology'), ('immunology', 'Immunology'), ('serology', 'Serology'), ('microbiology', 'Microbiology'), ('pathology', 'Pathology'), ('histopathology', 'Histopathology'), ('molecular', 'Molecular Diagnostics'), ('blood_bank', 'Blood Bank'), ('urinalysis', 'Urinalysis')], max_length=30)),
                ('worklist_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('priority_mode', models.CharField(choices=[('fifo', 'First In First Out'), ('priority_first', 'Priority First (STAT/Urgent)'), ('timed', 'Timed Collection'), ('analyzer_batch', 'Analyzer Batch')], default='priority_first', max_length=20)),
                ('created_by', models.UUIDField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('analyzer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worklists', to='lab_worklists.analyzer')),
            ],
            options={
                'db_table': 'cymed_lab_worklists',
            },
        ),
        migrations.CreateModel(
            name='TechnologistAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('technologist_id', models.UUIDField()),
                ('assigned_by', models.UUIDField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('active', 'Active'), ('completed', 'Completed'), ('reassigned', 'Reassigned')], default='assigned', max_length=20)),
                ('items_target', models.PositiveIntegerField(default=0)),
                ('items_completed', models.PositiveIntegerField(default=0)),
                ('worklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologist_assignments', to='lab_worklists.labworklist')),
            ],
            options={
                'db_table': 'cymed_lab_technologist_assignments',
            },
        ),
        migrations.CreateModel(
            name='WorklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resulted', 'Resulted'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('technologist_id', models.UUIDField(blank=True, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklist_items', to='lab_orders.laborderitem')),
                ('worklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lab_worklists.labworklist')),
            ],
            options={
                'db_table': 'cymed_lab_worklist_items',
                'ordering': ['worklist', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='WorklistQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('queue_depth', models.PositiveIntegerField(default=0)),
                ('estimated_completion_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('analyzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_records', to='lab_worklists.analyzer')),
                ('worklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='lab_worklists.labworklist')),
            ],
            options={
                'db_table': 'cymed_lab_worklist_queues',
            },
        ),
        migrations.CreateModel(
            name='AnalyzerInterface',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('instrument_test_code', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=True)),
                ('priority_order', models.PositiveSmallIntegerField(default=0)),
                ('analyzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='lab_worklists.analyzer')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzer_interfaces', to='lab_orders.labtest')),
            ],
            options={
                'db_table': 'cymed_lab_analyzer_interfaces',
                'unique_together': {('analyzer', 'test')},
            },
        ),
        migrations.AddIndex(
            model_name='analyzermessage',
            index=models.Index(fields=['analyzer', 'status', 'received_at'], name='cymed_lab_a_analyze_8c26d4_idx'),
        ),
        migrations.AddIndex(
            model_name='labworklist',
            index=models.Index(fields=['tenant_id', 'department', 'worklist_date'], name='cymed_lab_w_tenant__8662ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='worklistitem',
            unique_together={('worklist', 'order_item')},
        ),
        migrations.AlterUniqueTogether(
            name='worklistqueue',
            unique_together={('worklist', 'analyzer')},
        ),
    ]
