# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutbreakModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('pathogen', models.CharField(max_length=64)),
                ('region_kind', models.CharField(choices=[('city', 'City'), ('governorate', 'Governorate'), ('country', 'Country'), ('cross_border', 'Cross-border')], max_length=32)),
                ('region_code', models.CharField(blank=True, max_length=32)),
                ('model_kind', models.CharField(choices=[('sir', 'SIR'), ('seir', 'SEIR'), ('seird', 'SEIRD'), ('abm', 'Agent-based'), ('statistical', 'Statistical')], default='seir', max_length=32)),
                ('parameters', models.JSONField(default=dict)),
                ('projection_start', models.DateField()),
                ('projection_end', models.DateField()),
                ('peaked_at', models.DateField(blank=True, null=True)),
                ('total_infected_projection', models.IntegerField(default=0)),
                ('total_deceased_projection', models.IntegerField(default=0)),
                ('ran_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'cymed_mrff_population_health_outbreakmodel',
            },
        ),
        migrations.CreateModel(
            name='PopulationCohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('inclusion_criteria', models.JSONField(default=dict)),
                ('exclusion_criteria', models.JSONField(default=dict)),
                ('size', models.IntegerField(default=0)),
                ('refreshed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'cymed_mrff_population_health_populationcohort',
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PopulationMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('metric_kind', models.CharField(choices=[('prevalence', 'Prevalence'), ('incidence', 'Incidence'), ('mortality', 'Mortality'), ('readmission', 'Readmission'), ('hba1c_control', 'HbA1c Control'), ('bp_control', 'BP Control'), ('vaccination_uptake', 'Vaccination Uptake'), ('medication_adherence', 'Medication Adherence'), ('cost_pmpm', 'Cost PMPM')], max_length=32)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('denominator', models.IntegerField(default=0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('breakdowns', models.JSONField(default=dict)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='cymed_mrff_population_health.populationcohort')),
            ],
            options={
                'db_table': 'cymed_mrff_population_health_populationmetric',
            },
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('chronic_disease', 'Chronic Disease'), ('cancer', 'Cancer'), ('cardiac', 'Cardiac'), ('diabetes', 'Diabetes'), ('rare_disease', 'Rare Disease'), ('infectious', 'Infectious'), ('immunisation', 'Immunisation'), ('maternal_child', 'Maternal & Child'), ('mental_health', 'Mental Health'), ('trauma', 'Trauma'), ('renal', 'Renal')], max_length=32)),
                ('icd_codes', models.JSONField(default=list)),
                ('inclusion_rules', models.JSONField(default=dict)),
                ('stewards', models.JSONField(default=list)),
                ('consent_required', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_mrff_population_health_registry',
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TreatmentComparator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('condition_code', models.CharField(max_length=32)),
                ('arm_a', models.CharField(max_length=255)),
                ('arm_b', models.CharField(max_length=255)),
                ('primary_endpoint', models.CharField(blank=True, max_length=255)),
                ('arm_a_outcome_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('arm_b_outcome_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('relative_effect', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('ci_low', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('ci_high', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('p_value', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('method', models.CharField(choices=[('propensity_matched', 'Propensity Matched'), ('regression_adjusted', 'Regression Adjusted'), ('instrumental_var', 'Instrumental Variable'), ('rct', 'Randomised Controlled Trial'), ('synthetic_control', 'Synthetic Control')], default='propensity_matched', max_length=32)),
                ('ran_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cohort_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cymed_mrff_population_health.populationcohort')),
                ('cohort_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cymed_mrff_population_health.populationcohort')),
            ],
            options={
                'db_table': 'cymed_mrff_population_health_treatmentcomparator',
            },
        ),
        migrations.CreateModel(
            name='RegistryCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_pseudonym', models.CharField(db_index=True, max_length=64)),
                ('patient_profile_id', models.UUIDField(blank=True, null=True)),
                ('diagnosis_code', models.CharField(blank=True, max_length=32)),
                ('diagnosed_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('enrolled', 'Enrolled'), ('active', 'Active'), ('remission', 'Remission'), ('lost_to_followup', 'Lost to Follow-up'), ('deceased', 'Deceased'), ('withdrawn', 'Withdrawn')], default='candidate', max_length=32)),
                ('enrollment_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stage_or_grade', models.CharField(blank=True, max_length=64)),
                ('comorbidities', models.JSONField(default=list)),
                ('treatments', models.JSONField(default=list)),
                ('last_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cymed_mrff_population_health.registry')),
            ],
            options={
                'db_table': 'cymed_mrff_population_health_registrycase',
                'unique_together': {('registry', 'patient_pseudonym')},
            },
        ),
    ]
