# Generated by Django 5.1.15 on 2026-06-23 00:21

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cymed_facilities", "__first__"),
        ("cymed_patients", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="BedAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cymed_facilities.bed"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cymed_patients.patient"
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_bed_assignments",
            },
        ),
        migrations.CreateModel(
            name="BedBlocking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("reason", models.CharField(max_length=255)),
                ("blocked_at", models.DateTimeField(auto_now_add=True)),
                ("unblocked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cymed_facilities.bed"
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_bed_blocking",
            },
        ),
        migrations.CreateModel(
            name="BedCleaning",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("cleaning", "Cleaning"),
                            ("completed", "Completed"),
                        ],
                        default="scheduled",
                        max_length=50,
                    ),
                ),
                ("cleaner_name", models.CharField(blank=True, max_length=255)),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cymed_facilities.bed"
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_bed_cleaning",
            },
        ),
        migrations.CreateModel(
            name="BedMaintenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("description", models.TextField()),
                ("scheduled_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cymed_facilities.bed"
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_bed_maintenance",
            },
        ),
        migrations.CreateModel(
            name="BedOccupancy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("occupied_date", models.DateField()),
                ("occupancy_status", models.CharField(default="occupied", max_length=50)),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cymed_facilities.bed"
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_bed_occupancy",
            },
        ),
        migrations.CreateModel(
            name="BedReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("reserved_from", models.DateTimeField()),
                ("reserved_to", models.DateTimeField()),
                ("status", models.CharField(default="pending", max_length=50)),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cymed_facilities.bed"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cymed_patients.patient"
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_bed_reservations",
            },
        ),
    ]
