# Generated by Django 6.0.7 on 2026-08-09 18:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyed_gradebook', '0001_initial'),
        ('cyed_lms', '0001_initial'),
        ('cyed_sis', '0002_classsection_campus_student_campus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('text', models.TextField()),
                ('kind', models.CharField(choices=[('multiple_choice', 'Multiple Choice (one correct)'), ('multi_select', 'Multi-Select (several correct)'), ('true_false', 'True / False'), ('short_answer', 'Short Answer'), ('essay', 'Extended Response (human-marked)')], default='multiple_choice', max_length=20)),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=6)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('accepted_answers', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'cyed_quiz_questions',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=7)),
                ('allow_late', models.BooleanField(default=False)),
                ('curriculum_code', models.CharField(blank=True, max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(blank=True, help_text='Link to the gradebook mark record. When set, grading a submission writes a Grade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='cyed_gradebook.assessment')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cyed_sis.classsection')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='cyed_lms.lesson')),
            ],
            options={
                'db_table': 'cyed_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='cyed_assessment.question')),
            ],
            options={
                'db_table': 'cyed_quiz_choices',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('time_limit_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Null means untimed.', null=True)),
                ('max_attempts', models.PositiveSmallIntegerField(default=1)),
                ('is_published', models.BooleanField(default=False)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('curriculum_code', models.CharField(blank=True, max_length=50)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='cyed_sis.classsection')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='cyed_lms.lesson')),
            ],
            options={
                'db_table': 'cyed_quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cyed_assessment.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('is_graded', models.BooleanField(default=False)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='cyed_assessment.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_quiz_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('text_answer', models.TextField(blank=True)),
                ('awarded_points', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='answers', to='cyed_assessment.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cyed_assessment.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cyed_assessment.quizattempt')),
            ],
            options={
                'db_table': 'cyed_quiz_answers',
                'ordering': ['question__sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('text_response', models.TextField(blank=True)),
                ('file_bytes', models.BinaryField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('late', 'Submitted Late'), ('graded', 'Graded'), ('returned', 'Returned to Student')], default='draft', max_length=20)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_by', models.CharField(blank=True, max_length=255)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='cyed_assessment.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_assignment_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['tenant_id', 'class_section'], name='idx_assignment_tenant_sec'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['tenant_id', 'class_section'], name='idx_quiz_tenant_sec'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['tenant_id', 'quiz'], name='idx_attempt_tenant_quiz'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'quiz', 'student', 'attempt_number'), name='uniq_attempt_per_student_quiz'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'attempt', 'question'), name='uniq_answer_per_attempt_question'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['tenant_id', 'assignment'], name='idx_submission_tenant_asgn'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'assignment', 'student', 'attempt_number'), name='uniq_submission_per_student_attempt'),
        ),
    ]
