# Generated by Django 6.0.6 on 2026-06-23 04:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('img_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PACSNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('ae_title', models.CharField(max_length=16)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=11112)),
                ('protocol', models.CharField(choices=[('dicom', 'DICOM'), ('dicomweb', 'DICOMweb'), ('wado', 'WADO-RS')], default='dicom', max_length=20)),
                ('wado_rs_url', models.CharField(blank=True, max_length=500)),
                ('qido_rs_url', models.CharField(blank=True, max_length=500)),
                ('stow_rs_url', models.CharField(blank=True, max_length=500)),
                ('wado_uri_url', models.CharField(blank=True, max_length=500)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('tls_enabled', models.BooleanField(default=False)),
                ('connection_verified_at', models.DateTimeField(blank=True, null=True)),
                ('api_key_reference', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'cymed_img_pacs_nodes',
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PACSEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('event_type', models.CharField(choices=[('study_received', 'Study Received'), ('study_stored', 'Study Stored'), ('study_deleted', 'Study Deleted'), ('connection_lost', 'Connection Lost'), ('connection_restored', 'Connection Restored'), ('worklist_queried', 'Worklist Queried')], max_length=50)),
                ('study_instance_uid', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(default=dict)),
                ('acknowledged', models.BooleanField(default=False)),
                ('pacs_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='img_pacs.pacsnode')),
            ],
            options={
                'db_table': 'cymed_img_pacs_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PACSQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('query_type', models.CharField(choices=[('find', 'C-FIND'), ('move', 'C-MOVE'), ('get', 'C-GET'), ('qido', 'QIDO-RS'), ('wado', 'WADO-RS')], default='find', max_length=20)),
                ('query_level', models.CharField(choices=[('patient', 'Patient'), ('study', 'Study'), ('series', 'Series'), ('image', 'Image')], default='study', max_length=20)),
                ('query_params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('response_payload', models.JSONField(default=list)),
                ('error_message', models.TextField(blank=True)),
                ('pacs_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='img_pacs.pacsnode')),
            ],
            options={
                'db_table': 'cymed_img_pacs_queries',
            },
        ),
        migrations.CreateModel(
            name='StudyRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('route_type', models.CharField(choices=[('store', 'Store'), ('retrieve', 'Retrieve'), ('forward', 'Forward')], default='store', max_length=20)),
                ('study_instance_uid', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bytes_transferred', models.PositiveBigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('destination_pacs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_routes', to='img_pacs.pacsnode')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='img_orders.imagingorderitem')),
                ('source_pacs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_routes', to='img_pacs.pacsnode')),
            ],
            options={
                'db_table': 'cymed_img_study_routes',
            },
        ),
    ]
