# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.IntegerField(default=1)),
                ('booked_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='open', max_length=32)),
            ],
            options={
                'db_table': 'cymed_img_patient_booking_imaging_slot',
            },
        ),
        migrations.CreateModel(
            name='BookableStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('modality', models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT'), ('mri', 'MRI'), ('us', 'Ultrasound'), ('mammo', 'Mammography'), ('fluoro', 'Fluoroscopy'), ('nucmed', 'Nuclear Medicine'), ('pet', 'PET'), ('dexa', 'DEXA'), ('dental', 'Dental')], max_length=32)),
                ('body_part', models.CharField(blank=True, max_length=64)),
                ('contrast_required', models.BooleanField(default=False)),
                ('duration_minutes', models.IntegerField(default=15)),
                ('preparation_instructions', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=5)),
                ('requires_referral', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'cymed_img_patient_booking_bookable_study',
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ImagingBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('patient_profile_id', models.UUIDField(db_index=True)),
                ('referral_url', models.URLField(blank=True)),
                ('referring_provider_id', models.UUIDField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=32)),
                ('payment_ref', models.CharField(blank=True, max_length=128)),
                ('bill_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('placed', 'Placed'), ('paid', 'Paid'), ('scheduled', 'Scheduled'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='draft', max_length=32)),
                ('booking_ref', models.CharField(blank=True, max_length=64)),
                ('preparation_confirmed', models.BooleanField(default=False)),
                ('fasting_confirmed', models.BooleanField(default=False)),
                ('consent_signed_at', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='cymed_img_patient_booking.bookablestudy')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='cymed_img_patient_booking.imagingslot')),
            ],
            options={
                'db_table': 'cymed_img_patient_booking_imaging_booking',
            },
        ),
        migrations.CreateModel(
            name='ModalityRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('facility_id', models.UUIDField(blank=True, null=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('modality', models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT'), ('mri', 'MRI'), ('us', 'Ultrasound'), ('mammo', 'Mammography'), ('fluoro', 'Fluoroscopy'), ('nucmed', 'Nuclear Medicine'), ('pet', 'PET'), ('dexa', 'DEXA'), ('dental', 'Dental')], max_length=32)),
                ('manufacturer', models.CharField(blank=True, max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('ae_title', models.CharField(blank=True, max_length=32)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_img_patient_booking_modality_room',
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.AddField(
            model_name='imagingslot',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='cymed_img_patient_booking.modalityroom'),
        ),
    ]
