# Generated by Django 6.0.7 on 2026-07-19 18:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycom_accounting', '0001_initial'),
        ('cycom_inventory', '0002_internalorder_internalorderline'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, help_text='How many units of `product` this BoM produces per run.', max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='cycom_inventory.product')),
            ],
            options={
                'db_table': 'cycom_manufacturing_boms',
                'ordering': ['product__sku', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BOMComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantity of `component` needed per one BoM run (see BillOfMaterial.quantity).', max_digits=14)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='cycom_manufacturing.billofmaterial')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_boms', to='cycom_inventory.product')),
            ],
            options={
                'db_table': 'cycom_manufacturing_bom_components',
            },
        ),
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cycom_manufacturing.billofmaterial')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_orders', to='cycom_inventory.warehouse')),
                ('wip_account', models.ForeignKey(help_text='Work-in-progress clearing account — debited on component consumption, credited on finished-goods receipt.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cycom_accounting.account')),
            ],
            options={
                'db_table': 'cycom_manufacturing_orders',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
