# Generated by Django 6.0.7 on 2026-09-21 20:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_catalog', '0005_product_controlled_substance_product_core_charge_and_more'),
        ('cycom_manufacturing', '0003_product_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routings', to='cycom_catalog.product')),
            ],
            options={
                'db_table': 'cycom_manufacturing_routings',
                'ordering': ['product__internal_ref', 'name'],
            },
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='routing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturing_orders', to='cycom_manufacturing.routing'),
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('capacity_per_day_hours', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('cost_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cycom_manufacturing_work_centers',
                'ordering': ['code'],
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='RoutingOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('sequence', models.PositiveIntegerField(default=10)),
                ('name', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Minutes to run this operation for one full BoM batch.')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='cycom_manufacturing.routing')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routing_operations', to='cycom_manufacturing.workcenter')),
            ],
            options={
                'db_table': 'cycom_manufacturing_routing_operations',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('sequence', models.PositiveIntegerField()),
                ('planned_duration_minutes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('manufacturing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='cycom_manufacturing.manufacturingorder')),
                ('routing_operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='cycom_manufacturing.routingoperation')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='cycom_manufacturing.workcenter')),
            ],
            options={
                'db_table': 'cycom_manufacturing_work_orders',
                'ordering': ['manufacturing_order', 'sequence'],
            },
        ),
    ]
