# Generated by Django 6.0.7 on 2026-09-21 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_company', '0001_initial'),
        ('cycom_manufacturing', '0004_routing_manufacturingorder_routing_workcenter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturing_orders', to='cycom_company.company'),
        ),
    ]
