# Generated by Django 6.0.7 on 2026-07-17 00:52

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDevRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('product_description', models.TextField()),
                ('requested_by', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('studying', 'Studying Existing Functionality'), ('requirements_gathering', 'Gathering Requirements'), ('requirements_confirmed', 'Requirements Confirmed'), ('technical_design', 'Technical Design Drafted'), ('design_approved', 'Design Approved'), ('generating', 'Generating Code'), ('code_generated', 'Code Generated — Isolated Workspace'), ('testing', 'Running Lint/Build/Tests'), ('diff_ready', 'Diff Ready For Review'), ('staging_deployed', 'Deployed To Staging'), ('uat', 'User Acceptance Testing'), ('production_approved', 'Production Deployment Approved'), ('deployed', 'Deployed To Production'), ('rejected', 'Rejected'), ('rolled_back', 'Rolled Back')], default='studying', max_length=30)),
                ('discovery_results', models.JSONField(blank=True, default=list)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('functional_spec', models.TextField(blank=True)),
                ('functional_spec_confirmed_by', models.CharField(blank=True, max_length=255)),
                ('functional_spec_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('technical_design', models.TextField(blank=True)),
                ('technical_design_approved_by', models.CharField(blank=True, max_length=255)),
                ('technical_design_approved_at', models.DateTimeField(blank=True, null=True)),
                ('module_name', models.CharField(blank=True, max_length=100)),
                ('workspace_path', models.CharField(blank=True, max_length=500)),
                ('generated_files', models.JSONField(blank=True, default=list)),
                ('lint_results', models.JSONField(blank=True, null=True)),
                ('build_results', models.JSONField(blank=True, null=True)),
                ('test_results', models.JSONField(blank=True, null=True)),
                ('diff_text', models.TextField(blank=True)),
                ('staging_deployed_at', models.DateTimeField(blank=True, null=True)),
                ('production_approved_by', models.CharField(blank=True, max_length=255)),
                ('production_approved_at', models.DateTimeField(blank=True, null=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('deploy_commit_sha', models.CharField(blank=True, max_length=100)),
                ('rollback_manifest', models.JSONField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cycom_cyai_moduledev_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
