# Generated by Django 6.0.6 on 2026-06-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxclass',
            name='rate',
            field=models.DecimalField(decimal_places=4, default='0.0000', max_digits=5),
        ),
    ]
