# Generated by Django 6.0.6 on 2026-07-14 00:12

import apps.tenants.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_taxclass_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KitComponent',
            fields=[
                ('id', models.UUIDField(default=apps.tenants.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('quantity_per_unit', models.DecimalField(decimal_places=4, default='1.0000', max_digits=15)),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_kits', to='catalog.product')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_components', to='catalog.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['component_product__name'],
                'unique_together': {('product', 'component_product')},
            },
        ),
    ]
