# Generated by Django 6.1.1 on 2026-09-04 02:22

import platform.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cymed_patients', '0003_encrypt_patient_identifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientaddress',
            name='line1',
            field=platform.common.fields.EncryptedText(blank=True, classification='pii', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='patientaddress',
            name='line2',
            field=platform.common.fields.EncryptedText(blank=True, classification='pii', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='patientaddress',
            name='postal_code',
            field=platform.common.fields.EncryptedText(blank=True, classification='pii', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='patientcontact',
            name='telecom_value',
            field=platform.common.fields.EncryptedText(blank=True, classification='pii', default=b'', editable=True),
        ),
    ]
