# Generated by Django 6.1 on 2026-08-12 12:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyed_gradebook', '0001_initial'),
        ('cyed_hr', '0004_staffleave_balance_override_by_and_more'),
        ('cyed_org', '0002_remove_campus_uniq_campus_code_per_group_and_more'),
        ('cyed_sis', '0006_student_exit_date_student_exit_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('capacity', models.PositiveSmallIntegerField(default=30)),
                ('rows', models.PositiveSmallIntegerField(default=5)),
                ('columns', models.PositiveSmallIntegerField(default=6)),
                ('is_accessible', models.BooleanField(default=False, help_text='Step-free and suitable for access arrangements.')),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_rooms', to='cyed_org.campus')),
            ],
            options={
                'db_table': 'cyed_exam_rooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExamSitting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('year_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('seated', 'Seating allocated'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('materials_permitted', models.CharField(blank=True, max_length=255)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_sittings', to='cyed_sis.academicyear')),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_sittings', to='cyed_gradebook.assessment')),
            ],
            options={
                'db_table': 'cyed_exam_sittings',
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamRoomAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilations', to='cyed_hr.staff')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='cyed_exams.examroom')),
                ('sitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_allocations', to='cyed_exams.examsitting')),
            ],
            options={
                'db_table': 'cyed_exam_room_allocations',
                'ordering': ['room__name'],
                'constraints': [models.UniqueConstraint(fields=('sitting', 'room'), name='uniq_room_per_sitting')],
            },
        ),
        migrations.CreateModel(
            name='ExamCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('seat_label', models.CharField(blank=True, max_length=10)),
                ('access_arrangement', models.CharField(blank=True, choices=[('', 'None'), ('extra_time', 'Extra time'), ('separate_room', 'Separate room'), ('reader', 'Reader'), ('scribe', 'Scribe'), ('rest_breaks', 'Rest breaks'), ('other', 'Other')], default='', max_length=30)),
                ('extra_time_minutes', models.PositiveSmallIntegerField(default=0)),
                ('attendance', models.CharField(choices=[('expected', 'Expected'), ('present', 'Present'), ('absent', 'Absent'), ('withdrawn', 'Withdrawn from exam')], default='expected', max_length=20)),
                ('ticket_number', models.CharField(blank=True, max_length=40)),
                ('ticket_issued_on', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_candidacies', to='cyed_sis.student')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='cyed_exams.examroom')),
                ('sitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='cyed_exams.examsitting')),
            ],
            options={
                'db_table': 'cyed_exam_candidates',
                'ordering': ['room__name', 'seat_label'],
                'constraints': [models.UniqueConstraint(fields=('sitting', 'student'), name='uniq_candidate_per_sitting'), models.UniqueConstraint(condition=models.Q(('seat_label__gt', '')), fields=('sitting', 'room', 'seat_label'), name='uniq_seat_per_room_per_sitting')],
            },
        ),
    ]
