# Generated by Django 6.0.7 on 2026-08-05 11:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('capability', models.CharField(choices=[('tutor', 'Curriculum-Aligned Learning Assistant'), ('lesson_planner', 'Lesson Plan Generator'), ('rubric', 'Rubric Generator'), ('differentiator', 'Differentiated Task Generator'), ('integrity', 'Academic Integrity / Authenticity'), ('adaptive', 'Adaptive / Special-Needs Support')], default='tutor', max_length=30)),
                ('model_name', models.CharField(default='claude-sonnet-5', max_length=100)),
                ('grounding', models.CharField(blank=True, default='ACARA', max_length=100)),
                ('no_train', models.BooleanField(default=True)),
                ('human_in_the_loop', models.BooleanField(default=True)),
                ('data_residency', models.CharField(default='AU', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cyed_agent_definitions',
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'key'), name='uniq_agent_key_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='AgentInteractionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('actor', models.CharField(blank=True, max_length=255)),
                ('prompt_summary', models.CharField(blank=True, max_length=500)),
                ('curriculum_code', models.CharField(blank=True, max_length=50)),
                ('reviewed_by_human', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='cyed_ai_agents.agentdefinition')),
            ],
            options={
                'db_table': 'cyed_agent_interaction_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
