# Generated by Django 6.0.7 on 2026-08-05 16:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_ai_agents', '0001_initial'),
        ('cyed_sis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('artifact_type', models.CharField(choices=[('lesson_plan', 'Lesson Plan'), ('rubric', 'Rubric'), ('differentiated_task', 'Differentiated Task')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('year_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('curriculum_codes', models.CharField(blank=True, max_length=255)),
                ('content', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=20)),
                ('generated_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('review_note', models.TextField(blank=True)),
                ('llm_generated', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='cyed_ai_agents.agentdefinition')),
            ],
            options={
                'db_table': 'cyed_generated_artifacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrityReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('assessment_ref', models.CharField(blank=True, max_length=255)),
                ('draft_versions', models.PositiveSmallIntegerField(default=0)),
                ('edit_span_minutes', models.PositiveIntegerField(default=0)),
                ('paste_events', models.PositiveSmallIntegerField(default=0)),
                ('large_paste_events', models.PositiveSmallIntegerField(default=0)),
                ('disclosed_ai_use', models.BooleanField(default=False)),
                ('ai_disclosure_note', models.TextField(blank=True)),
                ('risk_band', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('signals', models.JSONField(default=dict)),
                ('decision', models.CharField(choices=[('pending', 'Pending Human Review'), ('cleared', 'Cleared'), ('concern', 'Concern Noted'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('decided_by', models.CharField(blank=True, max_length=255)),
                ('decision_note', models.TextField(blank=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrity_reviews', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_integrity_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
