# Generated by Django 5.1.15 on 2026-06-23 00:21

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cymed_patients", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaborEpisode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("admitted_at", models.DateTimeField(auto_now_add=True)),
                ("stage_of_labor", models.PositiveSmallIntegerField(default=1)),
                (
                    "cervical_dilation_cm",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                ("contractions_frequency_mins", models.PositiveIntegerField(blank=True, null=True)),
                ("fetal_monitoring_status", models.CharField(default="normal", max_length=100)),
            ],
            options={
                "db_table": "cymed_hospital_maternity_labor",
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("delivery_time", models.DateTimeField()),
                ("delivery_method", models.CharField(max_length=100)),
                ("apgar_1m", models.PositiveIntegerField()),
                ("apgar_5m", models.PositiveIntegerField()),
                ("outcome", models.CharField(default="live_birth", max_length=100)),
                (
                    "labor_episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="cymed_hospital_maternity.laborepisode",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_maternity_deliveries",
            },
        ),
        migrations.CreateModel(
            name="NewbornRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("gender", models.CharField(max_length=10)),
                ("weight_grams", models.PositiveIntegerField()),
                ("height_cm", models.DecimalField(decimal_places=1, max_digits=4)),
                ("head_circumference_cm", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "baby_patient",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cymed_patients.patient",
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newborns",
                        to="cymed_hospital_maternity.delivery",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_maternity_newborns",
            },
        ),
        migrations.CreateModel(
            name="Pregnancy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("estimated_delivery_date", models.DateField()),
                ("gravidity", models.PositiveIntegerField()),
                ("parity", models.PositiveIntegerField()),
                ("status", models.CharField(default="active", max_length=50)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pregnancies",
                        to="cymed_patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_maternity_pregnancies",
            },
        ),
        migrations.CreateModel(
            name="PostpartumCare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("checked_by", models.UUIDField()),
                ("maternal_condition", models.CharField(max_length=255)),
                ("baby_condition", models.CharField(max_length=255)),
                (
                    "pregnancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cymed_hospital_maternity.pregnancy",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_maternity_postpartum",
            },
        ),
        migrations.AddField(
            model_name="laborepisode",
            name="pregnancy",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labor",
                to="cymed_hospital_maternity.pregnancy",
            ),
        ),
        migrations.CreateModel(
            name="PrenatalEncounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("encounter_date", models.DateTimeField(auto_now_add=True)),
                ("gestational_weeks", models.DecimalField(decimal_places=1, max_digits=4)),
                ("fetal_heart_rate", models.PositiveIntegerField(blank=True, null=True)),
                ("maternal_bp_sys", models.PositiveIntegerField()),
                ("maternal_bp_dia", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True)),
                (
                    "pregnancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cymed_hospital_maternity.pregnancy",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_maternity_prenatal_encounters",
            },
        ),
    ]
