# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkReferral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('source_tenant_id', models.UUIDField(db_index=True)),
                ('source_provider_id', models.UUIDField(blank=True, null=True)),
                ('target_tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('target_provider_id', models.UUIDField(blank=True, null=True)),
                ('target_kind', models.CharField(choices=[('clinic', 'Clinic'), ('hospital', 'Hospital'), ('pharmacy', 'Pharmacy'), ('lab', 'Lab'), ('imaging', 'Imaging'), ('telehealth', 'Telehealth')], max_length=32)),
                ('patient_profile_id', models.UUIDField(db_index=True)),
                ('reason', models.CharField(max_length=255)),
                ('clinical_summary', models.TextField(blank=True)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=32)),
                ('preferred_locations', models.JSONField(default=list)),
                ('consent_grant_id', models.UUIDField(blank=True, null=True)),
                ('matched_rule_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('routed', 'Routed'), ('acknowledged', 'Acknowledged'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('result_returned', 'Result Returned'), ('declined', 'Declined'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn')], default='created', max_length=32)),
                ('routed_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_documents', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'cymed_eco_referral_routing_network_referral',
            },
        ),
        migrations.CreateModel(
            name='RoutingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kind', models.CharField(choices=[('rule_matched', 'Rule Matched'), ('candidate_selected', 'Candidate Selected'), ('candidate_declined', 'Candidate Declined'), ('fallback_used', 'Fallback Used'), ('manual_override', 'Manual Override'), ('expired', 'Expired')], max_length=32)),
                ('candidate_tenant_id', models.UUIDField(blank=True, null=True)),
                ('rule_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cymed_eco_referral_routing.networkreferral')),
            ],
            options={
                'db_table': 'cymed_eco_referral_routing_routing_log',
            },
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('source_kind', models.CharField(choices=[('clinic', 'Clinic'), ('hospital', 'Hospital'), ('pharmacy', 'Pharmacy'), ('lab', 'Lab'), ('imaging', 'Imaging'), ('telehealth', 'Telehealth'), ('any', 'Any')], max_length=32)),
                ('target_kind', models.CharField(choices=[('clinic', 'Clinic'), ('hospital', 'Hospital'), ('pharmacy', 'Pharmacy'), ('lab', 'Lab'), ('imaging', 'Imaging'), ('telehealth', 'Telehealth')], max_length=32)),
                ('specialty', models.CharField(blank=True, max_length=64)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=32)),
                ('geo_scope', models.CharField(choices=[('same_city', 'Same City'), ('same_country', 'Same Country'), ('cross_border', 'Cross Border'), ('anywhere', 'Anywhere')], default='same_country', max_length=32)),
                ('preferred_tenant_ids', models.JSONField(default=list)),
                ('fallback_tenant_ids', models.JSONField(default=list)),
                ('payer_ids', models.JSONField(default=list)),
                ('priority', models.IntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_eco_referral_routing_routing_rule',
                'unique_together': {('tenant_id', 'code')},
            },
        ),
    ]
