# Generated by Django 5.1.15 on 2026-06-23 03:25

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductCatalogEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("short_description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("current_version", models.CharField(default="1.0.0", max_length=50)),
            ],
            options={
                "db_table": "cymed_commercial_product_catalog",
            },
        ),
        migrations.CreateModel(
            name="ProductEdition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                            ("community", "Community Hospital"),
                            ("enterprise_hospital", "Enterprise Hospital"),
                            ("medical_city", "Medical City"),
                            ("basic", "Basic"),
                            ("advanced", "Advanced"),
                            ("reference_lab", "Reference Lab"),
                            ("retail", "Retail"),
                            ("chain", "Chain"),
                            ("hospital_pharmacy", "Hospital Pharmacy"),
                            ("standard", "Standard"),
                            ("government", "Government"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("max_users", models.PositiveIntegerField(default=0)),
                ("max_providers", models.PositiveIntegerField(default=0)),
                ("max_beds", models.PositiveIntegerField(default=0)),
                ("max_facilities", models.PositiveIntegerField(default=0)),
                ("max_clinics", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editions",
                        to="commercial_editions.productcatalogentry",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_commercial_product_editions",
                "unique_together": {("product", "code")},
            },
        ),
        migrations.CreateModel(
            name="EditionModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("module_code", models.CharField(max_length=200)),
                ("is_included", models.BooleanField(default=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="commercial_editions.productedition",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_commercial_edition_modules",
                "unique_together": {("edition", "module_code")},
            },
        ),
        migrations.CreateModel(
            name="EditionLimit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("resource_name", models.CharField(max_length=100)),
                ("max_value", models.PositiveIntegerField(default=0)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limits",
                        to="commercial_editions.productedition",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_commercial_edition_limits",
                "unique_together": {("edition", "resource_name")},
            },
        ),
        migrations.CreateModel(
            name="EditionFeature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("feature_code", models.CharField(max_length=200)),
                ("is_enabled", models.BooleanField(default=True)),
                ("limit_value", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="commercial_editions.productedition",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_commercial_edition_features",
                "unique_together": {("edition", "feature_code")},
            },
        ),
    ]
