# Generated by Django 5.1.15 on 2026-06-23 00:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_encounters', '__first__'),
        ('cymed_patients', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'cymed_hospital_admission_reasons',
            },
        ),
        migrations.CreateModel(
            name='AdmissionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'cymed_hospital_admission_types',
            },
        ),
        migrations.CreateModel(
            name='DischargeDisposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'cymed_hospital_discharge_dispositions',
            },
        ),
        migrations.CreateModel(
            name='DischargeReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'cymed_hospital_discharge_reasons',
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('admitting_physician_id', models.UUIDField()),
                ('admitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged')], default='admitted', max_length=50)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_admission', to='cymed_encounters.encounter')),
                ('admission_reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cymed_hospital_adt.admissionreason')),
                ('admission_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cymed_hospital_adt.admissiontype')),
            ],
            options={
                'db_table': 'cymed_hospital_admissions',
            },
        ),
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('discharged_at', models.DateTimeField(auto_now_add=True)),
                ('discharged_by', models.UUIDField()),
                ('summary_text', models.TextField()),
                ('instructions', models.TextField()),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_details', to='cymed_hospital_adt.admission')),
                ('disposition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cymed_hospital_adt.dischargedisposition')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cymed_hospital_adt.dischargereason')),
            ],
            options={
                'db_table': 'cymed_hospital_discharge_summaries',
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('source_bed_id', models.UUIDField(blank=True, null=True)),
                ('target_bed_id', models.UUIDField()),
                ('requested_by', models.UUIDField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('reason', models.TextField()),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cymed_encounters.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cymed_patients.patient')),
            ],
            options={
                'db_table': 'cymed_hospital_transfer_requests',
            },
        ),
        migrations.CreateModel(
            name='TransferApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('approved_by', models.UUIDField()),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('transfer_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='cymed_hospital_adt.transferrequest')),
            ],
            options={
                'db_table': 'cymed_hospital_transfer_approvals',
            },
        ),
    ]
