# Generated by Django 5.1.15 on 2026-06-23 00:21

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cymed_hospital_adt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalStay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("care_team_leader_id", models.UUIDField()),
                ("expected_length_of_stay", models.PositiveIntegerField(default=3)),
                ("actual_length_of_stay", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "admission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stay",
                        to="cymed_hospital_adt.admission",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_stays",
            },
        ),
        migrations.CreateModel(
            name="DischargePlanning",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("target_discharge_date", models.DateField()),
                ("barriers_to_discharge", models.TextField(blank=True)),
                ("is_cleared", models.BooleanField(default=False)),
                (
                    "stay",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discharge_plan",
                        to="cymed_hospital_inpatient.hospitalstay",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_discharge_planning",
            },
        ),
        migrations.CreateModel(
            name="DailyRound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("clinician_id", models.UUIDField()),
                ("round_time", models.DateTimeField(auto_now_add=True)),
                ("subjective_notes", models.TextField()),
                ("objective_notes", models.TextField()),
                ("assessment_notes", models.TextField()),
                ("plan_notes", models.TextField()),
                (
                    "stay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="cymed_hospital_inpatient.hospitalstay",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_daily_rounds",
            },
        ),
        migrations.CreateModel(
            name="InpatientCarePlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("title", models.CharField(max_length=255)),
                ("goals", models.TextField()),
                ("interventions", models.TextField()),
                (
                    "stay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cymed_hospital_inpatient.hospitalstay",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_inpatient_careplans",
            },
        ),
        migrations.CreateModel(
            name="ProgressReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                ("reviewer_id", models.UUIDField()),
                ("progress_status", models.CharField(max_length=50)),
                (
                    "stay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cymed_hospital_inpatient.hospitalstay",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_hospital_progress_reviews",
            },
        ),
    ]
