# Generated by Django 6.0.7 on 2026-08-24 09:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cycom_catalog.category')),
            ],
            options={
                'db_table': 'cycom_catalog_categories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('tenant_id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cycom_catalog_units',
                'unique_together': {('tenant_id', 'abbreviation')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('product_type', models.CharField(choices=[('STORABLE', 'Storable Product'), ('CONSUMABLE', 'Consumable'), ('SERVICE', 'Service'), ('KIT', 'Kit / Bundle')], default='STORABLE', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('internal_ref', models.CharField(blank=True, max_length=100)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cost_price', models.DecimalField(decimal_places=4, default='0.0000', max_digits=15)),
                ('sell_price', models.DecimalField(decimal_places=4, default='0.0000', max_digits=15)),
                ('track_stock', models.BooleanField(default=True)),
                ('min_stock_qty', models.DecimalField(decimal_places=4, default='0.0000', max_digits=15)),
                ('pos_available', models.BooleanField(default=True)),
                ('pos_category_sequence', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='cycom_catalog.category')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='cycom_catalog.productunit')),
            ],
            options={
                'db_table': 'cycom_catalog_products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100)),
                ('cost_price', models.DecimalField(decimal_places=4, default='0.0000', max_digits=15)),
                ('sell_price', models.DecimalField(decimal_places=4, default='0.0000', max_digits=15)),
                ('attributes', models.JSONField(default=dict)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='cycom_catalog.product')),
            ],
            options={
                'db_table': 'cycom_catalog_variants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, default='0.0000', max_digits=5)),
            ],
            options={
                'db_table': 'cycom_catalog_tax_classes',
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tax_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='cycom_catalog.taxclass'),
        ),
        migrations.CreateModel(
            name='KitComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('quantity_per_unit', models.DecimalField(decimal_places=4, default='1.0000', max_digits=15)),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_kits', to='cycom_catalog.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_components', to='cycom_catalog.product')),
            ],
            options={
                'db_table': 'cycom_catalog_kit_components',
                'ordering': ['component_product__name'],
                'unique_together': {('product', 'component_product')},
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('internal_ref', ''), _negated=True), fields=('tenant_id', 'internal_ref'), name='uniq_catalog_product_ref_per_tenant'),
        ),
    ]
