# Generated by Django 6.0.7 on 2026-09-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_catalog', '0003_product_inventory_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricing_mode',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('weight', 'Weight-Based')], default='fixed', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='tracking_mode',
            field=models.CharField(choices=[('none', 'Not Tracked'), ('batch', 'Batch / Lot + Expiry'), ('serial', 'Serial Number')], default='none', max_length=10),
        ),
    ]
