# Generated by Django 6.0.7 on 2026-09-14 10:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_catalog', '0004_product_pricing_mode_product_tracking_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='controlled_substance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='core_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_prescription',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VehicleFitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year_start', models.PositiveSmallIntegerField()),
                ('year_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('engine_trim', models.CharField(blank=True, max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='cycom_catalog.product')),
            ],
            options={
                'db_table': 'cycom_catalog_vehicle_fitments',
                'ordering': ['make', 'model', 'year_start'],
            },
        ),
    ]
