# Generated by Django 6.0.7 on 2026-09-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_catalog', '0005_product_controlled_substance_product_core_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_published_online',
            field=models.BooleanField(default=False),
        ),
    ]
