# Generated by Django 6.0.6 on 2026-09-06 20:19

import apps.tenants.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_branch_commission_policy_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=apps.tenants.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=120)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=64)),
                ('iban', models.CharField(blank=True, max_length=40)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('gl_account_id', models.UUIDField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'banking_accounts',
                'ordering': ['name'],
                'unique_together': {('tenant_id', 'company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.UUIDField(default=apps.tenants.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('statement_date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='banking.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'banking_statements',
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.UUIDField(default=apps.tenants.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('txn_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed: positive = money in, negative = money out', max_digits=15)),
                ('matched', models.BooleanField(default=False)),
                ('match_type', models.CharField(blank=True, max_length=24)),
                ('match_id', models.UUIDField(blank=True, null=True)),
                ('match_note', models.CharField(blank=True, max_length=255)),
                ('reconciled', models.BooleanField(default=False)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_lines', to='banking.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='banking.bankstatement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'banking_statement_lines',
                'ordering': ['txn_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationSession',
            fields=[
                ('id', models.UUIDField(default=apps.tenants.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('statement_closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('book_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='banking.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'banking_reconciliation_sessions',
                'ordering': ['-period_end'],
            },
        ),
    ]
