# Generated by Django 6.0.6 on 2026-06-23 04:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('encounter_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('ordered_by', models.UUIDField()),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT'), ('critical', 'Critical')], default='routine', max_length=20)),
                ('order_type', models.CharField(choices=[('outpatient', 'Outpatient'), ('inpatient', 'Inpatient'), ('emergency', 'Emergency'), ('scheduled', 'Scheduled'), ('teleradiology', 'Teleradiology')], default='outpatient', max_length=30)),
                ('clinical_indication', models.TextField(blank=True)),
                ('icd11_codes', models.JSONField(default=list)),
                ('fhir_service_request_id', models.CharField(blank=True, max_length=255)),
                ('hl7_placer_order_number', models.CharField(blank=True, max_length=100)),
                ('hl7_filler_order_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], db_index=True, default='pending', max_length=30)),
                ('ordering_facility', models.CharField(blank=True, max_length=255)),
                ('transport_required', models.BooleanField(default=False)),
                ('is_portable', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cymed_img_orders',
            },
        ),
        migrations.CreateModel(
            name='ImagingProcedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('modality', models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT'), ('mri', 'MRI'), ('us', 'Ultrasound'), ('mg', 'Mammography'), ('pet', 'PET'), ('nm', 'Nuclear Medicine'), ('fl', 'Fluoroscopy'), ('xa', 'Angiography'), ('dxa', 'DEXA')], max_length=20)),
                ('snomed_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('loinc_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('body_part', models.CharField(blank=True, max_length=100)),
                ('laterality', models.CharField(blank=True, max_length=20)),
                ('preparation_instructions', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('contrast_required', models.BooleanField(default=False)),
                ('radiation_dose_estimate', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('rvu_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_img_procedures',
            },
        ),
        migrations.CreateModel(
            name='ImagingProtocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('modality', models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT'), ('mri', 'MRI'), ('us', 'Ultrasound'), ('mg', 'Mammography'), ('pet', 'PET'), ('nm', 'Nuclear Medicine'), ('fl', 'Fluoroscopy'), ('xa', 'Angiography'), ('dxa', 'DEXA')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('parameters', models.JSONField(default=dict)),
                ('contrast_phases', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_img_protocols',
            },
        ),
        migrations.CreateModel(
            name='ImagingOrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('changed_by', models.UUIDField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='img_orders.imagingorder')),
            ],
            options={
                'db_table': 'cymed_img_order_status_history',
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagingOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('body_part', models.CharField(blank=True, max_length=100)),
                ('laterality', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('bilateral', 'Bilateral'), ('none', 'None')], max_length=20)),
                ('contrast_required', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30)),
                ('dicom_study_instance_uid', models.CharField(blank=True, db_index=True, max_length=255)),
                ('accession_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='img_orders.imagingorder')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='img_orders.imagingprocedure')),
            ],
            options={
                'db_table': 'cymed_img_order_items',
            },
        ),
        migrations.AddField(
            model_name='imagingprocedure',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='img_orders.imagingprotocol'),
        ),
        migrations.AlterUniqueTogether(
            name='imagingprocedure',
            unique_together={('tenant_id', 'code')},
        ),
    ]
