# Generated by Django 6.0.7 on 2026-07-21 06:33

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('file', models.FileField(upload_to='cyvault/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=150)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('category', models.CharField(choices=[('generic', 'Generic'), ('dicom_study', 'DICOM Study'), ('catalog_image', 'Catalog Image'), ('invoice_pdf', 'Invoice PDF'), ('patient_document', 'Patient Health Document')], default='generic', max_length=30)),
                ('linked_model', models.CharField(blank=True, max_length=100)),
                ('linked_id', models.UUIDField(blank=True, null=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'cyvault_files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['linked_model', 'linked_id'], name='cyvault_fil_linked__774c46_idx'), models.Index(fields=['category'], name='cyvault_fil_categor_8d9af6_idx')],
            },
        ),
    ]
