# Generated by Django 6.0.6 on 2026-06-23 04:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('img_orders', '0001_initial'),
        ('img_worklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('modality_type', models.CharField(max_length=20)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('shielding_type', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cymed_img_rooms',
            },
        ),
        migrations.CreateModel(
            name='RadiologistSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('radiologist_id', models.UUIDField(db_index=True)),
                ('schedule_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('modality_types', models.JSONField(default=list)),
                ('subspecialty', models.CharField(blank=True, max_length=100)),
                ('is_on_call', models.BooleanField(default=False)),
                ('is_teleradiology', models.BooleanField(default=False)),
                ('site_code', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'cymed_img_radiologist_schedule',
            },
        ),
        migrations.CreateModel(
            name='ImagingAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('patient_id', models.UUIDField(db_index=True)),
                ('radiologist_id', models.UUIDField(blank=True, null=True)),
                ('technologist_id', models.UUIDField(blank=True, null=True)),
                ('scheduled_start', models.DateTimeField(db_index=True)),
                ('scheduled_end', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], db_index=True, default='scheduled', max_length=20)),
                ('patient_arrived_at', models.DateTimeField(blank=True, null=True)),
                ('exam_started_at', models.DateTimeField(blank=True, null=True)),
                ('exam_completed_at', models.DateTimeField(blank=True, null=True)),
                ('check_in_notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('contrast_pre_screening', models.JSONField(default=dict)),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='img_worklist.modality')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='img_orders.imagingorderitem')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='img_scheduling.imagingroom')),
            ],
            options={
                'db_table': 'cymed_img_appointments',
            },
        ),
        migrations.CreateModel(
            name='ModalitySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('schedule_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('available_slots', models.PositiveIntegerField(default=0)),
                ('booked_slots', models.PositiveIntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('downtime_reason', models.CharField(blank=True, max_length=255)),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='img_worklist.modality')),
            ],
            options={
                'db_table': 'cymed_img_modality_schedule',
                'unique_together': {('modality', 'schedule_date')},
            },
        ),
    ]
