# Generated by Django 6.0.6 on 2026-06-23 04:10

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lab_orders", "0001_initial"),
        ("lab_specimens", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Culture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("culture_number", models.CharField(max_length=100, unique=True)),
                ("culture_type", models.CharField(max_length=100)),
                ("medium", models.CharField(blank=True, max_length=100)),
                (
                    "incubation_temperature_celsius",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
                ),
                ("incubation_hours", models.PositiveIntegerField(default=24)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Inoculation"),
                            ("inoculated", "Inoculated"),
                            ("incubating", "Incubating"),
                            ("no_growth", "No Growth at 24h"),
                            ("preliminary", "Preliminary Result"),
                            ("final", "Final Result"),
                            ("amended", "Amended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("inoculated_at", models.DateTimeField(blank=True, null=True)),
                ("inoculated_by", models.UUIDField(blank=True, null=True)),
                ("read_at_24h", models.DateTimeField(blank=True, null=True)),
                ("read_at_48h", models.DateTimeField(blank=True, null=True)),
                ("read_at_72h", models.DateTimeField(blank=True, null=True)),
                ("final_read_at", models.DateTimeField(blank=True, null=True)),
                ("comments", models.TextField(blank=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cultures",
                        to="lab_orders.laborderitem",
                    ),
                ),
                (
                    "specimen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cultures",
                        to="lab_specimens.specimen",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_lab_cultures",
            },
        ),
        migrations.CreateModel(
            name="MicrobiologyResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("final_interpretation", models.TextField()),
                ("clinical_notes", models.TextField(blank=True)),
                ("reported_by", models.UUIDField()),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_by", models.UUIDField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("fhir_diagnostic_report_id", models.CharField(blank=True, max_length=255)),
                (
                    "order_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="microbiology_result",
                        to="lab_orders.laborderitem",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_lab_microbiology_results",
            },
        ),
        migrations.CreateModel(
            name="Organism",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("snomed_code", models.CharField(blank=True, max_length=50)),
                ("organism_name", models.CharField(max_length=255)),
                (
                    "gram_stain",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gram_positive", "Gram Positive"),
                            ("gram_negative", "Gram Negative"),
                            ("gram_variable", "Gram Variable"),
                            ("not_applicable", "Not Applicable"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "morphology",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cocci", "Cocci"),
                            ("bacilli", "Bacilli"),
                            ("coccobacilli", "Coccobacilli"),
                            ("spirochete", "Spirochete"),
                            ("yeast", "Yeast"),
                            ("mold", "Mold"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "growth_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "No Growth"),
                            ("rare", "Rare (< 10 CFU)"),
                            ("few", "Few (10â€“100 CFU)"),
                            ("moderate", "Moderate (100â€“1000 CFU)"),
                            ("many", "Many (> 1000 CFU)"),
                            ("heavy", "Heavy (Confluent)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("identification_method", models.CharField(blank=True, max_length=100)),
                (
                    "identification_confidence",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("is_contaminant", models.BooleanField(default=False)),
                ("identified_at", models.DateTimeField(blank=True, null=True)),
                ("identified_by", models.UUIDField(blank=True, null=True)),
                (
                    "culture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organisms",
                        to="lab_microbiology.culture",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_lab_organisms",
            },
        ),
        migrations.CreateModel(
            name="ResistanceProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "resistance_mechanism",
                    models.CharField(
                        choices=[
                            ("mrsa", "MRSA â€” Methicillin-Resistant S. aureus"),
                            ("esbl", "ESBL â€” Extended-Spectrum Beta-Lactamase"),
                            ("cre", "CRE â€” Carbapenem-Resistant Enterobacteriaceae"),
                            ("vrsa", "VRSA â€” Vancomycin-Resistant S. aureus"),
                            ("vre", "VRE â€” Vancomycin-Resistant Enterococcus"),
                            ("mdr", "MDR â€” Multi-Drug Resistant"),
                            ("xdr", "XDR â€” Extensively Drug Resistant"),
                            ("pan_resistant", "PDR â€” Pan-Drug Resistant"),
                            ("other", "Other Resistance Mechanism"),
                        ],
                        max_length=30,
                    ),
                ),
                ("confirmed", models.BooleanField(default=False)),
                ("detection_method", models.CharField(blank=True, max_length=100)),
                ("detected_at", models.DateTimeField(blank=True, null=True)),
                ("reported_to_infection_control", models.BooleanField(default=False)),
                ("outbreak_flagged", models.BooleanField(default=False)),
                (
                    "organism",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resistance_profiles",
                        to="lab_microbiology.organism",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_lab_resistance_profiles",
            },
        ),
        migrations.CreateModel(
            name="Sensitivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("antibiotic_code", models.CharField(max_length=50)),
                ("antibiotic_name", models.CharField(max_length=255)),
                ("method", models.CharField(blank=True, max_length=50)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("S", "Susceptible"),
                            ("I", "Intermediate"),
                            ("R", "Resistant"),
                            ("NA", "Not Applicable"),
                            ("NT", "Not Tested"),
                        ],
                        default="NT",
                        max_length=5,
                    ),
                ),
                ("mic_value", models.CharField(blank=True, max_length=20)),
                ("disk_zone_mm", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("breakpoint_standard", models.CharField(blank=True, max_length=50)),
                ("tested_at", models.DateTimeField(blank=True, null=True)),
                ("tested_by", models.UUIDField(blank=True, null=True)),
                (
                    "organism",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensitivities",
                        to="lab_microbiology.organism",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_lab_sensitivities",
            },
        ),
        migrations.AddIndex(
            model_name="culture",
            index=models.Index(
                fields=["tenant_id", "status"], name="cymed_lab_c_tenant__fc21cf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sensitivity",
            unique_together={("organism", "antibiotic_code")},
        ),
    ]
