# Generated by Django 6.0.7 on 2026-08-19 04:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundingFormulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('sterile', 'Sterile'), ('non_sterile', 'Non-Sterile'), ('hazardous', 'Hazardous'), ('iv_admixture', 'IV Admixture'), ('tpn', 'TPN')], default='non_sterile', max_length=32)),
                ('usp_chapter', models.CharField(choices=[('usp797', 'USP <797>'), ('usp795', 'USP <795>'), ('usp800', 'USP <800>'), ('none', 'None')], default='none', max_length=32)),
                ('dosage_form', models.CharField(choices=[('capsule', 'Capsule'), ('cream', 'Cream'), ('ointment', 'Ointment'), ('solution', 'Solution'), ('suspension', 'Suspension'), ('injection', 'Injection'), ('iv_bag', 'IV Bag')], default='solution', max_length=32)),
                ('final_volume_ml', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('beyond_use_hours', models.IntegerField(default=24)),
                ('storage', models.CharField(choices=[('room', 'Room'), ('refrigerated', 'Refrigerated'), ('frozen', 'Frozen')], default='room', max_length=32)),
                ('requires_hood', models.BooleanField(default=False)),
                ('requires_ppe', models.BooleanField(default=False)),
                ('controlled_substance', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cymed_pharmacy_compounding_formulation',
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CompoundingIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('position', models.IntegerField(default=0)),
                ('drug_id', models.UUIDField(blank=True, null=True)),
                ('ingredient_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('uom', models.CharField(max_length=16)),
                ('is_active_ingredient', models.BooleanField(default=False)),
                ('hazard_class', models.CharField(blank=True, max_length=32)),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cymed_pharmacy_compounding.compoundingformulation')),
            ],
            options={
                'db_table': 'cymed_pharmacy_compounding_ingredient',
                'ordering': ['formulation_id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='CompoundingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('prescription_id', models.UUIDField(blank=True, null=True)),
                ('patient_profile_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('requested_qty', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('verified', 'Verified'), ('ingredients_pulled', 'Ingredients Pulled'), ('mixing', 'Mixing'), ('qa_pending', 'QA Pending'), ('released', 'Released'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='requested', max_length=32)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'Stat')], default='routine', max_length=32)),
                ('assigned_compounder_id', models.UUIDField(blank=True, null=True)),
                ('assigned_verifier_id', models.UUIDField(blank=True, null=True)),
                ('hood_id', models.CharField(blank=True, max_length=64)),
                ('lot_number', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('release_signed_by', models.UUIDField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='cymed_pharmacy_compounding.compoundingformulation')),
            ],
            options={
                'db_table': 'cymed_pharmacy_compounding_order',
            },
        ),
        migrations.CreateModel(
            name='CompoundingStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('position', models.IntegerField()),
                ('step_kind', models.CharField(choices=[('hand_hygiene', 'Hand Hygiene'), ('gowning', 'Gowning'), ('gather', 'Gather'), ('calc', 'Calculation'), ('measure', 'Measure'), ('mix', 'Mix'), ('fill', 'Fill'), ('label', 'Label'), ('qa_visual', 'QA Visual'), ('qa_gc', 'QA GC'), ('release', 'Release')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('performed_by', models.UUIDField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail'), ('skipped', 'Skipped')], default='pending', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='cymed_pharmacy_compounding.compoundingorder')),
            ],
            options={
                'db_table': 'cymed_pharmacy_compounding_step',
                'ordering': ['order_id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='IngredientLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('ingredient_name', models.CharField(max_length=255)),
                ('lot_number', models.CharField(max_length=64)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('ndc', models.CharField(blank=True, max_length=32)),
                ('qty_on_hand', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('source_vendor', models.CharField(blank=True, max_length=255)),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_lots', to='cymed_pharmacy_compounding.compoundingformulation')),
            ],
            options={
                'db_table': 'cymed_pharmacy_compounding_ingredient_lot',
            },
        ),
        migrations.CreateModel(
            name='QATest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('kind', models.CharField(choices=[('visual', 'Visual'), ('ph', 'pH'), ('potency', 'Potency'), ('sterility', 'Sterility'), ('endotoxin', 'Endotoxin')], max_length=32)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail')], default='pending', max_length=32)),
                ('value', models.CharField(blank=True, max_length=64)),
                ('performed_by', models.UUIDField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_tests', to='cymed_pharmacy_compounding.compoundingorder')),
            ],
            options={
                'db_table': 'cymed_pharmacy_compounding_qa_test',
            },
        ),
    ]
