# Generated by Django 6.0.7 on 2026-08-06 17:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyed_sis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentIntake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('doc_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('transcript', 'Transcript'), ('receipt', 'Receipt'), ('id', 'ID Document'), ('other', 'Other')], default='other', max_length=30)),
                ('application_ref', models.CharField(blank=True, max_length=64)),
                ('file_bytes', models.BinaryField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('raw_text', models.TextField(blank=True)),
                ('extracted_fields', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('ocr_pending', 'OCR Pending'), ('extracted', 'Extracted'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_document_intakes',
                'ordering': ['-created_at'],
            },
        ),
    ]
