# Generated by Django 6.0.7 on 2026-07-21 10:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_cyidentity', '0003_personidentity_userprofile_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('currency', models.CharField(max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='platform_cyidentity.personidentity')),
            ],
            options={
                'db_table': 'platform_wallet_accounts',
            },
        ),
        migrations.CreateModel(
            name='WalletLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('entry_type', models.CharField(choices=[('topup', 'Top-Up'), ('debit', 'Debit'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='platform_wallet.walletaccount')),
            ],
            options={
                'db_table': 'platform_wallet_ledger_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='walletaccount',
            index=models.Index(fields=['person', 'currency'], name='platform_wa_person__229b95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='walletaccount',
            unique_together={('person', 'currency')},
        ),
    ]
