# Generated by Django 6.0.7 on 2026-07-21 11:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_cyidentity', '0003_personidentity_userprofile_person_and_more'),
        ('platform_wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('currency', models.CharField(max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_receipts', to='platform_cyidentity.personidentity')),
                ('wallet_ledger_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_receipt', to='platform_wallet.walletledgerentry')),
            ],
            options={
                'db_table': 'platform_checkout_receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckoutReceiptLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('item_type', models.CharField(choices=[('cymed_order', 'Cymed Order Payment'), ('cyshop_order', 'Cyshop Retail Order')], max_length=20)),
                ('external_reference', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='platform_wallet.checkoutreceipt')),
            ],
            options={
                'db_table': 'platform_checkout_receipt_lines',
                'ordering': ['id'],
            },
        ),
    ]
