# Generated by Django 6.0.7 on 2026-07-15 09:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_encounters', '0001_initial'),
        ('cymed_patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('soap', 'SOAP Note'), ('progress', 'Progress Note'), ('procedure', 'Procedure Note'), ('consultation', 'Consultation Note'), ('discharge', 'Discharge Summary')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final / Signed'), ('amended', 'Amended')], default='draft', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('digitally_signed_by', models.CharField(blank=True, max_length=255)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='cymed_encounters.encounter')),
                ('parent_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='cymed_documents.clinicaldocument')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cymed_patients.patient')),
            ],
            options={
                'db_table': 'cymed_clinical_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('reason_for_consult', models.TextField()),
                ('recommendations', models.TextField()),
                ('clinical_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_note', to='cymed_documents.clinicaldocument')),
            ],
            options={
                'db_table': 'cymed_consultation_notes',
            },
        ),
        migrations.CreateModel(
            name='DischargeNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('discharge_status', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('clinical_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_note', to='cymed_documents.clinicaldocument')),
            ],
            options={
                'db_table': 'cymed_discharge_notes',
            },
        ),
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cymed_documents.clinicaldocument')),
            ],
            options={
                'db_table': 'cymed_document_sections',
            },
        ),
        migrations.CreateModel(
            name='ProcedureNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('procedure_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('clinical_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_note', to='cymed_documents.clinicaldocument')),
            ],
            options={
                'db_table': 'cymed_procedure_notes',
            },
        ),
        migrations.CreateModel(
            name='ProgressNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('narrative', models.TextField()),
                ('clinical_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_note', to='cymed_documents.clinicaldocument')),
            ],
            options={
                'db_table': 'cymed_progress_notes',
            },
        ),
        migrations.CreateModel(
            name='SOAPNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('clinical_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soap_note', to='cymed_documents.clinicaldocument')),
            ],
            options={
                'db_table': 'cymed_soap_notes',
            },
        ),
    ]
