# Generated by Django 6.0.7 on 2026-08-09 17:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyed_hr', '0002_staff_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendanceDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('date', models.DateField()),
                ('scheduled_start', models.TimeField(blank=True, null=True)),
                ('scheduled_end', models.TimeField(blank=True, null=True)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent (unexplained)'), ('sick', 'Sick Leave'), ('leave', 'Approved Leave'), ('holiday', 'Public Holiday'), ('weekend', 'Non-working Day')], default='present', max_length=20)),
                ('minutes_late', models.PositiveIntegerField(default=0)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_days', to='cyed_hr.staffleave')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='cyed_hr.staff')),
            ],
            options={
                'db_table': 'cyed_staff_attendance_days',
                'ordering': ['-date', 'staff__last_name'],
                'indexes': [models.Index(fields=['tenant_id', 'date'], name='idx_staff_att_tenant_date')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'staff', 'date'), name='uniq_staff_attendance_per_day')],
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('period_label', models.CharField(max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('days_present', models.PositiveSmallIntegerField(default=0)),
                ('days_absent', models.PositiveSmallIntegerField(default=0)),
                ('days_leave', models.PositiveSmallIntegerField(default=0)),
                ('total_minutes_late', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='cyed_hr.staff')),
            ],
            options={
                'db_table': 'cyed_staff_timesheets',
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'staff', 'period_label'), name='uniq_timesheet_per_staff_period')],
            },
        ),
    ]
