# Generated by Django 5.1.15 on 2026-06-23 00:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cymed_hospital_adt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NursingShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'db_table': 'cymed_hospital_nursing_shifts',
            },
        ),
        migrations.CreateModel(
            name='NursingAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('assessed_by', models.UUIDField()),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('nursing_summary', models.TextField()),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cymed_hospital_adt.admission')),
            ],
            options={
                'db_table': 'cymed_hospital_nursing_assessments',
            },
        ),
        migrations.CreateModel(
            name='NursingCarePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('goals', models.TextField()),
                ('activities', models.TextField()),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cymed_hospital_adt.admission')),
            ],
            options={
                'db_table': 'cymed_hospital_nursing_careplans',
            },
        ),
        migrations.CreateModel(
            name='NursingHandover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('outgoing_nurse_id', models.UUIDField()),
                ('incoming_nurse_id', models.UUIDField()),
                ('handover_time', models.DateTimeField(auto_now_add=True)),
                ('situation_background', models.TextField()),
                ('assessment_recommendation', models.TextField()),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cymed_hospital_adt.admission')),
            ],
            options={
                'db_table': 'cymed_hospital_nursing_handovers',
            },
        ),
        migrations.CreateModel(
            name='NursingAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('nurse_id', models.UUIDField()),
                ('ward_id', models.UUIDField()),
                ('assigned_date', models.DateField()),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cymed_hospital_nursing.nursingshift')),
            ],
            options={
                'db_table': 'cymed_hospital_nursing_assignments',
            },
        ),
        migrations.CreateModel(
            name='NursingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('task_name', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=50)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cymed_hospital_adt.admission')),
            ],
            options={
                'db_table': 'cymed_hospital_nursing_tasks',
            },
        ),
    ]
