# Generated by Django 6.0.7 on 2026-07-19 18:56

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('technician', models.CharField(blank=True, max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('en_route', 'En Route'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('worksheet_notes', models.TextField(blank=True)),
                ('customer_signature', models.TextField(blank=True, help_text='Base64-encoded signature capture or signature reference.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cycom_field_service_tasks',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
