# Generated by Django 6.0.7 on 2026-09-21 19:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_field_service', '0002_servicetask_attributes_servicetask_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetask',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('contract_number', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('sla_hours', models.PositiveIntegerField(help_text="Hours from a task's scheduled_at to completion this contract guarantees.")),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cycom_field_service_contracts',
                'ordering': ['-start_date'],
                'unique_together': {('tenant_id', 'contract_number')},
            },
        ),
        migrations.AddField(
            model_name='servicetask',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='cycom_field_service.servicecontract'),
        ),
    ]
