# Generated by Django 6.1.1 on 2026-09-04 03:19

import platform.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticalfinding',
            name='finding_description',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='radiologyfinding',
            name='description',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='radiologyfinding',
            name='location_detail',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='radiologyimpression',
            name='impression_text',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='radiologyreport',
            name='ai_summary',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='radiologyreport',
            name='clinical_indication',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='radiologyreport',
            name='comparison_studies',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='radiologyreport',
            name='findings',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='radiologyreport',
            name='impression',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='radiologyreport',
            name='recommendations',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='radiologyreport',
            name='technique',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='reportamendment',
            name='amendment_reason',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='reportamendment',
            name='new_findings',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='reportamendment',
            name='new_impression',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='reportamendment',
            name='previous_findings',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='reportamendment',
            name='previous_impression',
            field=platform.common.fields.EncryptedText(blank=True, classification='phi', default=b'', editable=True),
        ),
    ]
