# Generated by Django 6.0.7 on 2026-07-17 16:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('agent_key', models.CharField(choices=[('ask_cycom', 'Ask CyCom'), ('report_studio', 'CyCom Report Studio AI'), ('builder_ai', 'CyCom Builder AI')], max_length=30, unique=True)),
                ('customer_facing_name', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('requires_elevated_approval', models.BooleanField(default=False)),
                ('suggested_pricing_note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cycom_cyai_agent_definitions',
                'ordering': ['agent_key'],
            },
        ),
        migrations.CreateModel(
            name='AgentUsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('user_id', models.CharField(blank=True, max_length=255)),
                ('request_type', models.CharField(max_length=50)),
                ('routed_confidence', models.FloatField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='cycom_cyai_platform.agentdefinition')),
            ],
            options={
                'db_table': 'cycom_cyai_agent_usage_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('plan_code', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('monthly_allowance', models.PositiveIntegerField(blank=True, null=True)),
                ('granted_by', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='cycom_cyai_platform.agentdefinition')),
            ],
            options={
                'db_table': 'cycom_cyai_agent_entitlements',
                'ordering': ['-created_at'],
                'unique_together': {('tenant_id', 'agent')},
            },
        ),
    ]
