# Generated by Django 6.1.1 on 2026-09-04 09:14

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('grantee_tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('grantee_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('granted_by', models.UUIDField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=16)),
            ],
            options={
                'db_table': 'core_consent_grants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerticalFlavor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(default='0.1.0', max_length=32)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('engine_only', 'Engine-only'), ('community', 'Community'), ('verified', 'Verified'), ('certified', 'Certified'), ('ga', 'GA')], default='engine_only', max_length=20)),
                ('feature_flag', models.CharField(blank=True, max_length=100)),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'platform_vertical_flavors',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('event_type', models.CharField(db_index=True, max_length=200)),
                ('aggregate_type', models.CharField(db_index=True, max_length=100)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'core_domain_events',
                'ordering': ['occurred_at'],
                'indexes': [models.Index(fields=['published_at', 'occurred_at'], name='core_domain_publish_960bb8_idx')],
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('as_of', models.DateField(db_index=True)),
                ('source', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'platform_fx_rates',
                'ordering': ['-as_of'],
                'indexes': [models.Index(fields=['base_currency', 'quote_currency', 'as_of'], name='platform_fx_base_cu_60b2cb_idx')],
                'unique_together': {('base_currency', 'quote_currency', 'as_of', 'source')},
            },
        ),
        migrations.CreateModel(
            name='LayoutTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('flavor_key', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('route', models.CharField(max_length=255)),
                ('slots', models.JSONField(blank=True, default=dict)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('device', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'platform_layout_templates',
                'ordering': ['flavor_key', 'route'],
                'unique_together': {('flavor_key', 'route', 'device')},
            },
        ),
    ]
