# Generated by Django 6.0.7 on 2026-07-17 00:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('query_spec', models.JSONField()),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('is_shared', models.BooleanField(default=False)),
                ('is_pinned_to_dashboard', models.BooleanField(default=False)),
                ('current_version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'cycom_cyai_report_definitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportBuilderSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('status', models.CharField(choices=[('gathering', 'Gathering Requirements'), ('drafting', 'Draft Ready'), ('confirmed', 'Confirmed & Saved'), ('abandoned', 'Abandoned')], default='gathering', max_length=20)),
                ('messages', models.JSONField(default=list)),
                ('draft_spec', models.JSONField(blank=True, null=True)),
                ('draft_title', models.CharField(blank=True, max_length=255)),
                ('started_by', models.CharField(blank=True, max_length=255)),
                ('saved_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cycom_cyai_reports.reportdefinition')),
            ],
            options={
                'db_table': 'cycom_cyai_report_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('cron_expression', models.CharField(max_length=100)),
                ('recipients', models.JSONField(default=list)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON')], default='csv', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='cycom_cyai_reports.reportdefinition')),
            ],
            options={
                'db_table': 'cycom_cyai_report_schedules',
            },
        ),
        migrations.CreateModel(
            name='ReportRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('version', models.PositiveIntegerField()),
                ('query_spec', models.JSONField()),
                ('change_summary', models.CharField(blank=True, max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='cycom_cyai_reports.reportdefinition')),
            ],
            options={
                'db_table': 'cycom_cyai_report_revisions',
                'ordering': ['-version'],
                'unique_together': {('report', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ReportShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('shared_with_email', models.EmailField(max_length=254)),
                ('can_edit', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='cycom_cyai_reports.reportdefinition')),
            ],
            options={
                'db_table': 'cycom_cyai_report_shares',
                'unique_together': {('report', 'shared_with_email')},
            },
        ),
    ]
