# Generated by Django 6.0.7 on 2026-08-09 17:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyed_finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('fiscal_year', models.CharField(max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'cyed_finance_budgets',
                'ordering': ['-fiscal_year'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'fiscal_year', 'name'), name='uniq_budget_per_year')],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bank_reference', models.CharField(blank=True, max_length=100)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled_by', models.CharField(blank=True, max_length=255)),
                ('matched_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_lines', to='cyed_finance.journalentry')),
            ],
            options={
                'db_table': 'cyed_finance_bank_statement_lines',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'is_reconciled'], name='idx_bankline_reconciled')],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='cyed_finance.account')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cyed_finance.budget')),
            ],
            options={
                'db_table': 'cyed_finance_budget_lines',
                'ordering': ['account__code'],
                'constraints': [models.UniqueConstraint(fields=('budget', 'account'), name='uniq_budget_line_per_account')],
            },
        ),
    ]
