# Generated by Django 6.0.7 on 2026-08-09 17:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyed_hr', '0002_staff_campus'),
        ('cyed_sis', '0002_classsection_campus_student_campus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignableDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('staff_contract', 'Staff Contract'), ('permission_slip', 'Excursion Permission Slip'), ('consent_form', 'Parent Consent Form'), ('policy', 'Policy Acknowledgement'), ('other', 'Other')], default='other', max_length=30)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent for Signature'), ('partially_signed', 'Partially Signed'), ('completed', 'Completed'), ('declined', 'Declined'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signable_documents', to='cyed_hr.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signable_documents', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_signable_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signatory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('staff', 'Staff'), ('parent', 'Parent/Guardian'), ('student', 'Student'), ('other', 'Other')], default='other', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('typed_signature', models.CharField(blank=True, max_length=255)),
                ('signed_hash', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('decline_reason', models.CharField(blank=True, max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatories', to='cyed_docsign.signabledocument')),
            ],
            options={
                'db_table': 'cyed_document_signatories',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('declined', 'Declined'), ('voided', 'Voided'), ('reminded', 'Reminder Sent')], max_length=20)),
                ('actor', models.CharField(blank=True, max_length=255)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='cyed_docsign.signabledocument')),
                ('signatory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='cyed_docsign.signatory')),
            ],
            options={
                'db_table': 'cyed_signature_audit_events',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='signatory',
            constraint=models.UniqueConstraint(fields=('document', 'email'), name='uniq_signatory_per_document'),
        ),
    ]
