# Generated by Django 6.0.6 on 2026-06-23 07:48

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Formulary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("name", models.CharField(max_length=255)),
                ("name_ar", models.CharField(blank=True, max_length=255)),
                (
                    "formulary_type",
                    models.CharField(
                        choices=[
                            ("hospital", "Hospital Formulary"),
                            ("retail", "Retail Formulary"),
                            ("government", "Government Formulary"),
                            ("insurance", "Insurance/Payer Formulary"),
                            ("national", "National Formulary"),
                            ("chain", "Pharmacy Chain Formulary"),
                        ],
                        default="hospital",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("managed_by", models.UUIDField(blank=True, null=True)),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "cymed_formularies",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "formulary_type", "is_active"],
                        name="cymed_formu_tenant__de247f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FormularyDrug",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("drug_code", models.CharField(db_index=True, max_length=100)),
                ("drug_name", models.CharField(max_length=500)),
                ("drug_name_ar", models.CharField(blank=True, max_length=500)),
                ("generic_code", models.CharField(blank=True, max_length=100)),
                ("generic_name", models.CharField(blank=True, max_length=500)),
                ("atc_code", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preferred", "Preferred"),
                            ("non_preferred", "Non-Preferred"),
                            ("restricted", "Restricted"),
                            ("non_formulary", "Non-Formulary"),
                            ("discontinued", "Discontinued"),
                        ],
                        default="preferred",
                        max_length=20,
                    ),
                ),
                (
                    "tier",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Tier 1 — Generic"),
                            (2, "Tier 2 — Preferred Brand"),
                            (3, "Tier 3 — Non-Preferred Brand"),
                            (4, "Tier 4 — Specialty"),
                            (5, "Tier 5 — Biologic"),
                        ],
                        default=1,
                    ),
                ),
                ("is_generic_allowed", models.BooleanField(default=True)),
                ("requires_prior_auth", models.BooleanField(default=False)),
                ("requires_step_therapy", models.BooleanField(default=False)),
                ("age_restriction_min", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("age_restriction_max", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "gender_restriction",
                    models.CharField(
                        choices=[("any", "Any"), ("male", "Male Only"), ("female", "Female Only")],
                        default="any",
                        max_length=10,
                    ),
                ),
                ("indication_restrictions", models.JSONField(default=list)),
                ("quantity_limits", models.JSONField(default=dict)),
                ("available_strengths", models.JSONField(default=list)),
                ("available_forms", models.JSONField(default=list)),
                ("dispensing_locations", models.JSONField(default=list)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("added_by", models.UUIDField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "formulary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drugs",
                        to="cymed_pharmacy_formulary.formulary",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_formulary_drugs",
            },
        ),
        migrations.CreateModel(
            name="FormularyRestriction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "restriction_type",
                    models.CharField(
                        choices=[
                            ("diagnosis_required", "Specific Diagnosis Required"),
                            ("specialist_only", "Specialist Prescriber Only"),
                            ("age_limit", "Age Limit"),
                            ("quantity_limit", "Quantity Limit"),
                            ("prior_auth", "Prior Authorization"),
                            ("step_therapy", "Step Therapy Required"),
                            ("lab_required", "Lab Result Required"),
                            ("gender_specific", "Gender Specific"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("criteria", models.JSONField(default=dict)),
                ("is_hard_stop", models.BooleanField(default=False)),
                ("effective_date", models.DateField(blank=True, null=True)),
                (
                    "formulary_drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restrictions",
                        to="cymed_pharmacy_formulary.formularydrug",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_formulary_restrictions",
            },
        ),
        migrations.CreateModel(
            name="TherapeuticClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("name_ar", models.CharField(blank=True, max_length=255)),
                ("atc_code", models.CharField(blank=True, max_length=20)),
                ("level", models.PositiveSmallIntegerField(default=1)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="cymed_pharmacy_formulary.therapeuticclass",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_formulary_therapeutic_classes",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="formularydrug",
            name="therapeutic_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="formulary_drugs",
                to="cymed_pharmacy_formulary.therapeuticclass",
            ),
        ),
        migrations.CreateModel(
            name="PreferredMedication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("non_formulary_drug_code", models.CharField(db_index=True, max_length=100)),
                ("non_formulary_drug_name", models.CharField(max_length=500)),
                ("preferred_drug_code", models.CharField(db_index=True, max_length=100)),
                ("preferred_drug_name", models.CharField(max_length=500)),
                (
                    "interchange_reason",
                    models.CharField(
                        choices=[
                            ("cost", "Cost Reduction"),
                            ("formulary_compliance", "Formulary Compliance"),
                            ("safety", "Safety Preference"),
                            ("efficacy", "Equivalent Efficacy"),
                            ("availability", "Drug Availability"),
                        ],
                        default="formulary_compliance",
                        max_length=30,
                    ),
                ),
                ("dose_conversion_notes", models.TextField(blank=True)),
                ("clinical_notes", models.TextField(blank=True)),
                ("requires_pharmacist_counseling", models.BooleanField(default=True)),
                ("approved_by", models.UUIDField(blank=True, null=True)),
                (
                    "formulary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_medications",
                        to="cymed_pharmacy_formulary.formulary",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_preferred_medications",
                "indexes": [
                    models.Index(
                        fields=["formulary", "non_formulary_drug_code"],
                        name="cymed_prefe_formula_25f858_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="formularydrug",
            index=models.Index(
                fields=["formulary", "status", "tier"], name="cymed_formu_formula_988775_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formularydrug",
            index=models.Index(
                fields=["drug_code", "status"], name="cymed_formu_drug_co_9739b8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="formularydrug",
            unique_together={("formulary", "drug_code")},
        ),
    ]
