# Generated by Django 6.0.7 on 2026-09-23 08:51

import django.db.models.deletion
import django.utils.timezone
import products.cycom.elearning.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cycom_elearning_courses',
                'ordering': ['-created_at'],
                'unique_together': {('tenant_id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('token', models.CharField(default=products.cycom.elearning.models._generate_token, editable=False, max_length=64, unique=True)),
                ('student_name', models.CharField(blank=True, max_length=255)),
                ('student_email', models.EmailField(blank=True, max_length=254)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cycom_elearning.course')),
            ],
            options={
                'db_table': 'cycom_elearning_enrollments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='cycom_elearning.course')),
            ],
            options={
                'db_table': 'cycom_elearning_lessons',
                'ordering': ['order', 'created_at'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('row_version', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_by', models.UUIDField(editable=False, null=True)),
                ('updated_by', models.UUIDField(editable=False, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='cycom_elearning.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cycom_elearning.lesson')),
            ],
            options={
                'db_table': 'cycom_elearning_lesson_progress',
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
    ]
