# Generated by Django 6.0.6 on 2026-06-23 07:48

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AutomationDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("device_code", models.CharField(db_index=True, max_length=100, unique=True)),
                ("device_name", models.CharField(max_length=255)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("adc", "Automated Dispensing Cabinet (ADC)"),
                            ("robot", "Dispensing Robot"),
                            ("smart_cabinet", "Smart Storage Cabinet"),
                            ("carousel", "Vertical Carousel"),
                            ("pyxis", "BD Pyxis"),
                            ("omnicell", "Omnicell"),
                            ("swisslog", "Swisslog"),
                            ("custom", "Custom Device"),
                        ],
                        max_length=30,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("model_number", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("firmware_version", models.CharField(blank=True, max_length=50)),
                ("facility_id", models.UUIDField(blank=True, null=True)),
                ("location", models.CharField(max_length=255)),
                ("ward_id", models.UUIDField(blank=True, null=True)),
                ("integration_hub_device_id", models.CharField(blank=True, max_length=255)),
                ("integration_hub_endpoint", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("maintenance", "Under Maintenance"),
                            ("error", "Error"),
                            ("syncing", "Syncing"),
                        ],
                        default="offline",
                        max_length=30,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("supports_barcode", models.BooleanField(default=True)),
                ("supports_biometric", models.BooleanField(default=False)),
                ("pocket_count", models.PositiveSmallIntegerField(default=0)),
                ("controlled_substance_capable", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "cymed_automation_devices",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "device_type", "status"],
                        name="cymed_autom_tenant__f3464e_idx",
                    ),
                    models.Index(
                        fields=["facility_id", "ward_id"], name="cymed_autom_facilit_0a691f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CabinetDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                (
                    "cabinet_type",
                    models.CharField(
                        choices=[
                            ("adc", "Automated Dispensing Cabinet"),
                            ("narcotic_safe", "Controlled Substance Safe"),
                            ("refrigerated", "Refrigerated Cabinet"),
                            ("chemotherapy", "Chemotherapy Cabinet"),
                        ],
                        default="adc",
                        max_length=30,
                    ),
                ),
                ("slot_count", models.PositiveSmallIntegerField(default=0)),
                ("is_networked", models.BooleanField(default=True)),
                ("requires_biometric", models.BooleanField(default=False)),
                ("requires_witness", models.BooleanField(default=False)),
                ("restocking_alert_threshold", models.PositiveSmallIntegerField(default=20)),
                ("assigned_formulary_id", models.UUIDField(blank=True, null=True)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cabinet_profile",
                        to="cymed_pharmacy_automation.automationdevice",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_cabinet_devices",
            },
        ),
        migrations.CreateModel(
            name="DispensingRobot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("dispensing_speed", models.PositiveSmallIntegerField(default=0)),
                ("storage_capacity", models.PositiveIntegerField(default=0)),
                ("supports_iv_admixture", models.BooleanField(default=False)),
                ("supports_unit_dose", models.BooleanField(default=True)),
                ("supports_blister_pack", models.BooleanField(default=False)),
                ("robot_hl7_endpoint", models.CharField(blank=True, max_length=500)),
                ("robot_api_version", models.CharField(blank=True, max_length=20)),
                ("last_calibrated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="robot_profile",
                        to="cymed_pharmacy_automation.automationdevice",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_dispensing_robots",
            },
        ),
        migrations.CreateModel(
            name="AutomationQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("tenant_id", models.UUIDField(db_index=True, editable=False)),
                ("dispense_order_id", models.UUIDField(db_index=True)),
                ("drug_code", models.CharField(max_length=100)),
                ("drug_name", models.CharField(max_length=500)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("quantity_unit", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent_to_hub", "Sent to CyIntegrationHub"),
                            ("accepted", "Device Accepted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("timeout", "Timeout"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("hub_request_id", models.CharField(blank=True, max_length=255)),
                ("hub_response", models.JSONField(default=dict)),
                ("hub_sent_at", models.DateTimeField(blank=True, null=True)),
                ("hub_completed_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("failure_reason", models.TextField(blank=True)),
                ("fallback_to_manual", models.BooleanField(default=False)),
                (
                    "priority",
                    models.CharField(
                        choices=[("stat", "STAT"), ("urgent", "Urgent"), ("routine", "Routine")],
                        default="routine",
                        max_length=20,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="queue_items",
                        to="cymed_pharmacy_automation.automationdevice",
                    ),
                ),
            ],
            options={
                "db_table": "cymed_automation_queue",
                "ordering": ["-priority", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "status"], name="cymed_autom_device__2d5be7_idx"
                    ),
                    models.Index(
                        fields=["dispense_order_id", "status"],
                        name="cymed_autom_dispens_e87498_idx",
                    ),
                ],
            },
        ),
    ]
