# Generated by Django 6.0.6 on 2026-07-14 22:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('service_areas', models.JSONField(blank=True, default=list)),
                ('cydrive_subscription_active', models.BooleanField(default=True)),
                ('network_status', models.CharField(choices=[('standalone_only', 'Standalone Only'), ('network_application_pending', 'Network Application Pending'), ('network_approved', 'Network Approved'), ('network_active', 'Network Active'), ('network_suspended', 'Network Suspended'), ('network_terminated', 'Network Terminated')], default='standalone_only', max_length=32)),
                ('network_joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cydrive_delivery_company',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('car', 'Car'), ('van', 'Van'), ('refrigerated_van', 'Refrigerated Van'), ('truck', 'Truck')], max_length=32)),
                ('plate_number', models.CharField(max_length=32)),
                ('capacity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_temperature_controlled', models.BooleanField(default=False)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='cydrive_fleet.deliverycompany')),
            ],
            options={
                'db_table': 'cydrive_vehicle',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, help_text='CyIdentity user id for this driver.')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('license_number', models.CharField(max_length=64)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('status', models.CharField(choices=[('off_shift', 'Off Shift'), ('available', 'Available'), ('on_job', 'On Job'), ('suspended', 'Suspended')], default='off_shift', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='cydrive_fleet.deliverycompany')),
                ('current_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_drivers', to='cydrive_fleet.vehicle')),
            ],
            options={
                'db_table': 'cydrive_driver',
            },
        ),
        migrations.CreateModel(
            name='DeliveryJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_order_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('pickup_address', models.JSONField(default=dict)),
                ('dropoff_address', models.JSONField(default=dict)),
                ('requires_temperature_control', models.BooleanField(default=False)),
                ('package_size', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('cash_collection_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_collected', models.BooleanField(default=False)),
                ('proof_of_delivery', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.CharField(blank=True, max_length=300)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='cydrive_fleet.deliverycompany')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='cydrive_fleet.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='cydrive_fleet.vehicle')),
            ],
            options={
                'db_table': 'cydrive_delivery_job',
            },
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('company', 'plate_number'), name='unique_plate_per_company'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(fields=('company', 'user_id'), name='unique_driver_user_per_company'),
        ),
        migrations.AddIndex(
            model_name='deliveryjob',
            index=models.Index(fields=['company', 'status'], name='cydrive_del_company_6dc384_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryjob',
            index=models.Index(fields=['driver', 'status'], name='cydrive_del_driver__69bf3e_idx'),
        ),
    ]
