# Generated by Django 6.0.7 on 2026-09-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycom_project', '0003_timesheetentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='depends_on',
            field=models.ManyToManyField(blank=True, help_text='Tasks that must finish before this one can start (finish-to-start).', related_name='dependents', to='cycom_project.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='duration_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
