# Generated by Django 6.0.7 on 2026-08-06 21:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyed_sis', '0002_classsection_campus_student_campus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutoryReportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('report_type', models.CharField(choices=[('nccd', 'NCCD Return'), ('attendance', 'Attendance Return'), ('naplan', 'NAPLAN Participation'), ('census', 'National Census (SES/demographics)')], max_length=20)),
                ('period', models.CharField(blank=True, max_length=40)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('generated_by', models.CharField(blank=True, max_length=255)),
                ('fmt', models.CharField(default='json', max_length=10)),
            ],
            options={
                'db_table': 'cyed_statutory_report_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NCCDRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('collection_year', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('cognitive', 'Cognitive'), ('physical', 'Physical'), ('sensory', 'Sensory'), ('social_emotional', 'Social/Emotional')], max_length=20)),
                ('level_of_adjustment', models.CharField(choices=[('qdtp', 'Support provided within quality differentiated teaching practice'), ('supplementary', 'Supplementary'), ('substantial', 'Substantial'), ('extensive', 'Extensive')], max_length=20)),
                ('evidence_note', models.TextField(blank=True)),
                ('imputed_disability', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nccd_records', to='cyed_sis.student')),
            ],
            options={
                'db_table': 'cyed_nccd_records',
                'ordering': ['-collection_year', 'student__last_name'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'student', 'collection_year'), name='uniq_nccd_student_year')],
            },
        ),
    ]
