# Generated by Django 6.0.7 on 2026-08-11 10:10

import core.crypto
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('identifier', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('mfa', 'MFA challenge'), ('login', 'Password login'), ('step_up', 'Step-up authorisation')], default='mfa', max_length=20)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('succeeded', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'db_table': 'cyed_login_attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'identifier', 'purpose'], name='idx_login_att_ident'), models.Index(fields=['tenant_id', 'created_at'], name='idx_login_att_created')],
            },
        ),
        migrations.CreateModel(
            name='MfaEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('user_email', models.CharField(max_length=255)),
                ('secret', core.crypto.EncryptedTextField()),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_counter', models.BigIntegerField(default=0)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'cyed_mfa_enrollments',
                'ordering': ['user_email', '-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'user_email'], name='idx_mfa_enrol_tenant_user')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'user_email'), name='uniq_mfa_enrollment_per_user')],
            },
        ),
        migrations.CreateModel(
            name='MfaSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('user_email', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('totp', 'Authenticator app (TOTP)'), ('backup', 'Backup code')], default='totp', max_length=20)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'cyed_mfa_sessions',
                'ordering': ['-verified_at'],
                'indexes': [models.Index(fields=['tenant_id', 'user_email'], name='idx_mfa_sess_tenant_user')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('event_type', models.CharField(choices=[('mfa_enrolled', 'MFA enrolment started'), ('mfa_confirmed', 'MFA enrolment confirmed'), ('mfa_verified', 'MFA verified'), ('mfa_failed', 'MFA verification failed'), ('mfa_disabled', 'MFA disabled'), ('mfa_backup_used', 'Backup code used'), ('mfa_backup_regenerated', 'Backup codes regenerated'), ('lockout', 'Account locked (too many failures)'), ('step_up_granted', 'Step-up authorisation granted'), ('step_up_denied', 'Step-up authorisation denied')], max_length=40)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('actor_email', models.CharField(blank=True, max_length=255)),
                ('actor_roles', models.CharField(blank=True, max_length=255)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('detail', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'cyed_security_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'event_type'], name='idx_sec_event_type'), models.Index(fields=['tenant_id', 'actor_email'], name='idx_sec_event_actor')],
            },
        ),
        migrations.CreateModel(
            name='MfaBackupCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('salt', models.CharField(max_length=64)),
                ('code_hash', models.CharField(max_length=128)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to='cyed_security.mfaenrollment')),
            ],
            options={
                'db_table': 'cyed_mfa_backup_codes',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['enrollment', 'used_at'], name='idx_mfa_backup_unused')],
            },
        ),
    ]
