# Generated by Django 6.0.7 on 2026-07-21 23:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('license_plate', models.CharField(max_length=50)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('driver_name', models.CharField(blank=True, max_length=150)),
                ('odometer_km', models.DecimalField(decimal_places=1, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_maintenance', 'In Maintenance'), ('retired', 'Retired')], default='active', max_length=20)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cycom_fleet_vehicles',
                'ordering': ['-created_at'],
                'unique_together': {('tenant_id', 'license_plate')},
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('maintenance_date', models.DateField()),
                ('maintenance_type', models.CharField(choices=[('preventative', 'Preventative'), ('corrective', 'Corrective'), ('inspection', 'Inspection')], default='preventative', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_provider', models.CharField(blank=True, max_length=150)),
                ('odometer_km', models.DecimalField(decimal_places=1, default=0, max_digits=12)),
                ('next_service_km', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='cycom_fleet.vehicle')),
            ],
            options={
                'db_table': 'cycom_fleet_maintenance_logs',
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True, editable=False)),
                ('log_date', models.DateField()),
                ('liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_liter', models.DecimalField(decimal_places=3, max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuel_station', models.CharField(blank=True, max_length=150)),
                ('odometer_km', models.DecimalField(decimal_places=1, default=0, max_digits=12)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='cycom_fleet.vehicle')),
            ],
            options={
                'db_table': 'cycom_fleet_fuel_logs',
                'ordering': ['-log_date'],
            },
        ),
    ]
